### ISSUE TITLE
webhint extension for Visual Studio Code

### ISSUE THREAD

**Issue by ajsb85** [webhintio/hint#1011]
Dearest.

It's a proposal to create an extension (vscode) :)

Best regards.

**Comment by alrra** [comment]
> It's a proposal to create an extension (vscode) :)

@ajsb85 It's on our roadmap, but I don't think it will be done in the very next period, unless someone offers to work on it.

**Comment by molant** [comment]
There are a few things we need to do first such as:
* #982 
* add HTML traverse to the local connector
* etc.

But I really want this feature 😄

**Comment by molant** [comment]
@ajsb85 just a friendly quick to let you know there's a [PR in progress](https://github.com/webhintio/hint/pull/1254) by @antross but things are looking really good 😊

**Comment by ajsb85** [comment]
![giphy](https://user-images.githubusercontent.com/663460/45857194-eebd7c00-bd57-11e8-8703-507462070e77.gif)
