### ISSUE TITLE
Change targeted browser defaults?

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1019]
We should change the [defaults](https://github.com/sonarwhal/sonarwhal/blob/376527ffe8cd13a6c6f2e73fe0dc7c451bfaa695/packages/sonarwhal/docs/user-guide/further-configuration/browser-context.md) to not use `last 2 versions`.

See also: 

* https://jamie.build/last-2-versions
* https://twitter.com/jamiebuilds/status/988559577313492992?s=09

**Comment by molant** [comment]
What about "defaults"? I think it was added recently.

**Comment by alrra** [comment]
> What about "defaults"? I think it was added recently.

Sorry, I do not follow?

 I was referring to not stick to `browserslist`’s defaults, and overwrite the `last 2 versions` part.

(see also: https://github.com/sonarwhal/sonarwhal/commit/c03079912beda28a7d4f7b4bc9427b3cd0e8e621)

**Comment by molant** [comment]
Browserlists added a new keyword "defaults" recently that we should probably use after updating to the latest version.

**Comment by alrra** [comment]
> Browserlists added a new keyword "defaults" recently that we should probably use after updating to the latest version.

You mean `not dead`?

From https://github.com/browserslist/browserslist#queries

> `defaults`: Browserslist’s default browsers (`> 0.5%`, `last 2 versions`, `Firefox ESR`, `not dead`).

**Comment by alrra** [comment]
> after updating to the latest version.

Note: [We are already using the latest version](https://github.com/sonarwhal/sonarwhal/blob/db50a74ac58a6a9bbef582d53aaad14e0047c542/packages/sonarwhal/package.json#L13). So,

**Comment by alrra** [comment]
`not dead`

See also: https://github.com/browserslist/browserslist/issues/218#issue-293689270

**Comment by alrra** [comment]
So, I'm guessing we just need to update the documentation.

**Comment by molant** [comment]
They have a query "defaults" that we should use and delegate to it.

There's already an issue to drop support: https://github.com/browserslist/browserslist/issues/249

**Comment by molant** [comment]
OK, I though we were hardcoding the defaults (maybe we were at one point?). Right now it seems we are just passing an empty array `[ ]`.

I think the places were we should make `defaults` explicit are:

* [browserslist.ts](https://github.com/sonarwhal/sonarwhal/blob/52b94074c49c70e829fc9be79f4d42dc505736aa/packages/sonarwhal/src/lib/cli/browserslist.ts#L47): If defaults we should put `defaults` inside the array
* [config.ts](https://github.com/sonarwhal/sonarwhal/blob/52b94074c49c70e829fc9be79f4d42dc505736aa/packages/sonarwhal/src/lib/config.ts#L145): If the array is empty, we should use `defaults`

But maybe I'm missing others.

In any case, we should look at the browserslist issue and update the documentation accordingly or maybe just update the documentation to say that we are using browserslist defaults and point them to the documentation.

**Comment by alrra** [comment]
From https://github.com/browserslist/browserslist#best-practices:

> ### Best Practices
>
> * We do not recommend to change browsers, if you are not 100% sure
  what are you doing. Browserslist’s default browsers selection is a result
  of long discussion. It is easy to make mistake by selecting own browsers
  without understanding what are you doing (like you can make your website
  inaccessible for Chinese users).
> * Select browsers directly (`last 2 Chrome versions`) only if you are making
  web app for kiosk with one browser. There are a lot browsers on the market.
  If you are making general web app you should respect browsers diversity.
> * If you want to change browsers we recommend `> 0.2%`, `> 1% in US`
  or `> 1% in my stats`. `last 2 versions` will add too many dead browsers
  and will not add many popular versions. If your contract requires
  last 2 versions support, set `last 2 versions, > 1% in my stats, not dead`.

**Comment by antross** [comment]
Closing as `browserslist` dealt with the `last 2 versions` issue by using `not dead`. Additionally, our current behavior falls back to letting `browserslist` choose if a user config was not provided (by not passing anything). This allows `browserslist` to search its own fallback locations (e.g. `.browserslistrc`) before falling back to `defaults`.
