### ISSUE TITLE
Split error messages in `http-cache` rule [0.1]

### ISSUE THREAD

**Issue by ramonTC** [webhintio/hint#1074]
Analyzing http-cache performance issues it seems that http-cache rule do not work properly in that case.

![image](https://user-images.githubusercontent.com/16465474/40105029-1eeff954-58f2-11e8-9dda-e74a9d6ee344.png)

Checking out the response headers cache-control, it is really setting the correct values. See below:

![image](https://user-images.githubusercontent.com/16465474/40105184-8c19e846-58f2-11e8-8ff7-02e385358fd7.png)

**Comment by molant** [comment]
Currently the `http-cache` will show the same message if you don't have a long `max-age` and/or you are missing the `immutable` directive.

To avoid confussion I think we should split this in 2 messages:

* Static resources should have a long cache value (31536000)
* Static resources should use the immutable directive

@sonarwhal/core, @kshyju, @qzhou1607 what do you think?

**Comment by kshyju** [comment]
TIL, chrome does not support immutable!  😆
