### ISSUE TITLE
Add a CSS parser

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1115]
Including a CSS parser would help in the creation of rules focused on interoperability in the CSS space. We can do some of this now using script injection by walking the CSSOM, but this has limitations such as only being able to be run in a browser environment. Having a CSS parser would enable analysis to be done statically in addition to run-time and enable checks for patterns that may be ignored and therefore inaccessible via CSSOM.

**Comment by alrra** [comment]
We could use: https://github.com/tabatkins/parse-css 

(according to @FremyCompany it should be up-to-date)

**Comment by antross** [comment]
Another possibility: https://github.com/postcss/postcss

It's geared toward plugins, has a number of existing plugins which may prove useful (e.g. [stylelint](https://stylelint.io/) as mentioned in #1179), and has plugins for parsing LESS, SASS, and other pre-processor languages in addition to vanilla CSS.
