### ISSUE TITLE
Look into create-* packages

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1132]
> npm init <initializer> can be used to set up a new or existing npm package.
>
>initializer in this case is an npm package named create-<initializer>, which will be installed by npx, and then have its main bin executed -- presumably creating or updating package.json and running any other initialization-related operations.

https://docs.npmjs.com/cli/init

This means we can extract the wizards (new-rule, new-parser) to new packages and simplify the CLI.

Thoughts?

---

- [x] [`create-parser`](https://github.com/sonarwhal/sonarwhal/commit/1b5af2862805bf03f767f45e1a40c40150ad5148)
- [x] [`create-rule`](https://github.com/sonarwhal/sonarwhal/commit/083e1cbe4632976897cb94f3fa638edf4b87dcd4)

**Comment by alrra** [comment]
- [x] [`create-parser`](https://github.com/sonarwhal/sonarwhal/commit/1b5af2862805bf03f767f45e1a40c40150ad5148)
- [x] [`create-rule`](https://github.com/sonarwhal/sonarwhal/commit/083e1cbe4632976897cb94f3fa638edf4b87dcd4)

**Comment by molant** [comment]
We now have those packages.
