### ISSUE TITLE
CLI not locating .hintrc in user's home directory 

### ISSUE THREAD

**Issue by jgarber623** [webhintio/hint#1142]
Hello!

There appears to be a small issue when running the `sonarwhal` CLI under the following conditions:

- `sonarwhal` is installed globally (consistent with the official documentation),
- There's a "global" `.sonarwhalrc` configuration file in the user's home directory (`~/.sonarwhalrc`),
- The user is running `sonarwhal [url]` in a folder _other than_ the user's home directory, and
- The current working directory contains `package.json`, `node_modules/`, etc.

I would expect that, regardless of the presence or absence of `package.json`, `node_modules/`, etc. in the current working directory that running `sonarwhal [url]` would first look in the current working directory for a configuration file then look in the user's home directory for the configuration file.

Note that running `sonarwhal [url]` in an arbitrary directory _without `package.json`, `node_modules/`, etc._ functions as expected, correctly locating and using the `~/.sonarwhalrc` configuration file.

This issue is related to PR #718.

## Environment

* __`sonarwhal` version:__ 1.11.2
* __`Node.js` version:__ 10.4.1
* __`npm` version:__ 6.1.0

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js
{
    "extends": [
        "web-recommended",
        "progressive-web-apps"
    ],
    "formatters": "stylish"
}
```

</details>

## URL for which `sonarwhal` failed

* __URL:__ https://sonarwhal.com

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text
$ npm install -g sonarwhal @sonarwhal/configuration-progressive-web-apps @sonarwhal/configuration-web-recommended
$ cd ~/some/directory
$ sonarwhal https://sonarwhal.com              

   ┌───────────────────────────────────────────────────────────────┐
   │                                                               │
   │             Couldn't find any valid configuration             │
   │                                                               │
   │       Running sonarwhal with the default configuration.       │
   │                                                               │
   │   Learn more about how to create your own configuration at:   │
   │                                                               │
   │            https://sonarwhal.com/docs/user-guide/             │
   │                                                               │
   └───────────────────────────────────────────────────────────────┘
```

</details>

**Comment by molant** [comment]
@jgarber623 that's the current expected behavior.

Our way of thinking is that if you are inside a project folder (aka something with a package.json) then sonarwhal should be installed/search things locally.

In general we would like users to install it locally instead of globally. That said, there are a couple things we could do to improve the experience:

- Do what you propose: even if there's a `package.json` search also in `~`. I can't remember the problems we had with this scenario. Maybe something related to resource loading? @sarvaje do you remember?
- Don't allow to execute sonarwhal in a folder that has `package.json` and tell the user to install it locally
- Something else?

@sonarwhal/core thoughts?

**Comment by alrra** [comment]
> Don't allow to execute sonarwhal in a folder that has package.json and tell the user to install it locally

I think it makes sense to do that.

----

If, for example, you run `npm i` inside a directory without  a `package.json` file it will give you the following:

```error

npm WARN saveError ENOENT: no such file or directory, open '/Users/xxxxx/projects/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/xxxxx/projects/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

up to date in 0.611s
found 0 vulnerabilities
```

**Comment by molant** [comment]
We've moved away from recommending installing webhint globally in 9f13687ebbd3d929875cab5a9b9084cf608fa21f because of issues like this one.

Going to close this as the scenario is not supported.
