### ISSUE TITLE
Tests for `aXe` fail on CI

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1143]
```error
rule-axe » dist » tests » tests » [chrome] Resource is not an HTML document
```

Bug [was introduced](https://ci.appveyor.com/project/NellieTheNarwhal/sonarwhal/build/1.0.1997/job/sjr986op0wa2mdiy#L2204) by https://github.com/sonarwhal/sonarwhal/commit/364ca831fab222bf8f6709cd5f6dfd64d68f1d78.

**Comment by molant** [comment]
The tests seem to fail on Travis as well but not locally for me on Windows not for @alrra on his Mac 😵

**Comment by alrra** [comment]
Fixed in https://github.com/webhintio/hint/commit/9e57bed9f3e3fac64a8a6dc9ba15e185a9bb22dd.
