### ISSUE TITLE
Rule `no-broken-links` infinite loop

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1146]
Steps to Reproduce:

1. Activate the rule `no-broken-links`
2. run sonarwhal http://edge.ms --debug
3. See that https://www.xamarin.com/ is requested infinitely.

After a first look, the `requester` get a status code 302 from https://www.xamarin.com/ and the header Location is `/` so the new url generated is the same.

**Comment by alrra** [comment]
I can confirm this bug.
