### ISSUE TITLE
Docs: Suggestions for `.hintrc` formats

### ISSUE THREAD

**Issue by aligneddev** [webhintio/hint#1174]
https://sonarwhal.com/docs/user-guide/further-configuration/sonarwhalrc-formats/index.html

It'd be great to state where this .sonarwhalrc file exists. I'm still searching after an `npm install -g --engine-strict sonarwhal`.

from the sonarwhal --help, I assumed that sonarwhal -f 'formatter-stylish' would work after a `npm install -g @sonarwhal/formatter-stylish`

Thanks

**Comment by aligneddev** [comment]
I found it ;-) C:\Users\{user}\AppData\Roaming\npm\node_modules\sonarwhal\.sonarwhalrc

**Comment by molant** [comment]
You actually need to create the sonarwhalrc file in your home folder or the folder where you are going to run sonarwhal.
The getting started guide should give you more information on this: https://sonarwhal.com/docs/user-guide/

I also agree that the formats documentation is very incomplete. I believe we have an issue for that.

Thanks!
