### ISSUE TITLE
Website: Invalid link to Github

### ISSUE THREAD

**Issue by Ruffio** [webhintio/hint#1175]
The link to this GitHub project on the frontpage of https://sonarwhal.com/ is invalid:

![image](https://user-images.githubusercontent.com/1877612/42676882-1c03f8a2-867a-11e8-9d6b-beeb465762ad.png)

**Comment by molant** [comment]
We are in the process of changing names so this is expected while we finish the process. The code in webhintio/webhint.io (code for the site) has the right links but hasn't been deployed because there are a few more changes we need to do before.

Thanks!

**Comment by molant** [comment]
We have a project for the whole org in https://github.com/orgs/webhintio/projects/1 but we haven't keep it a lot up to date mainly because we want the rename process to be a bit under the radar.
