### ISSUE TITLE
Detection/Error message of svg mime type looks to be incorrect

### ISSUE THREAD

**Issue by Ruffio** [webhintio/hint#1180]
When scanning my website (https://www.rcfed.com) I get an error regarding the mime type of scg images:
![image](https://user-images.githubusercontent.com/1877612/42865459-fb6e5dc8-8a69-11e8-8cfb-f70d13b30062.png)

I have investigated the issue and it looks like we are having an inconsistency. 
The error message states that the type is 'image/svg+xml' but should be 'image/svg+xml'.

According to the W3C spec. (https://www.w3.org/TR/SVG11/) the correct mime type is 'image/svg+xml': 
https://www.w3.org/TR/SVG11/mimereg.html

![image](https://user-images.githubusercontent.com/1877612/42865714-d2665164-8a6a-11e8-94a4-880f7692f3d0.png)

Also 'W3C Server Settings' (https://www.w3.org/services/svg-server/) states 'images/svg+xml':
![image](https://user-images.githubusercontent.com/1877612/42865611-7ba84e40-8a6a-11e8-8478-8800856af233.png)

If you have performed a scanning and follow the 'documentation link', then you end up at: https://sonarwhal.com/docs/user-guide/rules/rule-content-type/

Also here it is suggested to use mime type 'image/svg+xml':
![image](https://user-images.githubusercontent.com/1877612/42865867-46b6e75e-8a6b-11e8-8906-906b29c33c7e.png)

**Comment by alrra** [comment]
@Ruffio Thanks for opening this issue!

[`'content-type' header should have media type 'text/xml' (not 'image/svg+xml')`](https://sonarwhal.com/scanner/368f4d16-c999-441a-93e5-51d655561558).

Yes, the media type should be `image/svg+xml`, it's just wrongly detected.
