### ISSUE TITLE
Cloud.com

### ISSUE THREAD

**Issue by ervin210** [webhintio/hint#1186]
Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by ervin210** [comment]
cloud.com   website

**Comment by molant** [comment]
@ervin210 can you please fill all the information asked in the template and let us know when you've done it?

**Comment by alrra** [comment]
Closing until further information is provided.
