### ISSUE TITLE
Feature Request: Alternate Stylesheets should also be required to use Subresource Integrity

### ISSUE THREAD

**Issue by dgotilla** [webhintio/hint#1197]
I noticed Sonarwhal _does not_ generate a Security Error when alternate stylesheets are linked to without a valid integrity attribute. However, I see no reason alternate stylesheets should be treated differently than regular stylesheets; they are also susceptible to manipulation by attackers since browsers (or extensions) may allow users to enable alternate stylesheets at their discretion.

In other words, I believe the _'Resource xxx requested without the "integrity" attribute'_ message should also be triggered by alternate stylesheets (`<link rel="alternate stylesheet">`); at the moment, it is only triggered by regular stylesheets (`<link rel="stylesheet">`).

**Comment by alrra** [comment]
Thanks, @dgotilla! Keep them coming!
