### ISSUE TITLE
Add a rule for unsupported CSS properties

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1203]
Related to #1179, the `doiuse` library warns about using CSS properties which aren't supported in a given set of target browsers backed by caniuse data (vs stylelint which focuses more on general CSS mistakes). This could be useful to warn not only about adoption of newer features, but also older features which haven't been implemented in all browsers (e.g. the [CSS `zoom` property](https://caniuse.com/#search=css%20zoom)). There's even [a stylelint plugin](https://github.com/ismay/stylelint-no-unsupported-browser-features) that wraps this, but I suspect it'd be better to avoid the extra middle man.

**Comment by antross** [comment]
Per recent discussions, we should look at using the [MDN compatibility data](https://github.com/mdn/browser-compat-data/) here as it has great coverage for CSS support.

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/rfcs/issues/4
