### ISSUE TITLE
Error while trying to use an icon from the Manifest

### ISSUE THREAD

**Issue by GuillaumeRossolini** [webhintio/hint#1220]
Hi,

This is by using the web scanner from a web browser. I got the following in Chrome Canary's console:
> Error while trying to use the following icon from the Manifest: https://webhint.io/static/images/manifest-icon.png (Download error or resource isn't a valid image)

Since I don't know if this happens every time, please find below the scan where I saw this:
https://webhint.io/scanner/ad6908fd-a4e2-4c70-99f0-2ec2ca0c9e7b

Which I guess means this manifest:
https://webhint.io/static/site-ba9e7c1c31.webmanifest

Cheers,

**Comment by alrra** [comment]
@GuillaumeRossolini Thanks for opening this issue, I've open an issue in our website repository: https://github.com/webhintio/webhint.io/issues/479.

**Comment by alrra** [comment]
@GuillaumeRossolini Issue was fixed in https://github.com/webhintio/webhint.io/commit/9473c831a5b112fabee714ba340aa37fb2ace115. Thanks again for taking the time to open this issue!
