### ISSUE TITLE
Polyfills to add to jsdom connector

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1223]
Making a list of polyfills or fallbacks we need to add to jsdom based on issues that have been opened:

* [ ] `requestAnimationFrame` ([`pretendToBeVisual`](https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser) might be enough #1144
* [ ] `document.domain` #521
* [ ] `clientWidth/Height` (https://github.com/jsdom/jsdom/issues/2342)

I expect this list to grow. I'll be closing all the other issues and point to this one.

**Comment by antross** [comment]
Note `jsdom` should provide `requestAnimationFrame` if we set the right flags, though our ability to do so may be dependent on #163:
```javascript
new JSDOM(``, { pretendToBeVisual: true })
```

See https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser

**Comment by molant** [comment]
Great, I didn't know about that option.
@sarvaje can you please add that option in your work for #163?

**Comment by molant** [comment]
Also we might want to do something like https://github.com/jsdom/jsdom/issues/2342 for `clientWidth` and `clientHeight`.
