### ISSUE TITLE
Emit typed events?

### ISSUE THREAD

**Issue by molant** [webhintio/hint#123]
Right now we are using `emitAsync` and trying to type the data we are sending through this method. The problem is that sometimes we forget (or will forget).
Should we create new events (`emitElement`, `emitFetchStart`, etc.) that will force the parameter to be of the right type?
**pros:**
No need to remember to type the object to be sure it is of the right type.
**cons:**
* Need to implement a method for each event.
* We might run into issues when testing because the types are different.

@alrra, @sarvaje, thoughts?

**Comment by molant** [comment]
Something similar is being proposed to webpack in [this Twitter thread](https://twitter.com/chriseppstein/status/880504882985226240).

Pinging @sonarwhal/contributors to get their thoughts. This will be breaking so better do it before v1

**Comment by alrra** [comment]
Closing as per https://github.com/sonarwhal/sonarwhal/pull/844#issuecomment-369468870.

**Comment by molant** [comment]
Reopening because of [this post](https://medium.com/@bterlson/strongly-typed-event-emitters-2c2345801de8) by @brterlson

We can probably do it in a not very complicated way :)
