### ISSUE TITLE
Tests fail for `jsdom` because of SIGSEGV

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1250]
* Steps to reproduce: 

  * Run the tests for `hint-http-compression` 
    (e.g.: https://travis-ci.org/webhintio/hint/jobs/418454213#L3194)

  * __`hint` version:__ latest
  * __`Node.js` version:__  LTS (8) and latest (10) 

* Output:

  Locally I get:  `dist/tests/tests-https.js exited due to SIGSEGV`

**Comment by molant** [comment]
Can you add your node version?

**Comment by alrra** [comment]
> Can you add your node version?

I did, all versions :(

**Comment by molant** [comment]
🤯 can't believe `mime-db` was the issue. Do you know more?
