### ISSUE TITLE
no-broken-links should probably only check urls using the http(s) protocol

### ISSUE THREAD

**Issue by chrisguttandin** [webhintio/hint#1253]
Please tell us about your:

## Environment

* __`hint` version: v3.2.2__
* __`Node.js` version: v10.9.0__
* __`npm` version: v6.4.0__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
    hints: {
        'no-broken-links': 'error'
    }
}
```

</details>

## URL for which `webhint` failed

* __URL: https://js-2ky5td.stackblitz.io__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
✖ Finishing...
mailto:hello@emxaple.com
line 12  col 7  Error  Broken link found (domain not found).  no-broken-links
✖ Found 1 error and 0 warnings

✖ Found a total of 1 error and 0 warnings
```

</details>

I would like to suggest to restrict the checks for broken links to URLs with an http(s) and maybe also a file protocol.

Currently the rule also checks for mailto links and any other protocol which doesn't make much sense in my opinion.

There is a slightly related issue with rules like `http-cache`. Those rules do also check URLs which do for example have a blob protocol. However these rules can be configured with the `ignoredUrls` config option which isn't possible for the `no-broken-links` rule.

**Comment by molant** [comment]
Nice catch! Want to try to do a PR with the fix?
I think you just need to filter the urls [right after `resourceURL`](https://github.com/webhintio/hint/blob/b0d4efa1829fbc697a1913cff5a9924cfe8def31/packages/hint-no-broken-links/src/hint.ts#L186) and add a test with a `mailto:` to verify things work. We can help you in the process if needed 😊

**Comment by molant** [comment]
ops, just saw your avatar. No need for our help 😛

**Comment by molant** [comment]
There's now a PR for this in https://github.com/webhintio/hint/pull/1275

**Comment by chrisguttandin** [comment]
Thanks a lot, @molant. I would have otherwise done it myself but I was busy over the weekend.

**Comment by alrra** [comment]
Fix included in [`@hint/hint-no-broken-links`](https://www.npmjs.com/package/@hint/hint-no-broken-links) `v1.0.5`. 🎉
