### ISSUE TITLE
HTML formatter counts test execution errors as warnings on the top and as errors in the details

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1257]
See #1256 

![test results](https://user-images.githubusercontent.com/150330/44500577-91061900-a65f-11e8-98db-d7d8dd1f1def.png)

![report detail](https://user-images.githubusercontent.com/150330/44500595-b98e1300-a65f-11e8-84f3-4086b8986eb0.png)

/cc @getify

**Comment by sarvaje** [comment]
The error is not in the formatter, is in the online scanner.
Closing in favor of https://github.com/webhintio/online-service/issues/141
