### ISSUE TITLE
Something is broken in requester with chrome connector

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1258]
## Environment

* __`hint` version:__ 3.2.3
* __`Node.js` version:__ 8.11.3
* __`npm` version:__ 6.1.0

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>
```js
{
  "connector": "chrome",
  "extends": ["web-recommended"]
}
```

</details>

## URL for which `webhint` failed

* __URL:__ https://webhint.io

## Output

There are a bunch of rules (the ones that do multiple requests via `requester`) that fail with the message

> Could not be fetched

@sarvaje could this be related to the changes you did recently in that area?

**Comment by sarvaje** [comment]
> @sarvaje could this be related to the changes you did recently in that area?

No, those changes are not merge yet.

I will take a look

**Comment by sarvaje** [comment]
@molant did you try this again? Can it be closed?

**Comment by molant** [comment]
Haven't tried it yet. Will try later today hopefully.

**Comment by molant** [comment]
Tried with the latest published version and I no longer see this issue.
