### ISSUE TITLE
Recommended content type for ico is "image/vnd.microsoft.icon" instead of "image/x-icon"

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1259]
This seems to be with [mime-db having `image/vnd.microsoft.icon`](https://github.com/jshttp/mime-db/blob/master/db.json) before [`image/x-icon`](https://github.com/jshttp/mime-db/blob/dd02f32bbd23cc2c081888754a5c1b688c6e9ebb/db.json#L6620).

**Comment by alrra** [comment]
This is because of `mime-db` breaking us. That issue was fixed in https://github.com/webhintio/hint/commit/1acc771321a2a83fc525e6743109982c85e40c0f but still lingers because of some issues with dependencies. :(

**Comment by chrisgraham** [comment]
Can't it just accept that both are in common use, and allow either? Seems inappropriate to force an opinionated choice between what is the registered mime-type vs the Microsoft-preferred mime-type, when in the wild using either will work just fine.
