### ISSUE TITLE
SRI: it seems overly strict to expect on HTTPS same-origin requests

### ISSUE THREAD

**Issue by getify** [webhintio/hint#1263]
Unless I'm missing something, I'm not sure why there's any benefit at all to an HTTPS site loading resources from its same origin and **also** being required to use SRI for them?

I can certainly understand the benefit of cross-origin SRI, but the hint complaining about same-origin while under HTTPS seems overly pedantic and unnecessary noise.

NOTE: I'm referring to the default configuration used by the web scanner.

**Comment by molant** [comment]
You can take a look at the discussion in https://github.com/webhintio/hint/issues/1077

There are many cases where it makes sense to have it even for the same origin and it's always better to be as secure as the platform allows you. Maybe in yours it doesn't but having it doesn't hurt and if you don't agree you can tweak the configuration.
