### ISSUE TITLE
False Error for Manifest File

### ISSUE THREAD

**Issue by ayumihamsaki** [webhintio/hint#1265]
When testing I see this result:

`Web app manifest should have the filename extension 'webmanifest', not 'json'.`

That is incorrect and false, you can use `.json` extension just fine, see their github issue: https://github.com/w3c/manifest/issues/689

**Comment by alrra** [comment]
> That is incorrect and false

@ayumihamsaki We recommend `.webmanifest` because of the reasons specified in the [documentation](https://webhint.io/docs/user-guide/hints/hint-manifest-file-extension/#why-is-this-important). 

> see their github issue: w3c/manifest#689

See: https://github.com/w3c/manifest/issues/689#issuecomment-402773032 :)

**Comment by ayumihamsaki** [comment]
I disagree with your reply, I have the following running:

`<link rel="manifest" href="https://www.example.com/manifest.json">`

and have the following mime-type (connected to the file):

`application/manifest+json`

See screenshot of it working fine in the broswer:

![untitledcdsc](https://user-images.githubusercontent.com/17784082/44597659-4bb12b00-a7c8-11e8-9036-33afa4bf5988.png)

The real issue is your tool is giving a false positibe and there is no mention of mime-types.
