### ISSUE TITLE
HTML formater shouldn't have a "perform another scan" link

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1266]
Looks like webhintio/webhint.io#496 points to the HTML formater.

[Code search result](https://github.com/webhintio/hint/search?q=perform+another&unscoped_q=perform+another).

I don't think it makes too much sense to have that link in the HTML formater. If we are seeing this report from the file system we are not going to do another scan. We should probably move this code to the website where it can work.

@sarvaje, you worked on this part, what do you think?

**Comment by sarvaje** [comment]
you shouldn't see the link when you run an scan locally. The link is part of an error message that we are showing if there is any error.
