### ISSUE TITLE
Summary formatter doesn't print the correct output if a rule has warnings and errors at the same time

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1272]
Please tell us about your:

## Environment

* __`hint` version:__ 3.2.3
* __`Node.js` version:__ 8.11.3
* __`npm` version:__ 6.2.0

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```json
{
    "formatters": ["summary"],
    "extends": ["web-recommended"]
}
```

</details>

## Output
![image](https://user-images.githubusercontent.com/1581288/44692544-3a5e5d80-aa18-11e8-993b-983b95c1b96f.png)

**Comment by molant** [comment]
@sarvaje what URL did you analyze to get this result?

**Comment by molant** [comment]
OK this is how it looks like with my current code:

![image](https://user-images.githubusercontent.com/606594/45070160-d590ac00-b084-11e8-8818-4034fc246e4e.png)
