### ISSUE TITLE
Include node locations for HTML in `connector-jsdom`

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1289]
This allows providing accurate line/col information for elements HTML even when other elements have been dynamically inserted/removed nearby. It is done by setting `includeNodeLocations: true` in the options passed to `new JSDOM()` and is already utilized in the new `parser-html` (PR #1277).

**Comment by antross** [comment]
Yes, I don’t think this was an option on the old API (though I could be wrong).

**Comment by molant** [comment]
@sarvaje can you add this to your PR #1277?

**Comment by sarvaje** [comment]
>@sarvaje can you add this to your PR #1277?

That's not my PR :P. But yep, I will add it to my PR.

>Yes, I don’t think this was an option on the old API (though I could be wrong).

The old API activate it by default.

**Comment by molant** [comment]
> The old API activate it by default.

Really? How did I miss that 😱
Maybe we should do some tests with various SPAs to see how the change in the location detection affects them?

**Comment by antross** [comment]
I should note the location information doesn't yet flow all the way to the hints in production. I have a commit on the vscode extension PR that updates the IAsyncHTMLElement and JSDOMAsyncHTMLElement types to expose this: https://github.com/webhintio/hint/pull/1254/commits/1db7fa16a00c3c33fd177f901e8e873b6a9b5e7a

I can put this in a separate PR if we want.

**Comment by sarvaje** [comment]
> Really? How did I miss that

Yep :)

I have added the option in the v12 PR https://github.com/webhintio/hint/pull/1274
