### ISSUE TITLE
Error loading a data-url image in jsdom

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1296]
jsdom fail to load some data url images due to a problem with `canvas-prebuilt`.

More info in: https://github.com/node-gfx/node-canvas-prebuilt/issues/52

Website affected: https://staging.smockle.com

**Comment by sarvaje** [comment]
@molant This should be done. I don't know if the change was published, but it is done :)

**Comment by molant** [comment]
Yes, canvas-prebuilt 1.6.11 is now available and users should get this version when doing a new install now that we don't have lock files.

Closing it.
