### ISSUE TITLE
[docs] Issue with 'HTTP Cache'

### ISSUE THREAD

**Issue by wallyfaye** [webhintio/hint#1302]
https://webhint.io/docs/user-guide/hints/hint-http-cache/index.html

I'm getting the error `No configured patterns for cache busting match` for the file `main.css`. 

However, my server is not showing that the built-in regular expressions for file revving are being requested (I also tried to update my `.hintrc` to use the sample revvingPatterns to try to trigger requests to a cache busting URL). 

Am I correct to expect that cache busting URLs should be tested here? Is there a change that I should make, or should I be approaching this differently?

**Errors**
![error_report](https://user-images.githubusercontent.com/948792/45367075-63512780-b5ae-11e8-82e2-a5646fe63944.png)

**Server requests**
![server requests](https://user-images.githubusercontent.com/948792/45367074-62b89100-b5ae-11e8-8a6e-f471323ca0a5.png)

**Example of pattern match 1**
![pattern match 1](https://user-images.githubusercontent.com/948792/45367072-621ffa80-b5ae-11e8-9581-978dd5150ab2.png)

**Example of pattern match 2**
![pattern match 2](https://user-images.githubusercontent.com/948792/45367071-61876400-b5ae-11e8-9289-a33b5e1e51df.png)

**Example of pattern match 3**
![pattern match 3](https://user-images.githubusercontent.com/948792/45367068-60eecd80-b5ae-11e8-979a-055693b6017d.png)

**Example of pattern match 4**
![pattern match 4](https://user-images.githubusercontent.com/948792/45367066-60563700-b5ae-11e8-85de-9a6036c4bb78.png)

**Hintrc file**
![hintrc](https://user-images.githubusercontent.com/948792/45367073-62b89100-b5ae-11e8-9b0a-8f528e0fc773.png)

**Comment by wallyfaye** [comment]
I resolved this by using the cache busting URLs in the files that webhint tested. So instead of pointing to `main.css` in my `index.html` file, I pointed to `main.123.css`.

**Comment by molant** [comment]
> I resolved this by using the cache busting URLs in the files that webhint tested. So instead of pointing to `main.css` in my `index.html` file, I pointed to `main.123.css`.

The browser only downloads the resources linked in the HTML so what you did is the right way 😊
