### ISSUE TITLE
Upgrade yarn version in Travis

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1317]
The version used by Travis is 1.3.2 but the team is using the latest one (1.9.4 at the moment of writing this issue).

We should use the same version in all environments.

For travis [this seems to be the recommended way](https://github.com/travis-ci/travis-ci/issues/7471#issuecomment-288832948) via `.travis.yml`:

```yml
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version [version]
  ⋮
```

**Comment by molant** [comment]
This is not working as expected.

**Comment by alrra** [comment]
See: https://travis-ci.org/webhintio/hint/jobs/430718088#L1057

**Comment by antross** [comment]
See: https://travis-ci.org/webhintio/hint/jobs/430718088#L1116

It installed, but is still using the old version. @molant found another link which mentions different instructions for `sudo: required` (which may be why this didn't work): https://yarnpkg.com/en/docs/install-ci

**Comment by alrra** [comment]
@antross Should be fixed in https://github.com/webhintio/hint/commit/97d3bab2848e6bcff032f0a4ba6b2a5974ef41c0 (see: https://travis-ci.org/webhintio/hint/jobs/430767158#L649).
