### ISSUE TITLE
[docs] Issue with 'User guide' - default .hintrc contents not shown

### ISSUE THREAD

**Issue by marknoble** [webhintio/hint#1319]
https://webhint.io/docs/user-guide/index.html

After the sentence "This configuration will be equivalent to the following .hintrc:" the contents of the default .hintrc file are not displayed.

**Comment by alrra** [comment]
@marknoble Good catch! We should just link to https://github.com/webhintio/hint/blob/master/packages/configuration-web-recommended/index.json.

Want to open a PR? The file that needs to be updated is [this one](https://github.com/webhintio/hint/blob/master/packages/hint/docs/user-guide/index.md).

**Comment by molant** [comment]
There's a PR for this now: https://github.com/webhintio/hint/pull/1322
