### ISSUE TITLE
Add rule that alerts if you are writing bogus code with flexbox

### ISSUE THREAD

**Issue by molant** [webhintio/hint#132]
It will use the data from [flexbugs](https://github.com/philipwalton/flexbugs).
Similar to #131, we will have to:
* [ ] Create a `JSON` for the patterns.
* [ ] Have a browser configuration (this config should probably be at the general `.sonarrc` level and not just the rule).

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/rfcs/issues/30

**Comment by hxlnt** [comment]
Fixed by https://github.com/webhintio/hint/pull/4073
