### ISSUE TITLE
[docs] Issue with 'User guide' - Windows Phython required?

### ISSUE THREAD

**Issue by marknoble** [webhintio/hint#1320]
https://webhint.io/docs/user-guide/index.html

Windows install seems to require Python.

I'm getting this error: gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

**Comment by molant** [comment]
@marknoble can you paste more output? I'm not sure why Python should be required as all the binary packages we are using have a precompiled version for most node versions that is downloaded automatically.

Additionally we should make a note about using [`windows-build-tools`](https://www.npmjs.com/package/windows-build-tools) to set all the environment on Windows.

**Comment by molant** [comment]
There's a PR for this now: https://github.com/webhintio/hint/pull/1322

**Comment by marknoble** [comment]
PS C:\WINDOWS\system32> npm install -g --engine-strict hint
C:\Users\{redacted}\AppData\Roaming\npm\hint -> C:\Users\{redacted}\AppData\Roaming\npm\node_modules\hint\dist\src\bin\hint.js

> iltorb@2.4.0 install C:\Users\{redacted}\AppData\Roaming\npm\node_modules\hint\node_modules\iltorb
> node ./scripts/install.js || node-gyp rebuild

info looking for cached prebuild @ C:\Users\{redacted}\AppData\Roaming\npm-cache\_prebuilds\2f6cf2-iltorb-v2.4.0-node-v59-win32-x64.tar.gz
http request GET https://github.com/MayhemYDG/iltorb/releases/download/v2.4.0/iltorb-v2.4.0-node-v59-win32-x64.tar.gz
http 404 https://github.com/MayhemYDG/iltorb/releases/download/v2.4.0/iltorb-v2.4.0-node-v59-win32-x64.tar.gz
WARN install No prebuilt binaries found (target=9.3.0 runtime=node arch=x64 platform=win32)

C:\Users\{redacted}\AppData\Roaming\npm\node_modules\hint\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\{redacted}\AppData\Roaming\npm\node_modules\hint\node_modules\iltorb
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\hint\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.0 (node_modules\hint\node_modules\iltorb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@2.4.0 install: `node ./scripts/install.js || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ hint@3.4.0
added 92 packages and updated 1 package in 20.578s
PS C:\WINDOWS\system32>


________________________________
