### ISSUE TITLE
Hint falsely suggests to use content-type "text/javascript"

### ISSUE THREAD

**Issue by dontbyte** [webhintio/hint#1381]
Hint suggests to use content-type "text/javasript" but it's already "text/javascript":

![image](https://user-images.githubusercontent.com/25500244/46601577-c8386880-caed-11e8-8d17-fe2159660847.png)

## Environment
Online scanner

**Comment by molant** [comment]
@dontbyte in what website does it happen? I believe in this case the header is taking precedence over the attribute. @alrra do you remember what the spec says?

**Comment by alrra** [comment]
@dontbyte That hint refers to the HTTP header, not the `type` attribute. 

See also: https://github.com/webhintio/hint/issues/568#issuecomment-339945844.
