### ISSUE TITLE
Redirect hops can fail in some cases

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1403]
Imagine this scenario:
http://a.com => https://a.com
https://a.com => https://a.com/token
https://a.com/token => https://a.com

where => is a redirect.

In the current `RedirectManager`, the last redirect overwrite the first one, because the "index" is the same `https://a.com`

**Comment by sarvaje** [comment]
I think this should be done as part of https://github.com/webhintio/hint/issues/1398

**Comment by molant** [comment]
> I think this should be done as part of #1398

This should be solved with the current refactor I'm working on 😊
