### ISSUE TITLE
[create hint] EventEmitter warning + script never ends on macOS and node 10+

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1405]
Node: v10.10.0
npm: 6.4.1
hint: v3.4.10

```sh
$ npm create hint

npx: installed 1 in 1.18s
? Is this a package with multiple hints? (yes) No
? What's the name of this new hint? tmp
? What's the description of this new hint 'tmp'? ...
? Please select the category of this new hint: development
? Please select the category of use case: (Use arrow keys)
❯ DOM 
? Please select the category of use case: DOM
? What DOM element does the hint need access to? (div) (node:6037) Error: Possible EventEmitter memory leak detected. 11 keypress listeners added. Use emitter.setMaxListeners() to increase limit
? What DOM element does the hint need access to? div
? Please select the scope of this new hint: any
Creating new hint in /Users/alrra/server/4/hint-copyright
External files copied
Creating new hint in /Users/alrra/server/4/hint-copyright
External files copied

New hint copyright created in /Users/alrra/server/4/hint-copyright

--------------------------------------
----          How to use          ----
--------------------------------------
1. Go to the folder 'hint-copyright'.
2. Run 'npm run init' to install all the dependencies and build the project.
3. Run 'npm run hint -- https://YourUrl' to analyze you site.
```

Also at the end it never returns the prompt.

**Comment by molant** [comment]
Can't repro with the following:
* OS: Windows 10
* Node: 8.11.3
* npm: 6.4.1
* hint: 3.4.10

I also made sure to not have `create-hint` installed globally. If you have it, it will use that version (although for your `npx: instaled 1 in 1.18s) doesn't seem like you have it.

**Comment by alrra** [comment]
> I also made sure to not have create-hint installed globally

I works now, maybe the problems were related to me trying to fix the vscode issues.

> Also at the end it never returns the prompt.

Does this happen to you?

**Comment by molant** [comment]
> Does this happen to you?

Nope, it always returns:

![image](https://user-images.githubusercontent.com/606594/47036140-add73e00-d130-11e8-8350-f89f2e105ebd.png)

**Comment by molant** [comment]
I can repro this on a mac 😔

**Comment by molant** [comment]
Last time this happened it was an issue with node itself https://github.com/SBoudrias/Inquirer.js/issues/115

**Comment by molant** [comment]
The `eventEmitter` issue doesn't repro with node 8.13.0 but the process doesn't finish.

**Comment by molant** [comment]
After debugging this a bit more, it looks like both issues are related to AppInsights:

* To finish the script we need to call `sendPendingData()`, this is an easy fix
* If we don't import `AppInsights` we don't get the `EventEmitter` warning

Not sure what to do about this. I think I'm more inclined towards removing AppInsights directly and rely on the number of downloads from npm to gather some data.

@webhintio/core thoughts?

**Comment by molant** [comment]
I've created a PR for this https://github.com/webhintio/hint/pull/1587
