### ISSUE TITLE
Review create-* packages templates

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1407]
At least `"build:ts": tsc"` has to be changed to `"build:ts": tsc -b`

**Comment by sarvaje** [comment]
You can take a look to other `hint`s or `parser`s. to see the differences.

**Comment by antross** [comment]
Looks like `"main"` in the `package.json` for `create-hint` needs changed to point to `hint.js` instead of `index.js`.

**Comment by molant** [comment]
And `index.js` doesn't have to be added. I'm renaming this issue.
