### ISSUE TITLE
Add rule(s) to check for caching 

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#142]
- [ ] Check if static resources (images, js, css, fonts) are served with far-future expires headers (allow this to be configurable).
- [ ] Check if resources cached for a long time use any form of cache busting .
- [ ] Check if the cache busting is done using [query strings (`?v231`) instead of something such as `.231.extension`](http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/).
- [ ] [Cache-Control: immutable](http://bitsup.blogspot.ro/2016/05/cache-control-immutable.html) ?
- [ ] Other?

**Comment by molant** [comment]
Some documentation:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9
https://jakearchibald.com/2016/caching-best-practices/
https://youtu.be/vAgKZoGIvqs?t=12m20s

**Comment by molant** [comment]
**Proposal**

The ideal configuration is:

* Static assets (anything but HTML): `max-age` + cache busting + `immutable`
* HTML content: `no-cache` or a relatively small `max-age` (a few minutes), although `no-cache` preferred
* Cache busting is done via filename and not query parameter
* No explicit `cache-control` is an error as the behavior is left to the browser implementation and it can change from one to another

On top of that:
* wrong `cache-control` configurations. E.g.: `no-cache` with `max-age`
* invalid directives. E.g.: `cache-control: max-ages=11234`
* alert about the use of extension directives not supported by any browser (`stale-while-revalidate` and `stale-if-error`)?
* `must-revalidate` doesn't seem to be recommended anywhere, should we 

**User configurations**

* `max-age` value: By default one year
* Preferred type of cache busting (parameter/file)
* Cache busting regular expression(s). By default we should find `filename.hash.ext` and `filename-hash.ext` (those are the 2 most popular I've found).
* **What do we do with explicit no caching**? Maybe have an option to not flag it?

**Some data from HTTP Archive**

Some data from the latest HTTP Archive (2017/10/15)

```SQL
SELECT cache_header, round(100*ratio) as percent, resource_count FROM (
SELECT count(*) as resource_count, RATIO_TO_REPORT(resource_count) OVER() ratio, 
       CASE WHEN resp_cache_control = "" THEN "no cache header"
            WHEN resp_cache_control contains "no-cache" THEN "no-cache"
            WHEN resp_cache_control contains "no-store" THEN "no-store"
            WHEN resp_cache_control contains "must-revalidate" THEN "must-revalidate"
            WHEN resp_cache_control contains "immutable" THEN "immutable"
            WHEN resp_cache_control contains "max-age=0" THEN "max age 0"
            WHEN resp_cache_control contains "no-cache" AND resp_cache_control contains "no-store" AND resp_cache_control contains "must-revalidate" THEN "no caching"
            ELSE "other"
       END as cache_header
FROM httparchive:runs.2017_10_15_requests
WHERE (resp_etag = "" AND resp_last_modified = "")
GROUP BY cache_header
)
ORDER BY resource_count desc
```

> Original query from https://discuss.httparchive.org/t/how-many-resources-return-last-modified-and-or-etag-values/407

cache_header | percent | resource_count
-- | -- | -- 
no-cache | 48.0 | 6656302
no cache header | 32.0 | 4394414
other | 16.0 | 2259399
immutable | 1.0 | 145738
no-store | 1.0 | 126617
must-revalidate | 1.0 | 126371
max age 0 | 1.0 | 124476

Interestingly, the method to avoid caching proposed in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Preventing_caching doesn't seem to be used anywhere.

I'll keep updating this message when I dig more results.

**Comment by molant** [comment]
Adding @jakearchibald, @mikewest, @aliams @torgo see if they have any comments about the `cache-control` rule or if they think someone else should be involved.

**Comment by molant** [comment]
Another link to review: https://www.smashingmagazine.com/2017/11/understanding-vary-header/

**Comment by Malvoz** [comment]
> Interestingly, the method to avoid caching proposed in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Preventing_caching doesn't seem to be used anywhere.

FWIW, I edited the code snippet on MDN some time ago - to prevent caching it now suggests: `Cache-Control: no-store`. When @molant linked to it, it was proposing `Cache-Control: no-cache, no-store, must-revalidate` which is overkill. https://www.mnot.net/blog/2017/03/16/browser-caching confirms that browsers correctly respond to each directive, e.g.:

> `Cache-Control: no-store` in responses bypasses all tested browser caches correctly, and `Cache-Control: no-cache` in responses will correctly get stored, but checked on each request.

so there's really no scenario where `Cache-Control: no-cache, no-store, must-revalidate` would be considered proper usage.
