### ISSUE TITLE
Add ability to link to a certain error

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1429]
Originally reported by @alrra in https://github.com/webhintio/webhint.io/issues/413

----------------

When there are a lot of errors, I often find myself linking to the scan page, but also copy pasting the error, which is not ideal.

We should have a ![](https://user-images.githubusercontent.com/1223565/37779213-18a95104-2da9-11e8-9526-dbe8dacdc40d.png) for all of these:

![](https://user-images.githubusercontent.com/1223565/37779124-dc420a30-2da8-11e8-8954-709f432da3b9.png)

**Comment by kshyju** [comment]
+1
