### ISSUE TITLE
Builds fail on `node` v11 because missing `canvas-prebuilt`

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1445]
Ref https://travis-ci.org/webhintio/hint/jobs/445942975#L1002-L1034

---

This issue is more of FYI then anything else.

**Comment by alrra** [comment]
This issues is more of FYI then anything else.

**Comment by molant** [comment]
I'll ping him.

**Comment by molant** [comment]
Maybe have a fallback to compile `canvas`?

**Comment by molant** [comment]
BTW<jsdom [will soon have canvas 2.0 support](https://github.com/jsdom/jsdom/pull/1964)

**Comment by sarvaje** [comment]
> BTW, jsdom will soon have canvas 2.0 support

In fact, it is already published: https://github.com/jsdom/jsdom/blob/master/Changelog.md

**Comment by molant** [comment]
Some updates about this.

* `canvas` will automatically download the binaries under release of `canvas-prebuilt`. `canvas-prebuilt` will not have another release on npm
* `jsdom` 13 drops support for `canvas` < 2
* there are binaries for Linux and Windows for node 11 and `canvas` 2.0.1
![image.png](https://images.zenhubusercontent.com/56d5e96d6caf56c9d38d18fe/a2f8ec36-db39-48b0-b827-82815e3f8621)

I'm upgrading version in #1465 but I'm starting to think that `canvas` should be an optional dependency and we should try to better handle when loading fails. E.g.: the vscode extension will complain if we've downloaded a version that is not for node 8 (current version used by vscode). This might involve doing a PR to jsdom to change how it's being loaded among other things.

@webhintio/core what do you think?

**Comment by antross** [comment]
What about dropping `canvas` entirely? If we don't include it, `jsdom` won't try to use it.

I understand this would provide a less realistic experience when using `connector-jsdom`, but I'm starting to think this isn't worth the trouble for supporting a few extra APIs - especially when a bunch of other visual APIs don't work in `jsdom` anyway.

**Comment by molant** [comment]
> What about dropping `canvas` entirely? If we don't include it, `jsdom` won't try to use it.

IIRC images will not be downloaded and thus provide less accurate results. @sarvaje can you confirm? Maybe this is no longer the case with the new `ResourceLoader`?

In any case I've opened https://github.com/jsdom/jsdom/issues/2410

**Comment by sarvaje** [comment]
>IIRC images will not be downloaded and thus provide less accurate results.

Yep, the resource loader for images is inside a `if (canvas) {` you can see the logic [here](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLImageElement-impl.js#L10).
