### ISSUE TITLE
Try to avoid redirects in CDP

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1452]
When there is a redirect in the website we are analyzing, sometimes under some circumstances, the nodes changes and when we try to get the info for those nodes, the nodes doesn't exists anymore.

**Comment by sarvaje** [comment]
Some examples:
ref: https://github.com/webhintio/scan-issues/issues/19052
ref: https://github.com/webhintio/scan-issues/issues/19613

**Comment by molant** [comment]
@antross maybe something to take into account in the extension connector?


________________________________

**Comment by antross** [comment]
@molant Perhaps, but I'm not sure if the extension connector has a similar dependency - where is this error originating from in the code?

**Comment by antross** [comment]
Got it, thanks.

That won't break the browser extension as the script doing the waiting will be unloaded when the page is navigated (and a new instance injected when the navigation is complete). We'd lose any problems reported prior to the script-triggered redirect, but I think that's okay in this scenario.

**Comment by sarvaje** [comment]
I have been taking a look and I didn't find any method to prevent the redirects.
But there is a few methods that looks that can help us to detect the redirect.

[DOM.documentUpdated](https://chromedevtools.github.io/devtools-protocol/tot/DOM#event-documentUpdated): "Fired when Document has been totally updated. Node ids are no longer valid"
[Page.loadEventFired](https://chromedevtools.github.io/devtools-protocol/tot/Page#event-loadEventFired): Fired when the page dispatch the load event.
[Page.navigatedWithinDocument](https://chromedevtools.github.io/devtools-protocol/tot/Page#event-navigatedWithinDocument): "Fired when same-document navigation happens, e.g. due to history API usage or anchor navigation. (Experimental)" 

The problem is that the node id we are trying to get from the DOM is no longer valid, so we have few options:
1. Ignore the error. The error is mostly calculating the position, but the html doesn't exists anymore, so is ok if the position is undefined.
1. Save the html for all the node at the beginning (I don't like this option, also, the querySelector will fail anyways)
1. Increase the time for the property waitFor.
1. Listen for some of the previous event an change the DOM we are storing.

**Comment by molant** [comment]
After discussing with the team we are going to try to see if we can start from scratch again when we detect this happens. Some thing to take into account:
* Some events/reports might have been fired already, need to clean them up
* Need to reactivate the Network probably
* ??

**Comment by molant** [comment]
The current proposal will not work in the online scanner as most of the code is in `analyze.ts` which is not used. I'll try to see if I have time next week to move part of this logic to `utils-debugging-protocol.ts`.

**Comment by sarvaje** [comment]
@molant I'm going to take a look to this.

**Comment by molant** [comment]
👍

________________________________

**Comment by sarvaje** [comment]
Because of the architecture of webhint, we have the next options:

1. Keep it as in the pr #1467 and the user (e.g. the online scanner) will have the responsibility of analyze the redirected URL or not.
1. Scan an keep all the reports for all the URLs visited.
1. Continue investigating and maybe change the architecture.

For the number two there is also a problem, when we try to get the position of an item that was present before the redirect, we are going to get an error, the ideal action would be report that the element is not present because there was a redirect. The problem with that is that webhint doesn't have a way to say that directly. As a solution, maybe we can use the position `[-2, -2]` to indicate that, and the `formatters` will need to deal with that position.

@webhintio/contributors thoughts?

**Comment by sarvaje** [comment]
@molant, should we close this issue?

**Comment by molant** [comment]
Let's connect it to https://github.com/webhintio/hint/issues/1707 and close it once it is done. Sounds good?

**Comment by molant** [comment]
#1707 is done so closing this.
