### ISSUE TITLE
 Settings Not able to install webhint cli

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1460]
Originally reported by @gakhrejah in https://github.com/webhintio/webhint.io/issues/552

-------------------------------------

Hi Team,

We are trying to use webhint cli in a docker container . But after scanning a url ( hint <some url>) , we are getting the below error. The error says configuration file in invalid 

ERROR LOG
```
added 186 packages from 163 contributors in 19.077s
Error: Connector "jsdom" not found
    at new Engine (/usr/lib/node_modules/hint/dist/src/lib/engine.js:30:19)
    at exports.default (/usr/lib/node_modules/hint/dist/src/lib/cli/analyze.js:223:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

We are using below node version
Node version : v10.12.0 

Steps followed to install the webhint cli
1) npm install -g --engine-strict hint
2) npm create hintrc -> we have use the default .hintrc file 
3) hint www.google.com -> after running this we are getting error

Please let us know what steps we should take to install the webhint cli and get a report generated .

**Comment by molant** [comment]
Hi @gakhrejah,

If you are going to use the default configuration you don't need to run `npm create hintrc`, webhint will use the built-in default one.

Couple things:
* Are you running node x86 or x64?
* Can you please run `hint https://www.google.com --debug` and paste the output in a comment?

Thanks!

**Comment by NehaOberoi92** [comment]
Hi, 
Thanks!
Please find attached logs. Also, we are using x64.
[webhintlogs.txt](https://github.com/webhintio/hint/files/2528818/webhintlogs.txt)

**Comment by gakhrejah** [comment]
Hi Team,

Please update on this ticket

**Comment by molant** [comment]
Sorry about the delay. We had some internal issues that took priority and completely forgot about this.
It looks like the error is when trying to load canvas:

> ResourceError: Error loading shared library libpng12.so.0: No such file or directory (needed by /usr/lib/node_modules/hint/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node)

Since this bug was reported we've done a few changes related to canvas that should hopefully fix this issue:

* [Make canvas optional](https://github.com/webhintio/hint/blob/master/packages/connector-jsdom/CHANGELOG.md#bug-fixes--improvements)
* [Update to jsdom 13 and thus canvas 2](https://github.com/webhintio/hint/blob/master/packages/connector-jsdom/CHANGELOG.md#new-features)

Please give it a try and open a new issue if this is still not working.
