### ISSUE TITLE
Look into non-standard `<meta>` tags

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#148]
TODO: investigate what to recommend be used or removed.

* [Apple specific](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html)
* [Microsoft specific](https://msdn.microsoft.com/en-us/library/gg491732.aspx)
* Other?

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/rfcs/issues/29
