### ISSUE TITLE
Update tsconfig schema

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1487]
With TypeScript 3.0 there are new configurations (like `composite`). We have to update our schema to the new version (and find a way to stay in sync).

![image](https://user-images.githubusercontent.com/606594/48289711-46f22f80-e425-11e8-8572-1965ef4e0dbb.png)

**Comment by antross** [comment]
We should at least update the schema in the next sprint. False-positives are a quick way to erode trust.
