### ISSUE TITLE
No documentation for 'accept-encoding: identity' rule

### ISSUE THREAD

**Issue by edmorley** [webhintio/hint#1493]
## Environment

N/A (docs)

## `webhint` configuration

N/A (docs)

## URL for which `webhint` failed

* __URL:__ http://treeherder.mozilla.org/

## Output

One of the failures listed was:

"Response should not be compressed for requests made with 'accept-encoding: identity'"

The "Why is this important" link points to:
https://webhint.io/docs/user-guide/hints/hint-http-compression/#why-is-this-important

...however there is no reference to "identity" on that page.

It would be good to add some documentation about that rule if possible :-)

**Comment by molant** [comment]
@alrra you are the one who did this hint. Want to complete the documentation?
