### ISSUE TITLE
[extension-browser] Reduce webhint bundle size [4]

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1499]
Part of #48.

Current bundle size after PR #2091 is ~6.3MB raw, ~3.1MB minified, and ~0.6MB minified and compressed.

See exactly how each dependency contributes to this size by downloading the breakdown [stats.zip](https://github.com/webhintio/hint/files/2994119/stats.zip), then view `report.html` or use `stats.json` with [webpack visualizer](https://chrisbateman.github.io/webpack-visualizer/).

Opportunities:
* [x] Minify bundle when building for release
* [x] Include only necessary portions of `highlight.js`
* [x] Eliminate `cheerio` dependency
* [x] Include only necessary portions of `lodash`
* [x] Include only necessary portions of `mdn-browser-compat-data`
* [x] Use `acorn` directly for `parser-javascript` (instead of `eslint`)
* [ ] Eliminate `caniuse` dependency
* [ ] Remove `async` package when bundled
* [ ] Remove `mime-db` when bundled
* [ ] Scope `snyk-snapshot.json` to libraries we can detect
* [ ] Mock `debug`

**Comment by antross** [comment]
Here's a tool that can help visualize what's taking up space in a webpack bundle:
https://chrisbateman.github.io/webpack-visualizer/

An initial look puts the top 4 contributors at:
* lodash (~700K)
* axe-core (~540K)
* caniuse (~480K)
* cheerio (~360K)

Both lodash and caniuse can probably be cut down to just the pieces we use, cheerio may be able to be eliminated entirely, and axe-core is probably going to remain as-is.

**Comment by molant** [comment]
@antross is this done? I see it closed but no related commit nor how much the size has improved.

**Comment by antross** [comment]
Good catch. I did not mean to close this.

**Comment by molant** [comment]
I believe we are bundling moment as well (at least we do for snyk and maybe others). That's also another source of potential savings.

**Comment by molant** [comment]
Another package we could mock is `debug`. We are never going to see the output from the extension.

**Comment by molant** [comment]
Related to #1824

**Comment by molant** [comment]
@jdalton can you please point us to the tools we should be using to reduce lodash's size?

**Comment by jdalton** [comment]
Sure!

There's [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) to transform to cherry-picking and [lodash-webpack-plugin](https://www.npmjs.com/package/lodash-webpack-plugin) to reduce extraneous functionality.

**Comment by antross** [comment]
Closing as the initial part of this work is done. Additional opportunities to reduce the bundle size are now being tracked as separate issues and linked to #2101.
