### ISSUE TITLE
Automatically transform markdown links in doc to correct website ones

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1518]
Right now the links in the markdown might not be correct because the website uses different paths
(as reported in https://github.com/webhintio/hint/pull/1486#issuecomment-437424410).

It will be good to improve [`update-content.js`](https://github.com/webhintio/webhint.io/blob/master/helpers/update-content.js) so we can have valid links in the markdown and the website.

The idea is to have all the links work when we are reading the documentation locally via markdown. This means that we will have to update all internal links in our docs to point to `.md` files (the bulk of the work will be in the `hint` package).

For example, `user-guide/index.md` has links to:

* `./troubleshoot/`
* `./concepts/hints/`
* `./concepts/connectors/`
* `./concepts/(...)/`

We will have to update the links to be:

* `./troubleshoot/summary.md`
* `./concepts/hints.md`
* `./concepts/connectors.md`

Based on this, the link transformation should be as follows:

```
if link ends with `index.md` → remove `index.md`
  e.g. `./concepts/index.md → `./concepts/`
if link ends with something different → replace `.md` with `/`
  e.g. `./concepts/hints.md → `./concepts/hints/`
```

Remaining things:

* [x] Check what happens with images. Seems like we have the right paths always.
* [x] Update links when navigating within the same section. E.g.: If we are in `summary.md` and link to `./apache.md`, in the website we actually need to link to `../apache/` because we are under `/summary/`.

**Comment by molant** [comment]
This should probably fix #523 if we add [`markdown-link-check`](https://www.npmjs.com/package/markdown-link-check) as well (haven't tried it so maybe there are some issues with it).

**Comment by molant** [comment]
The idea is to have all the links work when we are reading the documentation locally via markdown. This means that we will have to update all internal links in our docs to point to `.md` files (the bulk of the work will be in the `hint` package).

For example, `user-guide/index.md` has links to:

* `./troubleshoot/`
* `./concepts/hints/`
* `./concepts/connectors/`
* `./concepts/(...)/`

We will have to update the links to be:

* `./troubleshoot/summary.md`
* `./concepts/hints.md`
* `./concepts/connectors.md`

Based on this, the link transformation should be as follows:

```
if link ends with `index.md` → remove `index.md`
  e.g. `./concepts/index.md → `./concepts/`
if link ends with something different → replace `.md` with `/`
  e.g. `./concepts/hints.md → `./concepts/hints/`
```

**Comment by molant** [comment]
I've looked into `markdown-lint-check` and I don't think it will work for us. What's more, I haven't found any package that does what we need so we might have to write something custom for us 😞

Ideally we should

* Validate external links, similar to [`remark-lint-no-dead-urls`](https://www.npmjs.com/package/remark-lint-no-dead-urls)
* Validate relative links by checking the file exists in the filesystem (all the ones I've found are for live sites)
* Validate headers exist when linking to one, similar to [`remark-validate-links`](https://www.npmjs.com/package/remark-validate-links)
* Be capable of ignoring patterns (although we might be able to get away without this)

**Comment by sarvaje** [comment]
> I've looked into markdown-lint-check and I don't think it will work for us. What's more, I haven't found any package that does what we need so we might have to write something custom for us 😞
>
>Ideally we should
>
>Validate external links, similar to remark-lint-no-dead-urls
Validate relative links by checking the file exists in the filesystem (all the ones I've found are for live sites)
Validate headers exist when linking to one, similar to remark-validate-links
Be capable of ignoring patterns (although we might be able to get away without this)

I'm going to open an issue for this.
