### ISSUE TITLE
Update titles and other tweaks of some of the docs

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1520]
Now that we are publishing everything in the website (extensions, parsers, connectors, etc.) we should look into updating some of the names. E.g.:

* All formatter, parser and connector titles are `XXXX formatter/parser/connector` which looks weird in the menu. We can probably drop the last part.
![image](https://user-images.githubusercontent.com/606594/48727204-7273d780-ebe6-11e8-9e2c-7af9982b7b60.png)
* VS Code extension is `webhint extension for Visual Studio Code`. In this case I'd just say `VS Code` or something similar. Also we should add a bit more information and maybe add a gif or similar.

@antross @alrra thoughts?

**Comment by alrra** [comment]
> XXXX formatter/parser/connector... We can probably drop the last part.

> VS Code... Also we should add a bit more information and maybe add a gif

👍
