### ISSUE TITLE
"Configuration schema is not valid" - missing feedback why it is invalid

### ISSUE THREAD

**Issue by donaldpipowitch** [webhintio/hint#1526]
**Propose a new feature/change** 

>   Write a short description of your proposal with (if applicable)
>   some examples of the expected behaviour.

Hi there 👋

I just try out `hint` for the first time. My first use case is running [WCAG2A checks](https://webhint.io/docs/user-guide/hints/hint-axe/#can-the-hint-be-configured). Props for the nice documentation about that 👍

I haven't used `hint` before and so I stripped out the invalid JSON parts and got a configuration like this one:

```json
{
  "hints": {
    "axe": ["error", {
      "runOnly": {
        "type": "tag",
        "values": ["wcag2a"]
      }
    }]
  }
}
```

But running `$ yarn hint http://localhost:9001/` shows this:

```
Configuration schema is not valid
Couldn't find any valid configuration
```

I _guess_ it is, because `connectors` and `formatters` are mandatory? (Because they can be seen [here](https://webhint.io/docs/user-guide/hints/hint-axe/#can-the-hint-be-configured), but without concrete values. However in the [configuration documentation](https://webhint.io/docs/user-guide/configuring-webhint/summary/) it is not highlighted _what_  is actually mandatory.) It would be nice, if the feedback could include the following parts:

1. _What_ was validated? E.g. change "Configuration schema is not valid" to something like "Configuration schema of /path-to/.hintc is not valid", so I know _my_ configuration was actually validated. (I _think_ it was picked up correctly, but I'm not sure.)
2. _Why_ is it invalid? E.g. change "Configuration schema is not valid" to something like "Configuration schema is not valid. The following fields are missing: connectors, formatters." (Similar to the way how Webpack gives feedback to invalid configurations.)

**Comment by sarvaje** [comment]
I'm working on this, and there is some cases where the result can be a little bit confusing. The results are "prettified" from the result that `ajv` return.
For example, if we change the value of a `hint` to an invalid numeric value e.g. `8`, this is the result:
![image](https://user-images.githubusercontent.com/1581288/50711091-d7ae4b80-1021-11e9-9328-697138e12565.png)

The last error, I think it is related to the other 'path' in the schema that is not failing, I mean, `hints` property can be a `hintobject` or an `array`, but because what we have in the config is an invalid `hintobject`, then the validator return than the property `hints` should be array.

The same logic is apply to the error number 2.

In this case, IMO, the ideal result would be, or just the first message, or all the messages joined with ` or `, but in this case, the message will be huge.

@webhintio/core thoughts?

**Comment by molant** [comment]
Even the first message is a bit weird with that "Or", right?

IMO we should have one message and starting right after "Or" (i.e.: hints should be equal to...)


________________________________

**Comment by sarvaje** [comment]
Anyways, the message for sure that may need some changes, but that is not the "issue" I was trying to expose the thing is if message 2 and 3 are necessary, or if message 2 should go with message 1, etc.

**Comment by molant** [comment]
And I think it should be just one message that better fits the user intention. If it's a number just provide the 0, 1, 2. If it's a string then off, warning, error, etc.


________________________________

**Comment by sarvaje** [comment]
and... how do you know what message is the one that fits better the user intention? I mean, `ajv` return an array of errors, and maybe we can ignore the message number 3, because the datapath is a sub path of the datapath in message 1 and 2, but how do you know that 1 fit better the user intention than 2?

**Comment by molant** [comment]
Are the error messages always in the same order or do they change depending on the wrong value (i.e.: string, number)?


________________________________

**Comment by sarvaje** [comment]
I don't know, I need to make more tests.

**Comment by antross** [comment]
Even if the order seems consistent at the moment, depending on the order of the messages is likely a fragile approach so I'd recommend we don't take it. Getting some feedback to the user here, even if the string isn't exactly what we want, is better than none.

To improve the messages in the future, it may be worth us filing an issue with ajv to see if either we're missing something obvious or if there's an improvement we can help make to get better messages.

**Comment by molant** [comment]
> Even if the order seems consistent at the moment, depending on the order of the messages is likely a fragile approach 

What I wanted to know is if ajv will output first the error that's most likely to be based on the type of the property. With @sarvaje's example, if the value is 8 get the errors related to the numbers first, if it's a string, then error, warning, off, etc. If that's the case we can probably use the first message. If that's not the case and the order is always the same no matter the used type, then we should just output whatever we receive.

**Comment by sarvaje** [comment]
The order of the errors depends on the schema file. For example, if we modify the file `packages/hint/src/lib/config/config-schema.json` editing the property 'hint->anyOf' to:
```json
"anyOf": [
                {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "array",
                                "items": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "object"
                                    }
                                ],
                                "minItems": 2,
                                "maxItems": 2
                            }
                        ]
                    },
                    "minItems": 1
                },
                {
                    "$ref": "#/definitions/hintobject"
                }
            ],
```
The error number 3 would be the number 1.

**Comment by molant** [comment]
Then I think we should print all the messages.


________________________________

**Comment by sarvaje** [comment]
Me too.

In that case, I think https://github.com/webhintio/hint/pull/1602 is ready to review. :)
