### ISSUE TITLE
Your VS Code extension is affected by a security issue and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [webhintio/hint#1540]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [x] Fix the extension, submit an update to the marketplace
2) [x] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by molant** [comment]
[The extension has been updated and published to 1.0.4](https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint) that shouldn't have that dependency.

**Comment by auchenberg** [comment]
We have run our validation and lifted the block. Thanks for the prompt action!
