### ISSUE TITLE
[release] Weird output when entering bad credentials for GitHub multiple times when releasing

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1546]
![image](https://user-images.githubusercontent.com/606594/49129083-17e01880-f283-11e8-886b-5fabf0fb1f80.png)

First time I incorrectly types my password. Second time I must have reused the same OTP because it hadn't expired yet. The rest I don't know.

In any case is weird that the error messages alternate.

**Comment by alrra** [comment]
https://blog.npmjs.org/post/180599338975/401-scoped-packages/?

**Comment by molant** [comment]
Going to close this as I haven't experienced it for the last few releases. I'll reopen if I encounter it again.
