### ISSUE TITLE
[hint-no-disallowed-headers] Removing `Server` header can break libraries

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1560]
When updating one of my other projects to remove the `Server` header based on feedback from `hint-no-disallowed-headers` I broke establishing a connection over WebSockets using SignalR 2.3.0 on iOS.

I'm still working on fully root-causing why this happened (and why only iOS was affected), but wanted to raise the issue here as it suggests removing the `Server` header is not always "safe" depending on the libraries involved in a project.

**Comment by molant** [comment]
IIRC you can remove the versions only and it should pass.


________________________________
