### ISSUE TITLE
[hint-compat-api] Ignore "cursor is not supported on webview_android browser"

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1588]
(Found testing the compat-api hint on webhint.io using the modified browser extension from #1574).

This is technically true, but not all that interesting since "cursor" doesn't have much meaning on a touch device anyway.

I'm thinking we should add a built-in list of ignored properties which consumers of the hint can choose to override (and are listed in our documentation) based on the work proposed in #1623.

**Comment by borgitas21** [comment]
Duplicated? #1623
Fixed as part of #1660
