### ISSUE TITLE
Create isolated repro and report AppInsights `EventEmitter` warning

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1590]
The other create packages don't have the `EventEmitter` warning message. I believe is a compat issue between AppInsights and inquirer/rxjs. I'm willing to take out analytics from this package and rely on downloads from npm to track this (and maybe open an issue to try once a newer version of AppInsights is released?).

_Originally posted by @molant in https://github.com/webhintio/hint/pull/1587#issuecomment-447941954_

**Comment by molant** [comment]
Closing this as I don't think we will ever get to it, there are new versions of the packages and we are even using our own implementation in the browser that we should probably propagate elsewhere.
