### ISSUE TITLE
[parser-html] Automatically disable in connectors which support HTML

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1593]
Currently if `parser-html` is used with the `jsdom` connector, we get double reports as both will generate `element::*` events.

Original thoughts from @molant on options:
- Make the configuration fail (not a huge fan)
- Make the parser smarter and disable itself if it receives one of the events it's supposed to send?
- Something else?

I'm in favor of making the parser smarter by recognizing the connector in use will be generated events for HTML. 

Personally I'd propose adding a flag to the `IConnector` interface where a connector can indicate whether or not it will generate `element::*` events and then update `parser-html` to become a no-op if this flag is set.

**Comment by sarvaje** [comment]
> Personally I'd propose adding a flag to the IConnector interface where a connector can indicate whether or not it will generate element::* events and then update parser-html to become a no-op if this flag is set.

I like this idea.

**Comment by molant** [comment]
How will the parser get access to this flag? Via the constructor? Context?

**Comment by antross** [comment]
> How will the parser get access to this flag? Via the constructor? Context?

I was originally assuming via the `Engine` that was already passed into `ParserConstructor`, but I missed that the `connector` property there is currently `private`. It seems too heavy-handed to make this `public` and too special-case to pass a flag into the `ParserConstructor`.

Thinking about this gave me another idea for a more generic solution: how about we extend `FetchEnd` to have a `parsed` flag to indicate a fetched resource has already been parsed? The `jsdom` and `chrome` connectors will then set `parsed: true` when emitting `fetch::end::html` for the top-level resource and `parser-html` will only do extra work if `fetchEnd.parsed` is not set. 

Going forward this would open up the potential to still use `parser-html` for HTML sub-resources (e.g. fragments loaded via XHR) as those are not analyzed by any connector today.

**Comment by molant** [comment]
I believe this will be obsolete once we merge #1943, right? I'm going to move it up to the backlog so we can close it next sprint.

**Comment by antross** [comment]
Yep, we won't want to disable it any longer as connector support will be tied to DOM traversal and `parser-html` will just emit parse events for the original source. Both can and should be available in all contexts going forward.

**Comment by antross** [comment]
No longer needed with DOM traversal refactor.
