### ISSUE TITLE
[Feature] Migrate brotli to built-in implementation 

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1604]
# 🚀 Feature request

## Description

Node will soon have built-in support for brotli per:
https://github.com/nodejs/node/pull/24938
https://twitter.com/addaleax/status/1081653502693257217?s=21

It will be great to migrate our usage to this version.

We will have to see where it lands (node 11 or maybe it gets back ported) and work on a planif it gets back ported to previos versions of node and if not work on a plan to remove our current dependencies in favor of this one.

 Are you willing to work on this?
Yup

## What scenarios will this solve?

Less dependencies to download and keep up to date. Also we had problems with the binaries in the past so less risk.

**Comment by molant** [comment]
Looks like 10.16.0 is going to have brotli built-in as well 🎉
https://twitter.com/mylesborins/status/1128874489180315648?s=21

I'm seriously thinking about dropping support for node 8 just because of this... It will solve a few of the binary issues people are having.

**Comment by molant** [comment]
[These are the current dates for the node versions](https://nodejs.org/en/about/releases/):


| Release | Status | Initial Release | Active LTS Start	| Maintenance LTS Start | End-of-life | 
| ---------|--------|----------------|------------------|--------------------------|-------------- |
| v8 |	Maintenance LTS | 2017-05-30 | 2017-10-31 | 2019-01-01 | 2019-12-31 |
| v10 | Active LTS | 2018-04-24 | 2018-10-30 | 2020-04-01 | 2021-04-01 |
| v12 | Current	| 2019-04-23 | 2019-10-22 | 2021-04-01 | 2022-04-01 |

Even though v8 EOL is 2019-12-31 I believe we should target November ourselves and remove brotli at the same time.

@sarvaje @antross thoughts?

**Comment by sarvaje** [comment]
I don't think we need to wait until v8 EOL, as soon we migrate to v10, the better.

**Comment by antross** [comment]
Agree with the sentiment we shouldn't wait on this. 

Binary dependencies have been a consistent pain so the sooner we eliminate them the better our overall install experience will be (assuming we also eliminate `canvas`).

Plus we already have dependencies that ask for v10 plus. They still work on v8 for the moment using `--ignore-engines`, but who knows how long that will last.

**Comment by molant** [comment]
Working on this right now.
Will also update docs to say to use node 10, etc.
