### ISSUE TITLE
Migrate to Azure Pipelines

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1608]
Per the research done in https://github.com/webhintio/rfcs/issues/63 we should migrate to Azure Pipelines and remove Travis. This depends on having dependabot working (#938)

**Comment by molant** [comment]
Things to do:

* [ ] Run tests in all platforms
* [ ] Cron job to validate links ➡ I think we can skip this with the work @sarvaje is doing in #1543 
* [ ] Notify the website of an update
* [ ] Run Travis + Azure Pipeline side by side
* [ ] Remove Travis

Something else I'm missing @alrra?

**Comment by molant** [comment]
The first parallel run looks promising:

* [Travis](https://travis-ci.org/webhintio/hint/builds/477857970)
* [Pipelines](https://dev.azure.com/webhint/webhint/_build/results?buildId=403&view=results)

2 of the Windows build have failed even after retries. Will have to investigate what's going on and if it's something particular to those node versions.

**Comment by molant** [comment]
* [ ] Figure out why `[skip ci]` doesn't work and if there's an alternative

**Comment by molant** [comment]
To avoid executing a build the comment needs to be `***NO_CI***`. 
[There's a request to support `[skip ci]`](https://developercommunity.visualstudio.com/idea/365801/use-ci-skip-rather-than-no-ci.html?inRegister=true) but it doesn't seem to have too much success (opened in 2017) 😞

We should probably change the commit message and maybe use both until we remove Travis. Thoughts?

**Comment by antross** [comment]
Using both `[skip ci]` and `***NO_CI***` until we remove Travis seems reasonable to me.

**Comment by molant** [comment]
Even though with Azure Pipelines we have 10 workers, I think we can improve build times with other workarounds. Here goes some ideas on how I'm thinking about organizing things to get your feedback:

* **PRs**: Execute on the latest version of node for each platform. @antross proposed this in a conversation we had a few weeks back and I'm leaning more and more towards it. We could have also one LTS and latest versions if we prefer, the idea being to free as many workers as we can.
* **Changes into `master`**: Same as PRs + a job to notify there have been changes to the website
* **Limit builds to the `master` branch and PRs**: If we create branches in the main repo and do a PR they will be running twice
* **Daily at night**: Run a full test with all the platforms and node versions
* Dependabot PRs: Run only on one platform and latest version of node. Most of the errors we've seen with dependencies should affect all platforms. Because dependabot seems to do PRs in batch this should help a lot in those circumstances.

@webhintio/contributors thoughts?

**Comment by molant** [comment]
For notifying the website I just find out there's this awesome thing that allows me to trigger a build when another one finishes it successfully even if it's another repo 😍

![image](https://user-images.githubusercontent.com/606594/51150321-a6502f80-181a-11e9-8f92-1e36b056d04a.png)

**Comment by molant** [comment]
Looks like `***NO_CI***` is not working for some reason 😔
