### ISSUE TITLE
Make tests more reliable

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1613]
For some reason tests on CI aren't super reliable and fail randomly. This is a problem to run a smooth CI system.
Some of the reasons I can think of:
- Concurrency errors when running on less capable hardware. I think that removing all `.serial` should help in there although we should check which tests are the one that fail the most.
- Spawn the web server into its own process. Right now the web server and the tests run in the same process and I think that some of the timeouts we are getting are because of that.

@alrra, @antross, @sarvaje any other idea of things that can be done to improve the reliability?

**Comment by molant** [comment]
> why removing `.serial` will fix the problem? that would add more concurrent tests...

Maybe something related to how we are stubbing or mocking that might not be entirely right. By removing the `.serial` we make sure that each test can be run completely independently of others without relying on `after` and `afterAll`, etc.

We should probably do #1597 before any other work in here.

**Comment by hxlnt** [comment]
Given that #1659 and #4035 are complete, we should be able to close this now.
