### ISSUE TITLE
Suggestion: Compile JSON schemas from TypeScript definitions

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1628]
Using a utility like [typescript-json-schema](https://github.com/YousefED/typescript-json-schema).

This would be particularly useful for custom options for hints (e.g. in [hint-html-checker](https://github.com/webhintio/hint/blob/ac9814ffd53d69056d3698fa3a3f875769630aa9/packages/hint-html-checker/src/hint.ts#L42)), where authoring the schema initially as TypeScript interfaces would allow better compile-time checks and auto-completion for how the hint itself consumes the options. Then compiling down to a json schema consumable by ajv would enable the existing run-time validation checks without having to write the definition twice. Currently we just treat the options objects as "any" in TypeScript.

**Comment by molant** [comment]
Closing in favor of #1594
