### ISSUE TITLE
Support `yarn` when installing missing `.hintrc` packages from CLI

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1630]
Currently this always uses `npm`, but should be able to be refactored to share code with `extension-vscode` which already detects `yarn.lock` and uses either `yarn` or `npm` to install `hint` if missing.

**Comment by shivangg** [comment]
@antross I'm working on this. 

Why checking for `global` flag in case of `npm` but not `yarn` in [extension-vscode](https://github.com/webhintio/hint/blob/60624562af11362cf834f1791c6f3c1dfe84385d/packages/extension-vscode/src/server.ts#L46).

**Comment by antross** [comment]
@shivangg that’s because if we’re installing globally we always use npm. You can see that in the isUsingYarn check on the following lines.
