### ISSUE TITLE
Browser extension v1

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1640]
We are in the final stretch to publish the v1 and we need your help to make it awesome!

# Extensions and installation instructions

* [**Firefox**](https://addons.mozilla.org/en-US/firefox/addon/webhint/)
* [**Edge (Chromium)**](https://microsoftedge.microsoft.com/insider-addons/detail/mlgfbihcfnkaenjpdcngdnhcpkdmcdee)
* [**Chrome**](https://chrome.google.com/webstore/detail/webhint/gccemnpihkbgkdmoogenkbkckppadcag)

# How can you help

Installing, testing and giving feedback in your favorite browser (see links above). Some example of feedback we are looking for:

* 📝 Any issues not in the "Known issues" list, if you find one please add a comment 
* 🤦‍♂️ Depending on the site, the reports can be a bit noisy and/or have some false positives. We want to know about those and fix them. E.g.: even though we try to detect progressive enhancement in the "Supported CSS features" hints, we might not have all the patterns. Or maybe you are using a feature that's safe even if it's not supported in old browser and it isn't in [the ignored list](https://github.com/webhintio/hint/blob/6762a89277bad213b841cee5bb7f7eff4918095f/packages/hint-compat-api/src/helpers/compat-css.ts#L20). Please tell us about them!
* 👎🏼 Are hints that you don't like? Others that should be warnings instead of errors? Vice-versa?
* 🕸 Should we change the default [`browserslist`](https://www.npmjs.com/package/browserslist) configuration for your supported browsers? If so, to what?
* 🐌 Is a website taking too long to get analyzed? Share it!
* 🙅🏾‍♀️ Are you getting different results with different browsers?
* 🤩 If you have an idea of a feature please check if [it hasn't been reported already](https://github.com/webhintio/hint/issues?q=is%3Aissue+label%3Aarea%3Abrowser-extension+is%3Aopen) and open a [feature request issue](https://github.com/webhintio/hint/issues/new?labels=type%3Anew-feature&template=3-feature-request.md&title=%5BFeature%5D+Feature+description)
* 🖖🏿 Any other feedback is also welcome in the discussion of this issue 

🙏🙏🙏Thanks for your help 🙏🙏🙏

# Known issues

* [x] Slow script popup when running Firefox on https://www.microsoftedgeinsider.com/en-us/ (#2316)
* [x] Make analyzing overflow be responsive with narrow width (#2593)

**Comment by antross** [comment]
Current browser extension build for testing:
* [webhint-browser-extension.zip](https://github.com/webhintio/hint/files/2746814/webhint-browser-extension.zip) (Updated 01/10/2019)

**Comment by brendyna** [comment]
When I ran this in Firefox on https://www.microsoftedgeinsider.com/en-us/, I got a yellow bar that popped up saying the webhint script was slowing the browser down. FYI.

**Comment by antross** [comment]
v0.0.5 has been submitted to the extension stores. Test package is available here for side-loading:
* [webhint-0.0.5.zip](https://github.com/webhintio/hint/files/3336807/webhint-0.0.5.zip)

**Comment by antross** [comment]
v0.0.6 has been submitted to the extension stores. Test package is available here for side-loading:
* [webhint-0.0.6.zip](https://github.com/webhintio/hint/files/3414125/webhint-0.0.6.zip)

**Comment by ondras** [comment]
I am unable to scan a website that has inline scripts disabled by CSP. The extension correctly reports this, though.

**Comment by molant** [comment]
@ondras that's with Firefox, right?
Unfortunately it is a current limitation of the browser. Here's the issue that tracks it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by ondras** [comment]
@molant yeah, Firefox. Thanks for the link!

**Comment by molant** [comment]
New versions for Chromium and Firefox
[chromium-webhint-1.0.0.zip](https://github.com/webhintio/hint/files/3632889/chromium-webhint-1.0.0.zip)
[firefox-webhint-1.0.0.zip](https://github.com/webhintio/hint/files/3632888/firefox-webhint-1.0.0.zip)

**Comment by molant** [comment]
New versions

[webhint-chromium-1.0.1.zip](https://github.com/webhintio/hint/files/3649102/webhint-chromium-1.0.1.zip)
[webhint-firefox.1.0.1.zip](https://github.com/webhintio/hint/files/3649103/webhint-firefox.1.0.1.zip)

**Comment by molant** [comment]
Closing this issue as we reached this milestone already 🎉

Thank you everyone who made this possible 🙏

**Comment by molant** [comment]
[webhint-chromium-1.0.3.zip](https://github.com/webhintio/hint/files/3666491/webhint-chromium-1.0.3.zip)

**Comment by molant** [comment]
Sources for version 1.0.3 [hint-master.zip](https://github.com/webhintio/hint/files/3670959/hint-master.zip)

**Comment by molant** [comment]
[webhint-chromium-1.1.0.zip](https://github.com/webhintio/hint/files/3736366/webhint-chromium-1.1.0.zip)
