### ISSUE TITLE
Create store accounts and publish extension in them [1.5]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1641]
Need to create accounts for:

* [x] Create account for Chrome: https://developer.chrome.com/webstore/publish
* [x] Create account for Firefox: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on
  * [x] Add more authors to Firefox (and Chrome if possible)
* [x] Generate bundles for each store

**Comment by molant** [comment]
Firefox account has been created. @antross I haven't seen any place to add multiple developers to the same account or give them publishing permissions :/

**Comment by molant** [comment]
Changing a bit the scope of this issue:

* Auto-increase the version (we will start with `0.0.1` for now until we go out of beta)
* Generate bundles for each store
* Sign them automatically (`web-ext` for Firefox, need to look into Chrome)
* Use the same guid for Firefox so we don't publish it multiple times (is there something to do for Chrome?)

Is there something else I'm forgetting @antross?

**Comment by molant** [comment]
Looks like if we want to autoupdate on Firefox we need to host the extension ourselves and also have a json that we update when there's a new version: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Updates

That will require some work on the website. Need to think how we can do it without complicating things but I don't think I can hack something in 1h so maybe we stick to sideloading until there's something in place 🤔

**Comment by digitarald** [comment]
> That will require some work on the website.

Gecko profiler has web-based install as well and we have not automated it a lot (but also ship not as much): [Instructions](https://github.com/firefox-devtools/Gecko-Profiler-Addon/blob/6d5d3679a9e3a0dfc274fa39bd9365bd643180e6/README.md#packaging-a-new-version). Shouldn't be too hard to get this part of a `gh-pages` based flow though.

**Comment by molant** [comment]
> What would be the downside of hosting webhint on addons.mozilla.org?

That's the plan in a few weeks but first we want to do some self hosting to make sure people using it understand this is beta. The moment you release something on a store people start being very opinionated and I think there are a few tweaks we have to do before then. 
Isthere a way for the extension to be in the store but not available via search? I haven't found anything about it and the beta channel examples seem to be for sideloading only and with extensions already published 😔

**Comment by digitarald** [comment]
Did some inquires on how on best solve this.

I recommend submitting the extension to AMO. As long as it doesn't get featured and doesn't massively grow users, it will not be very visible. There are no option to control visibility in search.

To indicate the early nature of it, addons have the option to be marked experimental:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/8599/57637860-474cbe00-7561-11e9-9cda-ea0b95af4a88.png">

Example: https://addons.mozilla.org/en-US/firefox/addon/perf-marker/

The installation can still be offered through an external site by linking to the XPI.

WDYT, @molant ?

**Comment by molant** [comment]
> WDYT, @molant ?

SGTM. My only concern is that we are using [`applicationinsights-web-basic 2.0.0-rc5`](https://www.npmjs.com/package/@microsoft/applicationinsights-web-basic) which is a RC and not final and IIRC might trigger an error during validation.

I'll try to submit it later today see what happens.

Thanks!

**Comment by molant** [comment]
I've submitted the extension to both stores. Waiting on review which might take a few days because we have some broad permissions...
