### ISSUE TITLE
[Feature] Release script should validate current branch before starting

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1645]
# 🚀 Feature request

## Description

While using the release script sometimes I've messed up by not being in the right branch or the branch pointing to a fork. I think the release script could validate that the current working branch points to the master branch of webhintio/hint to avoid any issue.

Additionally it should probably check that everything is up-to-date and there aren't any pending changes.

## What scenarios will this solve?

This will solve publishing packages that are not the good ones and creating a bad state for future releases.

**Comment by molant** [comment]
@alrra @antross any feedback about this?

**Comment by antross** [comment]
Sounds like a good enhancement to me.
