### ISSUE TITLE
Scanner `details` look broken in Firefox

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#1648]
E.g.: https://webhint.io/scanner/13648822-a735-4204-a601-70417896d990

<img width="24" src="https://user-images.githubusercontent.com/1223565/50907409-29692400-13dc-11e9-8cb5-f124767ed892.png">
<img width="23" src="https://user-images.githubusercontent.com/1223565/50907411-2a01ba80-13dc-11e9-84b3-703bb6f20af8.png">

**Comment by molant** [comment]
This is part of the html-formatter so I'm moving the issue to the other repo.
