### ISSUE TITLE
[extension-browser] Create infra to align UX colors with current browser theme

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1670]
Currently the extension respects the user's choice of light/dark theme, but provides a single implementation of each that doesn't always match the theme of the tools it's running in. This includes work to define themes that align with each of our target browsers and logic to choose the correct styles based on the current browser + theme choice.

**Comment by digitarald** [comment]
Cross-posting from chat via @captainbrosset:

> For browser detection […], you should avoid testing various WebExtension API features to infer whether the extension is running in Firefox or elsewhere, as this is likely to break soon and often.
> 
> You could check the extension url protocol as described in http://www.glazman.org/weblog/dotclear/index.php?post/2018/06/07/Browser-detection-inside-a-WebExtension
> 
> We also have a `browser.runtime.getBrowserInfo` API method (which is "ironically" only supported on Firefox).
> Finally, you could always rely on `navigator.userAgent` but UA strings are usually not a great idea to rely upon.
