### ISSUE TITLE
[extension-browser] a11y testing

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1678]
Tracks testing to validate the browser extension is accessible.

**Comment by molant** [comment]
I'll ping Amanda on this to see what they are currently doing in the DevTools and see what we can automate on our side.

**Comment by antross** [comment]
I chatted with Amanda and running `axe` is the right place to start from an automation perspective. Some manual testing will also be needed to verify scenarios that are difficult to automate, but we should fix all the bugs that can be automatically detected first.

For our purposes we should probably do this by running `axe` as part of `webhint` against the extension. We may discover a few other interesting issues to fix by including all the hints.
