### ISSUE TITLE
Investigate VS Code extension boot up perf [2.5]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1679]

**Comment by jdalton** [comment]
After investigation I believe the majority of the time spent in startup is related to simply loading the modules. On load `hint` is loading more than 2,000 modules from `server.js` (loadWebHint) and 300+ from the `resource-loader`. After applying [`v8-compiler-cache`](https://www.npmjs.com/package/v8-compile-cache) _(modified to work with `Buffer`)_ to both I managed to shave ~500ms off the load time.  However, I think for the biggest win leveraging bundling to produce a single larger module load will improve load time and can be further improved with `v8-compiler-cache`.

Here's [a gist](https://gist.github.com/jdalton/aaf76b03b5077f9bdb3c95bb36640c5f) listing the 2,000+ entries.
