### ISSUE TITLE
[Feature] New category pitfalls

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1683]
# 🚀 Feature request

## Description

There are a few hints (or requests) that don't fit exactly in any of the categories we currently have:

* [button attribute set](#1674)
* [createElement svg](#1625)
* and maybe more

We should create a new category ([pitfalls?](https://github.com/webhintio/hint/pull/1674#discussion_r247334082)).
Using this issue to track any proposals and if not default to this one.

@webhintio/core thoughts?

**Comment by antross** [comment]
I'm okay with "Pitfalls" as the category name. 

I'm sure there's a long list of other potential hints that could fit here once we start thinking about them.

**Comment by molant** [comment]
I believe this Epic is done. We have the new category in code and live in the site with a couple hints. Closing.
