### ISSUE TITLE
[Bug] Browser selection should be radios and not checks

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1685]
# 🐛 Bug report

## Description

The browser selection control currently uses checkboxes instead of radios allowing to select the default values and a custom expression.

> Also I find it weird that I can select the defaults and a custom regexp. Shouldn't it be a radio?

https://github.com/webhintio/hint/pull/1681#pullrequestreview-192481172

![image](https://user-images.githubusercontent.com/606594/51197502-9716c380-18a6-11e9-99dd-99f2d5beb90a.png)

After talking with @antross we believe they should be changed to radios.

**Comment by antross** [comment]
@ststimac What do you think? 

If we switch these to radios a user can still modify the recommended settings by starting the query with `defaults` (or the more explicit text we list under "Recommended settings").
