### ISSUE TITLE
Make sure all `reject` use an `Error` instead of a string

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1745]
# 🐛 Bug report

## Description

In some instances we are returning a `string` instead of an `Error` and it's causing some issues with the upgrade to the latest ava version. Also it kind of makes sense to use `Error`.

**Comment by michaelneu** [comment]
If nobody is working on this yet, I'd like to grab this one.

**Comment by molant** [comment]
Go for it @michaelneu!

**Comment by sarvaje** [comment]
@molant there are some cases where the reject use an object instead of an `Error`, is that ok?

#3489 only takes care of the strings.

**Comment by molant** [comment]
Can you show me an example? We might want to switch to Error and add some properties?

**Comment by sarvaje** [comment]
```ts
const fetchError: FetchError = {
    element: null as any,
    error: err.error ? err.error : err,
    hops,
    resource: href
};

await this.server.emitAsync('fetch::error', fetchError);
debug(`Failed to fetch: ${href}\n${err}`);

await this.server.emitAsync('scan::end', initialEvent);

reject(fetchError);
```

**Comment by molant** [comment]
where is that handled?

**Comment by sarvaje** [comment]
That code is part of the `collect` method in the `connector-jsdom` so it should be handled by the analyzer (if you are using it) or for anyone.

I think we have a couple more cases in the code where we reject an object.

**Comment by molant** [comment]
If the code can be changed to use an error without too many problems I think I prefer that.

**Comment by sarvaje** [comment]
Maybe we can open a new issue to handle that scenario.

**Comment by molant** [comment]
> Maybe we can open a new issue to handle that scenario.

Can you please do it?

**Comment by sarvaje** [comment]
sure thing
