### ISSUE TITLE
[Bug] Not all file names follow the same convention

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1748]
# 🐛 Bug report

## Description

All files should be lower case and dash separated. There are some that don't follow this convention such as `fetchContent.ts` in `connector-chrome`.

**Comment by karansapolia** [comment]
There are more files in `packages/hint/src/lib/enums` , namely `hintscope.ts`, `errorstatus.ts`, `resourcetype.ts` which do not follow the convention. Possibly there are more. If renaming the files does not cause anything to break, I would be more than happy to do the legwork here :-). Should I go ahead with it?
