### ISSUE TITLE
[hint compat] Add architeture documentation

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1749]
# 📚 Docs improvements

The `compat-api` hint is pretty big and complex. We need to document how it works, ideally with some diagrams and such, in an `architecture.md` file to make sure we don't forget how it works in a couple months.

**Comment by borgitas21** [comment]
About the documentation I’m not 100% sure about what kind of diagrams you are expecting. Could you check this diagram and let me know your feedback? 
![compat-api-flow-2](https://user-images.githubusercontent.com/817394/51696024-c21ab900-2004-11e9-8a49-992dc4cf52af.png)

**Comment by molant** [comment]
This diagram looks good. I think that we will need more detail in the documentation with examples of `Error refinement`, quirks, etc.

@antross anything else you can think of?
