### ISSUE TITLE
[Feature] htpasswd support

### ISSUE THREAD

**Issue by selfagency** [webhintio/hint#1750]
# 🚀 Feature request

## Description

 What do you want to be added?
Support for htpasswd logins.

 Are you willing to work on this?
Sure.

## What scenarios will this solve?

 Why do you want/need this?
Working on a development site hosted behind an htpasswd login and want to run webhint tests.

**Comment by molant** [comment]
@selfagency have you tried using the chrome connector and use a Basic Authentication URL as the target? Haven't tried it myself but I think it should work.
