### ISSUE TITLE
[Bug] Commented-out tests in hint-compat-api fail

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1766]
@borgitas21 Can you take a look?

Not sure when these tests were commented out, but if I understand them correctly they should pass (when I uncomment them they fail). We should understand if there's a bug here we should fix.

https://github.com/webhintio/hint/blob/33ab25e1f6e46301185635a4d206ed2865b29774/packages/hint-compat-api/tests/css-next.ts#L212

**Comment by borgitas21** [comment]
Good catch! These tests were outdated, so one of them was failing because the syntax was modified. However, there was an "actual" bug with the other one.
