### ISSUE TITLE
Create a list of all reports generated by existing hints [0.5]

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1775]
Some formats are easier to localize than others, so we need to assess the current set of messages to see what might need changed.

Full list of hints:

* [x] hint-amp-validator 
  * Messages come from third party tool
* [x] hint-apple-touch-icons
  * 'apple-touch-icon' link element should have non-empty 'href' attribute.
  * '${appleTouchIconHref}' could not be fetched (request failed).
  * '${appleTouchIconHref}' could not be fetched (status code: ${response.statusCode}).
  * '${appleTouchIconHref}' should be a valid PNG image.
  * '${appleTouchIconHref}' should be a PNG image.
  * '${appleTouchIconHref}' should be 180x180px.
  * 'apple-touch-icon' link element was not specified.
  * 'apple-touch-icon' link element should have 'rel="apple-touch-icon".
  * 'apple-touch-icon' link element should not have 'sizes' attribute.
  * 'apple-touch-icon' link element should be specified in the '<head>'.
  * 'apple-touch-icon' link element is not needed as one was already specified.
* [x] hint-axe
  * Messages come from third party tool
* [x] hint-babel-config
  * There is no fixed messages or come from node (JSON.parse) or a third party tool.
* [x] hint-button-type
  * Button type attribute has not been set.
  * Invalid button type: ${elementType}.
* [x] hint-compat-api
  * `${feature.displayableName} is not supported by any of your target browsers.`
  * `${feature.displayableName} is not supported by ${browserList}.`
  * `${feature.displayableName} prefixed with ${feature.prefix} is not supported by ${browserList}.`
* [x] hint-content-type
  * Response should include 'content-type' header.
  * 'content-type' header value should be '${userDefinedMediaType}'.
  * 'content-type' header value should be valid (${e.message}).
  * 'content-type' header media type value should be '${mediaType}', not '${originalMediaType}'.
  * 'content-type' header charset value should be '${charset}'${originalCharset ? `, not '${originalCharset}'` : ''}.
  * 'content-type' header value should not contain 'charset=${originalCharset}'.
* [x] hint-create-element-svg
  * SVG elements cannot be created with createElement; use createElementNS instead
* [x] hint-disown-opener
  * '${cutString(await element.outerHTML(), 100)}' should have 'rel' attribute value include ${prettyPrintArray(requiredValues)} ${requiredValues.length === 1 ? 'keyword' : 'keywords'}.
* [x] hint-doctype
  * 'doctype' was not specified.
  * 'doctype' should be specified as '<!doctype html>'.
  * 'doctype' should be specified before anything else.
  * 'doctype' is not needed as one was already specified.
  * Resource has no content.
* [x] hint-highest-available-document-mode
  * Response should include 'x-ua-compatible' header.
  * Response should not include unneeded 'x-ua-compatible' header.
  * 'x-ua-compatible' header value should be 'ie=edge', not '${!originalHeaderValue ? '' : originalHeaderValue}'.
  * 'x-ua-compatible' meta element should not be specified as it is not needed.
  * 'x-ua-compatible' meta element should not be specified, and instead, equivalent HTTP header should be used.
  * 'x-ua-compatible' meta element should be specified.
  * 'x-ua-compatible' meta element 'content' attribute value should be 'ie=edge', not '${!contentValue ? '' : contentValue}'.
  * 'x-ua-compatible' meta element should be specified before all other elements except for '<title>' and other '<meta>' elements.
  * 'x-ua-compatible' meta element should be specified in the '<head>', not '<body>'.
  * 'x-ua-compatible' meta element is not needed as one was already specified.
* [x] hint-html-checker
  * Messages come from third party service
* [x] hint-http-cache
  * No "cache-control" header or empty value found. It should have a value
  * The ${invalidDirectives.size === 1 ? 'directive' : 'directives'} ${Array.from(invalidDirectives.keys()).join(', ')} ${invalidDirectives.size === 1 ? 'is' : 'are'} invalid
  * The following ${invalidValues.size === 1 ? 'directive has' : 'directives have'} an invalid value:\n${directivesToString(invalidValues)}
  * The directive "${nonRecommendedDirective}" is not recommended.
  * The following Cache-Control header is using a wrong combination of directives:\n${header}
  * The target should not be cached, or have a small "max-age" value (${maxAgeTarget}):\n${header}
  * Static resources should have a long cache value (${maxAgeResource}):\nDirectives used: ${header}
  * Static resources should use the "immutable" directive:\nDirectives used: ${header}
  * No configured patterns for cache busting match ${resource}. See docs to add a custom one.
* [x] hint-http-compression
  * Response should include 'vary' header containing 'accept-encoding' value.
  * Response should not be served compressed with Brotli as the compressed size is bigger than the uncompressed one.
  * Response should not be served compressed with gzip as the compressed size is bigger than the uncompressed one.
  * Response should not be served compressed with Zopfli as the compressed size is bigger than the uncompressed one.
  * Response should not be served compressed with Brotli as the compressed size is the same size as the uncompressed one.
  * Response should not be served compressed with gzip as the compressed size is the same size as the uncompressed one.
  * Response should not be served compressed with Zopfli as the compressed size is the same size as the uncompressed one.
  * Could not be fetched when requested compressed with Brotli
  * Response should not be compressed with Brotli over HTTP.
  * Response should be compressed with Brotli when Brotli compression is requested over HTTPS.
  * Response should be compressed with Brotli when Brotli compression is requested over HTTPS, regardless of the user agent.
  * Response should be compressed with gzip when gzip compression is requested.
  * Response should be compressed with Zopfli when gzip compression is requested.
  * Response should be compressed with gzip when gzip compression is requested, regardless of the user agent.
  * Response should be compressed with Zopfli when gzip compression is requested, regardless of the user agent.
  * Response should not be compressed for requests made with 'accept-encoding: identity'.
  * Response should not be compressed.
  * Response should include 'content-encoding: br' header.
  * Response should include 'content-encoding: gzip' header.
  * Response should not include 'content-encoding' header for requests made with 'accept-encoding: identity'.
  * Could not be fetched when requested compressed with Brotli.
  * Could not be fetched when requested compressed with gzip
  * Could not be fetched when requested compressed with gzip.
  * Could not be fetched
  * Response should not be compressed with disallowed '${encoding}' compression method.
  * Could not be fetched when requested uncompressed
  * Response should not include 'content-encoding' header.
* [x] hint-https-only
  * Site should be served over HTTPS.
  * Should not be redirected from HTTPS.
  * Should be served over HTTPS.
* [x] hint-image-optimization-cloudinary
  * No valid configuration for Cloudinary found. Hint could not run.
  * '${cutString(file.originalUrl)}' could be around ${sizeDiff.toFixed(2)}kB (${percentageDiff}%) smaller.
  * Total size savings optimizing the images on '${data.resource}' could be of around ${totalSavings.toFixed(0)}kB.
* [x] hint-manifest-app-name
  * Web app manifest should have '${propertyName}' property.
  * Web app manifest should have non-empty '${propertyName}' property value.
  * Web app manifest should have '${propertyName}' property value under ${shortNameLengthLimit} characters.
* [x] hint-manifest-exists
  * 'manifest' link element was not specified.
  * 'manifest' link element is not needed as one was already specified.
  * 'manifest' link element should have non-empty 'href' attribute.
* [x] hint-manifest-file-extension
  * Web app manifest should have the filename extension '${standardManifestFileExtension}'${fileExtension ? `, not '${fileExtension}'` : ''}.
* [x] hint-manifest-is-valid
  * Web app manifest should not have invalid value '${colorValue}' for property '${property}'.
  * Web app manifest should not have unsupported value '${colorValue}' for property '${property}'.
  * Web app manifest should not have invalid value '${manifest.lang}' for property 'lang'.
  * Web app manifest should contain valid JSON.
  * **Invalid schema messages** --> Not sure how we can translate those automatically
* [x] hint-meta-charset-utf-8
  * 'charset' meta element was not specified.
  * 'charset' meta element should be specified using shorter '<meta charset="utf-8">' form.
  * 'charset' meta element value should be 'utf-8', not '${charsetMetaElement.getAttribute('charset')}'.
  * 'charset' meta element should be the first thing in '<head>'.
  * 'charset' meta element should be specified in the '<head>', not '<body>'.
  * 'charset' meta element is not needed as one was already specified.
* [x] hint-meta-theme-color
  * 'theme-color' meta element was not specified.
  * 'theme-color' meta element 'content' attribute should not have invalid value of '${contentValue}'.
  * 'theme-color' meta element 'content' attribute should not have unsupported value of '${contentValue}'.
  * 'theme-color' meta element 'name' attribute value should be 'theme-color', not '${nameAttributeValue}'.
  * 'theme-color' meta element is not needed as one was already specified.
  * 'theme-color' meta element should be specified in the '<head>', not '<body>'.
* [x] hint-meta-viewport
   * 'viewport' meta element should have non-empty 'content' attribute.
   * 'viewport' meta element 'content' attribute value should not contain unknown property '${key}'.
   * 'viewport' meta element 'content' attribute value should not contain invalid value '${content.invalidValues[key]}' for property '${key}'.
   * 'viewport' meta element 'content' attribute value should not contain disallowed property '${key}'.
   * 'viewport' meta element 'content' attribute value should contain 'width=device-width'.
   * 'viewport' meta element 'content' attribute value should contain 'initial-scale=1'.
   * 'viewport' meta element was not specified.
   * 'viewport' meta element should be specified in the '<head>', not '<body>'.
   * 'viewport' meta element is not needed as one was already specified.
* [x] hint-minified-js
   * JavaScript content should be minified.
* [x] hint-no-bom
   * Content could not be fetched.
   * Text-based resource should not start with BOM character.
* [x] hint-no-broken-links
   * Broken link found (domain not found).
   * Broken link found (${brokenStatusCodes[statusIndex]} response).
   * Broken link found (invalid URL).
   * Broken link found (${brokenStatusCodes[statusIndex]} response).
* [x] hint-no-disallowed-headers
   * 'server' header value should only contain the server name, not '${(response.headers as any).server}'.
   * Response should not include disallowed ${prettyPrintArray(headers)} ${numberOfHeaders === 1 ? 'header' : 'headers'}.
* [x] hint-no-friendly-error-pages
   * Response with status code ${key} should have more than ${threshold} bytes.
* [x] hint-no-html-only-headers
   * Response should not include unneeded ${prettyPrintArray(headers)} ${numberOfHeaders === 1 ? 'header' : 'headers'}.
* [x] hint-no-http-redirects
   * ${response.hops.length} ${response.hops.length === 1 ? 'redirect' : 'redirects'} detected for '${cutString(request.url)}' (max is ${maxHops}).
* [x] hint-no-p3p
   * P3P should not be used as it is deprecated.
* [x] hint-no-protocol-relative-urls
  * '${url}' should not be specified as a protocol-relative URL.
* [x] hint-no-vulnerable-javascript-libraries
   * '${library.name}@${library.version}' has ${vulnerabilities.length} known ${vulnerabilities.length === 1 ? 'vulnerability' : 'vulnerabilities'} (${detail}). See '${link}' for more information.
   * webhint did not return the result fast enough. Please try again later, or report an issue if this problem persists.
   *  Error executing script: '${e.message}'.  Please try again later, or report an issue if this problem persists.
* [x] hint-performance-budget
   * To load all the resources on a ${config.id} network, it will take about ${loadTime.toFixed(1)}s in optimal conditions (that is ${(loadTime - config.load).toFixed(1)}s more than the ${config.load}s target).
* [x] hint-sri
   * Cross-origin scripts need a "crossorigin" attribute to be eligible for integrity validation
   * Attribute "crossorigin" doesn't have a valid value, should "anonymous" or "use-credentials": crossorigin="${crossorigin}"
   * Resource ${resource} requested without the "integrity" attribute
   * The format of the "integrity" attribute should be "sha(256|384|512)-HASH": ${integrity!.substr(0, 10)}…
   * The hash algorithm "${Algorithms[highestAlgorithmPriority]}" doesn't meet the baseline "${this.baseline}"
   * The resource is not delivered via a secure context
   * The hash in the "integrity" attribute doesn't match the received payload.
Expected: ${integrities.join(', ')}
Actual:   ${hashes.join(', ')}
* [x] hint-ssllabs
   * '${resource}' does not support HTTPS.
   * ${serverName}'s grade ${grade} does not meet the minimum ${minimumGrade} required.
   * Could not get results from SSL Labs for '${resource}'.
   * '${resource}' does not support HTTPS.
   * Didn't get any result for ${resource}.
There might be something wrong with SSL Labs servers.
* [x] hint-strict-transport-security
   * Error with getting preload status for ${resource}.
   * Error with getting preload status for ${resource}. There might be something wrong with the verification endpoint.
   * Error with getting preload eligibility for ${resource}.
   * 'strict-transport-security' header should't be specified in pages served over HTTP.
   * 'strict-transport-security' header was not specified
   * 'strict-transport-security' header requires 'max-age' directive
   * 'strict-transport-security' header 'max-age' value should be more than ${minMaxAgeValue}
* [x] hint-stylesheet-limits
   * Maximum of ${maxImports} nested imports reached (${results.imports})
   * Maximum of ${maxRules} CSS rules reached (${results.rules})
   * Maximum of ${maxSheets} stylesheets reached (${results.sheets})
* [x] hint-typescript-config
  * The compiler option "forceConsistentCasingInFileNames" should be enabled to reduce issues when working with different OSes.
  * The compiler option "importHelpers" should be enabled to reduce the output size.
  * Couldn't find package "tslib".
  * The compiler option "removeComments" should be enabled to reduce the output size.
  * The compiler option "strict" should be enabled to reduce type errors.
  * Based on your browser configuration your "compilerOptions.target" should be "${maxESVersion}". Current one is "${target}"
  * Some messages come from node (JSON.parse) or a third party tool.

* [x] hint-validate-set-cookie-header
  * '${headerName}' header doesn't contain a cookie name-value string.
  * '${headerName}' header to set '${cookieName}' has an invalid cookie name.
  * '${headerName}' header to set '${cookieName}' has an invalid cookie value.
  * '${headerName}' header contains prefixes but is from an insecure page.
  * ${headerName} header contains '__Host-' prefix but the 'path' directive doesn't have a value of '/'.
  * ${headerName} header contains '__Host-' prefix but the 'domain' directive is set.
  * Insecure sites (${resource}) can't set cookies with the 'secure' directive.
  * '${headerName}' header to set '${cookieName}' doesn't have the 'secure' directive.
  * '${headerName}' header to set '${cookieName}' doesn't have the 'httponly' directive.
  * Invalid date in 'expires' value of the '${headerName}' header to set '${cookieName}'.
  * Invalid date format in 'expires' value of the '${headerName}' header to set '${cookieName}'. The recommended format is: ${utcTimeString}
  * Internet Explorer (IE 6, IE 7, and IE 8) doesn't support 'max-age' directive in the '${headerName}' header to set '${cookieName}'.
  * The 'max-age' attribute takes precedence when both 'expires' and 'max-age' both exist.
* [x] hint-webpack-config
  * webpack configuration file not found in your project.
  * webpack is not installed in your project.
  * The parser webpack-config should be activated
  * The parser typescript-config should be activated
  * TypeScript `compilerOptions.module` option should be `esnext`
  * The parser babel-config should be activated
  * Babel presets `modules` option should be `false`
  * \`${config.devtool.toString()}\` not recommended for prodution
  * Message from node if package load fails.
* [x] hint-x-content-type-options
  * Response should include 'x-content-type-options' header.
  * 'x-content-type-options' header value should be 'nosniff', not '${headerValue}'.

**Comment by molant** [comment]
@antross any suggestion as to how to store this information?

**Comment by antross** [comment]
How about a JSON file or a spreadsheet?

**Comment by sarvaje** [comment]
All messages should be added to the list.
