### ISSUE TITLE
Create an icon for new "Pitfalls" category

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1777]

**Comment by ststimac** [comment]
<img width="833" alt="screen shot 2019-02-05 at 11 44 26 am" src="https://user-images.githubusercontent.com/18073131/52299970-9f10d300-293b-11e9-9523-7a9f35146d72.png">

@antross @molant @sarvaje I have a few options for a "pitfalls" icon. Kind of tricky and I may be taking the term too literally so if anyone else has any other ideas please let me know. Also looking for feedback on this.

**Comment by molant** [comment]
I like the ones with the foot 😁

**Comment by antross** [comment]
I've been playing the latest Tomb Raider lately and the spikes are all too familiar...

My vote is for the spikes on the dark circle. The foot over the bear trap is my runner-up, though I'd want to see how that one fits in with the other icons.

No bright ideas on other ways to portray this, unfortunately.

**Comment by ststimac** [comment]
Should I add an option with the spikes and the foot?

**Comment by antross** [comment]
I'd probably still vote for the current spikes one. Which one do you prefer?

**Comment by ststimac** [comment]
And I'll post that here.

**Comment by ststimac** [comment]
Pitfalls icons inline with the rest of the icons:

<img width="473" alt="screen shot 2019-02-05 at 2 13 52 pm" src="https://user-images.githubusercontent.com/18073131/52307762-5fa0b180-2950-11e9-93f9-f43a262084de.png">

**Comment by molant** [comment]
Bear trap?

**Comment by ststimac** [comment]
Ok, we'll use the bear trap. :D

**Comment by antross** [comment]
Works for me. :)

**Comment by ststimac** [comment]
@antross I have this in a branch under the webhint.io site repo, is that ok?

**Comment by sarvaje** [comment]
I like the bear trap too :)

**Comment by antross** [comment]
> I have this in a branch under the webhint.io site repo, is that ok?

Let's open a PR to add it to the same folder as the other icons in the site. I don't think it should matter that we're not using it just yet. Sound ok to everyone?

**Comment by molant** [comment]
Webhint.io branch is fine!

________________________________

**Comment by ststimac** [comment]
Some code needs to be added so that the icon actually shows up. I can do this today.

Current site:

![pitfalls-icon](https://user-images.githubusercontent.com/18073131/52435808-93eaae00-2ac7-11e9-8035-9f18709953da.JPG)

**Comment by antross** [comment]
@ststimac That'd be awesome if you have time. Thanks for catching this!

**Comment by molant** [comment]
It's done

**Comment by molant** [comment]
Although it might take a while to get it published because CI

**Comment by ststimac** [comment]
So I don't need to do anything? 

The icon isn't coming through on the scan results page either but I'm not sure how that is being pulled in because the icon classes aren't being used.

**Comment by molant** [comment]
@sarvaje the `src` of the image is set to `unknown`:

![image.png](https://images.zenhubusercontent.com/56d5e96d6caf56c9d38d18fe/7305395e-1864-4243-abbd-b55236643cf5)

**Comment by sarvaje** [comment]
We need to be sure that the website is using the last version of the html formatter.

**Comment by molant** [comment]
The icon in the hints page is showing up already. I've updated the formatter version in the website so when Azure Pipelines gets to it we should see it.

**Comment by molant** [comment]
All icons are now in the website. Closing this issue.
