### ISSUE TITLE
[Bug] formatter property needs to be an array

### ISSUE THREAD

**Issue by renestalder** [webhintio/hint#1865]
# 🐛 Bug report

## Description

Currently when defining the `formatter` property as described in the documentation with a single string, the CLI will show an error as the formatter property is processed with Array.map() (based on the error description).

## Environment

* __`hint` version:__ 4.4.0
* __`Node.js` version:__ 10.15.0
* __`OS`:__ macOS Mojave
* __URL for which webhint failed:__ Independent

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
  "connector": {
    "name": "chrome",
    "options": {
      "flags": ["--headless"]
    }
  },
  "formatters": "html",
  "hints": {
    "axe": "error"
  }
}
```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
TypeError: config.formatters.map is not a function
    at Function.toAbsolutePaths (/projectpath/node_modules/hint/dist/src/lib/config.js:203:51)
    at Function.loadConfigFile (/projectpath/node_modules/hint/dist/src/lib/config.js:173:23)
    at getUserConfig (/projectpath/node_modules/hint/dist/src/lib/cli/analyze.js:126:47)
    at exports.default (/projectpath/node_modules/hint/dist/src/lib/cli/analyze.js:191:30)
    at projectpath/node_modules/hint/dist/src/lib/cli/actions.js:7:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
A valid configuration file can't be found. Do you want to use the default configuration? To know more about the default configuration see: https://webhint.io/docs/user-guide/#default-configuration (Y/n)
```

</details>

**Comment by molant** [comment]
Taking a look at this now. Thanks for reporting it @renestalder !

**Comment by molant** [comment]
The schema currently allows `string | Array` but when loading the configuration we are expecting an array. I think this is a leftover from the migration from `formatter` to `formatters` so we have 2 options:

1. Update the schema and documentations which should be relatively easy and allign with the rest of the options like `parsers`
1. Make it work with just a string and thus modifying all the load config methods and tests

@webhintio/core my vote is with 1. What do you think?

-

**Comment by sarvaje** [comment]
My vote is 1.

**Comment by molant** [comment]
There's a PR now with the fix https://github.com/webhintio/hint/pull/1867
