### ISSUE TITLE
[docs] Issue with 'Compatibility'

### ISSUE THREAD

**Issue by renestalder** [webhintio/hint#1874]
https://webhint.io/docs/user-guide/hints/compatibility/index.html

The 4 compat-api links of the sub topics are broken:

compat-api/css-next
compat-api/css
compat-api/html-next
compat-api/html

I can make a pull request with the fixed links, but I want to make sure that #1596 doesn't address this issue already.

**Comment by sarvaje** [comment]
> Interestingly, the webpack and typescript rules seem to work and they are basically the same thing 🤔
@sarvaje will you take a look?

I'm taking a look, with the new PR https://github.com/webhintio/webhint.io/pull/633 I think this will not be a problem, but for some reason, I don't see the compact API rules in the compatibility section. I'm going to investigate that.

**Comment by molant** [comment]
@sarvaje I've already explained what the problem is above :)

https://app.zenhub.com/workspaces/webhint-5bc4f59f4b5806bc2bed23d0/issues/webhintio/hint/1874#issuecomment-462225592

**Comment by sarvaje** [comment]
@molant but with the new PR, I think that is not a problem anymore. The problem I see is another one.

**Comment by sarvaje** [comment]
Ahhh, @molant you are right, that can be the problem in the index file too.

**Comment by molant** [comment]
Going to take care of this now 💪

**Comment by molant** [comment]
There's now a pr for this (#1884)
