### ISSUE TITLE
Refactor connectors to unify DOM access

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1882]

**Comment by sarvaje** [comment]
We have talk about using the `parser-html` for this. The `parser-html` use `jsdom` to parse the script and also evaluate scripts.

I've been investigating a littler bit, talking with @molant and @antross these are some of the options we have:
1. Keep the parser as is, but each connector will use their own `evaluate` to run scripts. (except `connector-local` that will use the one from the parser)
1. Keep `jsdom` for the parser and remove the `evaluate`. The parser will just traverse through the elements. (this will need add the option to evaluate scripts in the `connector-local` using its own `jsdom` to run scripts.
1. Remove jsdom and use `cheerio` for the traversing using a workaround (until v1) to get the location of the elements. https://github.com/cheeriojs/cheerio/issues/1084
1. Use a parser like `parse5` or similar to build this from scratch.

The easier and probably faster option is 1 and 2.
For option 3, we will need some extra work, but I think it can be implemented more or less fast.
IMO, option 4 is not worth the effort.

If we don't want to load jsdom in the browser extension, maybe the best option is cheerio.

@webhintio/core thoughts?

**Comment by antross** [comment]
I vote for 1.

It's the most incremental, but still gets us sharing significant amounts of code and should boost overall performance. We already load plenty else in the browser extension, so I'm okay adding `jsdom` to the list unless/until we've seen an actual problem with using it there.

I don't like that 2, 3, 4 all add an extra parse to `connector-local` as we re-run often using that connector in `extension-vscode`. I want to be careful to avoid regressing performance there.

**Comment by molant** [comment]
Also 1. I'm not thrilled about the parser evaluating JS but right now it probably is the most cost effective. We can always improve later.

**Comment by sarvaje** [comment]
Just one thing I have just thought, the parser shouldn't run any script at all if we want it to be reliable. Remember that there is a lot of API that fail in jsdom, but not in `chrome`. So, I'm not sure if option 1 is the best... (I'm assuming that to use the evaluate, we need to allow running scripts)

**Comment by antross** [comment]
Not a problem as `parser-html` is already configured to only let "outside" scripts run (e.g. ones we inject). The page itself is still evaluated as static content.

https://github.com/webhintio/hint/blob/5385d4479e58a74053531608e2b2b7e0237c54a4/packages/parser-html/src/parser.ts#L64

See https://github.com/jsdom/jsdom#executing-scripts for full details.

**Comment by sarvaje** [comment]
That was my concern, then option 1 is the winner :)

**Comment by antross** [comment]
Fixed as part of #1943.
