### ISSUE TITLE
[Feature]Enable https-only in online scanner

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1903]
# 🚀 Feature request

## Description

Looks like `https-only` is not enabled in the online scanner. Can't really remember why is the case (too many issues?) but we should look into enabling it.

Context:

https://twitter.com/hanno/status/1095789109912707074
https://webhint.io/scanner/dc776434-d6b9-47b2-bc8d-34d5acdc836b

In the [config](https://webhint.io/scanner/config/dc776434-d6b9-47b2-bc8d-34d5acdc836b) you can see that `https-only` is not enabled.

It is not activated in `configuration-web-recommended`.

**Comment by sarvaje** [comment]
@molant I don't remember the reason.

I'm going to activate it.
