### ISSUE TITLE
Scan results overview padding broken on smaller screens

### ISSUE THREAD

**Issue by ststimac** [webhintio/hint#1918]
![screen shot 2019-02-14 at 3 28 49 pm](https://user-images.githubusercontent.com/18073131/52824435-62488880-306d-11e9-80af-bea14fc76f4f.png)

There needs to be a space between "Hints" and the number next to it.

**Comment by molant** [comment]
@ststimac I've move the issue to the hint repo because it comes from the html- formatter.

**Comment by ststimac** [comment]
@molant ok....oddly when I use the HTML Formatter option from the command line and open the generated file the issue is not there, only on the website.

**Comment by sarvaje** [comment]
Maybe it is an issue in the website. We could have some CSS overriding the formatter CSS and causing the issue.

**Comment by molant** [comment]
It might be removed when minifying if it's not the whitespace character `&nbsp;`

**Comment by ststimac** [comment]
It looks like the hint number is being wrapped in a `<span>` via the HTML Formatter but that  `<span>` is not present in the website.

**Comment by ststimac** [comment]
This is what is being output in the HTML Formatter: 

`<p class="rule-tile__sub-category rule-tile__hints"><span>7<span></span></span></p>`

**Comment by ststimac** [comment]
To follow up here, I'm not sure why there are spans being added in the HTML Formatter but not in website. I can add styling just to the website that will fix this but let me know if that's the way I should proceed.

**Comment by sarvaje** [comment]
I need to take a look to this. It is weird that the html is different in one place and in another.

**Comment by sarvaje** [comment]
@ststimac I found the issue, is just an issue with a selector. I will create a PR in the website repostory.

Also I'm moving this issue to the website repo.

**Comment by sarvaje** [comment]
Closing in favor of https://github.com/webhintio/webhint.io/issues/652
