### ISSUE TITLE
[Feature] Find a way to walk the AST only once when analyzing JS

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1925]
# 🚀 Feature request

## Description

Right now when a hint needs to access the JavaScript AST  to analyze anything it needs to create a new `Linter` object:

```ts
public constructor(context: HintContext<ScriptEvents>) {
        const linter = new Linter();

        linter.defineRule('eslint-like-rule', {
            create(eslintContext) {
// ...
            },
            meta: ...
        } );
}
```

We should find a way to only create one shared `linter` object.

## What scenarios will this solve?

Perf improvements and memory reduction

**Comment by antross** [comment]
Should we always have `parser-javascript` create one and include it on the `parse::javascript::end` event?

**Comment by molant** [comment]
I was thinking about using events but wasn't sure which one would be the best one for this.
Also rules call `linter.verify` each time so we should probably try to do all in one go for all hints, otherwise we are just solving half the problem 😔

**Comment by molant** [comment]
With the refactor to use only `acorn` the goal is to not `walk` multiple times now.

**Comment by antross** [comment]
To do this we could return our own `walk` implementation with the same API as `acorn`, but which aggregates the callback objects provided by various hints and then triggers the actual walk (if needed) after the `parse::javascript::end` event has finished being dispatched.

Also, since the updated implementation is already lighter weight we should do some performance testing before spending too much time here to see if such an optimization is still needed.

**Comment by sarvaje** [comment]
Taking a look into this.

This is the signature of walk.simple:

```ts
simple(node: ESTree.Node, visitors: NodeVisitor, base?: NodeVisitor, state?: any)
```

the param `visitors` is ok, that is what we expect to be different, but the user can use a diferent `node`, wich it is ok too, we can do as many walks as `node` we receive.

My biggest concern is that `base` and `state` can also be different, and at the end, we are going to work on a solution for something that maybe never is used hehehe.

Anyways, the solution I'm working now is that I'm going to have an index using `node`, `base` and `state`. So we just will call to walk as many times as combination of those three components we have.

@webhintio/contributors what do you think? It is worthy work on this?

**Comment by molant** [comment]
I think it's worth it. I don't think that `base` and `state` are going to be used that much so this should be useful (🤞)

**Comment by sarvaje** [comment]
There is a draf PR for this: https://github.com/webhintio/hint/pull/2202

If you like the solution, I can work on the tests.

@antross I may need help with the types, can you take a look? :)

**Comment by molant** [comment]
From a quick look it looks good 😊

**Comment by antross** [comment]
@sarvaje No problems with the approach, but let's not worry about the types or unit tests too much until we know how much of an improvement this actually makes. 

Specifically I'd like to see the results of a stress test or two on large JS files so we can compare the performance of this approach vs the current implementation. If you need a candidate file, I'd recommend `extension-browser`'s built `dist/bundle/content-script/webhint.js`.

**Comment by sarvaje** [comment]
I have made a quick test using the bundle `dist/bundle/content-script/webhint.js` and `walk.simple` spend ~110ms to finish.

With the old code, the time is proportional to the number of walks we have in our hints, for 2 `walk`s, ~220ms, 3 `walk`s ~330ms

For this new code, the time is ~110ms and is always the same with 1, 2 or 3 `walk`s.

So the improvement is proportional to the number of `walk`s.

Right now we only have one rule that use `walk`, so we are not going to notice the improvement, but IMO, this is worthy for the future.
