### ISSUE TITLE
[aXe] Improve reporting of hint-axe to link to deque documentation

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1941]
# 🚀 Feature request

## Description

The current report coming from aXe is not as useful as it could be, especially if the user is not aware of some of the a11y issues.

**What do you want to be added?**

We should deep link to the [deque university documentation](https://dequeuniversity.com/rules/axe/3.1/) for each one of the warnings so developers can better understand the issue and fix it.

**Are you willing to work on this?**

Yup

## What scenarios will this solve?

This will help develoeprs improve their site's a11y faster

**Comment by antross** [comment]
Fixed by fb0d984d8eadce74e38ca5063bf0a2c90d2048db
