### ISSUE TITLE
[docs] Issue with 'HTML'

### ISSUE THREAD

**Issue by thany** [webhintio/hint#1945]
https://webhint.io/docs/user-guide/formatters/formatter-html/index.html

It might be worth mentioning what the actual output is. At first I couldn't find where it saved the supposed html output to. It turns out it saves to a folder called `hint-report`.

Maybe also change the CLI output to say where it's been saved?

**Comment by molant** [comment]
@thany there's a PR for this now in https://github.com/webhintio/hint/pull/1950 if you want to take a look and provide feedback.

Thanks!
