### ISSUE TITLE
[Feature/Docs] How to analyze websites that require authentication

### ISSUE THREAD

**Issue by NehaOberoi92** [webhintio/hint#1946]
Hi Team,

I have one query, I am running webhint against my website, how we can scan the website pages which are authenticated. Is there a way to do that ? 

Thanks

**Comment by molant** [comment]
Take a look at (and ignore the edge part, we need to update that):

https://webhint.io/docs/user-guide/configuring-webhint/website-authentication/

https://webhint.io/docs/user-guide/concepts/connectors/#remote-debugging-connector-configuration

The idea is to manually authenticate with Chrome in the website and then use that same browser profile. That will only work if the authentication state persists after closing the browser.
If that is not the case there are 2 more options:

* increase the value of the `waitFor` property so you can manually authenticate
* we could add a new property to connect to a given chrome instance, you authenticate and because the session is still valid webhint should be capable of analyzing. This might require a bit of work (at least updating the docs) but might be worth looking into.
* we are working on a browser extension that you could use. It's still not published so you will have to install it manually and there might be some issues with it (not all hints are active) but might be interesting for you

Let us know how it goes with the links above and we can figure out something!

**Comment by molant** [comment]
Looking into the options of connecting to an existing browser this would be more or less the process:

- Launch chrome with a debugging protocol port open ➡ This will have to be done by the user and will be something like executing `google-chrome --remote-debugging-port=9222` from the command line (adapted to each OS)
- User authenticates in the website
- Create a new option for `port` under the `chrome connector` so the user can use the same one. Following the previous example:
```json
{
  "extends": ["web-recommended"],
  "connector": {
    "name": "chrome",
    "options": {
      "port": 9222
    }
  }
}
```

- Within the chrome-launcher, if `port` is defined in the options use it instead of the one in `cdp.pid` file. We will not be able to close the browser but I think that's fine because we are conneting to one that's already opened. We will probably have to update the closing logic for this particular case

@sarvaje @antross what do you think?

@NehaOberoi92 is this something that will work for your use case? This shouldn't take too long to implement and could work until #421 is implemented (which doesn't have an ETA and will be a lot more costly).

**Comment by antross** [comment]
@NehaOberoi92 to be clear all of these solutions (other than the browser extension) are for the CLI version of webhint. 

Are you already using the CLI or were you running webhint from the https://webhint.io website?

**Comment by NehaOberoi92** [comment]
Thanks for your help

I am using webhint inside docker container alpine image.
So should I install chrome in dockerfile and make sure that my website is logged in before webhint is executed ?

**Comment by molant** [comment]
Where are you getting that docker image? I don't think we have any official release for those.
Any specific reason why you need it to run in a container instead of your dev environment?

**Comment by NehaOberoi92** [comment]
Yes I can see there is no official documentation regarding docker, but I meed to integrate webhint with our CI pipeline and the tool we are using for CI purpose is Drone which works on docker containers.
So to integrate webhint with my pipeline I need to run it in a docker container, I tool a node official image as base image and then installed webhint in that. But now I am not sure how to proceed with authentication, do I need to install chrome in my node dockerfile and then authenticate it to my website

**Comment by molant** [comment]
I understand. Unfortunatelly the solutions I was providing were for manual testing and I don't think they will work in CI 😔

Does the website use basic auth? If so maybe putting the `user/pass` in the url will work.
If not, then we probably need to do something with webdriver and webhint's node API. 
@NehaOberoi92 can you detail how the authentication is done in your website?

We could maybe look into partially implementing #421 to enable filling a form before doing any analysis. This has been asked a few times already and has been in our backlog for a long time.

**Comment by NehaOberoi92** [comment]
I need to confirm but I think it is basic authentication as we need to enter username and password, how can we can do this - If so maybe putting the `user/pass` in the url will work. ? Can you please tell me that. Till that time I will confirm with team if authentication is basic or not

**Comment by molant** [comment]
Try doing something like `hint http://username:password@example.com` where `example.com` will be the url you need to test.

**Comment by NehaOberoi92** [comment]
Let me give it a try and get back to you, thanks for your help !

**Comment by NehaOberoi92** [comment]
It is not basic authentication ,so this solution will not work for me

**Comment by molant** [comment]
@NehaOberoi92 can you detail how the authentication is done in your website? Did the user need to click somwhere to get the form or is it visible on load? Something else that needs to happen?

We can use that as a base to prototype Auth

**Comment by NehaOberoi92** [comment]
I am working to find the answer to your question, Suddenly I have started facing some other issue, 
I was using and installing web recommended packages and it was working fine, but suddenly I am facing error 
https://github.com/webhintio/hint/tree/master/packages/configuration-web-recommended


error - { ResourceError: Module hint/dist/src/lib/enums/hintscope not found when loading @hint/hint-highest-available-document-mode
    at Object.exports.tryToLoadFrom (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:141:19)
    at getResource (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:148:30)
    at sources.some (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:210:21)
    at Array.some (<anonymous>)
    at Object.exports.loadResource (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:209:13)
    at items.reduce (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:262:38)
    at Array.reduce (<anonymous>)
    at loadListOfResources (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:260:35)
    at Object.exports.loadResources (/usr/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:302:90)
    at exports.default (/usr/lib/node_modules/hint/dist/src/lib/cli/analyze.js:196:36) name: 'ResourceError', status: 'DependencyError' }

I tried to install  @hint/hint-highest-available-document-mode globally but no luck. I can see some changes were made recently in above reporsitory around 6 hours back...Is there any issue with webhint currenlty

**Comment by NehaOberoi92** [comment]
I am getting similar type of error for other packages as well for example - { ResourceError: Module hint/dist/src/lib/enums/hint-scope not found when loading @hint/hint-axe
    at Object.exports.tryToLoadFrom (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:141:19)
    at getResource (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:148:30)
    at sources.some (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:210:21)
    at Array.some (<anonymous>)
    at Object.exports.loadResource (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:209:13)
    at items.reduce (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:262:38)
    at Array.reduce (<anonymous>)
    at loadListOfResources (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:260:35)
    at Object.exports.loadResources (/usr/local/lib/node_modules/hint/dist/src/lib/utils/resource-loader.js:302:90)
    at exports.default (/usr/local/lib/node_modules/hint/dist/src/lib/cli/analyze.js:196:36) name: 'ResourceError', status: 'DependencyError' }

**Comment by molant** [comment]
We know, see https://github.com/webhintio/hint/issues/1947#issuecomment-466271450 😔

**Comment by NehaOberoi92** [comment]
Okay thanks for informing ,  for authentication - it is based on oAuth or SAML and we don’t think it can be done through basic authentication

**Comment by molant** [comment]
@NehaOberoi92 can you please describe how do you authenticate in the website? No need to explain the underlying techniques. An example of what I'm looking for:

1. Open website
1. Click on login button
1. Fill form (user and password)
1. Click on "submit" button

Thanks!

**Comment by molant** [comment]
@NehaOberoi92 I've finished publishing all the packages and you should not encounter your last reported error any more.

**Comment by NehaOberoi92** [comment]
@molant : I will get back to you on the exact login procedure of website. In the meanwhile I was trying to do above steps manually. "https://github.com/webhintio/hint/issues/1946#issuecomment-466112997 "

But when I try to do this  it is not scanning . I have attached screenshot
![image](https://user-images.githubusercontent.com/15037065/53326855-97c26100-390c-11e9-9dec-b5b2297c2e1a.png)

**Comment by NehaOberoi92** [comment]
> * Open website
> * Click on login button
> * Fill form (user and password)
> * Click on "submit" button

Website workflow - 
Open the website
It will automatically redirect to login url
Fill in id/pwd combo
click submit
a few redirections happen
it then goes to the landing page

**Comment by NehaOberoi92** [comment]
I have few queries , as I told I am looking for the CI automation -

1.) can we use chrome connector with headless chrome ? If yes can you help me to understand way for the same . I can see in chrome connector documentation we are giving headless flag
2.) How can we automate the authentication rather than manually entering username password ? Can we do using headless chrome feature?
3.) If I am doing scanning manually, what is the way to scan all the urls after login page, can we give multiple urls ?

**Comment by NehaOberoi92** [comment]
Hi @molant , can you help me with any of the above query ?

**Comment by molant** [comment]
Hi @NehaOberoi92,

I've been 😷 the last few days and working on the next spring planning.

> 1.) can we use chrome connector with headless chrome ? If yes can you help me to understand way for the same . I can see in chrome connector documentation we are giving headless flag

Yes, [more information in the connector docs](https://webhint.io/docs/user-guide/concepts/connectors/#remote-debugging-connector-configuration). Your `.hintrc`  should look something like:

```json 
{
  "connector": {
    "name": "chrome",
    "options": {
      "flags": ["--headless", "--disable-gpu"]
    }
  }
``` 

> 2.) How can we automate the authentication rather than manually entering username password ? Can we do using headless chrome feature?

Are you doing any kind of testing other than webhint with this website? If so you should be doing something similar. If not an option will be to use webdriver to do all the authentication, leave the browser open and then connect with webhint. In any case there's some work we will have to do. We are going to start exploring #421 in this sprint so **we should have a supported solution in the next few weeks that doesn't look like a hack**.

> 3.) If I am doing scanning manually, what is the way to scan all the urls after login page, can we give multiple urls ?

You could have a script that loads a text file with all the urls to scan and then executes webhint on each one of them.

The following is a snippet of what you could do:

```js
const { spawnSync } = require('child_process');
const urls = fs.readFileSync('urls.txt', 'utf-8').split('\n');

for(const url of urls) {
  const {stdout, stderr} = spawnSync(`hint`, [url]);
  console.error(stderr);
  console.log(stdout);
}
```

Keep in mind it is really unefficient: we are using sycn calls and analyzing urls one by one. Also I haven't tested it so it might not work. This is to give you an idea of how it could look like and get you started 😊

**Comment by NehaOberoi92** [comment]
1.) Regarding 3rd point I have query, I am trying to execute url after my login page and want consolidate report for all of them is it possible,? I think you specified above to give multiple url in text file and execute one by one 
2.) I would like to know if I can create one package.json file and install all the hints using npm install ? I tried and was able to use webrecommended hint - using https://github.com/webhintio/hint/blob/master/packages/configuration-web-recommended/package.json package.json file. But if I add any other package in this file like for hint amp-validator ...It is not able to work and when I execute hint url it give error that package are missing.

**Comment by molant** [comment]
1. You can create a custom formatter that consolidates everything. I'm not sure how the HTML formatter would consolidate everything without being overwhelming

> Also let me know scan can happen on multiple url's on same authenticated session of chrome ?? I need launch chrome do webhint analysis for one url then for next url scanning I need to close chrome instance and then proceed with scanning..Is this some kind of bug ?

I think that if you have another opened tab with something different webhint shouldn't close it. Can you give it a try? This is a bit of a hack for now but hopefully we can add an option to not close it when sending commands.

2. You should be capable of doing that. For that you will have to install webhint in the scope of the project and install any additional hints locally as well:

```
npm install -d hint
npm install -d @hint/hint-amp-validator
```

And then have a `.hintrc` file such as:

```json
{
  "extends": ["web-recommended"],
  "hints": {
    "amp-validator": "error"
  }
}
```

The above will use the `web-recommended` hints and will activate also the `amp-validator` one.
Do you mind sharing what are the hints that you are most interested in that are not in `web-recommended`?

**Comment by NehaOberoi92** [comment]
1.) I tried below scenario -
Open chrome and authenticate my website login page
Run hint url ( url after login which is default one) - successfull
then again tried hint url (one more url of the same website that we can open after login) - It started analyzing and then stopped ...not started downloading or created any report.

Then I tried-

- Open chrome and authenticate my website login page
- Run hint url ( url after login which is default one) - successfull
- Stop chrome process
- Again open chrome and login
- then again tried hint url (one more url of the same website that we can open after login) - successfull.

So I am bit confused if this is something expected or I am doing something wrong !

2.)

I was trying it in a different way. I have created package.json file in which I specifed all the hints . I used this file - https://github.com/webhintio/hint/blob/master/packages/configuration-web-recommended/package.json
Then I run npm install and it installs all the required hints.
Now if I try to include any other hint for eg..hint-amp-validator 
- I update the same in package.json
- Then run npm install
- Now when I run hint url - it givess error for some of the dependencies of amp-validator or any of the new hint I try ( apart from web recommended) I can not do npm install package name everytime for any hint because I am integrating this with CI/CD solution

**Comment by NehaOberoi92** [comment]
We can also arrange a call to discuss this in case required. @molant

**Comment by NehaOberoi92** [comment]
@molant : I am able to resolve 2nd point , now installing webhint and other hints via package.json
Would like to take your help for multiple url scanning.

**Comment by NehaOberoi92** [comment]
@molant : I can see in webhint documentation for chrome connector it is given - Due to an issue in chrome-launcher, all the instances of the browser need to be closed before run webhint- https://webhint.io/docs/user-guide/connectors/connector-chrome/

So for the multiple url scanning in which I have running chrome instance , then do webhint analysis , do I need to close browser and reopen it before second run analysis ? I am running all this in headless chrome in docker container.

**Comment by NehaOberoi92** [comment]
@molant any update on this ?

**Comment by molant** [comment]
Hi @NehaOberoi92,

I've been busy with #2066 and haven't had the time to look into this until now.

> So for the multiple url scanning in which I have running chrome instance , then do webhint analysis , do I need to close browser and reopen it before second run analysis ? I am running all this in headless chrome in docker container.

You should close any browser instances prior executing webhint for the first time. After that webhint shouldn't have any problems connecting to the browser and using a new tab per url.

**Comment by molant** [comment]
@NehaOberoi92 there's a PR for the proposal on how to tell webhint how to analyze websites that require authentication in https://github.com/webhintio/hint/pull/2166

The most relevant part for you is probably [this section](https://github.com/webhintio/hint/pull/2166/files#diff-5d0a5e63cd4b415734799f42b0dca434R21). Feel free to comment on it and give feedback!

**Comment by NehaOberoi92** [comment]
@molant : Thanks for your efforts, I will check this.

**Comment by molant** [comment]
Moving this under #2200 now that the RFC has been approved. Will start working on this next week 😊

**Comment by molant** [comment]
@NehaOberoi92 after some delay and some hiccups there's finally a PR for this https://github.com/webhintio/hint/pull/2475 

Hopefully we can get it merged soon and released 😊

**Comment by NehaOberoi92** [comment]
Great news :) I hope this feature will be useful for many teams
