### ISSUE TITLE
[Bug] Location reports for HTML elements are often incorrect

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1975]
# 🐛 Bug report

## Description

The line/column provided for elements during traversal are often incorrect as they're generated from a dynamic snapshot of the DOM instead of the original source. This is a hard problem to solve as many elements may have been dynamically added (meaning pointing to somewhere in a JS file may be more appropriate).

At a minimum I'd suggest omitting line/column information when an element can't be resolved back to the original HTML source. In the browser extension webhint can/should still link to the that element in the Elements tab in this case. As a stretch goal, I'd suggest trying to find the template or piece of JavaScript code that caused the element to be created and link there instead of the HTML source code.

**Comment by molant** [comment]
This is fixed now 🎉
