### ISSUE TITLE
[Bug] Expand all close all buttons are cut.

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1985]
Steps to reproduce:

1. Go to https://webhint.io/scanner/
2. Scan an url

Expected:
Expand/collapse all button should looks ok.

Actual:
![image](https://user-images.githubusercontent.com/1581288/53526547-6034ef80-3a99-11e9-9450-d3ef7dcf7e37.png)
![image](https://user-images.githubusercontent.com/1581288/53526558-69be5780-3a99-11e9-8fd5-5f032a828cf4.png)

**Comment by molant** [comment]
Guess this is for @ststimac?

**Comment by sarvaje** [comment]
Yes, or for me if @ststimac  doesn't have time.

**Comment by ststimac** [comment]
I've got time. :)

**Comment by ststimac** [comment]
This is one of the tasks under my "scan results clean up" already.

**Comment by sarvaje** [comment]
Ok!

**Comment by ststimac** [comment]
Hmmm, so this is still showing up in the formatter as cut off.

**Comment by molant** [comment]
In the website or using the CLI? We haven't released a new version of the site in a few days because of an issue with SRI and I'm not sure if the change got in the latest published version if you are using the CLI.

**Comment by ststimac** [comment]
I've cleared my cache just to make sure, but the old code and style is still coming through. Need to look into this.

**Comment by ststimac** [comment]
Still an issue, but only in one state: 

![Screen Shot 2019-03-15 at 9 20 42 AM](https://user-images.githubusercontent.com/18073131/54446198-a5952600-4703-11e9-8341-036005dbb31e.png)

Background position is only being applied to the `closed` class.
