### ISSUE TITLE
[Bug] ignoredUrls doesn't work on SRI anymore [0.5]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1990]
# 🐛 Bug report

## Description

Since https://github.com/webhintio/hint/commit/b230947a15783cd4b5442f97bab3583f52934bca it seems like `ignoredUrls` no longer works with `sri`.
The reason is that the `resource` is now the HTML instead of the asset, which is where the error actually is.

I don't think `ignoredUrls` is accessible to the hints via `context` so the only solution I see is to add a new option to the hint to ignore specifc domains.

This is currently blocking us from deploying a new version of the site 😞

@antross @sarvaje any other ideas?

**Comment by sarvaje** [comment]
I think the problem is the traverse events. In those events, the resource is the url we are analyzing and not the url of the element (src in scripts, href in css).

Maybe an option is adding the ignoredUrls to the context?

**Comment by molant** [comment]
> Maybe an option is adding the ignoredUrls to the context?

We will still have to add code to the rule to handle the issue.
Should we provide the whole `ignoredUrls` or filtered based on the hint? I.e.: if the `ignoredUrl` has a value of `*` we pass it to all the hints. If not, we just pass it to the ones indicated.

**Comment by sarvaje** [comment]
> We will still have to add code to the rule to handle the issue.

Yep. The developer of the hint should take care of this in each rule if necessary.

I like the filtered by hint idea.

**Comment by antross** [comment]
Agreed. Since `HintContext` already has the hint ID, how about making an `ignoreUrl` helper on the context that takes the URL we want to know if we should ignore (and then the hint can take care of *how* to ignore it)?
```ts
public ignoreUrl(url: string): boolean
```

**Comment by kunal999** [comment]
Sorry for reviving an old thread. But I am looking of the reverse scenario. Is there a way for me to use `ignoredUrls` but still be able to trigger the SRI hint for those domains?
The reasoning is that I want to lint the code that belongs to my site, and the HTML code that references those crossorigin resources belongs to my site. So it should trigger the SRI hint. Currently it does not.

**Comment by molant** [comment]
If you are using the CLI you can [ignoreURLs for particular hints](https://webhint.io/docs/user-guide/configuring-webhint/ignoring-domains/) only so you could leave the SRI enabled for those ones.

If you are using the browser extension then you should use a regex that matches all the domains you don't want to analyze:

![image](https://user-images.githubusercontent.com/606594/83307063-a30fd680-a1b8-11ea-8bdc-5ac5e02748ad.png)

And the online scanner does not allow you to configure anything.

Does this answer your question?

**Comment by kunal999** [comment]
Yes. Thank you
