### ISSUE TITLE
[Bug] Compat-API tests fail fairly often on Windows and Azure Pipelines [0.2]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2031]
I believe it's because there are so many tests with different configurations. This causes:

- Fully new instances of Chrome to be created
- Lots of new tests servers

From what @sarvaje told me his machine runs like a 🐌 and is on 🔥 when running these tests (and he has a good one...)

The solutions I can think of are:

- Split the tests in multiple files so ava doesn't try to execute all simultaneously
- Add the option to have a single server when testing on CI (I though I opened an issue for this but can't find it right now)

@webhintio/core thoughts?

**Comment by antross** [comment]
I think more re-use here would be great: both of the server and engine. 

Within each of the four sub-hints the only bit of the configuration that varies is `browserslist`. I bet we could cook up something to run all of the tests within each sub-hint on a single server and potentially even a single `Engine` instance (if the former wasn't enough of an improvement on its own).
