### ISSUE TITLE
[Feature] Include hints for validating PWAs manifest content

### ISSUE THREAD

**Issue by Maggers** [webhintio/hint#2058]
# 🚀 PWA manifest file content validation

## Description
In addition to the PWA rules already proposed in this issue #770, this feature suggestion would go beyond checking for strings existing in the manifest.json to validate that the resources are available. For example, specifying an icon or 2 in the manifest is a good first step but this work would actually visit the resource and ensure a 200 OK is sent back.

 What do you want to be added?
Manifest Field | Rule to pass
----------------|--------------
Short name or name exists | `short_name` or `name` exists
Start URL | Check `start_url` exists and returns `200 OK` when requested
Start URL | Check that the `start_url` is within the scope
Icons | Ensure at least one icon of `192x192` and one of `512x512` exists and icon array and returns `200 OK` when requested

 Are you willing to work on this?
Yes. A little.
## What scenarios will this solve?
This will help when crawling the web for the number of available PWAs and useful for tracking growth or decline over time to gauge the industry interest in PWAs.

**Comment by Maggers** [comment]
#770 referenced above missed the following rules that I've also created for this manifest file feature.
#2059. Hint 15 needs to be reopened,

**Comment by shivangg** [comment]
@molant  Working on this. Looks like this should be a new hint. Can't come up with a good name for this hint😅


> Icons | Ensure at least one icon of 192x192 and one of 512x512 exists and icon array and returns 200 OK when requested  

This has been handled in #462

**Comment by shivangg** [comment]
> `short_name` or `name` exists

This seems to have been handled in the `manifest-app-name`.
