### ISSUE TITLE
[Hint] Check resources are served over SSL

### ISSUE THREAD

**Issue by Maggers** [webhintio/hint#2059]
# 🚀 Hint request
As part of the PWA feature checks, this hint would ensure that resources are delivered over SSL/TLS. 

## Description
For a given start page for a PWA, ensure all resources on the page are served over SSL

 Are you willing to work on this?

## What should be tested exactly?
Open a PWA manifest.json on a site served over SSL - fail if manifest.json exists but isn't served over SSL

Ensure resources specified on the `start_page` or \ of manifest.json location is loaded entirely over SSL - fail if any mixed content

## Relevant links
#2058 #770 
 Any links to documentation, discussions, etc. relevant to the
proposed hint that motivated you to open this issue.

**Comment by molant** [comment]
I think this is covered by https://webhint.io/docs/user-guide/hints/hint-https-only/ that checks that all resources are served over https. What do you think @Maggers ?

**Comment by antross** [comment]
If so, we should probably add it to `configuration-progressive-web-apps` so users get it by default when explicitly testing for PWAs.

**Comment by Maggers** [comment]
Yes that hint covers the reuquirement. Will close this.
