### ISSUE TITLE
hint-sri doesn't decompress requests on manual downloads

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2068]
Hi @molant, I tried to narrow down the problem today.

I can confirm that everything still works as expected with hint v4.4.0, @hint/hint-sri v3.0.2 and @hint/connector-chrome v3.0.0.

When I update everything to the latest version I still get an error although it's a different one now. Only one resource is reported to have a wrong hash. I think the problem is that this particular resource gets loaded with the `request` module of Node.js and not with the browser connector. It's the only resource which goes through this code path in my example.

https://github.com/webhintio/hint/blob/master/packages/hint-sri/src/hint.ts#L422

My server only returns the resources encoded with GZIP but the `request` module doesn't decode GZIP content. The browser on the other hand does.

Do you think it's feasible to replace the `request` module with the connector that is otherwise used to download resources?

_Originally posted by @chrisguttandin in https://github.com/webhintio/hint/issues/2035#issuecomment-471225905_

**Comment by molant** [comment]
> Do you think it's feasible to replace the `request` module with the connector that is otherwise used to download resources?

The biggest problem with that is that we are using `iltorb` which is a binary and could break in some scenarios (notably VS Code if the node version is different). We should at least be capable of handling gzip in this scenario.

This is somehow related to #1604 (starting in node 11.7.0 there's native brotli support).

@sarvaje can you take a look at this? I think we should be capable of doing something similar to what we do in the compression hint. Once this is fixed we need to figure out how to port it back without the current breaking changes we have :/
We might have to create a new branch 4.5.0 and cherry-pick from there so we can get @chrisguttandin unblocked. @antross thoughts?

**Comment by sarvaje** [comment]
@molant do we have the repro steps?

**Comment by molant** [comment]
No, but I've checked the code and it makes sense. We are not decompressing the body if we have to manually download it from the hint and if the server sends it always compressed the content will be different.
