### ISSUE TITLE
[Feature] Add `--tracking` option to `--help` menu

### ISSUE THREAD

**Issue by RyannosaurusRex** [webhintio/hint#2112]
# 🚀 Feature request

## Description

Webhint needs the ability to suppress or specify an opt-in or opt-out for telemetry via a command line parameter.

Example: `npx hint https://webhint.io --telemetry=false`

## What scenarios will this solve?

I'm working on an Azure DevOps plugin for webhint to allow it to be easily added and run as part of an Azure DevOps build and release pipeline. As such, `npx hint https://mysite.com` will be run unattended as part of a build process. A prompt for the telemetry opt-in in an interactive way will hang/fail the build.

**Comment by molant** [comment]
Already implemented, check https://webhint.io/docs/user-guide/telemetry/summary/#what-are-we-tracking

`--tracking=on|off`

You can also use the environment variable`HINT_TRACKING`.

Let us know if that is not enough!

**Comment by RyannosaurusRex** [comment]
Thanks! That's exactly what I needed. 

I checked under --help and didn't see it, but didn't think to look under the telemetry/tracking docs specifically. Feel free to close or potentially change this as feedback to add it under --help.

**Comment by molant** [comment]
I'm repurposing this issue to add it to the `--help` menu.

Btw, there's issue #1260 which is exactly what you are doing. Let us know if you want to contribute it to this repo and make it "official". If so we will give you the right permissions to the org :)

**Comment by RyannosaurusRex** [comment]
Sure, I'd love to! Current repo is at https://github.com/RyannosaurusRex/webhint-azure-devops-task. I can clean it up and then give the webhint organization permissions to take it over.

**Comment by molant** [comment]
Closing this as `--tracking` is already an option under `--help`

![image](https://user-images.githubusercontent.com/606594/55091863-cac45580-506e-11e9-9060-e14533bd0b2e.png)

Will follow up about the ADO task. @RyannosaurusRex if you want us to dogfood it with webhintio/webhint.io let us know!
