### ISSUE TITLE
Refactor per-project eslint commands to offload more to eslintrc.json

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2187]
# 🚀 Feature request

## Description

 What do you want to be added?
Currently each project defines a `lint:js` command which passes a number of CLI arguments. Ideally these would be part of our root `.eslintrc.json` instead (where possible) so they can be shared between projects.

 Are you willing to work on this?
Yes.

## What scenarios will this solve?

 Why do you want/need this?
Any global changes to the `eslint` CLI args require touching every project. Moving these options to the config file will allow updates to be more easily shared.

**Comment by molant** [comment]
Going to take a look at this.
