### ISSUE TITLE
Refactor DOM utils inside hint to `@hint/utils`

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2192]
These should be able to be moved through a combination of moving any types they need to `@hint/utils` as well. The few exceptions are:
1. Use of `HTMLElement` in `content-type`
    * Replace with a minimal local interface
2. Use of `Engine` in `traverse`
    * Replace with `EventEmitter2`

Another thing to do is to re-export the types from `hint`.
Also classes like `HTMLDocument` might be moved as well.

**Comment by antross** [comment]
These should be able to be moved through a combination of moving any types they need to `@hint/utils` as well. The few exceptions are:
1. Use of `HTMLElement` in `content-type`
    * Replace with a minimal local interface
2. Use of `Engine` in `traverse`
    * Replace with `EventEmitter2`

**Comment by molant** [comment]
Another thing to do is to re-export the types from `hint`.
Also classes like `HTMLDocument` might be moved as well.
