### ISSUE TITLE
Friendlier import syntax for `@hint/utils`

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2194]
To get the `fs` utils a user has to do something like:

```ts
import { readFileAsync } from '@hint/utils/dist/src/fs';
```

Ideally this should look like

```ts
import { readFileAsync } from '@hint/utils/fs';
```

so it doesn't look like we are using a private API

**Comment by sarvaje** [comment]
Now, we have access directly from `@hint/utils` to all the method in utils. Do we still want to investigate if this is possible to do?

**Comment by molant** [comment]
With the split and those changes I don't think this is needed anymore. Closing.
