### ISSUE TITLE
Normalize how we exit scripts using `process.exit()`

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2198]
Some packages have a folder `scripts` in them. The scripts in these folder use different ways to exit. Some of those `throw` an exception, others use an exit code.

We should be using `process.exit()` as uncaught exception in promises do not change the exit code and thus can cause problems.

- - - - - - - - - - - - - - - - - - - - -

_Originally posted by @molant in https://github.com/webhintio/hint/pull/2140_

**Comment by Shri-Humrudha** [comment]
I will pick this issue.

**Comment by molant** [comment]
Awesome! Let us know if you need anything @Shri-Humrudha

**Comment by Shri-Humrudha** [comment]
I do see 7 scripts folder in respective packages. What is the best way you recommend to identify the appropriate place to look for.
![Scripts folder](https://user-images.githubusercontent.com/52764236/67119332-c773f100-f19b-11e9-9efa-be666087f2eb.png)

**Comment by molant** [comment]
I think that using the search vscode options is the best way. I've tried the following:

![image](https://user-images.githubusercontent.com/606594/67121302-0a37c800-f1a0-11e9-9846-8852d1c118e3.png)

I think we want to normalize to `throw` exceptions.

**Comment by Shri-Humrudha** [comment]
The issue description says 'Some packages have a folder scripts in them.' where I see the handling are different. The root scripts folder is already standardized to use exit code as appropriate. Please correct me if the understanding is different.

**Comment by molant** [comment]
Most of the scripts in the root use `process.exitCode = 1` or `process.exit(1)`. There are some exceptions like `scripts\dist-management` where we `throw`.

Haven't checked `packages/PACKAGENAME/scripts` but I guess there's going to be a mix too.

We would like to replace all the `process.exit(1)` or `process.exitCode =1` (or variants) to `throw` an error unless there's a good reason to keep the current code 😊

**Comment by molant** [comment]
I've reviewed the scripts and it seems like all are using `throw` were applicable.

The guidance from now on is to use `throw` unless the exception is in a `Promise`, in that case use `process.exitCode = 1`.

Most of our scripts use callbacks so no need to change anything.
