### ISSUE TITLE
[Bug] Bogus error locations for HTTP Headers

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2209]
Hints like `hint-content-type` which point to HTTP headers also include a location, however this location appears to point to a location in the HTML file that triggered the request (as opposed to the listed resource that contains the HTTP header).

This should be fixed to omit line/column information in these cases as it doesn't make sense.

Actual:
```
'content-type' header charset value should be 'utf-8'
https://www.google-analytics.com/analytics.js:1:17293
```

Expected:
```
'content-type' header charset value should be 'utf-8'
https://www.google-analytics.com/analytics.js
```

**Comment by sarvaje** [comment]
@antross @molant what do you think about adding a new option `isServerConfig` (please, feel free to suggest a new name hehehe) to the report method, so if that option is true, the location will be omitted?

**Comment by molant** [comment]
Is this the only scenario where we are sending an HTML element but we want to report the error somewhere else (or we actually don't want to show the HTML)?

E.g.: If I create a hint to validate the metadata of images, `report` is going to receive an `element` but the issue will be inside the image. What should we do in this cases? Maybe we need a richer way to report issues and provide more context?

**Comment by sarvaje** [comment]
I also realize that the position of the element has more priority than the location in the options.

I have change this and right now the priority is:
1. `omitLocation`
1. `location` in options
1. `location` in element
