### ISSUE TITLE
[Bug] Source code snippets can be too large

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2211]
Source code snippets in reports from hints include the entire `outerHTML` of a tag. This works well for items like `<link>`, but when a hint reports something on `<html>` a serialization of the entire document gets included.

These should be fixed to at least be truncated, but perhaps to only include the start tag of the element instead.

**Comment by molant** [comment]
I think this should be done at the `report` level. Otherwise we will have to update all the packages to repeat the code.

What about:

* Include only the opening tag (regular expression?)
* Check the size and if it's still to long truncate it
  * How can truncate this correctly? I don't think we are providing the position relative in the element so if the tag is too long we might have to do something like `<div [...] failingAttribute="blah">` because otherwise we might crop it

Or maybe we just use the opening tag because it should still be a lot shorter than what we are providing right now.

@webhintio/contributors, thoughts?

**Comment by antross** [comment]
I'm okay just including the opening tag regardless of length for now.

**Comment by antross** [comment]
Thinking about this some more, I do think if the overall content is small enough we could still include the outerHTML. This may be useful for leaf items like `<button>`. Maybe we do a size check before switching to just the opening tag?

**Comment by antross** [comment]
Also because `report` deals with different types of source code (e.g. CSS in addition to HTML) I'm not sure it's the right place to put this logic. We'd quickly end up with sniffing logic to determine what type of source code is being reported (though perhaps we should be able to specify the source code type anyway when calling `report`)...

Maybe a helper on our `HTMLElement` type to get the snippet would be better, and then updating hints to call this instead of `outerHTML`.

**Comment by molant** [comment]
> We'd quickly end up with sniffing logic to determine what type of source code is being reported (though perhaps we should be able to specify the source code type anyway when calling report)...

That will be a bit of a change. The printing of the HTML is done already in `report`, the interesting part looks like this:

```js
if (element) {
     // When element is provided, position is an offset in the content.
    position = this.findProblemLocation(element, position);
    sourceCode = element.outerHTML.replace(/[\t]/g, '    ');
}
```

So if there's an `element` we do the `outerHTML`. Haven't checked what we are doing for JS or CSS but maybe `element` should be a bit more abstract and have a `toString()` that's smart enought to know what to do? And we will have an implementation for each type of resource we need.

The other option is to have other properties in the `options` the same way we have `element` (`css`,  `js`, etc.) but that doesn't scale very well...

**Comment by sarvaje** [comment]
We already have an option `codeSnippet` that overwrite any other value. That is the option I'm using in `hint-compat-api` to pass the code snippet.
