### ISSUE TITLE
[Bug] `dispensary` doesn't support node <10

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2214]
# 🐛 Bug report

## Description

When running `yarn` on the root of this project with node < 10 we get the following output:

```
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
warning vscode-webhint@1.0.5: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
error dispensary@0.30.0: The engine "node" is incompatible with this module. Expected version ">= 10.0.0". Got "8.15.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The reason is that `dispensary` requires node 10 minimum (which is used in the browser extension for packaging and linting). I took a quick look at the code and I don't think there's anything us from preventing us to ignore the node version via `yarn install --ignore-engines` until we drop support for node 8 (once node 12 becomes LTS later this year ~Oct).

@webhintio/contributors thoughts?

**Comment by antross** [comment]
I'm okay using `--ignore-engine` until we're ready to drop support for node 8.
