### ISSUE TITLE
[Warning] Difference in node binary used during install

### ISSUE THREAD

**Issue by shivangg** [webhintio/hint#2219]
# 🐛 Bug report

## Description

While running `yarn test`, according to the Webhint [contributor guide](https://webhint.io/docs/contributor-guide/getting-started/development-environment/), after installing webhint `master` using `yarn`, it shows the warning that the node binary used by `yarn` and `npm` are different. See raw output for more info.

**I am using node through `nvm` only.**

![image](https://user-images.githubusercontent.com/10586637/55996797-16fdcf80-5cd6-11e9-8a18-20a322b50e84.png)

## Environment

* __`hint` version:__ NA
* __`Node.js` version:__ `v11.14.0` 
* __`Yarn` version:__ `1.15.2` 
* __`nvm` version:__ `0.34.0` 
* __`which node`:__ `/home/shivangg/.nvm/versions/node/v11.14.0/bin/node` 
* __`which npm`:__ `/home/shivangg/.nvm/versions/node/v11.14.0/bin/npm` 
* __`OS`:__ Ubuntu 16.04  
* __URL for which webhint failed:__ NA

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
<!-- Not Applicable -->

```

</details>

## Debug output

<details>
<summary>webhint’s raw output</summary>

```bash
> @hint/hint-axe@2.1.2 build /home/shivangg/Pesto/week9/hint/packages/hint-axe
> npm-run-all build:*

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1555020581681-0.03967647915236805/node but npm is using /home/shivangg/.nvm/versions/node/v11.14.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @hint/hint-axe@2.1.2 build:assets /home/shivangg/Pesto/week9/hint/packages/hint-axe
> cpx "./{src,tests}/**/{!(*.ts),.!(ts)}" dist

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1555020581681-0.03967647915236805/node but npm is using /home/shivangg/.nvm/versions/node/v11.14.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

```

</details>

**Comment by shivangg** [comment]
Able to resolve this by adding the `scripts-prepend-node-path=auto` line in the `.npmrc` file. Should I open a PR for this?

**Comment by molant** [comment]
So it's in the `.npmrc` file of all the packages, right?
If you want, go for it but if you are in the middle of something (guide, trying something, etc.) don't spend time on this right now.

**Comment by shivangg** [comment]
@molant No, I just had to add this to the `.npmrc` at the root folder (just under `hint`)

**Comment by molant** [comment]
Awesome! Do a PR then @shivangg
