### ISSUE TITLE
Create figma file with new extension design

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2226]

**Comment by ststimac** [comment]
I've emailed the link to the file. Let me know if folks can access.

**Comment by molant** [comment]
@shivangg can you check your email? That's the design we want to implement in the browsers extension. Nothing to do with the file right now other than checking that you have access.

**Comment by shivangg** [comment]
@molant Yeah, I got the access to the Figma file.

**Comment by molant** [comment]
Awesome. I'll close this issue then 😊
