### ISSUE TITLE
[browser extension] Loading should be an overlay instead of a new panel

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2233]
Right now it's a separate panel but we discussed showing it as an overlay.

@ststimac is that still the case? If so maybe a good first issue for @shivangg with the extension? What do you think @antross ?

**Comment by antross** [comment]
I agree this would be a good issue to tackle, but I'd recommend focusing on a few of the other UI updates first.

**Comment by molant** [comment]
This has been implemented in f7c8314fae1f0962a546b56066e695a31288ddc8 🎉
