### ISSUE TITLE
Add support for user actions in chromium puppeteer

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2249]

**Comment by molant** [comment]
Going to start working on this. There's been some requests from Microsoft teams to enable this scenario sooner rather than later so bumping the priority 😄

**Comment by molant** [comment]
Here goes the proposal

Add a new property to the connector configuration called `action` that accepts a `string` that points to the absolute path of a `.js` file.E.g.:

```json
{
  "connector": {
    "name": "puppeteer",
    "options": {
       "action": "/user/molant/action.js"
    }
  }
}
```

The `authentication` and `action` properties are mutually exclusive.

If `action` is present, the connector will check if the file exists and if not throw and exception.

If it exists, then it will dynamically load it and execute it after `await this._page.goto()`

The `action` file should export a well known function that accepts a [`puppeteer.Page`](https://pptr.dev/#?product=Puppeteer&version=v1.20.0&show=api-class-page) and an `options` object that will be the connector one, and returns a `Promise`. The following would be an action that goes to a different site:

```json
const action = async (page, options) => {
  await page.goto('https://anotherwebsite.com');
}

module.exports = {
  action
}
```

By passing `options` to the `action` we will have to allow other properties in the schema than the "official" ones.

On top of that, the connector will drop all network events that aren't related to the last navigation. I.e.: The connector navigates to `page A`, then `page B` and finally `page C`, all the payloads related to `page A` and `page B` (resources, etc.)  will be ignored so only the latest page resources get analyzed.

@antross am I forgetting anything else we discussed? Something that seems off?

**Comment by sarvaje** [comment]
> The authentication and action properties are mutually exclusive.

You can't use both at the same time?

**Comment by molant** [comment]
> You can't use both at the same time?

Nope, if you need to authenticate on a website and run actions you should do all of that in your action script. Otherwise it complicates things to know when to run the authentication. Is it before or after the action?

**Comment by sarvaje** [comment]
> Otherwise it complicates things to know when to run the authentication. Is it before or after the action?

Makes sense

**Comment by antross** [comment]
I think we should allow `options.action` to be a path relative to the `.hintrc` file. Other than that, sounds good.
