### ISSUE TITLE
New util to find chromium browser

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2260]
This is a new util under `packages/utils` that allows to find the path of an installed chromium browser.
This will be based in[ `chrome-finder`](https://raw.githubusercontent.com/GoogleChrome/chrome-launcher/master/src/chrome-finder.ts) from [`chrome-launcher`](https://raw.githubusercontent.com/GoogleChrome/chrome-launcher).

List of browser to find (in Win, macOS, Linux, wsl?):

* Chrome: Stable, Canary
* Chromium
* Edge: Dev, Canary
* Opera: ?
* Brave: ?
* Others: ?

It will have a list of aliases (e.g.: edge-canary) that will automatically try to find the executable for that browser for the current platform.

It should also have a method to run the first one found. I think it should follow the same priority as chrome-launcher in case we end up contributing this upstream.

**Comment by molant** [comment]
This is a new util under `packages/utils` that allows to find the path of an installed chromium browser.
This will be based in[ `chrome-finder`](https://raw.githubusercontent.com/GoogleChrome/chrome-launcher/master/src/chrome-finder.ts) from [`chrome-launcher`](https://raw.githubusercontent.com/GoogleChrome/chrome-launcher).

List of browser to find (in Win, macOS, Linux, wsl?):

* Chrome: Stable, Canary
* Edge: Dev, Canary
* Opera: ?
* Brave: ?
* Others: ?

It will have a list of aliases (e.g.: edge-canary) that will automatically try to find the executable for that browser for the current platform.

It should also have a method to run the first one found. I think it should follow the same priority as chrome-launcher in case we end up contributing this upstream.

**Comment by molant** [comment]
@paulirish let us know if this is something chrome-launcher might be interested and we can first test it here and contribute it later there!

**Comment by paulirish** [comment]
Yeah we'd be into this. sounds good.

**Comment by paulirish** [comment]
> @paulirish let us know if this is something chrome-launcher might be interested and we can first test it here and contribute it later there!

chrome-launcher is ready and waiting for it. ;)

**Comment by molant** [comment]
Hi @paulirish 👋

I'm currently on parental leave so this will have to wait for a bit. I also ended up modifying more than I expected [on that file](https://github.com/webhintio/hint/blob/master/packages/utils/src/chromium-finder.ts) so I'll have to revisit it 🤔
Another thing is that we want to support Firefox when their puppeteer support is out so probably this file will have to change again.
