### ISSUE TITLE
[Bug]  Can't generate custom .hintrc 

### ISSUE THREAD

**Issue by shivangg** [webhintio/hint#2263]
# 🐛 Bug report

## Description

Even after installing the connector packages as well as some hints, the commands exits when I select `custom` for creating custom `hintrc` file.
Predefined `hintrc` works fine.

## Environment

* __`hint` version: v4.5.0 
* __`Node.js` version:v11.14.0 
* __`OS`:Ubuntu 16.04 
* __URL for which webhint failed:Not applicable 

## `devDependencies` in `package.json`

<details>
<summary>devDependencies</summary>

```js
  "devDependencies": {
    "@hint/configuration-development": "^6.1.1",
    "@hint/configuration-web-recommended": "^6.1.0",
    "@hint/connector-chrome": "^3.0.1",
    "@hint/connector-jsdom": "^3.0.1",
    "@hint/hint-stylesheet-limits": "^3.0.1",
    "hint": "^4.5.0"
  }


```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
$ yarn create hintrc

yarn create v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-hintrc@2.0.4" with binaries:
      - create-hintrc
[######################################################################################] 93/93Welcome to hint configuration generator
? Do you want to use a predefined configuration or create your own based on your installed pack
ages? custom
Couldn't find any installed connectors. Visit https://www.npmjs.com/search?q=%hint%2Fconnector.
Done in 15.18s.


$ yarn create hintrc --debug
yarn create v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-hintrc@2.0.4" with binaries:
      - create-hintrc
[######################################################################################] 93/93  hint:home:shivangg:.config:yarn:global:node_modules:create-hintrc:dist:src:create-hintrc Enabling Application Insights +0ms
  hint:home:shivangg:.config:yarn:global:node_modules:create-hintrc:dist:src:create-hintrc Starting --init +0ms
Welcome to hint configuration generator
? Do you want to use a predefined configuration or create your own based on your installed pack
ages? custom
Couldn't find any installed connectors. Visit https://www.npmjs.com/search?q=%hint%2Fconnector.
Done in 11.25s.


```

</details>

![noCustomConfig](https://user-images.githubusercontent.com/10586637/56235071-40d33f80-60a4-11e9-984f-cbd0368c90a7.gif)

**Comment by molant** [comment]
I've investigated a bit more this issue and I believe the problem is in the way we decide how to resolve for the installed dependencies.

Right now we assume that if we are running `_npx` we should look into the global folder in [`hint/utils`](https://github.com/webhintio/hint/blob/43d153e840c91bd2dab7d4189654e4d4969708e4/packages/hint/src/lib/utils/resource-loader.ts#L150). This is right when running `hint` but now when running the create packages 😕

I'm thinking about adding an optional parameter `cwd` or similar so we don't use `NODE_MODULES_ROOT` and pass it from `create-hintrc`.

@webhintio/contributors thoughts?
