### ISSUE TITLE
Refactor `engine.report` to accept a `ReportOptions` object [0.1]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2276]
Not sure we need to do it in this PR, but it'd be nice to refactor `engine.report` to take something similar to `ReportOptions` instead of continuing to add extra parameters...

_Originally posted by @antross in https://github.com/webhintio/hint/pull/2269_

**Comment by karansapolia** [comment]
Hello @molant. I would like to give this a shot. Any helpful pointers?

**Comment by antross** [comment]
Hey @karansapolia, thanks for taking this on!

The change should be as simple as refactoring [`engine.report`](https://github.com/webhintio/hint/blob/15aeb57f2753dce8e6b7c78a9cc5c5376a538835/packages/hint/src/lib/engine.ts#L285) to take a `Problem` object directly. That way when we add new pieces of data to `Problem` we no longer have to update this call.

The only caveat is to ensure the current internal caller in `HintContext` takes on the duty of falling back to a location of `-1, -1` if none is provided. Other than that `engine.report` is already blindly copying properties anyway.

**Comment by karansapolia** [comment]
Hello @antross, My sincere apologies for not following up on this. I came back to this yesterday and was about to push my local commits as PR. The next time I am not available or able to follow up with a task I will make sure to let it be known to the team at the earliest. :disappointed: :cry:

**Comment by molant** [comment]
No worries, usually we would have waited but we want to publish a new version this week with all the breaking changes and that's why @antross did a PR. There are still a few ["good first issue"](https://github.com/webhintio/hint/labels/good%20first%20issue) that are not breaking changes in case you want to pick one 😊

Thanks!

**Comment by antross** [comment]
@karansapolia My apologies as well. I should have checked to ensure you didn't have any work in progress, but I assumed you just hadn't had time to get to this.

As @molant mentioned we'll usually wait anyway, but if a similar situation arises in the future I'll check-in first to ensure we don't duplicate work. Also if you ever have some other in-progress work but need to step away for awhile, feel free to open a draft PR so we can see where it's at.
