### ISSUE TITLE
[docs] Location of the tests.ts file

### ISSUE THREAD

**Issue by shivangg** [webhintio/hint#2314]
The location of the test.ts file is at `hint-<hint-id>/src/tests/tests.ts` as made by the `create-hint` package but the docs say location should be at `src/tests/hints/<hint-id>/tests.ts`

![image](https://user-images.githubusercontent.com/10586637/56728840-5d8d0880-6771-11e9-8a51-4aaeb4ca5a70.png)

https://webhint.io/docs/contributor-guide/how-to/test-rules/index.html

Is the location stated in the docs correct?

**Comment by molant** [comment]
The location in the docs is wrong. Can you please open a PR?

**Comment by shivangg** [comment]
Resolved in #2323
