### ISSUE TITLE
[Feature] Convert both `Category` and `HintScope` to `const enum` [0.1]

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2335]
@molant If we convert both `Category` and `HintScope` to `const enum` then they become type-only imports and can be loaded directly from `hint` without dragging along additional dependencies when bundled.

Looking at the code it doesn't appear we ever use these in a non-const fashion so it should be straightforward.

_Originally posted by @antross in https://github.com/webhintio/hint/pull/2328_

**Comment by antross** [comment]
Turns out some of these enums, specifically both `Category` and `HintScope` are accessed in a non-const way using `Object.entries` in `create-hint` to enumerate all possible options. Makes more sense to keep them non-const in this case, so closing.
