### ISSUE TITLE
[Feature] Update `configuration-pwas` with `manifest-icons`

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2352]
Now that `manifest-icons` is merged, we should update the `configuration-pwa` to have it.

@antross thoughts?

@shivangg want to take care of that?

**Comment by shivangg** [comment]
@molant yeah, absolutely.

**Comment by antross** [comment]
Yep, let's do this. 👍

**Comment by shivangg** [comment]
@molant How will `manifest-icons` be installed unless it is published to NPM. 
On using the `configuration-progressive-web-apps`, this would try to install the package `@hint/hint-manifest-icons`.

**Comment by molant** [comment]
@shivangg [I've answered you in the PR](https://github.com/webhintio/hint/pull/2357#issuecomment-488718476)
