### ISSUE TITLE
Add tests for `json-parser` in `hint` package

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2386]
The problem seems to be with `json-parser`:
![image](https://user-images.githubusercontent.com/606594/57244465-452cb180-6fed-11e9-9943-9eddcdeeb563.png)

I'm going to ignore that file and open an issue to add tests but I wonder if we should move it to the `utils`  package. @antross ?

_Originally posted by @molant in https://github.com/webhintio/hint/pull/2378#issuecomment-489714463_

**Comment by molant** [comment]
@sarvaje I believe this is in another package. Do we still need to do it?

**Comment by sarvaje** [comment]
That is in another package and now we have one test to pass the coverage in that package, but take a look to see if there is something else you would like to test.

**Comment by molant** [comment]
@sarvaje can you please checkif we should increase the coverage for that package regarding this and if not close this issue?

**Comment by sarvaje** [comment]
@molant I have added a few more tests.
