### ISSUE TITLE
[Bug] axe reports an `li` not being in a `ul` when it actually is

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2404]
Found running a scan on bing.com. Needs investigation to figure out if this is a webhint issue or an axe issue.

![image](https://user-images.githubusercontent.com/785009/57397176-b73dfb80-7191-11e9-806c-56728e931b86.png)

![image](https://user-images.githubusercontent.com/785009/57397232-d89ee780-7191-11e9-8308-65836bfdfb34.png)

**Comment by molant** [comment]
Are we bundling the latest version of `axe`? Does it repro with their devtools extension?

**Comment by antross** [comment]
Yes and yes. Guess that makes this an `axe` bug. I'll file an issue over there.

**Comment by antross** [comment]
Already an issue there: https://github.com/dequelabs/axe-core/issues/1171

The root cause appears to be the use of `role="navigation"` on the `ul`.

**Comment by antross** [comment]
Apparently `role="navigation"` is not allowed on `ul`, so `axe` isn't technically incorrect, though the error message could have been more helpful.

https://github.com/w3c/html-aria/issues/10
