### ISSUE TITLE
[Bug] Inconsistent results for Edge & FF webhint extensions

### ISSUE THREAD

**Issue by brendyna** [webhintio/hint#2428]
# 🐛 Bug report

## Description

When using the v1.0 extension in Edge (76.0.158.0 (Official build) canary (64-bit)), side-loaded from the zip in #1640, and v0.0.1 in FF (66.0.5 (64-bit)), loaded from the store, I get the below inconsistent results for the same URL: https://webhint.io.

**Edge**
![image](https://user-images.githubusercontent.com/4712801/57660230-6ca9ee00-759a-11e9-815f-882a5f1f3608.png)

**Firefox**
![image](https://user-images.githubusercontent.com/4712801/57660277-a7ac2180-759a-11e9-9d88-b40f82e6eb3c.png)

## Environment

* __webhint version:__ 
* __Browser version:__ 
* __Operating system:__ 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment]
No longer repros for me on the latest Firefox. 

A fix for [an issue with the `devtools.network.onRequestFinished` API](https://bugzilla.mozilla.org/show_bug.cgi?id=1472653) affecting the extension shipped in Firefox 67 that likely resolved the problem (as the original report was on Firefox 66).
