### ISSUE TITLE
[Bug-extension] Audit fails if invalid `integrity` attribute in markup

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#2434]
# 🐛 Bug report

## Description

Runmning webhint audit fails in Firefox Nightly and DevEd for webhint.io.

## Environment

* __webhint version:__ 0.0.1
* __Browser version:__ 68.0a1 (2019-05-14) (64-bit) & 67.0b18 (64-bit)
* __Operating system:__ OSX
* __URL for which webhint failed:__ webhint.io

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
docsearch is not defined

@https://webhint.io/:1:21
@https://webhint.io/:1:501
```

</details>

**Comment by digitarald** [comment]
`docsearch` CDN dependency fails loading.

Firefox: `None of the “sha384” hashes in the integrity attribute match the content of the subresource.`
Chrome: `Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js' with computed SHA-256 integrity 'qybEsgf0PGiQS22AmoozPs09oRnSC7Gu7eBu4fbS2Ac='. The resource has been blocked.`

Looks like webhint catches that error and stops the audit. Maybe an ignore-error mode could help to run even in flaky sites.

**Comment by digitarald** [comment]
WFM!

**Comment by molant** [comment]
So now is passing, right? Then we have an issue on webhint failing when there's an invalid `integrity` attribute, correct?

I'll reopen this an update the title so we can investigate.

**Comment by digitarald** [comment]
Just to clarify. The audit didn't fail directly because of the resource-integrity issue; but because the JS error that was thrown because of the missing dependency which could not be loaded.

**Comment by antross** [comment]
I need to test, but I suspect this might be the case for any unhandled JS error in the target page. 

The extension is listening for the `error` event on `window` from its isolated content script. The intent was only to pick up unhandled exceptions from the content script itself, but I could easily see this firing for exceptions generated by the page too. 

We can probably work around this by checking if the stack we get back originates within the extension code.
