### ISSUE TITLE
[Bug] Fun facts could be misunderstood as analysis insights

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#2440]
# 🐛 Bug report

## Description

The process dialog tries to be helpful with short fun facts, like `52% of resources aren't cachable` or `The average load time for mobile sites is 19 seconds over 3G connections.`. As a user looking at this, there is little to no indication that this is an insight generated from my page or not and might be misunderstood.

Options might be making these hints more subtle and adding a "Did you know?"

**Comment by molant** [comment]
I like the idea. Additionally we should look into [expanding the list of messages](https://github.com/webhintio/hint/blob/da7769b00b98903911b79d9505a2f1c49a3c636e/packages/extension-browser/src/_locales/en/messages.json#L146).
