### ISSUE TITLE
[Feature] Allow flattened imports from utils

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2444]
So we can `import { isSupported } from '@hint/utils'` instead of having to import `compat` first.

**Comment by antross** [comment]
@sarvaje, @molant If we're wanting to tackle this along with other breaking changes, are there any other utilities we should consider breaking out into their own packages as part of this process (like we recently did for `@hint/utils-compat-data`? 

Currently an update to `@hint/utils` requires nearly all our other packages to be updated. I think if we break these down a little more we can reduce the frequency with which that happens (though it won't help if something left in `@hint/utils` still depends on the broken out package).

**Comment by sarvaje** [comment]
Do you have any particular util in mind?

I think that the localization utils (folder 'i18n') could be a candidate to have its own package. We are using it in almost all the packages, but it is rarely modified.

Something else?

**Comment by antross** [comment]
I was thinking of `dom` in particular, though we may need to take `report` along for the ride to avoid `utils` still having a dependency on it. Since `i18n` already is used by almost everything I don't think we get much of a win by splitting it out into it's own package.

**Comment by sarvaje** [comment]
Because is used everywhere, it makes them depend on @hint/utils, so any change done to any other utils will affect to those packages, that's why I think is a good idea to move it.

**Comment by antross** [comment]
Ah, I see your point. So if we move it does that mean a number of packages can drop direct references to `@hint/utils`? Or would there be other items that still need broken out?

**Comment by sarvaje** [comment]
Because of the `meta.ts` all the hints are going to have a dependency on @hint/uitls (now it dependes on hint, but Category is parte of utils so at some point we should start pointing there and remove the shortcut from 'hint').

One way to remove the dependency in some packages would be moving to its own package:
`types` (this one includes enums and types)
`debug` (this one is also used in a lot of packages I think)
`i18n`

**Comment by antross** [comment]
I think we could move `Category` out as part of `i18n` if we wanted.

Also where possible I think `types` should not be in a separate directory and instead live in the same folder as the related utility the types are for. Once we do that we may not need a separate `types` package - or if we do, it could me a minimal set of core enums/types like `Category` (e.g. if we don't want that as part of `i18n`).

**Comment by sarvaje** [comment]
Now that I'm thinking, this flattened think makes more sense if we have smaller `utils` packages, for example, in the current `@hint/utils`, if I flatten everything, I could do something like this:

```
import { enable } from '@hint/utils`;
```
or even the initial example:
```
import { isSupported } from '@hint/utils'
```

what `enable` does? This will enable the utils?
what `isSupported` does? check if I support an utils?

But If I have my @hint/util-compat-data`, then it is more intuitive what `import { isSupported } from '@hint/utils` does.

**Comment by molant** [comment]
There are also some stuff in hint that I believe should be in `utils` or a separate package. For example `/ src/lib/parser.ts`. This is only for JSON parsing and it is weird to have it in there. I think we had a good reason to keep it (like to big of a change?) but can't remember it.

**Comment by sarvaje** [comment]
Because it has a dependency on `engine`.

**Comment by molant** [comment]
Don't know what `engine` is used after a quick glance TBH 😓

**Comment by antross** [comment]
>  For example / src/lib/parser.ts. This is only for JSON parsing and it is weird to have it in there. I think we had a good reason to keep it (like to big of a change?) but can't remember it.

I don't see a `/src/lib/parser.ts` in `hint`. Were you referring to `/src/lib/types/parser.ts`? If so that's not for JSON parsing, it's the foundation for `parser-*` packages...

**Comment by molant** [comment]
>  Were you referring to `/src/lib/types/parser.ts`?

Yes. It seems mostly oriented to `JSON` parsers:

```json
try {
  const extendedConfig = loadJSONFile(configPath);
  
  configIncludes.push(configPath);
  finalConfigJSON = merge({}, extendedConfig, finalConfigJSON);
}
```

Maybe there's some decoupling that needs to happen there?

**Comment by antross** [comment]
> Maybe there's some decoupling that needs to happen there?

Ah, I see what you mean. Yes, feels like we should decouple that into a helper util that just JSON-related parsers can import/call.

**Comment by sarvaje** [comment]
>Now that I'm thinking, this flattened think makes more sense if we have smaller utils packages, for example, in the current @hint/utils, if I flatten everything, I could do something like this:
>
>import { enable } from '@hint/utils`;
or even the initial example:
>
>import { isSupported } from '@hint/utils'
what enable does? This will enable the utils?
what isSupported does? check if I support an utils?
>
>But If I have my @hint/util-compat-data, then it is more intuitive what import { isSupported } from @hint/utils does.

@molant @antross Thoughts?

**Comment by antross** [comment]
I'm a fan of smaller utils packages, but we should pay careful attention to where we have dependencies. Plus I still don't think we want to have too many of them so some reasonable grouping may still be necessary.

**Comment by molant** [comment]
Smaller utils packages are 👍 with me.
What if we see that a util is only used by one hint? Should we move it there?

**Comment by antross** [comment]
> What if we see that a util is only used by one hint? Should we move it there?

Maybe. We'll probably want to discuss depending on the specific util, though.

**Comment by sarvaje** [comment]
@antross @molant one question, do we still want to be able to access as before.
For example, to access to the function `readFile`, it would be
```
import { readFile } from '@hint/utils'
```

and also

```
import { fs } from '@hint/utils'

const { readFile } = fs;
 ```

**Comment by molant** [comment]
Can we do something like `from '@hint/utils/fs'`?




________________________________

**Comment by antross** [comment]
> > do we still want to be able to access as before.
>
> Can we do something like `from '@hint/utils/fs'`?

I'm fine dropping `import { fs } from '@hint/utils'` in favor of only supporting the flattened `import { readFile } from '@hint/utils'`.

I agree `import { readFile } from '@hint/utils/fs'` may still be needed for webpack purposes, though I expect that to still work anyway unless we move files around.

**Comment by molant** [comment]
So if I understood this correctly:

* Flatten everything to the first level even if it is a bit weird (let's hope there isn't any collusion)
* Implement `Friendlier import syntax` (#2194)

Is that right? If so, I'm OK with it 🙂

**Comment by antross** [comment]
No, I misunderstood about `@hint/utils/fs` - I was thinking that was the existing `@hint/utils/dist/src/fs` reference and I'm not sure we'll need it after this work. I'm thinking more:
* Break out select utils into new `@hint/utils-*` packages (e.g. `debug`, `dom`, `css`, and `i18n`).
* Flatten everything remaining to the first level (fewer things should be weird due to the first step)
