### ISSUE TITLE
[Bug] Correctly support `<base>` in all connectors [3]

### ISSUE THREAD

**Issue by chrisguttandin** [webhintio/hint#2465]
# 🐛 Bug report

We have a few issues with `<base>` not working properly. This can be verified in the `hint-sri` and `hint-no-broken-links`.

* `base` can be relative and our current code path with `new URL` does not accept it and fails. We should use the following code or something similar to fix that (currently available in https://github.com/webhintio/hint/pull/2468/commits/c3c8e2392ff62cf2c6f40eb822f785f95802773c but should be added to `no-broken-links` as well):
```ts
const createResourceURL = (resource: string) => {
    const targetURL = evt.resource;
    const pageDOM = this.context.pageDOM!;
    const baseTags = pageDOM.querySelectorAll('base');
    const hrefAttribute = (baseTags.length === 0) ? '' : (baseTags[0].getAttribute('href') || '');
    const baseURL = new URL(hrefAttribute, targetURL);

    /**
        * `new URL(path, base)` only uses `base.origin` to create
        * the new URL. E.g.:
        *
        * ```ts
        * const resourceURL = new URL('/style.css', 'https://localhost/nested/');
        *
        * resourceURL.href === 'https://localhost/style.css';
        * ```
        * What is needed is `https://localhost/nested/style.css`
        *
        * To solve this we use `path.join` with `base.pathname`
        * and we use the result to create a new `URL`.
        */
    const pathname = join(baseURL.pathname, resource);
    const resourceURL = new URL(pathname, baseURL);

    debug(`calculated "resourceURL": ${resourceURL}`);

    return resourceURL;
};
``` 
* `resourceLoader` for jsdom is not taking into account `base` correctly. Don't know if it's because we pass a `_finalHref` or what. Need to investigate a bit more. Chrome seems to be reporting the right downloaded URL.
* not sure that `getElementByUrl` is going to work correctly with `base`. We might be passing a different URL than expected. Need to double check this.

-------------------------------------------------

**OLD REPORT**

## Description

Hi 👋,
I noticed that the sri hint doesn't resolve URLs with the base href anymore in case it is used. Some time ago I submitted a pull request to fix this. But there seems to be no trace of those changes anymore in the current code.

Here is a link to one of the commits from last August:
https://github.com/webhintio/hint/commit/4817bc884ddd958cfbaa886ddc3ac6103e3d8040

## Environment

* __`hint` version:__ v5.0.1
* __`Node.js` version:__ v11.15.0
* __`OS`:__ OS X
* __URL for which webhint failed:__ https://chrisguttandin.github.io/angular-meetup-berlin-april-2019/slides/1

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
    "browserslist": [
        "last 2 Chrome versions",
        "last 2 Edge versions",
        "last 2 Firefox versions",
        "last 2 Opera versions",
        "last 2 Safari versions"
    ],
    "connector": {
        "name": "chrome",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": [
        "stylish"
    ],
    "hints": {
        "sri": [
            "error",
            {
                "originCriteria": "all"
            }
        ]
    },
    "hintsTimeout": 120000
}


```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
https://chrisguttandin.github.io/web-audio-conference-2016/slides/1
line 0  col 888   Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/styles.0d342b82d21c340a7319.css doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-91mdN8qjIiXZ0GEwH8MUuEbd7RCwdwesDZ0pHnF5f4OZCu7zvmBokMYjKbpxZ17X    sri
line 0  col 1065  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/4.a0a92c5a6ca72d866ceb.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-25mC50a1kqLhhBEcS+mw4DIBVoluiE22vMKqM2Go+auygPWdE+k2F4pZhyyFp1T5          sri
line 0  col 5244  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/polyfills.61ddf36ababb35d368c0.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-+N7evcl7zrc6o9kMNnhuSkeAgOTW8X1IJ9QNoUeFg1Nk2F9iePwtyeN23Xmrfvl8  sri
line 0  col 5440  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/scripts.2e1ce7e02614f3c7a0cf.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-yI6gqSjsIyAXA7wFcWkQ4wOL/tjbFiuFsNpCjJ8HTMnMqjIRVSzn3rALqetuHCfy    sri
line 0  col 5634  Error  The hash in the "integrity" attribute in resource https://chrisguttandin.github.io/web-audio-conference-2016/slides/main.d5fd304e58c763fb812c.js doesn't match the received payload.
Expected: sha384-Ra84+SB14QcHtUcO+5znERKRYeENUMgGJadAsRAqwxAGf/istbLb/TgRhhvQXUsz
Actual:   sha384-hoMI7obu/2kkxYGPqjXQxSxWT6qgUjNl5eks+Jla4W/FiWlpmAS/TeKQTHc7BdVa       sri
✖ Found 5 errors and 0 warnings

✖ Found a total of 5 errors and 0 warnings
```

</details>

It fails because it resolves the URLs incorrectly and downloads a different (the 404.html file) file instead.

**Comment by molant** [comment]
Looking into this

**Comment by chrisguttandin** [comment]
Thanks @molant. Please let me know if I can do anything to support you.

**Comment by molant** [comment]
@chrisguttandin The commit you are pointing at is for `no-broken-links` but you talk about `sri`. Going to see if I can find any commit from you about this in `sri`.

**Comment by chrisguttandin** [comment]
Oh maybe I remembered that incorrectly and I only applied this fix for the `no-broken-links` hint and now due to some other changes I experienced the same problem with the `sri` hint. That could be possible.

**Comment by molant** [comment]
It could be, I'm not seeing anything commit from you that fits the criteria 🤔

https://github.com/webhintio/hint/commits?author=chrisguttandin

**Comment by molant** [comment]
@chrisguttandin let me know if you have time to look into this. Otherwise I'll try to get it done once I finish the new tests for #2419

**Comment by chrisguttandin** [comment]
Okay, I will give it a try.

And sorry for causing confusion.

**Comment by molant** [comment]
> And sorry for causing confusion.

No worries at all and thanks for giving it a try! Right now we are focusing on puppeteer and the browser extension so any help is really appreciated 😊

If you get stuck or is taking you longer than you expected let us know!

**Comment by molant** [comment]
We have a few issues with `<base>` not working properly. This can be verified in the `hint-sri` and `hint-no-broken-links`.

* `base` can be relative and our current code path with `new URL` does not accept it and fails. We should use the following code or something similar to fix that:
```ts
const createResourceURL = (resource: string) => {
    const targetURL = evt.resource;
    const pageDOM = this.context.pageDOM!;
    const baseTags = pageDOM.querySelectorAll('base');
    const hrefAttribute = (baseTags.length === 0) ? '' : (baseTags[0].getAttribute('href') || '');
    const baseURL = new URL(hrefAttribute, targetURL);

    /**
        * `new URL(path, base)` only uses `base.origin` to create
        * the new URL. E.g.:
        *
        * ```ts
        * const resourceURL = new URL('/style.css', 'https://localhost/nested/');
        *
        * resourceURL.href === 'https://localhost/style.css';
        * ```
        * What is needed is `https://localhost/nested/style.css`
        *
        * To solve this we use `path.join` with `base.pathname`
        * and we use the result to create a new `URL`.
        */
    const pathname = join(baseURL.pathname, resource);
    const resourceURL = new URL(pathname, baseURL);

    debug(`calculated "resourceURL": ${resourceURL}`);

    return resourceURL;
};
``` 
* `resourceLoader` for jsdom is not taking into account `base` correctly. Don't know if it's because we pass a `_finalHref` or what. Need to investigate a bit more. Chrome seems to be reporting the right downloaded URL.
* not sure that `getElementByUrl` is going to work correctly with `base`. We might be passing a different URL than expected. Need to double check this.
