### ISSUE TITLE
[Design] Create "small" Fluent icons for hint categories in browser extension

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2506]

**Comment by ststimac** [comment]
Here is a screenshot of the proposed category icons: 

![Screen Shot 2019-06-24 at 4 39 57 PM](https://user-images.githubusercontent.com/18073131/60058837-cc69dd80-969e-11e9-8cbc-20e739c3bd8a.png)

**Comment by ststimac** [comment]
SVGs

[icons.zip](https://github.com/webhintio/hint/files/3322953/icons.zip)

**Comment by antross** [comment]
Nice! Thanks @ststimac!

**Comment by antross** [comment]
Closing this task since the design is done - I've created #2635 to track implementing the new icons.

**Comment by antross** [comment]
@ststimac I just realized we're missing an icon for one category - Pitfalls.

Can you add one for that as well? Thanks!

**Comment by ststimac** [comment]
@antross Pitfalls. New design. Proposing a cone as the one on the webhint.io website is a bit too complex for the line style of icons. 

[Pitfalls.svg.zip](https://github.com/webhintio/hint/files/3340565/Pitfalls.svg.zip)

**Comment by ststimac** [comment]
[icons 2.zip](https://github.com/webhintio/hint/files/3347495/icons.2.zip)
icons round 2

**Comment by antross** [comment]
Closing as all the icons are up-to-date. Implementation is being done in PR #2655.
