### ISSUE TITLE
Refactor `Label` control in extension UI to use CSS grid for layout

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2589]
Change needed in https://github.com/webhintio/hint/blob/master/packages/extension-browser/src/devtools/views/controls/label.css

For an example, see https://github.com/webhintio/hint/blob/master/packages/extension-browser/src/devtools/views/pages/results/category-summary.css

* Should allow the current use of a descendant selector to be removed
* Also should allow `label-text` control to be removed as it should become unnecessary

**Comment by dennisgon** [comment]
Can you assign this issue to me? I will try to help it

**Comment by JackRobards** [comment]
I ended up taking a crack at this since there hadn't been any update in awhile. I hope that that is alright!
