### ISSUE TITLE
Refactor shadow styles to be defined as CSS variables in extension

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2590]
Variables should be defined as part of the `App` control styles for each supported design system ("fluent" and "photon") under https://github.com/webhintio/hint/tree/master/packages/extension-browser/src/devtools/views.

This will allow shadows to be more easily adjusted to match the current design system across controls.

**Comment by blenderskool** [comment]
@antross Can I work on this? 🙂

**Comment by antross** [comment]
Absolutely @blenderskool, thanks for offering! 

Feel free to ask if you need any help.

**Comment by blenderskool** [comment]
@antross Now that I understand the project structure, I found small usage of the shadow styles in the CSS. Do I make those as CSS variables in the `app.photon.css` and `app.fluent.css`?

Also, would they be part of fluent or photon design system?

**Comment by molant** [comment]
> Do I make those as CSS variables in the `app.photon.css` and `app.fluent.css`?

Yes, please!

> Also, would they be part of fluent or photon design system?

What do you mean by that? These styles are only used in the extension. We publish it for Firefox and Chromium and we try to adapt the style to each browser. There's a bit more of work we need to do for photon but in general the shadows should follow the design system of each browser 🙂
