### ISSUE TITLE
[Bug] Gracefully handle very small widths in extension UI

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2593]
A few pieces of the UI such as buttons on the configuration and results page as well as the "Analyzing..." overlay don't look great at the smallest widths allowed for the devtools.

**Comment by jaspreet57** [comment]
Hi @antross I have good sense in design, so thinking of fixing this bug and making UI of extension nice.

Could you please add some screenshots. I just want to be sure that I am on same page. And I am seeing same issue in design as you are.

and what is smallest width allowed or we want to support. Is it 320px or even less upto 240px?

**Comment by antross** [comment]
240px would be ideal if we could handle it, but I understand if practically speaking it's difficult to make the results page usable at that size. Here are the main items I've been looking at

![image](https://user-images.githubusercontent.com/785009/63050297-60d30e00-bea0-11e9-8b7e-ae44c9ae1335.png)
![image](https://user-images.githubusercontent.com/785009/63050311-67618580-bea0-11e9-9135-7d4b0475938f.png)
![image](https://user-images.githubusercontent.com/785009/63050318-6c263980-bea0-11e9-9ad7-715ae6b36a07.png)
