### ISSUE TITLE
[docs] Issue with 'Connectors'

### ISSUE THREAD

**Issue by gesa** [webhintio/hint#2599]
There's are two lines on https://webhint.io/docs/user-guide/concepts/connectors/ which have a link that does not point to any meaningful content.

The specific lines can be found at https://github.com/webhintio/hint/blob/f65e1751117e785387432d1d37c58db1f8c11bdd/packages/hint/docs/user-guide/concepts/connectors.md#L28
https://github.com/webhintio/hint/blob/f65e1751117e785387432d1d37c58db1f8c11bdd/packages/hint/docs/user-guide/concepts/connectors.md#L44 

That link just leads back to itself, not a list of connectors
https://github.com/webhintio/hint/blob/f65e1751117e785387432d1d37c58db1f8c11bdd/packages/hint/docs/user-guide/concepts/connectors.md#L50

**Comment by antross** [comment]
Thanks for the report @gesa!

@sarvaje Can you take a look at this next? At a minimum `[connectors]` should probably link to https://webhint.io/docs/user-guide/connectors/ which actually shows a list of available connectors, but I think it'd be better if we inline a list of connectors on this page along with a brief description of each like we do for `formatters` and `parsers`.

**Comment by sarvaje** [comment]
ok, I'm going to take a look

**Comment by gesa** [comment]
🐇 wow speedy resolution, thanks y'all!

**Comment by antross** [comment]
No problem, thanks again for the report! The site should now be up-to-date too. 😊
