### ISSUE TITLE
[Bug] UI Bug: Toggle on results page isn't centered

### ISSUE THREAD

**Issue by ststimac** [webhintio/hint#2616]
This is purely a UI bug:

<img width="182" alt="Screen Shot 2019-06-18 at 10 35 22 AM" src="https://user-images.githubusercontent.com/18073131/59706461-602a3e00-91b5-11e9-93a8-0db01d5aa435.png">

The toggle for the Passed Hints isn't centered and needs to be bumped up just a hair. It's not as noticeable when it's toggled on.

**Comment by antross** [comment]
Yep, looks like it needs just about a 2px (0.125rem) shift up.

**Comment by sarvaje** [comment]
My vision is not that good, so I'm going to apply what @antross said hehehe.

**Comment by ststimac** [comment]
@sarvaje can you post a screenshot of the fix when you have it? Thanks!

**Comment by sarvaje** [comment]
Sure thing.

![image](https://user-images.githubusercontent.com/1581288/59806593-b5e01280-92a9-11e9-8a0e-4b05f1f29c3f.png)
