### ISSUE TITLE
[Extension Design] New 'inspect/open elements' icon

### ISSUE THREAD

**Issue by ststimac** [webhintio/hint#2622]
New icon in a Fluent style to replace the current inspect icon in the extension. 

@antross I'll send you the icon because I can't attach SVGs.

For reference: 
<img width="574" alt="Screen Shot 2019-06-19 at 3 24 06 PM" src="https://user-images.githubusercontent.com/18073131/59805483-53394780-92a6-11e9-84bd-b381da468feb.png">

**Comment by antross** [comment]
Attaching a zip with the icon SVG in case someone else gets to this before I do: [Open Elements.zip](https://github.com/webhintio/hint/files/3312016/Open.Elements.zip)

**Comment by antross** [comment]
Closing as the design is done. Opened #2659 to track implementation.
