### ISSUE TITLE
[Bug] Keep create hint packages up-to-date

### ISSUE THREAD

**Issue by pratiyush2706** [webhintio/hint#2657]
## Description
On running ```npm create hint``` it installs deprecated version or outdated version of the dependencies required in the hint folder.

**Comment by antross** [comment]
Thanks @pratiyush2706. I'd have to double check the `create-hint` package, but I suspect there's an opportunity here to automatically increment these as part of our release process.

**Comment by pratiyush2706** [comment]
@antross Yes, automatically incrementing these would be good as developers tend to overlook the versions of the dependencies if the ```package.json``` file is created automatically.
