### ISSUE TITLE
[Bug] hint-create-element-svg false positives for React.createElement

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2706]
Run a scan on a page using React to create SVG elements.
(e.g. https://codepen.io/acusti/pen/qNWMGL)

Expected:
No reports from `hint-create-element-svg`.

Actual:
The hint raises a warning:
![image](https://user-images.githubusercontent.com/785009/61478214-af9b8f80-a956-11e9-9920-6c4317a2b1fd.png)

-----

I see two possible fixes here:
1. Require the left-hand side to be `document`.

   This has the disadvantage of missing cases where a local variable was used to reference the document (e.g. as `doc` or `d`).

2. Require that only one argument was provided to the function.

   Technically a second argument is allowed in browsers that support custom elements, but this is rare, especially with SVG elements so the missed cases should be few.

   In theory this could still false positive in some `React.createElement` cases if only one argument is provided (since the second argument is technically optional). However current transpilation from JSX seems to always include a `null` if no attributes are provided and most SVG elements are likely to include attributes when used in JSX anyway. 

Personally I'm leaning toward option 2.

**Comment by sarvaje** [comment]
Probably 2 is the best option.
