### ISSUE TITLE
[Feature] Add hint to warn about styles bleeding across inline SVGs

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2729]
Credit to @molant for suggesting we make a hint for the issue detailed in this tweet from Sara Soueidan: https://twitter.com/sarasoueidan/status/1153947911526453249?s=21

The summary: `<style>` tags inside inline `<svg>` elements are *not* scoped, so selectors contained within can end up matching other inline `<svg>` blocks within the same page, leading to unexpected rendering behavior.

We should be able to identify this scenario very accurately by extracting the selectors from inline `<style>` elements inside `<svg>` blocks, using them to query for matching elements in the page, and reporting an error if any of those elements are not contained within the originating `<svg>` block.

**Comment by jaspreet57** [comment]
Hi @antross, I would like to start working on it.

I have one question. If selector is ID and it is matching two elements (in same svg or two separate svgs, or in page). Shouldn't it be reported differently like `ID <id> already exists in document`?

Or in this hint, our goal will be just to report if selector inside svg, is matching any other element outside the svg. Right?

**Comment by antross** [comment]
Yes, we already have other hints that cover reporting duplicate IDs (specifically as part of `hint-axe`), so we should just focus here on selectors within an `<svg>` block matching elements outside of it regardless of what type of selector is being used.

**Comment by jaspreet57** [comment]
Ok, sounds good. Could you suggest me the hint name :)

**Comment by antross** [comment]
How about `hint-scoped-svg-styles`?

**Comment by jaspreet57** [comment]
`scoped` is a suitable word. I will start with it. If any other name comes to my mind, I will let you know. Thanks
