### ISSUE TITLE
[Docs Bug] `hint-http-cache` outdated HTTP Archive link

### ISSUE THREAD

**Issue by Malvoz** [webhintio/hint#2731]
The link to HTTP Archive in `hint-http-cache` [#L439](https://github.com/webhintio/hint/blame/master/packages/hint-http-cache/README.md#L439) does no longer return relevant content. I'm unable to find an appropriate replacement in https://httparchive.org/reports.

Perhaps https://mobile.httparchive.org/trends.php#maxage0 or https://desktop.httparchive.org/trends.php#maxage0?

Needless to say, the changes to the HTTP archive site may affect other source links if these exists in other hints documentation.

**Comment by antross** [comment]
@Malvoz Thanks for catching this and sorry for the delayed response! I ran a code search and found a similar instance in `hint-image-optimization-cloudinary`.

@sarvaje Can you take a look at updating the links to httparchive.org and associated charts for both `hint-http-cache` and `hint-image-optimization-cloudinary`? Thanks!
