### ISSUE TITLE
[Feature] Test mode for the release script

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#2737]
If you want to make a change in the release script, there are some steps that you need to comment, or add extra configuration, etc.

The idea is to have a "test mode" that skip some of the validation.

For example, if I want to add a new task to the release script, I don't need to be authenticated to github, I don't want to commit my changes everytime I'm going to run the script, etc.

**Comment by molant** [comment]
There's already a test mode and flags to bypass some things. We should document properly those and list clearly any missing "bypass".


________________________________

**Comment by sarvaje** [comment]
I agree, but it would be nice a "test mode" flag to avoid everything with one flag hehehe.
