### ISSUE TITLE
[Bug] In VS Code, webhint tries to validate random TypeScript tsconfig schema files

### ISSUE THREAD

**Issue by dechamps** [webhintio/hint#2747]
# 🐛 Bug report

## Description

When opening my `tsconfig.json` file, which looks like this:

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "removeComments": true,
    "strict": true,
    "target": "es5"
  }
}
```

The "Problems" pane in Visual Studio Code looks like this:

![image](https://user-images.githubusercontent.com/866859/61997670-f72fc300-b09c-11e9-9a06-80afad3daecf.png)

Obviously, these warnings are spurious and should be suppressed. Not only are they reporting issues in files I don't have any control over, but it doesn't even make sense to issue such warnings against schema files.

I tried to work around the issue using the `pattern` options of the local connector, but I get the impression that's ignored by the VS Code extension.

## Environment

* __`hint` version:__ v5.1.1
* __`Node.js` version:__ v10.15.2
* __`OS`:__ remote; Debian Unstable (VS Code server); Windows 10 (VS Code client)
* __URL for which webhint failed:__ local development in VS Code

## `webhint` configuration

Default configuration (i.e. `@hint/configuration-development`).

## Debug output

It's not clear to me how to get debug output when webhint is running in the VS Code extension.

**Comment by antross** [comment]
Thanks for reporting @dechamps! 

I reproduced the same issue on my machine by installing the TSLint VS Code extension (which I could see referenced in the logs). 

So far I've confirmed one bug where we're matching `tsconfig.*.json` when we should probably limit to `tsconfig.json`. I'm still investigating why we're even searching files in extension paths as we should be scoped to just files in the current workspace.

I'll post another update here once I know more.

**Comment by antross** [comment]
I've traced the second part down to a potential issue in the `vscode-languageserver` library. Depending on the outcome of the discussion there we could potentially add our own filter to exclude files outside of the current workspace. 

In the short term, I think we should update `parser-typescript-config` to exclude `tsconfig.schema.json` files which should resolve the user-visible portion of the issue. I'll open a PR for this shortly.

**Comment by antross** [comment]
@dechamps as a workaround until our fix ships, I confirmed adding an `ignoredUrls` section to `.hintrc` can be used to suppress these warnings:
```json
{
    "extends": ["development"],
    "ignoredUrls": [{
        "domain": "tsconfig.schema.json",
        "hints": ["*"]
    }]
}
```
