### ISSUE TITLE
[Feature] Deprecate `parsers` in `.hintrc` and infer from active `hints` instead

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2767]
Also, random thought about future behavior: should we even specify parsers via `.hintrc` anymore? It just seems like a way to have hints not work by forgetting them. I'd prefer having hints specify which parser(s) they need and having those automatically pulled in based on which hints are enabled.

_Originally posted by @antross in https://github.com/webhintio/hint/pull/2734_

**Comment by molant** [comment]
How do you think this could work once we start adding support for [LESS](#2886), [SASS](#2887), etc.?

**Comment by antross** [comment]
> How do you think this could work once we start adding support for LESS, SASS, etc.?

Good point. Hard to say for sure until we do it, but assuming they end up as separate parsers we could add them as peer dependencies of `parser-css`. Not sure that's my favorite approach, though. Let's see where those land before considering this work.

**Comment by molant** [comment]
But even if they are peer dependencies how do they get enabled? Maybe the solution is to just look for all the available parsers and enable them automatically.

**Comment by antross** [comment]
> But even if they are peer dependencies how do they get enabled? 

I was thinking we'd follow `peerDependencies` from the original `hint`, so we'd hit `parser-css` first, then keep looking to find other parsers. Still not my favorite approach, though.

> Maybe the solution is to just look for all the available parsers and enable them automatically.

Yeah, perhaps that's best.

**Comment by molant** [comment]
If we see the perf impact is big we could look into lazy-loading the parsers until they are needed somehow.

**Comment by molant** [comment]
After discussing this internally we've decided not to hide this option.

There's been significant work done around configurations, severities, etc.
We can review this topic again in a few months after we roll the new version.
