### ISSUE TITLE
[Docs] Restore dead link in `hint-doctype` documentation

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2779]
The following link is being removed from the README for `hint-doctype` because it currently fails to resolve:

```md
Although an alternative legacy compatibility `doctype` is available,
this hint does not recommend it. It is a common misconception that
the legacy compatibility `doctype` refers to compatibility with
legacy browsers, when, in fact, it is used to deal with [compatibility
issues with outdated XML tools][compat issue]

...

[compat issue]: http://bugzilla.bluegriffon.org/show_bug.cgi?id=634#c0
```

However this issue may be temporary as it appears to be due to a server error. Filing to restore the link should it become usable again in the future.

**Comment by hxlnt** [comment]
Link is still dead after 16 months, let's close this one. :)
