### ISSUE TITLE
Bundle the VS Code extension using webpack

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2803]
Currently we can't reference shared code from other packages (e.g. `@hint/utils`) without pulling in the entirety of that package and *ALL* of its dependencies into the final packaged extension (adding many MB to the file size). 

Adding a webpack step similar to what we do for the browser extension would help solve this problem by only bundling the parts of reference dependencies we actually use. It's also the approach now recommended by the VS Code team: https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by molant** [comment]
Do you want to bundle webhint into the vs code extension?
I don't think we should do that as the version referenced in the package.json and the one bundled could be incompatible.
If it's bundling the other resources specific to the extension then I'm on board.

________________________________

**Comment by antross** [comment]
Completely agree. This is about bundling shared utilities, not webhint itself 😁

That said, I am making a tweak to how the extension uses webhint as part of fixing #1942. I'll leave a comment there explaining and we can discuss.
