### ISSUE TITLE
[Feature] Prompt user to opt in to telemetry in browser extension

### ISSUE THREAD

**Issue by hxlnt** [webhintio/hint#2818]
# 🚀 Feature request

Prompt user to opt in to telemetry in browser extension.

**Comment by sarvaje** [comment]
IIRC, we talk to do something similar to what devtools does, something like this:
![image](https://user-images.githubusercontent.com/1581288/63464678-9cc42100-c414-11e9-82b6-2bad0cc5582d.png)

@ststimac do you want to make a design, or should we just do something similar to that?

**Comment by ststimac** [comment]
@sarvaje we should imitate the DevTools.
