### ISSUE TITLE
[Bug] Base href is not being applied correctly to all links; initial letter of relative links truncated

### ISSUE THREAD

**Issue by tmb-github** [webhintio/hint#2829]
OS: Windows 8.1
Webhint online scanner 

The online scanner is not reading the base element href for some of the relative links in the head.

At https://thomasbrodhead.com, the base element is:

`<base href="https://thomasbrodhead.com/">`

. . . and the favicon is:

`<link rel=icon href="favicons/favicon.20190811163149.ico" type="image/x-icon">`

But scanning https://thomasbrodhead.com, the online scanner concludes that the favicon is found at: 

https://thomasbrodhead.com/avicons/favicon.20190811163149.ico

Notice that the scanner has dropped the "f" in "/favicons/", resulting in a 404, as the resource as stated does not exist.

This can be found in the link reported in the "no-http-redirects" hint that is triggered by the scanner's inability to find the resource.

When scanning a subdirectory of the site, it becomes apparent that the base href is not being read and applied correctly.

At https://thomasbrodhead.com/chromatic-geometry, the base href is still set with:

`<base href="https://thomasbrodhead.com/">`

. . . and the favicon is indicated with:

`<link rel=icon href="favicons/favicon.20190811163149.ico" type="image/x-icon">`

But the scanner uses the URL, not the base href, for determining the location of the favicon, and concludes that it is:

https://thomasbrodhead.com/chromatic-geometry/avicons/favicon.20190811163149.ico

When it rightly is located at

https://thomasbrodhead.com/favicons/favicon.20190811163149.ico

Notice the double-problem here: the scanner has used the URL (https://thomasbrodhead.com/chromatic-geometry/) as the base of the link, not the href supplied in the html (https://thomasbrodhead.com/"). But then it then appends "avicons/favicon.20190811163149.ico" to the URL href, not "favicons/..." with an initial "f"...i.e., it truncates the initial letter of the resource.

In my scanning, this was revealed in the "http-cache" hints section. This problem results in 404 errors that trigger other hints (when the resource can't be found and interrogated by the scanner, the 404 page of the site is returned, and webhint then reports errors on those responses, etc.)

Many thanks,
Tom

# 🐛 Bug report

## Environment

* __`hint` version:__ 
* __`Node.js` version:__ 
* __`OS`:__ 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
<!-- Paste the content of your `.hintrc` here -->

```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
<!-- ✍️ Paste the raw output here -->


```

</details>

**Comment by sarvaje** [comment]
@tmb-github Thanks for reporting this issue. I'm going to take a look to see what is happening.

**Comment by sarvaje** [comment]
There was a problem generating the favicon, we were ignoring the url in the base element in this case.

I will try to deploy a new version of the online scanner as soon as the fix is published.

Thanks for opening the issue!

**Comment by bmt-systems** [comment]
The online scanner is still affected by the bug.
