### ISSUE TITLE
[Proposal] Support HTML reports

### ISSUE THREAD

**Issue by patrick-steele-idem** [webhintio/hint#284]
It would be great if an HTML report could easily be generated and, for each rule, show the full description for the rule (rendered to HTML from [`my-rule/README.md`]()). Sometimes the CLI just doesn't cut it. In addition, it would be nice if maybe a link (file path or URL?) to the [rule's README.md](https://github.com/MicrosoftEdge/Sonar/issues/285) could be included in the output on the CLI.

**Comment by molant** [comment]
@qzhou1607 this could be a fun one for you. What do you think? Still need to define how the exact output 
will be but I'm sure @sonarwhal/contributors can help with some ideas :)

**Comment by claire514** [comment]
@molant Sounds great to me :smile:. Should the html report just contain the same content as the output in the CLI?

**Comment by qzhou1607** [comment]
@molant Sounds great to me. Should the html report just contain the same content as the output in the CLI?

**Comment by molant** [comment]
It should contain more data than the CLI. What @patrick-steele-idem proposed is a good start. There are other things to discuss now like:

* Just one file or multiple (index page with issues and number with links to more details, for example)
* How does it look like
* More information that should be added

**Comment by molant** [comment]
The plan at the moment is to use the same HTML as the one from the online scanner once https://github.com/sonarwhal/sonarwhal.com/pull/187 gets merged.

We need to decide how we want to keep the online scanner in sync with the HTML report, at least until we start adding things exclusive to the online like comparing over time or against the rest of the web.

**Comment by DanielRuf** [comment]
Any updates? It's merged now.

**Comment by molant** [comment]
Starting on that really soon 😊
We need to finish #1133 and https://github.com/webhintio/webhint.io/issues/466 and that's the next thing will be working on. We want to make the online scanner results more actionable for the user and at the same time separate it into its own module.

**Comment by molant** [comment]
We are in the process of renaming but we haven't finished yet.
