### ISSUE TITLE
Bug: PWA manifest-file-extension is wrong

### ISSUE THREAD

**Issue by lovetingyuan** [webhintio/hint#2849]
1. Bug report:
pwa section: manifest-file-extension rule offers wrong file extension, should consider the url query part.
```html
     <link rel=manifest href="/site.webmanifest?v=v0.1.2">
```
![image](https://user-images.githubusercontent.com/7310471/63422617-4ae3c100-c43d-11e9-8528-de9c3631c371.png)

**Comment by sarvaje** [comment]
This issue is part of the `hint` repository. Moving to the right place
