### ISSUE TITLE
[Feature] Improve logging in CI

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#2892]
Right now, we are using `formatter-summary` by default for the configurations. This formatter only says what "needs to be fixed" but not where.

During today's retrospective we agree that we should give more information by default in CI.

Even if the user is able to use its own configuration, the idea is to offer to the user more information by default.

To achieve this we have at least two options:

1. Check if we are in CI and set by default another formatter like `stylish`.
1. Modify the configurations to use `stylish` instead of `summary`.

I'm saying `stylish` but we can use any other. (But I prefer stylish :P)

**Comment by antross** [comment]
@molant I think we should change the default formatter across the board. What about you?

I recall being confused the first time I ran the CLI trying to figure out how to see exactly what had failed. The summary looks nice, but it's not that useful.

**Comment by molant** [comment]
The reason why the default is summary + html is that the summary output can be really intimidating and not very useful when outputted all in the console (it's very common to have dozens of errors of first run). We had stylish initially and change it to summary for this particular reason (there's an issue about it).

I'm more inclined to detect that we are in ci and change the formatter, similar to what ava does (and I suspect others).

I still want to do the xunit formatter which should be helpful for jenkins and Azure devops, but we could have others depending on the CI platform that create an artifact that is stored and can be downloaded later by the use (or something similar).

I think we should do a bit of research as to what users prefer in terms of reporting, and I suspect it will differ depending on the platform and the project.




________________________________
