### ISSUE TITLE
[Browser Extension Bug] 'x-content-type-options' header not detected for .webmanifest file 

### ISSUE THREAD

**Issue by bmt-systems** [webhintio/hint#2895]
Windows 8.1
Chrome version 76
Webhint extension 0.0.6
Website: https://thomasbrodhead.com

hint 1: Response should include 'x-content-type-options' header.
https://thomasbrodhead.com/favicons/site.20190828080756.webmanifest:1:2724
<link rel="manifest" href="favicons/site.20190828080756.webmanifest" type="application/manifest+json">

However, Network tab in Chrome shows for resource https://thomasbrodhead.com/favicons/site.20190828080756.webmanifest

x-content-type-options: nosniff

Why isn't it picking up that header?

# 🐛 Bug report

## Environment

* __webhint version:__ 
* __Browser version:__ 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment]
Thanks for the report! We just fixed this for #2832, but the fix for that is in version `0.0.7` of the browser extension.

Closing for now, but let us know if you still run into problems after upgrading to the latest version.

**Comment by bmt-systems** [comment]
In version 0.0.7 under Security, it's now complaining:

hint 1: Response should include 'x-content-type-options' header.
https://thomasbrodhead.com/sw.min.20190903063620.js

Is this related to the fix for the webmanifest?

**Comment by antross** [comment]
No, the service worker issue appears a Chrome bug that has already been fixed in Chrome Canary. See  https://github.com/webhintio/hint/issues/2832#issuecomment-524049446 for more details.
