### ISSUE TITLE
[Bug] HTML compat data in shows mixed set of browser formats

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#2896]
# 🐛 Bug report

## Description

Ran webhint with ie11 off on figma.

`hint 1: link[rel=preload] is not supported by and_ff 67, firefox 60, 66-68.` has 2 issues:

1. `and_ff 67` is an unexpected format
2. (Filed as #2897) `link[rel=preload]` is a progressive enhancement that should not cause warnings

(Filed as #2898) Performance points out inline JS as issue, 4 times the same file

```
hint 1: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
hint 2: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
hint 3: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
hint 4: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
```

## Environment

* __webhint version:__ 0.0.7 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [ ] Recommended settings
* [x] Custom: defaults, not IE 11 

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

**Comment by antross** [comment]
Thanks @digitarald!

I agree the displayed browser names could be a bit more user-friendly. We're currently picking these up from `browserslist`, but as we already map them internally to `mdn-browser-compat-data` I suspect we could pick up and use the `name` property from there as well.
