### ISSUE TITLE
[Bug] Unminified JS points to the same file in repeated warnings

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#2898]
Breakout from #2896, see STR.

Performance points out inline JS as issue, 4 times the same file

```
hint 1: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
hint 2: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
hint 3: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
hint 4: JavaScript content should be minified.
https://www.figma.com/file/Zl3RrMFmDnVBmeQg2Jy5Mv/DevPhoton?node-id=0%3A1
```

**Comment by antross** [comment]
I think it's referring to separate inline `<script>` tags, though clearly the output doesn't provide enough context to narrow down which one. The fact that this is reporting at all may be related to #2645. 

I think a couple of fixes are probably needed here:
1. Ignore scripts below a minimum length by default
2. Include a reference to the offending `script` element in the report
