### ISSUE TITLE
[Browser Extension Bug] 'x-content-type-options' header not detected for .js file

### ISSUE THREAD

**Issue by bmt-systems** [webhintio/hint#2915]
Windows 8.1
Chrome 76
Webhint extension version 0.0.7

An 'x-content-type-options' hint is thrown for a JavaScript resource:

> Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/sw.min.20190903063620.js

My .htaccess file has:

```
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options nosniff
</IfModule>

```
I've tried adding quotes around nosniff, like this:

```
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
</IfModule>
```

...but the result is the same.

**Comment by antross** [comment]
Per https://github.com/webhintio/hint/issues/2832#issuecomment-524049446, this appears to be a Chrome bug that has been fixed in Chrome Canary.

Given the fix is on its way, I don't think we should try to work around this in webhint.

**Comment by bmt-systems** [comment]
Ah, sorry about that. It still affects the webmanifest file in Canary 78. Let me make sure I haven't reported that.

**Comment by antross** [comment]
No worries, we appreciate the reports! 😊
