### ISSUE TITLE
[Extension bug] Ignore resources used by extensions (e.g.: `chrome-extension://`)

### ISSUE THREAD

**Issue by bmt-systems** [webhintio/hint#2916]
Windows 8.1
Chrome 76
Webhint extension 0.0.7

I'm using the suggested .htaccess file by webhint. It contains the content-type for webmanifest:

`AddType application/manifest+json                   webmanifest`

It also has:

`AddDefaultCharset utf-8`

...as well as an explicit `AddCharset utf-8` for several file types, including webmanifest. 

The extension throws this hint:

> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190903064115.webmanifest
> Content-Type: application/manifest+json; charset=utf-8

Please help.

**Comment by antross** [comment]
That certainly seems like a bug, but so far I haven't been able to trigger the same report using the webhint extension `0.0.7` on Chrome 76. I am on Win 10 instead of 8.1, but I'd be shocked if that was the reason.

Was https://thomasbrodhead.com/ the target page you were analyzing? Also, were there any other options for webhint you customized? I've tried a few different configurations with no luck.

**Comment by bmt-systems** [comment]
I've checked it on Win 10 and I get the same result. But I'm also using incognito mode, which may be part of the problem. Here's what I've found:

In Chrome 76 using Incognito Mode with *ONLY* Webhint and the "Disable Extensions Temporarily" extension (https://chrome.google.com/webstore/detail/disable-extensions-tempor/lcfdefmogcogicollfebhgjiiakbjdje?hl=en) active in that mode, and with Webhint 0.0.7 and with all default settings and all hint categories enabled, I get the result I reported before.

In Chrome 76 in standard mode with ALL of my extensions available, I get the following curious hint:

> hint 1: 'content-type' header charset value should be 'utf-8'.
> chrome-extension://mgijmajocgfcbeboacabfgobmjgjcoja/content.min.css
> Content-Type: text/css 

So, Webhint is picking up a CSS file of one of my Chrome browser extensions and is throwing a hint based on it. (Who knows which one? It's not "Disable Extensions Temporarily", because I deactivated it and Webhint threw the same hint)  So, could one of the extensions be the problem?

So I deactivated ALL extensions except for Webhint, and allowed it to function in Incognito mode as before. 

The result: the hint is not triggered in standard mode or in incognito mode.

However, subsequent retesting produced inconsistent results, with the error reported even when Webhint was the only extension active.

The one consistency is that when all of my extensions are active, Webhint throws hints responding to the resources they employ. I suspect that that is the root of the problem, and some kind of caching of extension data (???) that's even present in Incognito Mode (since I tested allowing the extension toggler and Webhint in Incognito Mode) must be a source of the problem.

At the very least, try installing the "Disable Extensions Temporarily" extension (https://chrome.google.com/webstore/detail/disable-extensions-tempor/lcfdefmogcogicollfebhgjiiakbjdje?hl=en) and let it and Webhint be allowed in Incognito Mode, and then run the Webhint extension in that mode to see what results you get. Something about the toggling of the extensions off and on correlated with the inconsistent hints I received.

**Comment by molant** [comment]
If I've understood correctly we are analyzing `chrome-extension://` resources.
Looks like we should be ignoring those and probably anything that's not `http(s)` in the browser extension.

I'll update the issue title. Nice find @bmt-systems and thanks for all these testing!

**Comment by molant** [comment]
Looks like we are indeed processing them:

![image](https://user-images.githubusercontent.com/606594/64656719-2435fc00-d3e5-11e9-849f-907b979efa2a.png)

@antross do you know the protocol for Firefox?

**Comment by molant** [comment]
Protocol seems to be `moz-extension://` but I don't see it pop up anywhere in the network tools or elsewhere.
I'll still add it to the ignore list just in case.

**Comment by antross** [comment]
> Protocol seems to be moz-extension:// but I don't see it pop up anywhere in the network tools or elsewhere.
> I'll still add it to the ignore list just in case.

Sounds good to me. My experience so far suggests Firefox limits the scope of the returned requests to the current page. Still, no idea if that would be subject to change and it doesn't hurt to filter it out.
