### ISSUE TITLE
[Extension] Cache-control of favicon

### ISSUE THREAD

**Issue by bmt-systems** [webhintio/hint#2917]
Windows 8.1
Chrome 76
Webhint extension 0.0.7

The extension scanner doesn't like "access plus 1 week" for the cache-control of the favicon. 

```
        <Files "favicon.ico">
            ExpiresByType image/x-icon               "access plus 1 week"
        </Files>
```

This hint is thrown...why?

> hint 1: The directive is invalid
> https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
> Cache-Control: max-age=604800,

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/hint/issues/2918
