### ISSUE TITLE
Issue parsing single value `cache-control` directive ending in comma

### ISSUE THREAD

**Issue by bmt-systems** [webhintio/hint#2918]
I'm using the .htaccess file configuration suggested by Webhint. The default cache-control for the favicon is 1 hour; why so short a period? Favicons aren't updated frequently. GTMetrix suggests 1 week, so I edited the directive in the .htaccess file to:

```
<Files "favicon.ico">
	ExpiresByType image/x-icon "access plus 1 week"
</Files>
```

But then the online scanner (with webhint version: 5.2.2) generates this hint:

> hint webhintio/online-service#1: The directive is invalid
> 
> https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
> 
> Cache-Control: max-age=604800,

...which is 1 week; why is this an error?

**Comment by bmt-systems** [comment]
I changed the directive in my .htaccess file to:

```
<Files "favicon.ico">
    ExpiresByType image/x-icon    "access plus 1 year"
</Files>

```
But the online scanner still throws a hint:

> hint #1: The directive is invalid
> 
> https://thomasbrodhead … avicon.20190811163149.ico
> 
> Cache-Control: max-age=31536000,

**Comment by molant** [comment]
At least we've changed the error message!

I'm thinking the error is the trailing `,` at the end of the directive. That's probably something we shouldn't flag. What version of apache are you using?

**Comment by bmt-systems** [comment]
Apache version 2.4.39

**Comment by molant** [comment]
I've reviewed the whole Apache configuration in the docs, and it should be ok.

There's the following lines a bit above the `favicon.ico` one:

```
# By default, inform user agents to cache all resources for 1 year.

ExpiresDefault                                   "access plus 1 year"
```

And the one you were modifying is only for files named `favicon.ico`. You are already revamping that file to `favicon.20190811163149.ico` so that rule shouldn't get applied in your case.

I'm looking into why webhint reports the directive is invalid.

**Comment by molant** [comment]
@bmt-systems I've opened #2927 to address the current issue. I've used your website for testing and now it should tell you to add the `immutable` directive.

**Comment by bmt-systems** [comment]
I'm using the browser extension and the online scanner. Please let me know when either is updated with the patch and I'll test on my end.
