### ISSUE TITLE
[extension] Create "extension settings" section in configuration page

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2920]
> we probably still need to expose some way to change the telemetry choice after the initial prompt.

@molant suggested adding a collapsed details/summary section to the configuration page for settings (maybe just below the "Restore defaults" button). Then we could put a toggle inside there for the telemetry setting. That would avoid needing to create a separate settings page until we have more things to include. 

_Originally posted by @antross in https://github.com/webhintio/hint/pull/2848#issuecomment-527630355_

**Comment by molant** [comment]
@sarvaje I believe you are going to work on this soon-ish as part of #2848 so I'm going to assign it to you directly 🙂

**Comment by sarvaje** [comment]
perfect!

**Comment by molant** [comment]
I believe this was addressed in #2848 and fixed via https://github.com/webhintio/hint/commit/85dbb7a980bbe9893f143152d3ddd087777f8899
