### ISSUE TITLE
[Bug] Don't log `FirstRun` when `isCI` is true

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2962]
CI environments aren't typically going to preserve state between runs so if someone allows telemetry, we can end up sending `FirstRun` events on every run.

**Comment by molant** [comment]
While the change for this is trivial, I don't think we should just remove this event.
The user has to explicitly opt-in for telemetry in CI and if we just disable this event we will not know when it is used in CI.

I think we should send another event like "CIRun" or something like that.

**Comment by antross** [comment]
> I think we should send another event like "CIRun" or something like that.

I'm not necessarily opposed, but is that really needed since we already send an "analyze" event for every run? Perhaps we just want to include an `isCI` flag on that event?

Either way I think that's a separate issue. The key here is to stop sending "FirstRun" on every run in CI as it's inaccurate and skews our telemetry.

**Comment by molant** [comment]
Anyone wanting to see the discussion please read https://github.com/webhintio/hint/pull/2993#issuecomment-532311373
