### ISSUE TITLE
Combine hint reports for same issue

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2970]
Right now we can get the same "hint" multiple times but for different resources, different parts of the code, etc.
This isn't a great experience and can cause the user to miss another hint  after too much repetition. We should combine then (maybe in a nested details/summary?). This applies to the browser extension and the html formatter, although probably the browser has higher priority (IMO).

![image](https://user-images.githubusercontent.com/606594/64809435-249dd680-d54e-11e9-9152-e8f08fa93e6d.png)

**Comment by antross** [comment]
We'll probably also want to think about how to combine "similar" messages, e.g. for axe color contrast where we expose the calculated contrast ratio. 

This may be a bit challenging if we're looking only at the message text - perhaps we'll want to split this out so a hint can provide both a message and additional details (so we can use just the message portion to combine reports).

**Comment by hxlnt** [comment]
Would something like this address the concern?

![whiteboard (3)](https://user-images.githubusercontent.com/9647195/65167457-74b9e480-d9f7-11e9-8801-c84c82be90a6.jpg)

One difference here is that the hint count represents categories rather than instances of or "hits on" each hint.

**Comment by antross** [comment]
@hxlnt I think that will work for v1 of merging messages. I'll get started on it later today.

Per my earlier concern, when we have similar messages that aren't exactly the same we may still want to combine them in some fashion, but that won't happen with this initial change. The color contrast rule is a good example of this:

![image](https://user-images.githubusercontent.com/785009/65170340-13514000-da0e-11e9-836e-6d96a4182931.png)

@molant and I discussed possibly merging on the first phrase/sentence and still let the unique remainder of the message display once a user expands. Not sure if that plays well with i18n, though. 

Alternatively we could update those problematic hints to provide two pieces of data: a message and additional details. Thoughts?

**Comment by antross** [comment]
@hxlnt Also to clarify, is the intent to drop the "hint n:" text before each message as part of this change?

**Comment by antross** [comment]
@hxlnt One more clarification: do we always want to have the extra level of nesting or only when we have multiple reports with the same message? 

E.g. in your example if "Second hint description" only had one report, would we avoid collapsing it and show the contained URL + code snippet by default?

**Comment by hxlnt** [comment]
> @hxlnt Also to clarify, is the intent to drop the "hint n:" text before each message as part of this change?

Yes, I would advocate for this for the following reasons.
- The number of hint categories is now conveyed in and matches the lozenge.
- The labels "hint 1," "hint 2," etc. may imply a certain order that doesn't exist

**Comment by hxlnt** [comment]
> @hxlnt One more clarification: do we always want to have the extra level of nesting or only when we have multiple reports with the same message?
> 
> E.g. in your example if "Second hint description" only had one report, would we avoid collapsing it and show the contained URL + code snippet by default?

I think so.
