### ISSUE TITLE
[Bug] VS Code extension failing to find shared connector-local

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2998]
Filing while I investigate. Not sure how I got into this state, but my local webhint VS Code extension is failing to load a shared webhint instance due to a missing connector-local. 

Also interesting is that most of the dependencies appear to have been installed under the `hint` package instead of as peers in the `node_modules` folder containing `hint`. However `connector-local` exists in the file system in both places, which make it even more interesting why it is flagged as "missing" when everything else can be found...

Location of resource loader:
```
C:\Users\tross\AppData\Roaming\Code\User\globalStorage\webhint.vscode-webhint\node_modules\hint\node_modules\@hint\utils\dist\src\packages\load-resource.d.ts
```

VS Code extension output
```
Found hint at c:\Users\tross\AppData\Roaming\Code\User\globalStorage\webhint.vscode-webhint\node_modules\hint\dist\src\lib\index.js
{ AnalyzerError: Missing or incompatible dependencies
    at validateResources (c:\Users\tross\AppData\Roaming\Code\User\globalStorage\webhint.vscode-webhint\node_modules\hint\dist\src\lib\analyzer.js:21:15)
    at Object.create [as createAnalyzer] (c:\Users\tross\AppData\Roaming\Code\User\globalStorage\webhint.vscode-webhint\node_modules\hint\dist\src\lib\analyzer.js:66:9)
    at t.Analyzer.initWebhint (c:\Users\tross\.vscode\extensions\webhint.vscode-webhint-1.2.0\dist\bundle\server.js:1:87515)
  name: 'AnalyzerError',
  status: 'ResourceError',
  resources:
   { connector: null,
     formatters: [],
     hints:
      [ [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function] ],
     incompatible: [],
     missing: [ 'connector-local' ],
     parsers:
      [ [Function: ManifestParser],
        [Function: BabelConfigParser],
        [Function: CSSParser],
        [Function: HTMLParser],
        [Function: CSSParser],
        [Function: CSSParser],
        [Function: TypeScriptConfigParser],
        [Function: WebpackConfigParser] ] } }

```
An initial look shows I also have a curious `node_modules` structure:

**Comment by antross** [comment]
It's been suggested this may have occurred due to version differences between published packages and the `package-lock.json` generated by the install process. I thought I had disabled generating `package-lock.json`, but looking at the code that's not the case. 

I'll update this to use `--no-package-lock` going forward. Will also need to check for and remove the existing `package-lock.json` if present.

**Comment by molant** [comment]
We think we've fixed this with the latest release but @antross will verify once he gets back home.

**Comment by antross** [comment]
Update: This still happens on my machine 😞

I think we're going to need to add a `package.json` to the shared install to help `npm` do the right thing here. I'll try to test again later this week.
