### ISSUE TITLE
[docs] Issue with 'No `P3P` headers'

### ISSUE THREAD

**Issue by gesa** [webhintio/hint#3010]
https://webhint.io/docs/user-guide/hints/hint-no-p3p/index.html

missing install instructions

**Comment by molant** [comment]
Good catch @gesa!

We are reworking the installation part (removing all references to global install) and we were wondering if that section was still needed or if we could maybe change it.

The current discussion is in https://github.com/webhintio/hint/pull/3008#discussion_r326393563

The 2 proposed options are:

* Remove it
* When a package is part of one of the default configurations, tell the user that it will get installed automatically by webhint

If you have any other proposals or like one better than the other please let us know!

**Comment by molant** [comment]
Hi @gesa this has been fixed via #3008 and an updated package will be published later today 🤞
