### ISSUE TITLE
[Bug] Improve CSP error reporting experience on Firefox

### ISSUE THREAD

**Issue by wellington1993** [webhintio/hint#3014]
# 🐛 Bug report

## Description

Can't scan Github

## Environment

* __webhint version:__ 1.0.0 
* __Browser version:__ Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0 
* __URL for which webhint failed:__ 
https://github.com/forketyfork/mtom-soap

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Cannot run analysis scripts. Page may have CSP restrictions.
evaluateInPage/</a<@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1608137
setTimeout handler*evaluateInPage/<@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1608129
evaluateInPage@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1608054
d/r/<@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1606469
setTimeout handler*r@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1606443
EventListener.handleEvent*d@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1606969
@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1089013
_/<@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1064922
_@moz-extension://3515716b-a6dd-47be-9b5a-c6e3389e3699/content-script/webhint.js:1:1065065
```

</details>

**Comment by molant** [comment]
Unfortunately this is a known Firefox limitation.

In the detail of the error we tell you more:

"Cannot run analysis scripts. Page may have CSP restrictions."


There's a bug in Bugzilla to get this fix but there isn't an ETA yet.

You are not the first person flagging this even though there's some information about what's going on in the error which makes me think we can do better.

@antross maybe we should make the reason  more obvious and not inside the error message?
Probably a link to the Bugzilla issue could help here?




________________________________

**Comment by molant** [comment]
Going to update the title of this issue to better reflect we have to improve the experience (or find out a workaround)
