### ISSUE TITLE
[Feature] Separate the compat data into its own utils package

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3035]
The browser compat data gets updated fairly often. Right now our compat util lives in `utils` which is used virtually by all hints and thus causing all the packages to update everytime there's something new.

We should take it to a different package to avoid releasing that often.

This will be a breaking change on `utils`.

**Comment by molant** [comment]
Adding @atopal as we talked about this earlier today 🙂

**Comment by molant** [comment]
Going to take a look at this now.

**Comment by Elchi3** [comment]
> We should take it to a different package to avoid releasing that often.

How often do you plan to update the data? Have users reported issues with outdated information?

**Comment by molant** [comment]
> How often do you plan to update the data?

Dependabot runs once per week and our plans is to publish once every other week more or less.

The issue is that the compat data is in the `utils` package that is virtually used by all our other packages. Updating `utils` means all the other packages (70+) need to be bumped and published to npm. By separating the compat data to a separate package only 4-5 packages will need to be published if only the compat data changes.

The interesting part of this change is that we are [documenting a lot more how we query the browser compat data](https://github.com/webhintio/hint/pull/3106/files#diff-b51a4586ba9acbb851990c5d1379e751). Please take a look and let us know if this could be useful for other projects using that data.

**Comment by Elchi3** [comment]
Ah, got it now. Thank you for elaborating! :) 

> The interesting part of this change is that we are documenting a lot more how we query the browser compat data. Please take a look and let us know if this could be useful for other projects using that data.

Yes, awesome! We should considers this if / when we start any work on https://github.com/mdn/browser-compat-data/issues/4106
