### ISSUE TITLE
[Bug] Need to add instructions when clicking on the extension to let users know they should go to the dev tools

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3041]
Clicking in the button that appears close to the address bar should tell the user to go to the dev tools and click on the hint tab. This is how it looks like right now:

![image](https://user-images.githubusercontent.com/606594/65796791-60c26100-e122-11e9-8519-5c860f727957.png)

**Comment by molant** [comment]
Working on this ATM.

This is how it looks like for now:

![image](https://user-images.githubusercontent.com/606594/65799920-17760f80-e12a-11e9-9bf7-6e08d5c4bc9c.png)


Need to figure out how to remove it from the manifest on Firefox.

@hxlnt @antross feedback? I'd like to have this published in the store before Monday :S

**Comment by hxlnt** [comment]
Wow, fast turnaround! 🤩 A few thoughts:

1. Can we increase the outer padding? The text is running pretty close to the edges.
2. What do you think about replacing some of the text with an screenshot mockup or GIF? Tony brought up a good point that the Hints pane may be in the overflow menu of DevTools. Showing the navigation there would help.

Ex:
[ Webhint header ]
Open DevTools (F12) and navigate to the Hints tab to start using webhint.
![image](https://user-images.githubusercontent.com/9647195/65804014-4fcf1b00-e135-11e9-81b3-f743a909f3d1.png)

**Comment by molant** [comment]
Sounds good to me. I'll use that image

**Comment by antross** [comment]
Should we use a different image for Chrome vs Edge so it matches the devtools in each (I’m okay if we do this later)?

Also, for modifying the manifest for Firefox see https://github.com/webhintio/hint/blob/master/packages/extension-browser/scripts/drop-persistent-flag.js

**Comment by molant** [comment]
This is how it's going to look in Chrome:

![image](https://user-images.githubusercontent.com/606594/65804905-6fb40e00-e138-11e9-801e-e1ff5960de4e.png)

Don't think we can get the Edge one published before Monday so I'll leave it to someone else to do the image swap 😛
