### ISSUE TITLE
[Feature] Links to MDN for CSS and HTML compat hints

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#3045]
CSS properties and incorrect values should link to MDN. The webhint pages on those features just broadly describe CSS and HTML hinting in general, but not specific features. The "Learn how to fix it" promised in the link text is not covered at all.

If you want to keep the page, maybe both can be combined into a `How this is tested.` and `Learn more about the CSS property.`

**Comment by antross** [comment]
I'd love to see this too. 

I think to pull it off we'll need to enhance webhint's `Problem` interface to allow including reference links. Our current documentation link is for the rule's implementation all-up, but to cover this scenario we'll need to be able to link to a different page for each individual report.

**Comment by sarvaje** [comment]
This is done as part of #3903 

The only part left is to expose it in the HTML formatter (https://github.com/webhintio/hint/issues/3930)
