### ISSUE TITLE
Make `browser` option for `connector-puppeteer` case-insensitive

### ISSUE THREAD

**Issue by antross** [webhintio/hint#3058]
Currently `connector-puppeteer` only accepts capitalized browser names: Chrome, Chromium, Edge.
It should also support the lower case versions.

The work that should happen is:
* [Update the connector schema](https://github.com/webhintio/hint/blob/c912cae69cc498471b960cf77646a90b7356c89a/packages/connector-puppeteer/src/connector.ts#L113)
* [Update `chromium-finder`](https://github.com/webhintio/hint/blob/c4f7ba5c45f9bdfae59055fce82b41af0c095f17/packages/utils/src/chromium-finder.ts#L334) to make sure we can pass the lower case versions and find the right values

--------------
Original comment:

@antross on top of merging thins we should probably open an issue to make that parameter case insensitive. What do you think?

_Originally posted by @molant in https://github.com/webhintio/hint/pull/3053#issuecomment-536848426_

**Comment by GabiOC** [comment]
Hi @antross , I'd be happy to pick this one up!

**Comment by molant** [comment]
Go for it @GabiOC !

If you have any questions during the process please let us know.

**Comment by fs1337** [comment]
@GabiOC I will pick it up if you are not working on it.

**Comment by GabiOC** [comment]
Hi @fs1337 , yes, go for it! Apologies, I wasn't able to find the time to work on this.

**Comment by fs1337** [comment]
No worries, thanks for your help!

On Fri, Oct 18, 2019 at 6:07 PM GabiOC <notifications@github.com> wrote:

> Hi @fs1337
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_fs1337&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=leos06zjRYjpiuryT2_arA&m=x-E0IxMrZuQ4Pnp48kSGfsY276Ywt_p8vvplCddUB5Q&s=-6cCeg2yCaoV4EvVQ4Y-iE160ttXHb9O8skPjVn9MpM&e=>
> , yes, go for it! Apologies, I wasn't able to find the time to work on this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_webhintio_hint_issues_3058-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAF4TC5BRYH4LCSPF7N7MFTLQPJMTLA5CNFSM4I4PHTL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBWUY3I-23issuecomment-2D544033901&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=leos06zjRYjpiuryT2_arA&m=x-E0IxMrZuQ4Pnp48kSGfsY276Ywt_p8vvplCddUB5Q&s=wVEyYdt_lpYEzhb2IDvWmoHxTFk02ePmJPqLdgnjjI8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AF4TC5CXALRNEHFGP5BBDVDQPJMTLANCNFSM4I4PHTLQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=leos06zjRYjpiuryT2_arA&m=x-E0IxMrZuQ4Pnp48kSGfsY276Ywt_p8vvplCddUB5Q&s=H-hKnIpEs7oxwvGlB-NuFtex25L_41JwYYzJsqjlSIk&e=>
> .
>
-- 
Regards,
Fangfang Sun
MS in Computer Engineering
NYU Tandon School of Engineering
