### ISSUE TITLE
Decide severity of hints

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3070]
We need to decide the severity of each report of each hint (Error, Warning, Information, or Hint).

The current spreadsheet is available [here](https://docs.google.com/spreadsheets/u/1/d/10QzDgAELjaolUYxcuex3f9PvalhfEVO225qeILLu_vo/edit?usp=sharing).

Ideally what we should do is a first pass of all of the reports, make comment in the ones where we have doubts and then meet online to discuss the pending or the ones we disagree on.

I've created a column for @sarvaje, @antross, @digitarald and myself. If someone else wants to contribute please do so and add a new column with your username.

The guideline we are using to decide the severity is:

* `Error` - Will definitely not work as intended in at least one of the target browsers
* `Warning` - Minor impact or may not cause problems in practice (even if technically "wrong")
* `Hint` - Fine for now, but could cause problems in the future if something changes
* `Information` - Additional context or FYI, possibly to help with other parts of a feature

**Comment by molant** [comment]
We need to decide the severity of each report of each hint.

The current spreadsheet is available [here](https://docs.google.com/spreadsheets/d/10QzDgAELjaolUYxcuex3f9PvalhfEVO225qeILLu_vo/edit?usp=sharing).

Ideally what we should do is a first pass of all of the reports, make comment in the ones where we have doubts and then meet online to discuss the pending or the ones we disagree on.

I've created a column for @sarvaje, @antross, @digitarald and myself. If someone else wants to contribute please do so and add a new column with your username.

**Comment by antross** [comment]
@molant Maybe I'm misunderstanding the intent, but I think the `hint` level is too coarse for a blanket default severity - for a number of these I think we're going to want different severity per-report within the same hint (e.g. `meta-charset-utf8`, `no-vulnerable-javascript-libraries`, etc.)

**Comment by molant** [comment]
That's the wrong file 🤦‍♂️

**Comment by molant** [comment]
Can you try again? The [link document should be updated](https://docs.google.com/spreadsheets/u/1/d/10QzDgAELjaolUYxcuex3f9PvalhfEVO225qeILLu_vo/edit?usp=sharing).

Sorry about that. If you get any permissions issue please let me know. I tried generating a shareable link with edit permissions but I think Rachel had to request access.

**Comment by antross** [comment]
Thanks! As I start to work on this I think it may be worth discussing some high-level guidelines for when we want to use each severity level. Here are my initial thoughts:
* `Error` - Will definitely not work as intended in at least one of the target browsers
* `Warning` - Minimal impact or may not cause problems at all depending on exact usage
* `Hint` - Fine for now, but could cause problems in the future if something changes
* `Information` - Additional context or FYI, possibly to help with other parts of a feature

**Comment by molant** [comment]
@antross and myself have gone through the excel file and agree on the severity of each message.

@digitarald, @malvoz (or anyone interested in this subject) it will be great if you could take a look and say if you disagree with anything.

I plan on leaving this issue for a few (working) days before closing it and start working on implementing the messages (and we can also update the severity later on based on feedback).

**Comment by Malvoz** [comment]
I have reviewed all the hints, and agree with your take on the severity of each report, but regarding the [`hint-content-type` report](https://docs.google.com/spreadsheets/d/10QzDgAELjaolUYxcuex3f9PvalhfEVO225qeILLu_vo/edit#gid=1093046857):

> Report message when response doesn't include the content type header: Response should include 'content-type' header.
>
> Severity
> Warning

I think it'd be safer in terms of interoperability to also have this be "_Error if `no-sniff` is present. Warning otherwise._", such that we allow the browser to sniff, if no content-type is specified. Unless browsers ignore `X-Content-Type-Options: no-sniff` when they detect that `Content-Type` is missing?

**Comment by molant** [comment]
TL;DR; I think it's an easy check and we should probably do it.


@antross I believe we discuss exactly this so hopefully I can get our reasoning right.

IIRC we want hints as independent as possible. We are already checking for `no-sniff` as another one and that's why we decided not to add more logic to this one and use `Warning` instead of `Error`. That said, adding the check for `no-sniff` in here and change the severity should be easy.

**Comment by antross** [comment]
Thanks @Malvoz!

@molant I think we just missed this case. We already proposed checking for `no-sniff` in this particular hint for a different message. I agree this seems like another reasonable place to make that distinction. I'm not sure what browsers do here, but ignoring `X-Content-Type-Options: nosniff` seems unlikely.

**Comment by molant** [comment]
Severities were agreed and work is in progress to update all hints. Closing this isse.
