### ISSUE TITLE
[Docs] Improve root README.md

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3095]
We need to improve the root README.md. I'm thinking about the following sections:

* Quick start user guide (what we have right now)
* Contributing to webhint
  * How the code is organized (mono repo with all the sources)
  * How to build the project
  * How to build the browser extension and how to test it
* Further reading (links to contributor guide, architecture, etc.)

@webhintio/core what do you think?

**Comment by antross** [comment]
> How to build the browser extension and how to test it

Would the intent here be to link off to [packages/extension-browser/CONTRIBUTING.md](https://github.com/webhintio/hint/blob/master/packages/extension-browser/CONTRIBUTING.md)? If so, then sounds good to me. 

We should probably include "How to build and test the VS Code extension" as well referencing [packages/extension-vscode/CONTRIBUTING.md](https://github.com/webhintio/hint/blob/master/packages/extension-vscode/CONTRIBUTING.md)

**Comment by molant** [comment]
> Would the intent here be to link off to 

Don't know TBH. While that seems reasonable, after the latest issues we've had with the extension submission I wonder if we should duplicate some of the information to make it easier for reviewers.

Guess we can try with the links and add more info if we run into other problems.

**Comment by antross** [comment]
> Guess we can try with the links and add more info if we run into other problems.

I'd prefer starting with that just to try to avoid having the content get out of sync.
