### ISSUE TITLE
Hide config all from site documentation and create-hintrc

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3099]
I learned about `all` through `npm create hintrc`, though it's also documented on the [site](https://webhint.io/docs/user-guide/configurations/configuration-all/)

_Originally posted by @orokanasaru in https://github.com/webhintio/hint/issues/3097#issuecomment-539626967_

**Comment by sarvaje** [comment]
@molant is this done? I think you were working on something like this few days ago.

**Comment by molant** [comment]
Yes, looks like this was a dupe. I closed 3097 via https://github.com/webhintio/hint/pull/3367

And I'm closing this one now.
