### ISSUE TITLE
[Bug] VSCode Extension applies standard HTML rules to Angular component HTML files

### ISSUE THREAD

**Issue by erichkray** [webhintio/hint#3139]
# 🐛 Bug report

## Description

Install Webhint VSCode extension when developing an Angular website.
- Applies standard HTML rules to component HTML
- Flags known input binding syntax as non-allowed elements

![example](https://user-images.githubusercontent.com/6619041/67123706-ec6d6180-f1a5-11e9-98b6-68cdebf633e4.jpg)

## Environment

* __`hint` version:__ hint@5.3.3
* __`Node.js` version:__ v12.8.1
* __`OS`:__ Windows
* __URL for which webhint failed:__ Local files, not published

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
{
    "extends": [
        "web-recommended"
    ]
}

```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>

<summary>webhint’s raw output</summary>

```text
N/A


```

</details>

**Comment by molant** [comment]
This is happening because we interpret all `.html` files as "full" HTML documents.

Wonder how we can make the distinction between fragments and full documents.
Maybe if we don't see a `<!doctype html>` or `<html>` tags and we are running on the local connector we could assume it's a fragment?
@antross what do you think?

**Comment by antross** [comment]
> Maybe if we don't see a `<!doctype html>` or `<html>` tags and we are running on the local connector we could assume it's a fragment?

Let's check for `<!doctype html>` or `<html>` for anything that runs through `parser-html` (fragments could be pulled in via XHR even in other connectors).

@molant I think we'll also need to do something about `{{expression}}` blocks in attribute values. What do you think about expanding the `isAttributeAnExpression` check to return `true` if an attribute value contains `{`?

**Comment by molant** [comment]
> What do you think about expanding the `isAttributeAnExpression` check to return `true` if an attribute value contains `{`?

Good idea. Seems like everyone uses that character for interpolation.

> Let's check for `<!doctype html>` or `<html>` for anything that runs through parser-html 

So if both are missing let's assume it's a fragment?

**Comment by antross** [comment]
> > Let's check for <!doctype html> or <html> for anything that runs through parser-html
> 
> So if both are missing let's assume it's a fragment?

Yep.

**Comment by molant** [comment]
We have something working 😁

![image](https://user-images.githubusercontent.com/606594/67133887-e8e8d300-f1c3-11e9-9ee9-3388069903f4.png)

**Comment by molant** [comment]
There's a  PR for this now: https://github.com/webhintio/hint/pull/3145

**Comment by molant** [comment]
#3145 got merged so closing this. We will do a release soon with this enabled 🎉
