### ISSUE TITLE
Decouple parser and JSON logic from `hint` package 

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3171]
> Maybe there's some decoupling that needs to happen there?

Ah, I see what you mean. Yes, feels like we should decouple that into a helper util that just JSON-related parsers can import/call.

_Originally posted by @antross in https://github.com/webhintio/hint/issues/2444#issuecomment-545100721_

**Comment by sarvaje** [comment]
Event if we move the method `finalConfig` to a helper, Parser still has the dependency on Engine.

**Comment by antross** [comment]
Yes, I think the intent is that the `Parser` type will remain in `hint`, but the logic that's specific to `JSON` parsers such as `parser-typescript-config` will be moved into a helper in some `utils-*` package.

**Comment by sarvaje** [comment]
Yep

**Comment by molant** [comment]
Then closing this issue 😛
