### ISSUE TITLE
Allow release script to release from a servicing branch

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3172]
In preparation for the next big release, we need the release script to be able to publish from a servicing branch in case we need to do any updates while we work in the newer release.

Right now the script only allows releases from `master`. The name of the branch hasn't been decided yet. Because there are many packages in the repo I'm not sure about using `5.x` as the name. Maybe `servicing`? I don't think we want to make this branch long-lived, right?

**Comment by antross** [comment]
I like `servicing` though I agree we don't want this to be a long-lived branch. My expectation would be that we'd delete it once the breaking changes have been merged. Though I'd keep changes to the release script so we can create a new `servicing` branch the next time we need to prepare breaking changes.

For any work that does need to go to `servicing` I think we should still commit it to `master` first to ensure it sticks around once `servicing` is deleted. I figure we can then `cherry-pick` and adapt desired work in `servicing` as needed. The main point being that we'll never actually merge `servicing`  itself back into `master`.

**Comment by molant** [comment]
>  I'd keep changes to the release script so we can create a new `servicing` branch the next time we need to prepare breaking changes.

Yup, that was my ideas as well 🤝
