### ISSUE TITLE
[Bug] Hint descriptions cut off in VS Code extension

### ISSUE THREAD

**Issue by hxlnt** [webhintio/hint#3175]
# 🐛 Bug report

## Description

Hint text is cut off in VS Code extension. It would be nice to either word wrap the descriptions or have the full text appear on hover.

![image](https://user-images.githubusercontent.com/9647195/67503250-28884280-f63c-11e9-81bc-0bd656a450fd.png)

## Environment

* __`OS`:__ Windows 10

**Comment by antross** [comment]
@hxlnt We'll have to file this on VS Code. We have no control over the UX presented here other than to provide the message text and a few pieces of metadata.
