### ISSUE TITLE
[Feature] Update browser extension to support new severity values

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3181]
As part of #3036 (and follow up of #3070 and #3071) we need to update the browser extension to report new severity values.

Right now it only supports Error and Warning but we are going to have Hint and Information as well.

Also we will need to allow the user to set the threshold.

This requires design and implementation work so assigning to @ststimac.

**Comment by ststimac** [comment]
@molant @hxlnt @antross what do we think of doing labels with an icon for different severity types. 
These are the icons I'm proposing but this does not encompass the whole label component of icon + text. 
![Screen Shot 2019-11-04 at 3 33 43 PM](https://user-images.githubusercontent.com/18073131/68166967-dd620f80-ff18-11e9-87ef-74aa6ca4f33b.png)

**Comment by antross** [comment]
> what do we think of doing labels with an icon for different severity types.

I like it. Where do you think we'd put the icons, before individual messages?
![image](https://user-images.githubusercontent.com/785009/68167452-258a2d80-ff2b-11e9-9729-8cdb5bea8d70.png)

I ask because the "Hints: 8" text in that screenshot that indicates a warning may be too general for a single icon because many hints will now report messages of differing severities (which probably means we'll need to rethink the "Hints: 8" formatting slightly too...)

**Comment by ststimac** [comment]
@antross that's what I was thinking. I was thinking similar to the badges we do already but different colors. I can mock it up. 

I was thinking: yellow for warning, red for error, webhint purple for hints, and maybe grey for information? I was originally thinking blue but don't want that to get lost.

**Comment by ststimac** [comment]
So something like this: 
![Screen Shot 2019-11-05 at 10 30 27 AM](https://user-images.githubusercontent.com/18073131/68235020-4ef09b00-ffb7-11e9-8598-901d6bcd3d6f.png)

**Comment by antross** [comment]
The badges look nice, though the start of the message text being shifted by different amounts feels slightly odd to me, especially for "Information". Curious to hear what others think.

Also, what do you think about the existing summaries, e.g. "Hints: 2" and the top-level colored dots for categories? Should we surface something about the differing contained severities at those levels too? The text "Hints: 2" itself will probably be out of place now that we have a distinct "Hint" severity.

**Comment by ststimac** [comment]
Yeah that's a good point about the Hints: 2 badge at the top. I think some sort of indicator with the dots would be good, to indicate there's an issue. Let me try a few things. 

As for the shifting of the message, that doesn't feel off to me but am open to others opinions.

**Comment by ststimac** [comment]
![Screen Shot 2019-11-05 at 12 01 39 PM](https://user-images.githubusercontent.com/18073131/68241737-15725c80-ffc4-11e9-9cbe-be03f1a9b952.png)

@antross, I think if we drop the badge and bold the lettering that should be sufficient.

**Comment by molant** [comment]
Not convinced about having **Hints: 2** and then another **Hint** right after.

Also, right now we have another badge with "No issues" that should probably be redesigned to be consistent with the rest.

Maybe having a summary of the results there? Something like"Errors: 3, Warnings: 2" and remove the categories that don't have any result or that do not meet the threshold?

That has the risk of making the title pretty long...

Or maybe we only have a message "No issues" or a ✔ and nothing when something has been found?

**Comment by ststimac** [comment]
I like the summary of issues idea and removing the categories that don't have results. 

No issues would probably just be a green badge with a check icon to match the other badges.

**Comment by ststimac** [comment]
Also for the config panel, I suggest we add another column with checkboxes for the severity types.

**Comment by molant** [comment]
> I suggest we add another column with checkboxes for the severity types.

I see it more as a "minimum threshold". I don't think why someone would just select "warning" but not "error" and I'm not even sure we should enable this scenario.
So basically the user needs to be able to decide what's the minimum type of report they want to receive:

1. Error
1. Warning
1. Information
1. Hint

Personally I see it more as a slider  but I'm fine as long as we don't allow things like "I want hints and warnings only"

**Comment by ststimac** [comment]
If that's the case, a radio button would probably be the better solution.

**Comment by ststimac** [comment]
@antross @molant what else do you need from me before I head to btconf next Tuesday?

**Comment by molant** [comment]
Can we have the design of the settings and the final look and feel of the results.

**Comment by ststimac** [comment]
Config panel. But we should discuss the title for the new settings. I'm not sure it's super clear what this will mean to folks. I have an idea for a different layout that would include a small caption to identify what this setting is for.

![Screen Shot 2019-11-08 at 11 37 48 AM](https://user-images.githubusercontent.com/18073131/68505494-37661c00-021c-11ea-9976-5f88416e01b9.png)

**Comment by ststimac** [comment]
Okay: for the results, I'm thinking we don't need actually need a green badge because we don't have a subset of items for those categories that have no issues. So I'm proposing we just keep "No issues" at the top level but match the styling of the error, warning message summary. Make sense?

![Screen Shot 2019-11-08 at 2 26 51 PM](https://user-images.githubusercontent.com/18073131/68514861-d3e7e880-0233-11ea-8332-9bd7b22f1a75.png)

**Comment by sarvaje** [comment]
Is the result page ready to implement?

**Comment by molant** [comment]
Yes, we can tweak things if needed but this should be a good starting point.


________________________________

**Comment by hxlnt** [comment]
Liking the latest revisions. Within a given tree, do we want the sort order to be all errors, then all warnings, then all hints, and then all informations?

**Comment by molant** [comment]
Under each particular hint I think we want to do that.

We need to start thinking about ways of improving the visualization in general. Do we want to sort everything by severity so the most important things are on top (and this mixing hints)? Group by resource? Something else?

I wouldn't block on that right now but something we should start looking into sooner rather than later.


________________________________

**Comment by molant** [comment]
@ststimac can we pretty please have the icons as svgs files? 🙏
Is the only thing missing to merge #3340

**Comment by ststimac** [comment]
[icons.zip](https://github.com/webhintio/hint/files/3852797/icons.zip)

@molant here ya go

**Comment by molant** [comment]
Thanks a lot!

**Comment by sarvaje** [comment]
Thanks @ststimac!!
