### ISSUE TITLE
[Docs Bug] Check links in content-type docs

### ISSUE THREAD

**Issue by Malvoz** [webhintio/hint#3187]
Affected documentation: https://webhint.io/docs/user-guide/hints/hint-content-type/

> [resources served with the wrong media type may be blocked](https://www.fxsitecompat.com/en-CA/docs/2016/javascript-served-with-wrong-mime-type-will-be-blocked/) (see also: [`X-Content-Type-Options` hint](https://webhint.io/docs/user-guide/hints/hint-x-content-type-options/)), or the official [media type may be required](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache#Referencing_a_cache_manifest_file)

The information in the source destination for "[media type may be required](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache#Referencing_a_cache_manifest_file)" seems to be incorrect/outdated.

**Comment by molant** [comment]
Need to address this before the next release which should be on Monday/Tuesday

**Comment by molant** [comment]
I've gone through the docs and I believe the link is correct although it seems a bit out of context:

> A cache manifest file can have any file extension, but it must be served with the MIME type `text/cache-manifest`.

Also we are talking about application cache which is deprecated so... A few options:

1. Explain in the text that this is for the case of application cache
1. Remove the link
1. Find another scenario where this applies

Easiest one will be 2 although I think it will be better if we find another example.

@Malvoz @antross thoughts?

**Comment by Malvoz** [comment]
I had just misinterpreted the sentence, it would read better if it instead said "_or in some cases, the official media type of a resource may be required_". I thought the intention was link to a more generic document explaining that, so that's why I was confused. 😄 

But indeed AppCache is deprecated, so we should delete that. And even without it, I think the document does a good job explaining why setting correct Content-Type is important it, so we don't necessarily need to find more examples IMO.

**Comment by Malvoz** [comment]
@molant can you review changes in https://github.com/webhintio/hint/commit/f6c3a32a3cdbc55ad0f7bd7712a15c94ea8019b1?

**Comment by molant** [comment]
Looks good to me!
The only problem I see is that lines are more than 80 characters long. I believe that's why CI has been failing for the last couple days. Glad to see is a quick fix 😁
I'll go ahead and change it.

Thanks for taking care of this!
