### ISSUE TITLE
[Bug] Could not find a declaration file for module 'request'

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#3206]
# 🐛 Bug report

## Description

If I use `@hint/utils` and enable `strict: true` in my tsconfig.json, then I get this error.

```text
node_modules/@hint/utils/dist/src/network/request-async.d.ts:1:26 - error TS7016: Could not find a declaration file for module 'request'. '/home/rootubuntu/github/test/packages/patata/node_modules/request/index.js' implicitly has an 'any' type.
  Try `npm install @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`

1 import * as request from 'request';
```

## Environment

* __`@hint/utils` version:__ 6.1.0
* __`Node.js` version:__ 12

**Comment by molant** [comment]
You mean from a different project, right?

We probably have to add `@types/request` to `dependencies` and not just `devDependencies`. Might be worth looking into the other types as well.

**Comment by sarvaje** [comment]
yes, sorry I forgot to mention that hehehe.

**Comment by sarvaje** [comment]
> Might be worth looking into the other types as well.

That is the only error I get for now.

**Comment by molant** [comment]
Can you add `@types/request` as a `devDependency` in your project and add `@types/request` as a `dependency` in your flattening PR?

Don't think we are going to publish `utils` again until the next breaking unless there's a major thing going on.

**Comment by sarvaje** [comment]
Sure, I can do that.

**Comment by sarvaje** [comment]
done!

**Comment by molant** [comment]
What happened with this? Did it got merged into master or is it part of your flattening PR?

**Comment by sarvaje** [comment]
It is part of the flattening PR
