### ISSUE TITLE
[Severity Updates] Hint-axe 

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3210]
| Report | Severity |
| --------| ----------|
| metadata name: XXXX | map impact |
| Message to show when there is an error running the script: $1. Please try again later, or report an issue if this problem persists. | Warning |

**Comment by molant** [comment]
@antross I believe this is the default behavior:

```ts
const severity = Severity[registration.options[violation.id]] || toSeverity(violation.impact);

registration.context.report(resource, message, { element, severity });
```

Can we close it?

**Comment by antross** [comment]
We wanted to tweak the `toSeverity` mapping slightly. Per our discussion:
> axe impact is minor, moderate, serious, or critical. 
Currently we map minor and moderate to Warning, then serious and critical to Error. 
I propose we modify this slightly to map minor to Hint, moderate and serious to Warning, and critical to Error.
