### ISSUE TITLE
[Severity Updates] hint-content-type 

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3214]
| Report | Severity |
| --------| ----------|
| Report message when the charset in the content type is not valid: 'content-type' header charset value should be '$1'. | Warning |
| Report message when the charset in the content type is not valid: 'content-type' header charset value should be '$1', not '$2'. | Warning |
| Report message when content type value fails to parse: 'content-type' header value should be valid ($1). |  "Error if no-sniff is present Warning otherwise"  |
| Report message when content type value is not valid: 'content-type' header value should be '$1'. |  "Error if no-sniff is present Warning otherwise" |
| Report message when a content type is not the right one: 'content-type' header media type value should be '$1', not '$2'. |  "Error if no-sniff is present Warning otherwise" |
| Report message when the content type shouldn't contain a charset: 'content-type' header value should not contain 'charset=$1'. |  Warning |
| Error message for invalid media type: invalid media type | "Error if no-sniff is present Warning otherwise" |
| Report message when response doesn't include the content type header: Response should include 'content-type' header. | "Error if no-sniff is present Warning otherwise" |

**Comment by molant** [comment]
@Malvoz we've updated some of these severities. Now everything that's not charset will be error if `no-sniff`, warning otherwise.

Let us know if you disagree!

**Comment by Malvoz** [comment]
LGTM
