### ISSUE TITLE
[Severity Update] hint-disown-opener

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3217]
| Report | Severity |
| --------| ----------|
| Missing noopener | Error |
| Missing noreferrer | Warning |

Will have to review this feedback once noopener starts being on by default

**Comment by molant** [comment]
Right now this hint combines if both values are missing. Do we want to keep the same behavior or report each missing value independently?

If we keep the same behavior then we will have:

| Report | Severity |
| --------| ----------|
| Missing noopener and noreferrer | Error |
| Missing noopener | Error |
| Missing noreferrer | Warning |

@webhintio/core thoughts?

**Comment by antross** [comment]
Personally I think it's more consistent to report each separately, but I don't feel too strongly about this either way.

**Comment by molant** [comment]
>  I think it's more consistent to report each separately

It will also make my code easier 😅
@Malvoz what do you think? Any strong opinion?

**Comment by Malvoz** [comment]
I don't see why they should combine, +1 for separating. :)

**Comment by molant** [comment]
Looks like there's consensus so I'll separate them :)

Thanks!
