### ISSUE TITLE
[Severity Updates] hint-performance-budget 

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3244]
| Report | Severity |
| --------| ----------|
| Report message when the validation fails: To load all the resources on a $1 network, it will take about $2s in optimal conditions (that is $3s more than the $4s target). | Hint: 90-<100% <br> Warning: >=100%-<150% <br> Error: >=150% |

**Comment by sarvaje** [comment]
what this means? `Hint: 90-<100%`
That even if the performance test pass (but "consuming" 90% of the time) we should report a hint?

**Comment by molant** [comment]
Yes


________________________________
