### ISSUE TITLE
[Severity Updates] hint-validate-set-cookie-header 

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3252]
| Report | Severity |
| --------| ----------|
| Report message when the header contains duplicated directives: '$1' header contains more than one $2. | Warning |
| Report message when the header contains prefix but the domain directive is set: $1 header contains '__Host-' prefix but the 'domain' directive is set. | Error |
| Report message when the header contains prefixes from an insecure page: '$1' header contains prefixes but is from an insecure page. | Error |
| Report message when the cookies have the 'secure' directive, but the site is insecure: Insecure sites ($1) can't set cookies with the 'secure' directive. | Error |
| Report message when the cookie have an invalid 'expires' date: Invalid date in 'expires' value of the '$1' header to set '$2'. | Error |
| Report message when the cookie have an invalid 'expires' date format: Invalid date format in 'expires' value of the '$1' header to set '$2'. The recommended format is: $3 | Warning |
| Report message when the header contains an invalid cookie name: '$1' header to set '$2' has an invalid cookie name. | Error |
| Report message when the header has an invalid cookie value: '$1' header to set '$2' has an invalid cookie value. | Error |
| Report message when 'max-age' and 'expires' exists in a cookie: The 'max-age' attribute takes precedence when both 'expires' and 'max-age' both exist. | Hint |
| Report message when max-age is not supported by a target browser: Internet Explorer (IE 6, IE 7, and IE 8) doesn't support 'max-age' directive in the '$1' header to set '$2'. | Error |
| Report message when the cookie doesn't have the 'httponly' directive: '$1' header to set '$2' doesn't have the 'httponly' directive. | Warning |
| Report message when the header doesn't contain a cookie name-value string: '$1' header doesn't contain a cookie name-value string.  | Error |
| Report message when the header contains prefix but not the right value for path: $1 header contains '__Host-' prefix but the 'path' directive doesn't have a value of '/'. | Error |
| Report message when a cookie doesn't have the 'secure' directive: '$1' header to set '$2' doesn't have the 'secure' directive. | Error |
| Report message when the header to set a cookie has a trailing ';': '$1' header to set '$2' has trailing ';' | Hint |
| Report message when the header contains an unknown attribute: '$1' header contains unknown attribute '$2'. | Warning |

**Comment by Malvoz** [comment]
> <table>
> <thead>
> <tr>
> <th>Report</th>
> <th>Severity</th>
> </tr>
> </thead>
> <tr>
> <td>Report message when the header contains duplicated directives: '$1' header contains more than one $2.
> </td>
> <td>
> Warning
> </td>
> </tr>
> </table>
> 
> <table>
> <thead>
> <tr>
> <th>Report</th>
> <th>Severity</th>
> </tr>
> </thead>
> <tr>
> <td>Report message when 'max-age' and 'expires' exists in a cookie: The 'max-age' attribute takes precedence when both 'expires' and 'max-age' both exist.
> </td>
> <td>
> Error
> </td>
> </tr>
> </table>

I Initially thought these 2 were fundamentally solving the same issue, i.e. alerting developers from (perhaps unawarely) setting an attribute multiple times - suggesting that these should have the same severity. 

But, setting both `max-age` and `expires` is a real use case for those who want support in _really_ old [browsers that don't support `max-age`](https://caniuse.com/#feat=mdn-http_headers_set-cookie_max-age). Based on that I think the latter report "_when 'max-age' and 'expires' exists in a cookie_" could do with `Warning`, maybe `Hint` even.

**Comment by antross** [comment]
> But, setting both max-age and expires is a real use case for those who want support in really old browsers that don't support max-age.

Looks like this is mostly just IE7 and below. I think the likelihood of someone targeting one of those browsers is quite low. That said, if we care about this case we could always make the severity conditional based on the list of target browsers (e.g. `Error` if only targeting browsers with `max-age` support, `Hint` otherwise).

**Comment by molant** [comment]
I'd say `Hint`. Nothing breaks and the message is clear about which directive takes precedence.
I'll update the table in the first comment to `Hint`.
