### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by sk3lk0** [webhintio/hint#3331]
can you give new dockerfile ? other docker files not working
https://github.com/webhintio/hint/issues/800

**Comment by sk3lk0** [comment]
my dockerfile is:

**Comment by sk3lk0** [comment]
https://github.com/molant

**Comment by sk3lk0** [comment]
@molant

**Comment by molant** [comment]
I'm not the docker expert in the team but I think there are a few things in that configuration that should probably be changed:

* It's using node 8. We are going to remove for that version in the next weeks. That should fix the issue `Error: Cannot find module '/root/.npm/_npx/563/lib/node_modules/hint/node_modules/iltorb/scripts/install.js'`
* You are also installing the `@hint/configuration-all` and `@hint/formatter-json`. `formatter-json` is part of `configuration-all` so no need to install it. Additionally, `configuration-all` was created so we could pull the documentation of all the packages with just one dependency. We have an issue to "hide" it (#3097). Can you please paste your `.hintrc` file? I'm 99.99% sure we can extend from `web-recommended` instead which get's downloaded automatically.
* You are running `npx hint` even though you are installing it as a dev dependency. This is probably the main reason why you are getting the permission errors. If you have a `package.json` file then you can add a property to `scripts` to execute it. Something like:

```json
{
...
  "scripts": {
    "hint": "hint https://example.com",
    ...
  }
}
```

The above will allow you to run it via `npm hint`. If `package.json` is in the same folder as `.hintrc` it should be automatically picked up so no need for `-c .hintrc`.

**Comment by sk3lk0** [comment]
my hint.rc is:
{
    "extends": ["all"],
    "formatters": ["json"]
}

**Comment by molant** [comment]
Looks like you want to have output in json format so whay I propose is:

- Install `@hint/formatter-json`
- Have a `.hintrc` file like:

```json
{
  "extends": "web-recommended",
  "formatters: ["json"]
}
```

- Do all the other things in my previous comment

I'm assuming you want to analyze a published website and not your local file system. Is that correct?

**Comment by sk3lk0** [comment]
> Looks like you want to have output in json format so whay I propose is:
> 
> * Install `@hint/formatter-json`
> * Have a `.hintrc` file like:
> 
> ```json
> {
>   "extends": "web-recommended",
>   "formatters: ["json"]
> }
> ```
> 
> * Do all the other things in my previous comment
ok
> I'm assuming you want to analyze a published website and not your local file system. Is that correct?
I'm assuming you want to analyze a published website and not your local file system. Is that correct?

**Comment by sk3lk0** [comment]
so now my docker file is:

FROM node:10-alpine
RUN apk add python pkgconfig pixman pixman-dev cairo cairo-dev pango pango-dev make g++ libjpeg libjpeg-turbo-dev
RUN npm install hint --save-dev
RUN npm install @hint/formatter-json  --save-dev
RUN npm create hintrc

what next?

**Comment by sarvaje** [comment]
@sk3lk0 I'm going to take to this.

For now, I see that you need to install chrome, because `web-recomended` use puppeteer by default.

**Comment by sarvaje** [comment]
@sk3lk0 You can try something like this:

Dockerfile:
```txt
FROM ubuntu:16.04

#Update ubuntu and install dependencies
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y curl apt-transport-https gnupg

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs build-essential

# Install chrome
RUN curl -sL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update
RUN apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst

WORKDIR /app

COPY .hintrc ./

# Add a chrome user and setup home and app dir.
RUN groupadd --system chrome && \
    useradd --system --create-home --gid chrome --groups audio,video chrome && \
    mkdir --parents /home/chrome/reports && \
    chown --recursive chrome:chrome /home/chrome && \
    chown -R chrome:chrome /app

USER chrome

ENTRYPOINT ["npx"]
```

.hintrc:
```json
{
    "connector": {
        "options": {
            "headless": true,
            "puppeteerOptions": {
                "args": [
                    "--no-sandbox",
                    "--disable-setuid-sandbox"
                ]
            }
        },
        "name": "puppeteer"
    },
    "extends": [
        "web-recommended"
    ]
}
```

**Comment by sk3lk0** [comment]
if i want use formatters json, my .hintrc must be something like:
{
    "connector": {
        "options": {
            "headless": true,
            "puppeteerOptions": {
                "args": [
                    "--no-sandbox",
                    "--disable-setuid-sandbox"
                ]
            }
        },
        "name": "puppeteer"
    },
    "extends": [
        "web-recommended"
    ],
    "formatters": ["json"]
}
?

**Comment by sarvaje** [comment]
yes
```json
{
    "connector": {
        "options": {
            "headless": true,
            "puppeteerOptions": {
                "args": [
                    "--no-sandbox",
                    "--disable-setuid-sandbox"
                ]
            }
        },
        "name": "puppeteer"
    },
    "extends": [
        "web-recommended"
    ],
    "formatters": ["json"]
}
```

**Comment by sk3lk0** [comment]
The following package is missing:

    formatter-json

**Comment by sk3lk0** [comment]
what is my next step?

**Comment by sarvaje** [comment]
Hi @sk3lk0:

This docker file should fix the problem with the formatter-json:

```txt
FROM ubuntu:16.04

#Update ubuntu and install dependencies
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y curl apt-transport-https gnupg

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs build-essential

# Install chrome
RUN curl -sL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update
RUN apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst

WORKDIR /app

# Add a chrome user and setup home and app dir.
RUN groupadd --system chrome && \
    useradd --system --create-home --gid chrome --groups audio,video chrome && \
    mkdir --parents /home/chrome/reports && \
    chown --recursive chrome:chrome /home/chrome && \
    chown -R chrome:chrome /app

USER chrome

COPY .hintrc ./

RUN npm install hint
RUN npm install @hint/formatter-json

ENTRYPOINT ["node", "node_modules/hint/dist/src/bin/hint.js"]
```

**Comment by sk3lk0** [comment]
it work. thanks all
