### ISSUE TITLE
CSS prefix order does not have full code snippet

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3347]
@sarvaje I'm seeing something weird on the extension and the CSS prefixes hint:

![image](https://user-images.githubusercontent.com/606594/68907899-38a4b680-06fe-11ea-98be-8c27c04de2f5.png)

I'm not seeing any of the prefixes in the code snippets.

This is form analyzing https://github.com/webhintio/hint/pull/3345/files with the sideloaded extension in this thread?

Can you please take a look?

_Originally posted by @molant in https://github.com/webhintio/hint/pull/3340#issuecomment-554156258_

**Comment by sarvaje** [comment]
Do we want the full code snippet only for CSS prefix order or for all the CSS hints?

**Comment by molant** [comment]
I think it depends on the situation. For the compat API I think things are OK as they are. For the CSS prefix order we should at least have the related ones in the order they appear and probably filter anything else out.

If we want to do something fancy we could have it in several levels and make it decide automatically

1. Everything if content is small enough (size TBD)
1. Related property(ies) if too long
