### ISSUE TITLE
Fresh install EACCES: permission denied, scandir '//lost+found'

### ISSUE THREAD

**Issue by martin-sweeny** [webhintio/hint#3363]
Please tell us about your:

## Environment

* __`hint` version:__ v5.4.1
* __`Node.js` version:__ v12.11.0
* __`npm` version:__ 6.11.3

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js

{
    "extends": ["development"]
}


```

</details>

## URL for which `webhint` failed

* __URL:__ http://localhost:3000

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text

  hint:engine Starting the analysis on http://localhost:3000/ +0ms
  hint:cli:analyze Failed to analyze: undefined +1s
  hint:cli:analyze AnalyzerError: EACCES: permission denied, scandir '//lost+found'
  hint:cli:analyze     at Analyzer.analyze (/run/media/msweeny/Data/Code/osedea-test/node_modules/hint/dist/src/lib/analyzer.js:150:23) +0ms
  hint:cli:analyze Total runtime: 38ms +0ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

</details>

**Comment by molant** [comment]
@martin-sweeny your debug output is really unexpected. Are you running Linux?
While we investigate what's going on, can you give it a try with `web-recommended`? That's the configuration we advice when analyzing `http` and it will catch other things that development doesn't (which is more for local files).

In any case, the error you are seeing is not expected at all 🤔

**Comment by sarvaje** [comment]
The issue in this case is because you are trying to use `configuration-development` with an URL.
`configuration-development` use by default the `connector-local` which is translating you URL to the `/` directory and basically is trying to scan all files in you computer. In the PR #3370 I'm adding a check to be sure the connector is receiving a file, if not, it will return an exception.

**Comment by molant** [comment]
@martin-sweeny fix will be in the next release that should be after Thanksgiving week (🤞)
