### ISSUE TITLE
[Bug] Color contrast with errors

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3365]
Report received via email:

> If you write "Hint:1" in a small white font on this red (#D83B01) the
contrast is not sufficient enough.
A much darker red would be better.

@ststimac I don't think we've updated the colors with the latest changes, right? What red do you want to use to fix this?

@sarvaje FYI as this will probably something you have to integrate.

**Comment by sarvaje** [comment]
Now "Hint:1" is not in the extension, but we have 
![image](https://user-images.githubusercontent.com/1581288/69358737-3087d200-0c3c-11ea-9ea0-4847dab7edd2.png)

**Comment by ststimac** [comment]
The current color contrast is 4:61 which is passing, but we can use #C02E00, that will bump color contrast up to 5:78
