### ISSUE TITLE
typescript-config/target error in VS code, but no browserslist.

### ISSUE THREAD

**Issue by goldingdamien** [webhintio/hint#3388]
I am getting "typescript-config/target" error from webhint via VScode extension.
According to the docs, this is checked via looking at browserslist configuration:
https://webhint.io/docs/user-guide/hints/hint-typescript-config/target/
I can't see any browserslist config in my project(Can only browserslist as a dependency in the yarn.lock file.).
What could be causing this issue?

Based on your browser configuration your "compilerOptions.target" should be "ES5". Current one is "ESNext"
(typescript-config/target)webhint

## Environment

* __`hint` version: 1.4.1
* __`Node.js` version: 12.1.0
* __`npm` version: 6.4.1

**Comment by molant** [comment]
In the absence of one, it will use browsers list defaults (https://github.com/browserslist/browserslist/blob/master/README.md#best practices) and that's probably the reason.

Is your project node only or does it have front end code? Are you using babel?
We would like to improve this hint to avoid false positives. We have some ideas around this (like disabling if babel is found) but want to identify as many scenarios as possible.

Thanks!


________________________________

**Comment by goldingdamien** [comment]
It's a nuxt project using Typescript. It includes Babel.
I thought because there is nothing specifying the environment that this hint would be ignored.
If there is a reason why the current functionality is preferred, please could you consider adding some additional documentation.

Regards.

**Comment by molant** [comment]
In the absence of an specific target, typescript transpiles to es3 which in most cases is not what the user wants.

UWe are changing the severities of the reports and the new ones are documented in https://github.com/webhintio/hint/issues/3251

I do think that looking for babel configurations and/or node targets in package.json to reduce the severity (or tune it off) should help with this.

We should look into this after the Thanksgiving week.


________________________________

**Comment by molant** [comment]
@goldingdamien there's a PR to improve this (#3415). If everything goes well a new version will be released tomorrow.
