### ISSUE TITLE
[Bug] application/x-httpd-php suggested for .php file

### ISSUE THREAD

**Issue by chrisgraham** [webhintio/hint#3402]
Running on webhint.io, a dependent resource (related to Facebook integration)...

https://staticxx.facebook.com/connect/xd_arbiter.php?version=44

Gives:
"'content-type' header media type value should be 'application/x-httpd-php', not 'text/html'. "

Clearly it is not meant to have a .php mime-type, as this is a server-side language. I don't know if maybe it's getting this from the file extension.

**Comment by molant** [comment]
We should only use the extension as the last resort to guess the mime type 🤔

Can you share the URL of the site doing the integration? If not, can you paste the minimum snippet of how this resource is used? Is it a xhr? script? iframe? That will help us identify where our code is getting confused.

Thanks!

**Comment by Malvoz** [comment]
@molant scanning this resource directly gives the same result, see https://webhint.io/scanner/f746c0ef-cdb2-4784-a338-3d4aad078a70#category-compatibility. 

As an aside, the scan times out and gives an error using the Chrome extension on v78.0.3904.108 (may or may not be related to this issue).

**Comment by sarvaje** [comment]
> As an aside, the scan times out and gives an error using the Chrome extension on v78.0.3904.108 (may or may not be related to this issue).

I couldn't reproduce this, I tried it on Chrome v78.0.3904.108 and in Edge Canary (v80...)

**Comment by Malvoz** [comment]
> I couldn't reproduce this

@sarvaje Nevermind! This was due to permissions settings configured to "When you click this extension" as opposed to "On all sites", I'd like to think that Chrome could do a better job of prompting users when an extension isn't allowed to run. 😟

**Comment by chrisgraham** [comment]
> We should only use the extension as the last resort to guess the mime type thinking
> 
> Can you share the URL of the site doing the integration? If not, can you paste the minimum snippet of how this resource is used? Is it a xhr? script? iframe? That will help us identify where our code is getting confused.
> 
> Thanks!

Looks like the issue might have been fixed, but for reference the site is https://compo.sr/
