### ISSUE TITLE
Unclosed span element in scan-category-summary.ejs

### ISSUE THREAD

**Issue by humphd** [webhintio/hint#3423]
There's a `<span>` vs. `</span>` in https://github.com/webhintio/hint/blob/68a2280a45070eb52807c5a739e04292b0cd599f/packages/formatter-html/src/views/partials/scan-category-summary.ejs#L9

**Comment by molant** [comment]
Good catch. @sarvaje is this fixed in your PR #3422?
In in mobile so can't check at the moment. If not can you add it or @humphd can you make a PR with the fix?

Thanks 🙏

**Comment by Malvoz** [comment]
It wasn't part of #3422, I added the fix. Thanks @humphd!
