### ISSUE TITLE
[Docs Bug] Explain severity values

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3437]
We need to document the [severity changes](https://github.com/webhintio/hint/issues/3036) somewhere in the docs and probably link from the browser extension and online scanner.

* `Error` - Will definitely not work as intended in at least one of the target browsers
* `Warning` - Minor impact or may not cause problems in practice (even if technically "wrong")
* `Hint` - Fine for now, but could cause problems in the future if something changes
* `Information` - Additional context or FYI, possibly to help with other parts of a feature

When configuring hints via `.hintrc`, the value `Default` can also be used to let webhint choose the appropriate level (typically when setting a configuration for some other aspect of a hint but wanting to keep the default severity).

**Comment by hxlnt** [comment]
@Reezaali will be working on this one next sprint.

**Comment by hxlnt** [comment]
I think we fixed this and forgot to link the PR to this issue See https://webhint.io/docs/user-guide/concepts/hints/. @antross @molant, feel free to reopen if this is in error.
