### ISSUE TITLE
Provide more contribution related details

### ISSUE THREAD

**Issue by alrra** [webhintio/hint#347]
- [x] Add `ISSUE_TEMPLATE.md`.
- [x] Add `PULL_REQUEST_TEMPLATE.md`.
- [x] Add [`CODEOWNERS` file](https://github.com/blog/2392-introducing-code-owners) (see: #382).
- [ ] Update `CONTRIBUTING.md` with more information.
- [ ] Add [`SUPPORT` file](https://github.com/blog/2400-support-file-support).

**Comment by alrra** [comment]
- [ ] Add [`CODEOWNERS` file](https://github.com/blog/2392-introducing-code-owners)

**Comment by alrra** [comment]
- [ ] Add [`SUPPORT` file](https://github.com/blog/2400-support-file-support).

**Comment by molant** [comment]
Adding this link from #372 https://github.com/eslint/eslint/tree/597c217f2c0ac5ca4bd1ddad321f2192a88fc40f/docs/developer-guide/contributing

and closing that issue in favor of this one.

**Comment by molant** [comment]
@alrra think you can take of this before the Edge Summit?
For `ISSUE_TEMPLATE.md` I think we should have at least:

* URL
* version
* .sonarrc file
* error

**Comment by alrra** [comment]
> For ISSUE_TEMPLATE.md I think we should have at least:
>
>  * URL
>  * version
>  * .sonarrc file
>  * error

Issues can be related to bug reports, suggesting new features, etc., so I think we should have different files for all those cases, and then in `ISSUE_TEMPLATE.md` just link to them.

**Comment by alrra** [comment]
Updated my [last comment](https://github.com/sonarwhal/sonar/issues/347#issuecomment-328204750).

**Comment by molant** [comment]
> but include the most common one: the bug report.
👍

**Comment by alrra** [comment]
See also: https://github.com/blog/2495-multiple-issue-and-pull-request-templates

**Comment by molant** [comment]
There are more improvements to the templates and now there can be several when opening an issue (feature request, bug report, etc.): https://blog.github.com/2018-05-02-issue-template-improvements/

**Comment by molant** [comment]
@brendyn if you want to take a look at this check https://blog.github.com/2018-05-02-issue-template-improvements/ first :)

**Comment by alrra** [comment]
> @brendyn 

@brendyna
