### ISSUE TITLE
[Bug] Update URL to get latest snyk version

### ISSUE THREAD

**Issue by codypierce** [webhintio/hint#3481]
# 🐛 Bug report

## Description

Auto-update of snyk database for hint-no-vulnerable-javascript-libraries gets an access denied error and future execution of webhint errors out

## Environment

nodejs

## `webhint` configuration

idk

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
/app # cat  /app/node_modules/@hint/hint-no-vulnerable-javascript-libraries/dist/src/snyk-snapshot.json
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>B3C2CF366476FDBE</RequestId><HostId>4hHUxAaQ4dgseWrLkb3Qno0lZ9ob5SNDW07CaYXhG4Bduui2FTuL5OJGXRSaS3ZOCwGncZnd75Q=</HostId></Error>/app #
{ AnalyzerError: /app/node_modules/@hint/hint-no-vulnerable-javascript-libraries/dist/src/snyk-snapshot.json: Unexpected token < in JSON at position 0
    at Analyzer.analyze (/app/node_modules/hint/dist/src/lib/analyzer.js:150:23) name: 'AnalyzerError', status: 'AnalyzeError' }

```

</details>

**Comment by molant** [comment]
Looks like snyk has updated the endpoint and https://snyk.io/partners/api/v2/vulndb/clientside.json no longer works.

Need to contact them to get the new one.

**Comment by molant** [comment]
@hxlnt fyi we worked with @tkadlec to get this working initially, but I think he no longer works there 😞

**Comment by tkadlec** [comment]
Well that's no good.

Maybe @lirantal can help get fixed?

**Comment by lirantal** [comment]
Sincere apologies for that issue, and thanks for the ping folks. I'm checking with the team what change did we introduce there and will update as soon as I have some answers.

**Comment by lirantal** [comment]
@molant ok so thanks too @tkadlec I have the context of this integration. Indeed that link is broken because the team had moved to a different way of updating the Lighthouse data with Snyk's vulnerabilities information. 

I'm kicking off a discussion internally to see how we can also support this project. It's a busy week with some activities planned at Snyk but I'm tracking this. Is this something that currently breaks things for this project?

**Comment by molant** [comment]
Hi @lirantal, thanks for looking into that.

Looks like the endpoint is working now and we get a json file. I guess you've changed something internally? Thanks!
I assume you'd like us to update to whatever the new recommended process is, right? 
If you want to have a private conversation can you please send me an email to amolleda at gmail dot com. @antross, what would be your preferred email?

**Comment by lirantal** [comment]
👋wanted to let you know that we've updated the previously broken link to function again. Apologies for that inconvenience and as we're now aware that you're dependent on it we'll try not to break it in the future 🙈🤗

We're good for now with this integration as is, but I'm happy to shoot out an email so we'll have a conversation going and points of contact when needed.

**Comment by molant** [comment]
Thanks a lot @lirantal !

I'll close this issue now.
