### ISSUE TITLE
[Bug] Chrome extension fails to read `localStorage` when 3p cookies are disabled.

### ISSUE THREAD

**Issue by Malvoz** [webhintio/hint#3494]
# 🐛 Bug report

## Description

Extension does not work [when third-party cookies are blocked](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document) in Chrome (79.0.3945.130):

`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

![webhint-not-working-if-3p-cookies-disallowed](https://user-images.githubusercontent.com/26493779/73079989-64de6f80-3ec5-11ea-9163-74128eb3357a.png)

## Environment

* __webhint version:__ 2.0.1

<hr>

This issue should ultimately be solved on Chrome's side, see: https://bugs.chromium.org/p/chromium/issues/detail?id=971848

**Comment by antross** [comment]
Thanks @Malvoz! Seems we should at least gracefully handle this in the meantime as the Chromium bug doesn't seem to have achieved consensus on whether the behavior should change.

The extension's use of `localStorage` is fairly minimal and all access goes through a single abstraction layer so this should be fairly easy to handle:
https://github.com/webhintio/hint/blob/master/packages/extension-browser/src/devtools/utils/storage.ts

At a minimum we should catch the error. Better yet we could back this with an in-memory object so the storage still "works", but doesn't persist across sessions.

**Comment by molant** [comment]
@Hirse is working on this 🎉
