### ISSUE TITLE
no-protocol-relative-urls has false-positive match on dns-prefetch links

### ISSUE THREAD

**Issue by Andrew-Cottrell** [webhintio/hint#3505]
`dns-prefetch` link are only used to request DNS resolution and not to open HTTP connections. The `no-protocol-relative-urls` test considers `dns-prefetch` links to be violations. This appears to be false-positive as there are no performance or security implications.

Reference: https://www.chromium.org/developers/design-documents/dns-prefetching

> To improve the speed of redirects, content authors can add the following tag to their page:
>
>     <link rel="dns-prefetch" href="//host_name_to_prefetch.com">
> 
>The above "link rel" tag has no impact on the visual rendering of the page, but causes Chromium to prefetch the DNS resolution of "host_name_to_prefetch.com" as though there was an actual href targeted at a path in that domain. The double slashes indicate that the URL starts with a host name (as specified in [RFC 1808](https://www.ietf.org/rfc/rfc1808.txt)). It is equivalent (but unnecessary) to use a full URL such as "http://host_name_to_prefetch.com/".

**Comment by Malvoz** [comment]
> Any other rel attributes that should be an exception?

`preconnect` too.

**Comment by antross** [comment]
Good catch @Andrew-Cottrell and thanks for reporting! 

@molant given the special nature of `dns-prefetch` I suspect it's one of the few (if not only) exceptions here. We'll definitely still want other `pre*` values (e.g. `preconnect`, `prefetch`, `preload`, etc.) to be flagged as they actually establish a connection to and potentially load content from the referenced server.
