### ISSUE TITLE
[Bug] Items in configuration page wrap poorly at smaller widths in browser extension

### ISSUE THREAD

**Issue by antross** [webhintio/hint#3528]
At certain sizes just before the layout changes from horizontal to vertical, items in the configuration page wrap poorly:

![image](https://user-images.githubusercontent.com/785009/73863041-1013f080-4805-11ea-867c-259a0e0748e1.png)

This is probably most easily fixed by adjusting the media queries being used to snap to the vertical layout slightly sooner.

**Comment by antross** [comment]
Note: this appears to have regressed when the newer "Minimum hint severity" column was added.

**Comment by antross** [comment]
A stretch goal would be to add an additional media query to have this drop to a two column layout in-between so the UI makes better use of available space before going full vertical.

**Comment by captainbrosset** [comment]
I believe the situation is better now, maybe something changed in the meantime. I tried resizing the container ever so slightly to try to replicate the problems you were seeing, but couldn't. In my case, the labels next to form controls never dropped to the next line, see below:

![Annotation 2020-05-25 074548](https://user-images.githubusercontent.com/1152698/82823176-f4883080-9e5b-11ea-9722-2f5a7ae7bacc.png)

That said, the stretch goal sounds great. I might give that a try soon.
