### ISSUE TITLE
[Bug] Long URLs break word wrap in results

### ISSUE THREAD

**Issue by hxlnt** [webhintio/hint#3587]
# 🐛 Bug report

## Description

When I run a scan against a very long URL, word wrap breaks in the results.

<img width="715" alt="long-url" src="https://user-images.githubusercontent.com/9647195/75826380-3f624280-5d5c-11ea-847e-c219635d45e4.png">

## Environment

* __webhint version:__ 1.2.1
* __Browser version:__ Edge Beta (80)

**Comment by antross** [comment]
I'm pretty sure we have correct wrapping styles on the URLs in the results, but I'm betting we missed this on the top-level URL displayed for the page. Should be as simple as replacing `overflow-wrap: break-word` with `word-break: break-all` for `.headerText` in https://github.com/webhintio/hint/blob/f847f6036569681f60d58fcc9214fe61f6ce2968/packages/extension-browser/src/devtools/views/pages/results/header.css#L16

See the formatting for `.problemLink` in the `Problem` component for an example:
https://github.com/webhintio/hint/blob/f847f6036569681f60d58fcc9214fe61f6ce2968/packages/extension-browser/src/devtools/views/pages/results/problem.css#L5

Of course I could have this backward on which one is correct (`.headerText` or `.problemLink`). Will need to test to verify my proposed fix works.
