### ISSUE TITLE
[Bug] call to Function() blocked by CSP

### ISSUE THREAD

**Issue by wellington1993** [webhintio/hint#3616]
# 🐛 Bug report

## Description

- Install Webhint 
- Use Firefox Nightly
- Try to Scan Webhint website

## Environment

__webhint version:__ 2.0.1
__Browser version:__ 76.0a1 (2020-03-10) (64-bit) - Mozilla/5.0 (Windows NT 10.0; rv:76.0) Gecko/20100101 Firefox/76.0
__URL for which webhint failed:__ https://webhint.io/

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output
![hint-blocked-by-CSP](https://user-images.githubusercontent.com/6920053/76341738-5c1aef00-62f5-11ea-8e1b-7f9ee7920e57.png)

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
call to Function() blocked by CSP
j@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1184208
d@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:258738
R@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1184766
e.exports@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1215797
e.exports@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:916185
e.exports@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1219147
e.exports@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:917620
e.exports@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1246705
e.exports@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:917620
j@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1183880
e@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1183548
v.prototype._compile@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1179648
v.prototype.getSchema@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1177651
v.prototype.validate@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1176305
v.prototype.validateSchema@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1177391
v.prototype._addSchema@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1179220
v.prototype.compile@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1176537
t.validate@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1175203
validateManifest@moz-extension://f1fdfcc6-aba8-412c-95bf-92062cba5b57/content-script/webhint.js:2:1642230



```

</details>

**Comment by molant** [comment]
I'm almost sure we are not using CSP in the website so I'm not sure why you are getting that specific error.
@wellington1993 have you tried with Firefox stable? Do you have the same issue?

Maybe there's some security/privacy setting enabled in FF that is causing this similar to https://github.com/webhintio/hint/issues/3590?

@digitarald do you know what could be going on?

**Comment by Malvoz** [comment]
There's a default CSP in extensions for both Chrome and Firefox, that are using manifest v2 or later:

https://developer.chrome.com/extensions/contentSecurityPolicy#restrictions  
https://blog.mozilla.org/addons/2019/12/12/test-the-new-csp-for-content-scripts/

**Comment by wellington1993** [comment]
@Malvoz @molant The problem only occurs on Firefox Nightly. IN the stable version I can use normally the add-on.

Thanks!

**Comment by antross** [comment]
The blog post @Malvoz shared from Mozilla seems relevant. I couldn't repro until I followed the steps there to explicitly enable the new CSP behavior (was off-by-default on my machine at least, even in Nightly).

I dug in and the particular failure we're seeing is in the `ajv` library we use to validate JSON schemas (it's part of the schema compilation process). I suspect even once we mitigate that the current `eval` approach we use to run some hints in the isolated world of the content script is going to fail with this setting.

Given this appears to be a planned change to default behavior in the future, we'll want to set aside some time to do more testing here. I added the label `agenda` so we can discuss at [tomorrow's sync](https://github.com/webhintio/hint/issues/3618).

As for potential workarounds, for `ajv` I could see us just stubbing the module as we don't need *real* schema validation in the browser extension. For the hints we run in the isolated world, we can probably switch to running them in the page instead. Unclear at this point if there's anything else that might also need to be addressed.

**Comment by digitarald** [comment]
I confirmed with @mixedpuppy that nothing needs to be done here. The pref that needs to be enabled for this issue to appear will further evolve into a CSP check that will be only enabled for v3 manifests.

**Comment by digitarald** [comment]
@wellington1993 just to double-check: Can you confirm that you had the `extensions.content_script_csp.*` prefs flipped?

**Comment by mixedpuppy** [comment]
> I confirmed with @mixedpuppy that nothing needs to be done here. The pref that needs to be enabled for this issue to appear will further evolve into a CSP check that will be only enabled for v3 manifests.

To clarify, the new CSP limits will be able to work in a V2 manifest if you use the new format for CSP.  It will be required for V3 manifest.  The issue I'll be fixing on current nightly is that if you flip the pref, it is applied to a V2 addon even if you do not use the new format.

**Comment by wellington1993** [comment]
@digitarald Sure.
```yaml
extensions.content_script_csp.enabled: true
extensions.content_script_csp.report_only:  false
```
Thanks!
