### ISSUE TITLE
[Bug] How to handle warnings and errors triggered by Google UniversalAnalytics and the Google TagManager?

### ISSUE THREAD

**Issue by tmb-github** [webhintio/hint#3662]
I'm using the webhint browser extension 2.1.0 on Chrome 81 on Windows 8.1.

How do I either handle correctly or suppress the warnings and/or errors triggered by my use of the Google TagManager and Google UniversalAnalytics at my site?

Here are the warnings and errors that trigger hints during an audit of https://thomasbrodhead.com using the browser extension (every JS file listed has been added dynamically by the Google routines).

**Compatibility:**

Warning
'content-type' header charset value should be 'utf-8'.
`https://www.google-analytics.com/analytics.js`
Content-Type: text/javascript

**Performance:**

**HTTP Cache:**

Warning
No configured patterns for cache busting match `https://www.google-analytics.com/analytics.js`. See docs to add a custom one.
`https://www.google-analytics.com/analytics.js`
`<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js">`

Warning
The directive "must-revalidate" is not recommended
`https://www.google-analytics.com/collect?v=1&_v=j81&aip=1&a=858750445&t=pageview&_s=1&dl=https%3A%2F%2Fthomasbrodhead.com%2F&ul=en-us&de=UTF-8&dt=Thomas%20Brodhead%20%7C%20Visual%20Art%3A%20Oil%20%26%20Acrylic%20Paintings&sd=24-bit&sr=1366x768&vp=882x657&je=0&_u=AACAAUAB~&jid=&gjid=&cid=1040537175.1586470383&tid=UA-141513157-1&_gid=212479708.1586470383&gtm=2ou432&z=1104530439`
Cache-Control: no-cache, no-store, must-revalidate

**Unneeded HTTP Headers:**

Warning
Response should not include unneeded 'x-xss-protection' header.
`https://www.googletagmanager.com/gtag/js?id=UA-141513157-1`

**Security**

**Use subresource integrity**

ERROR
Cross-origin resource `https://www.google-analytics.com/analytics.js` needs a "crossorigin" attribute to be eligible for integrity validation
`https://thomasbrodhead.com/`
`<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js">`

**Use 'X-Content-Type-Options' Header:**
ErrorResponse should include 'x-content-type-options' header.
`https://www.googletagmanager.com/gtag/js?id=UA-141513157-1`

**Comment by molant** [comment]
Hi @tmb-github 

In the settings you can play with the "Ignored resources" options:

![image](https://user-images.githubusercontent.com/606594/78946566-f054af00-7a77-11ea-9acb-011c998c1f58.png)

You could ignore directly everything that does not come from https://thomasbrodhead.com or ignore specific urls. The instructions for the later are in the link [See expression instructions](https://webhint.io/docs/user-guide/configuring-webhint/ignoring-domains/)
