### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by hellosct1** [webhintio/hint#3694]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.1.0 
* __Browser version:__ Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by antross** [comment]
Thanks for the report @hellosct1! 

Is there a particular page you were trying to scan that timed out? The extension is working for me in Firefox 77 (nightly) against webhint.io at least.

**Comment by hxlnt** [comment]
Hi, @hellosct1--Let us know if you're still having issues with this scan and, if so, what URL you're running against. Without more information, we're not able to investigate and will close the issue. Thanks!
