### ISSUE TITLE
[Bug] The site is returning an error

### ISSUE THREAD

**Issue by gregwhitworth** [webhintio/hint#3709]
# 🐛 Bug report

## Description

Sorry for the generic description but unfortionately there is no information in the failure. Here are the repro steps:

1. Go to https://karenwhitworth.com/pages/about-the-artist-and-oil-painter-karen-whitworth-1
2. Open the dev tools
3. Go to hints
4. Start the scan (all the defaults are set)

Expected: Get a report
Actual: Error with no details

![image](https://user-images.githubusercontent.com/865244/80292715-3d3db400-870d-11ea-89d2-37e59d5c7d88.png)

## Environment

- Extension version is: 2.1.0
- URL: https://karenwhitworth.com/pages/about-the-artist-and-oil-painter-karen-whitworth-1
- Browser: Microsoft Edge Canary: Version 84.0.495.0 (Official build) canary (64-bit)

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Nothing

**Comment by gregwhitworth** [comment]
I went ahead and tested a few other pages, same result - so it isn't choking on something specific to that page.

**Comment by molant** [comment]
What's your privacy level? We've had issues in the past similar to this.

________________________________

**Comment by Malvoz** [comment]
Using the same version of Edge Canary and with Tracking prevention disabled entirely I get the same result. Error details:

![webhint-edge-canary](https://user-images.githubusercontent.com/26493779/80294007-422e5200-8765-11ea-8034-67a0db17f8ac.png)

**Comment by antross** [comment]
I'm seeing the failure for this page, but not all others (e.g. webhint.io works fine). We're getting a "Permission Denied" response when trying to invoke `chrome.devtools.inspectedWindow.eval`. I also see this in Chrome Canary.

My first guess is some sort of policy change for extensions, possibly related to enforcing the Content Security Policy of the page. Or it could just be a browser bug. I'll have to keep digging to see if I can find any other clues...

**Comment by gregwhitworth** [comment]
I can confirm that it is working on other sites, just not that one. It may be a situation for any Shopify site.

**Comment by antross** [comment]
Update: This appears to be a regression in the Chrome devtools extensions API. Filed as https://bugs.chromium.org/p/chromium/issues/detail?id=1078135

**Comment by antross** [comment]
Fixed in Chromium.
