### ISSUE TITLE
[Feature] Include links and text in problem reports

### ISSUE THREAD

**Issue by antross** [webhintio/hint#3769]
Related to #3045, we should generally include explicit links along with problem reports (along with suggested link text), whether we're linking to MDN, webhint.io, or somewhere else.

**Comment by molant** [comment]
Can you provide an example?
We already link to the hint description. Would that be linking to specific parts?
We will need to make sure that the links aren't dead periodically as well.

**Comment by antross** [comment]
Yes, like when hint-compat-api tells us we have an issue with `background-color` we should link to the MDN page for that specific property. Similarly we should consider doing this for axe.

Furthermore, we link to this in the hint description, but we build that link based on the hint id. For consumers like `@hint/utils-worker` or our node API, we should include the link in the returned `Problem[]` so they have it without having to build it themselves.

**Comment by sarvaje** [comment]
I'm going to start working on this, but I have a couple of questions:

1. I get the part of including the link, but what do you mean with include the text?
2. For other hints that are not `hint-compat-api` nor `hint-axe` the link should be the lint to the webhint.io documentation?

**Comment by molant** [comment]
There's also the no vulnerable js libraries that should point to snyk (see #3780).
By text I think we meant "Learn more in BLA" and then the formatter can use it or not.

**Comment by sarvaje** [comment]
Ok,

Thanks!
