### ISSUE TITLE
webhint's Chrome Devtools Protocol + puppetter requirements

### ISSUE THREAD

**Issue by digitarald** [webhintio/hint#377]
Thanks for the great work on sonar and congrats on the release!

The Firefox team is investigating the effort needed to have a [CDP](https://chromedevtools.github.io/devtools-protocol/) adapter. Main goal is to come up with a subset of protocol features needed to be compatible with common use cases and maybe tools.

Given that Sonar aims to be a browser agnostic tool, we hoped that it could guide this work and make Firefox an easy target to run against.

What are the *required* and *recommended* Sonar requirements for CDP features?

Are there other concerns with CDP that would be good to address in our implementation like shortcuts for complex use cases, design flaws, etc?

# Puppeteer

| Action | API |
| ------ | --- |
| Start  | [`puppeteer.launch([options])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-puppeteerlaunchoptions) <br> [`puppeteer.connect(options)`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-puppeteerconnectoptions) <br> [`browser.wsEndpoint()`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-browserwsendpoint)|
| JS evaluation         | [`page.evaluate(pageFunction[, ...args])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pageevaluatepagefunction-args) |
| Request notification  | [`page.on('request')`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-event-request) <br> [`page.on('requestfailed')`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-event-requestfailed) <br> [`page.on('requestfinished')`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-event-requestfinished) |
| Page errors | [`page.on('error)`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-event-error) <br> [`page.on('pageerror)`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-event-pageerror) (for uncaught exceptions) |
| Response notification | [`page.on('response')`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-event-response) |
| Close browser         | [`browser.close()`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-browserclose) <br> [`page.close()`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pagecloseoptions) <br> [`browser.pages()`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-browserpages)|
| Navigate              | [`browser.newPage()`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-browsernewpage) <br> [`page.goto(url[, options])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pagegotourl-options) <br> [`page.waitForNavigation([options])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pagewaitfornavigationoptions) <br> [`page.setDefaultTimeout(timeout)`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pagesetdefaulttimeouttimeout) |
| Set page content | [`page.setContent(html[, options])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pagesetcontenthtml-options) |
| Input | [`page.type(selector, text[, options])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pagetypeselector-text-options) <br> [`page.click(selector[, options])`](https://pptr.dev/#?product=Puppeteer&version=v1.16.0&show=api-pageclickselector-options) |

# CDP

This is the features we are using from CDP

Methods:
* `cdp.List`
* `cdp.New`
* `cdp.closeTab`

Then from the client returned by cdp we use the following:

Methods:
* `close()` to close the browser

Properties:

* `Page`:
  * `enable()`
  * `loadEventFired()`
  * `navigate()`
  * `getAppManifest()`

* `Network`:
  * `enable()`
  * `clearBrowserCache()`
  * `setCacheDisabled()`
  * `requestWillBeSent()`
  * `responseReceived()`
  * `loadingFailed()`
  * `getResponseBody()` (It would be great if we can access to the raw response before decompress)

* `Runtime`:
  * `evaluate()`

* `DOM`:
  * `getOuterHTML()`
  * `querySelectorAll()`
  * `getDocument()`

* `Security`:
  * `certificateError()`
  * `handleCertificateError()`
  * `enable()`
  * `setOverrideCertificateErrors()`

**Comment by sarvaje** [comment]
Hi @digitarald!

This is the features we are using from CDP

Methods:
* `cdp.List`
* `cdp.New`
* `cdp.closeTab`

Then from the client returned by cdp we use the following:

Methods:
* `close()` to close the browser

Properties:

* `Page`:
  * `enable()`
  * `loadEventFired()`
  * `navigate()`
  * `getAppManifest()`

* `Network`:
  * `enable()`
  * `clearBrowserCache()`
  * `setCacheDisabled()`
  * `requestWillBeSent()`
  * `responseReceived()`
  * `loadingFailed()`
  * `getResponseBody()` (It would be great if we can access to the raw response before decompress)

* `Runtime`:
  * `evaluate()`

* `DOM`:
  * `getOuterHTML()`
  * `querySelectorAll()`
  * `getDocument()`


I think this is everything.

If you want to take a look, all the features we use from cdp are used in these to files [async-html.ts](https://github.com/sonarwhal/sonar/blob/master/src/lib/connectors/shared/async-html.ts) and [remote-debugging-connector.ts](https://github.com/sonarwhal/sonar/blob/master/src/lib/connectors/shared/remote-debugging-connector.ts).

Thanks!!

**Comment by molant** [comment]
@sarvaje maybe you can point them to the current work you have for the edge connector and also chrome?

The idea is to extend the remote-debugging-connector and just have a launcher and a couple other things when creating an specific one.

**Comment by alrra** [comment]
> Are there other concerns with CDP that would be good to address in our implementation like shortcuts for complex use cases, design flaws, etc?

@digitarald One limitation that we hit with CDP was getting the [raw response data](https://github.com/sonarwhal/sonar/issues/164).

**Comment by clarkbw** [comment]
> @sarvaje maybe you can point them to the current work you have for the edge connector and also chrome?

Perhaps a separate discussion... If you have a CDP test suite we could collaborate on we'd be very keen to help out there as well.  Thanks!

**Comment by molant** [comment]
@clarkbw you should take a look at [how to develop a connector](https://sonarwhal.com/docs/developer-guide/connectors/index.html) documentation.

If it is going to work with CDP it should be very similar to the Chrome one and should pass the same tests (this is what we are doing for edge).

**Comment by digitarald** [comment]
@sarvaje thanks a lot for the list. Combining your list with https://github.com/Microsoft/edge-diagnostics-adapter/pull/60 I see a few things missing from your list like `Network.disable` or `Network.loadingFinished`. Should I just take the combination of both lists or is your list here more recent?

**Comment by sarvaje** [comment]
@digitarald the list above is what we are using in sonar. CDP support more events and methods, but we are not using them on sonar (at least for now).

@clarkbw I have a little [demo](https://github.com/sarvaje/edge-adapter-tests) with some tests I'm doing to show my colleges where there were errors so they can fix the edge adapter and test the changes easily. It is not the best test suite, but it can help hehehe

>@sarvaje maybe you can point them to the current work you have for the edge connector and also chrome?

The branch where I'm working on the edge connector is [this one](https://github.com/sarvaje/sonar/tree/edge-adapter).
Basically you need to have a launcher for firefox, similar to the one to [cdp](https://github.com/sarvaje/sonar/blob/edge-adapter/src/lib/connectors/cdp/cdp-launcher.ts) or [eda](https://github.com/sarvaje/sonar/blob/edge-adapter/src/lib/connectors/eda/eda-launcher.ts) (this is not the final version of the edge launcher hehehe), and the conector for firefox, similar to [cdp](https://github.com/sarvaje/sonar/blob/edge-adapter/src/lib/connectors/cdp/cdp.ts) and [eda](https://github.com/sarvaje/sonar/blob/edge-adapter/src/lib/connectors/eda/eda.ts).

If everything is ok with the adapter, just creating those two files everthing should works fine :)

@digitarald @clarkbw if you have any question, please let me know

**Comment by paulirish** [comment]
> If you have a CDP test suite we could collaborate on we'd be very keen to help out there as well. Thanks!

I only know of one test suite that asserts against the protocol:  [the `inspector-protocol` tests](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/inspector-protocol/) within Chromium.

They were refreshed recently and sport a pretty modern look, you can pretty easily see the [similarities](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/inspector-protocol/cpu-profiler/enable-disable.js) to a typical chrome-remote-interface script. That said, there is missing test coverage for a number of things, including some of the methods that @sarvaje  listed above.  

Regardless, it seems reasonable that these could work against a chrome-remote-interface target.

**Comment by hxlnt** [comment]
@digitarald OK to close this issue, or is there still work here?

**Comment by molant** [comment]
@digitarald is now working in vs code. I think it's safe to close.
