### ISSUE TITLE
[Feature] Provide the actual link to the package page

### ISSUE THREAD

**Issue by lirantal** [webhintio/hint#3780]
# 🚀 Feature request

Add a link to the detailed package vulnerabilities page

## Description

The `no JS vulnerabilities` hint already shows the information and  includes a URL to the package and the database.

I'd like to update the page results so that the URL would be an actual link and to add a UTM so we can recognise the source.

Currently results look like this:

![image](https://user-images.githubusercontent.com/316371/83016141-28b14c00-a02a-11ea-9815-6330876b40eb.png)

I think that making a change here: https://github.com/webhintio/hint/blob/c0898120c1d0cb2f6760814e687605aba45175be/packages/hint-no-vulnerable-javascript-libraries/src/hint.ts#L144 to format this as an HREF anchor element will be the change proposed by a PR to solve this.

## What scenarios will this solve?

 Why do you want/need this?

Allow users to quickly gain more information on the vulnerabilities for this package.
Furthermore, we can also provide a link that actually highlights the relevant versions, like this: 

![image](https://user-images.githubusercontent.com/316371/83016807-3adfba00-a02b-11ea-91d1-e08d58702a0a.png)

(reference: https://snyk.io/vuln/npm:jquery?lh=3.1.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit).

This is basically what Lighthouse does and I thought would be great if we could do the same.

**Comment by molant** [comment]
My biggest concern is that the output is consumed by different formatters so the anchor could be printed in the console, vs code, etc. which will make it weird.

IIRC we were thinking about automatically parsing links and converting them. We will have to do that for the HTML and the browser extension at least.

**Comment by antross** [comment]
@molant if we did #3769 so related links are explicitly separate pieces of data off of `Problem` (instead of mixed in with the message text) we'd provide this in a way that each formatter could handle appropriately for its own context.

**Comment by molant** [comment]
That seems like the best approach 👍

**Comment by lirantal** [comment]
I'm not fluent with the code-base so I'm happy to receive some directions/help as to what changes to make, or if someone would like to pick this up and commit the required changes :-)

**Comment by lirantal** [comment]
I'm not fluent with the code-base so I'm happy to receive some directions/help as to what changes to make, or if someone would like to pick this up and commit the required changes :-)

**Comment by molant** [comment]
What we are proposing will affect the core of webhint so definitely not a first contributor task.
@sarvaje is coming back in the next couple of weeks and I believe already has #3769 assigned.

Once the infrastructure is in place it should be easier to add the links 😊

**Comment by lirantal** [comment]
Cool. So I have notifications turned on from this thread and hopefully once someone comments here I'll be able to chime in again and help with what I can.

Appreciate the input, I'll stay on standby-mode :-)
