### ISSUE TITLE
web manifest does not support combination of values for icon purpose

### ISSUE THREAD

**Issue by tmb-github** [webhintio/hint#3791]
The commit that added support for `maskable` is https://github.com/webhintio/hint/commit/c5eb40f819f79b6f92b18dcd015bfda5807bb034#diff-07d179b4d8516fb968d006563b37bfe3

Unfortunately, as @amazingcaio it does not allow for combinations:

> I don't think this issue is fixed. `"purpose"` can have multiple valid values, so `"any maskable"` and `"maskable any"`, and (I suppose) even `"any maskable badge"` should also be accepted. I think the real issue here is, because the possible options are hardcoded you'd have to have all 15 different possibilities (cos you have to treat `"any maskable badge"` and `"ask badge maskable"` as different, for instance). I reckon having to type 15 different possible options is fine, but it gets more complicated as more values are added to the web manifest spec. If one more value is added, for instance, there would be 60 different possible combinations. So changing the code so you don't have to hardcode every option and disregard the order of the values (so `"any maskable"` and `"maskable any"` would be considered the same) is the best solution.

Need to find a way to enable this in the schema and our types.

_Note: Original issue text by @tmb-github is available in the history_

**Comment by molant** [comment]
Looks like we will have to update the manifest, can't remember if we update them automatically on release or if we just copied from schema store, but more reason to do #3413 to automate this.

@tmb-github do you know if Firefox supports it as well?

**Comment by tmb-github** [comment]
@molant  Sadly, I don't. I just learned about this last week with the most recent version of Chrome Canary.

**Comment by tmb-github** [comment]
@molant It turns out Firefox Preview does support maskable icons...see these articles:
https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/
https://tigeroakes.com/projects/mozilla-firefox/

**Comment by molant** [comment]
I'm looking at the commit history of our schema and [`maskable` was added back in January](https://github.com/webhintio/hint/commit/c5eb40f819f79b6f92b18dcd015bfda5807bb034#diff-07d179b4d8516fb968d006563b37bfe3) 🤔

Looking at the original issue it looks like @amazingcaio [disagreed with the resolution](https://github.com/webhintio/hint/issues/3451) and correctly points out that we don't support combinations which seems to be your case (`any maskable`). Not sure why I didn't see the comment earlier 😓

Maybe there's something we can do with json schema to enable this (and find something similar in TypeScript).

I'll update the title and description of the issue.

@hxlnt is this something your team might want to get considered?

**Comment by tmb-github** [comment]
@molant I can no longer see my original message (it was apparently clipped when the topic was transferred). FWIW, the article referenced by the Lighthouse audit is: https://web.dev/maskable-icon-audit/ which suggests that users "Set the value of purpose to maskable or any maskable. See Values." And "Values" links to https://developer.mozilla.org/en-US/docs/Web/Manifest/icons#Values, which only lists 3 possible purposes. Are there more purposes than those listed in this spec?

**Comment by molant** [comment]
@tmb-github you can access the original one by pressing on "edited by @molant":

![image](https://user-images.githubusercontent.com/606594/84056033-8159e080-a96a-11ea-8c0f-0712deeb79f0.png)

The current issue is that you have `any maskable` and we only support `any` or `maskable`, not both at the same time 🤦‍♂️

**Comment by Malvoz** [comment]
Just a heads-up, when https://github.com/w3c/manifest/pull/833 is merged we'll have to support `monochrome` too.
