### ISSUE TITLE
webhint meeting 2020-07-10

### ISSUE THREAD

**Issue by hxlnt** [webhintio/hint#3859]
## Time

**UTC Friday 09-Jul-2020 17:00 (05:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Friday 10-Jul-2020 09:00 (09:00 AM) |
| US / Mountain | Friday 10-Jul-2020 10:00 (10:00 AM) |
| US / Central  | Friday 10-Jul-2020 11:00 (11:00 AM) |
| US / Eastern  | Friday 10-Jul-2020 12:00 (12:00 PM) |
| London        | Friday 10-Jul-2020 17:00 (05:00 PM) |
| Amsterdam     | Friday 10-Jul-2020 18:00 (06:00 PM) |
| Moscow        | Friday 10-Jul-2020 20:00 (08:00 PM) |

## Agenda

* Announcements if any
* **agenda** labelled issues and pull requests from the **webhintio org** prior to the meeting.

Join Zoom Meeting
https://us04web.zoom.us/s/79401109959
Password: 2jPn6S

**Comment by molant** [comment]
@hxlnt i won't be able to attend. Will be good to find something fo the issue about browserlist and development environment.

**Comment by hxlnt** [comment]
Notes (ended meeting early due to lack of quorum):
 - Mockup for browser extension improvements posted to https://github.com/webhintio/hint/issues/3690 -- PTAL
 - Thanks, @sarvaje for looking into the website scanner issues. They look to be resolved now.
 - Work will continue on currently-assigned sprint items (moved into 2007-2).
