### ISSUE TITLE
[Bug] When running Analyzer.format(), the resources from Analyzer.create() are not referenced

### ISSUE THREAD

**Issue by jackkoppa** [webhintio/hint#3910]
# 🐛 Bug report

## Description

*Note: if the intended behavior is to always have all categories when using the programmatic API, then this could be closed & we could stick with our workaround. However, given that formatters have methods to only display categories for actual hints, it seems likely we'd want to "fix" this*

```js
// index.js
const hint = require('hint')
const fs = require('fs')
const userConfig = require('./hintConfig')

const webhint = hint.Analyzer.create(userConfig)
const results = await webhint.analyze('http://example.com')
await webhint.format(results[0].problems)
```

**Actual Result**: When running `webhint.format()`, the `resources` array that gets used during `webhint.analysis()` is not referenced. This means that while `analyze` checks the correct hints based on our configuration (in our case, those from the `accessibility` default), the generated HTML file does not know which hints were used. Meaning that the output file includes *all* categories, rather than just the categories where hints are actually targeted.

**Expected Result**: `webhint.format()` should generate a response that only includes the categories for targeted hints; i.e. if a user doesn't provide a custom list of `resources`, then the instance list of `Analyzer._resources` should be referenced

**Possible line to add:**
https://github.com/webhintio/hint/blob/main/packages/hint/src/lib/analyzer.ts#L269
```js
options = { ...options, resources: this.resources }
```

**Current Workaround:**
```js
await webhint.format(results[0].problems, { resources: webhint.resources })
```

Current:
![Screen Shot 2020-07-23 at 1 19 31 PM](https://user-images.githubusercontent.com/14101491/88317402-38c27080-cce7-11ea-87ab-2e93c01e0528.png)

After Workaround:
![Screen Shot 2020-07-23 at 1 19 06 PM](https://user-images.githubusercontent.com/14101491/88317388-352ee980-cce7-11ea-98f6-b3264646b853.png)

## Environment

* __`hint` version:__ v6.0.6
* __`Node.js` version:__ v12.16.1
* __`OS`:__ MacOS 10.15.6
* __URL for which webhint failed:__ any

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
// hintConfig.js
module.exports = {
	extends: ['accessibility']
}
```

</details>

## Debug output

n/a (Webhint completes successfully, see screenshots for issue)

**Comment by hxlnt** [comment]
Your workaround actually looks like a good candidate for a fix here. Would you be willing to open a PR to make the change you suggest above?

**Comment by jackkoppa** [comment]
Thanks @hxlnt - PR'd
