### ISSUE TITLE
Testing: [Bug] Bug description

### ISSUE THREAD

**Issue by sheikhazrin** [webhintio/hint#3917]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.1.2 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.44 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment]
Hi @sheikhazrin is there a particular issue with the webhint browser extension you were trying to report? Or was this just a test?

**Comment by sheikhazrin** [comment]
> 
> 
> Hi @sheikhazrin is there a particular issue with the webhint browser extension you were trying to report? Or was this just a test?

Just test only. Sorry for disturbing you.

**Comment by antross** [comment]
No problem, just wanted to make sure we weren't missing additional details. Thanks for clarifying!
