### ISSUE TITLE
[Feature] App shortcut support

### ISSUE THREAD

**Issue by hxlnt** [webhintio/hint#3921]
# 🚀 Feature request

Add hint for app shortcuts > https://web.dev/app-shortcuts/

**Comment by claudiush** [comment]
Currently https://webhint.io/docs/user-guide/hints/hint-manifest-is-valid/index.html is flagging a false error
_'root' should NOT have additional properties. Additional property found 'shortcuts'._ 
if the site manifest contains **shortcuts** as member even thought this is following the documented standard: https://w3c.github.io/manifest/#shortcuts-member
