### ISSUE TITLE
"Cache-Control preferred to Expires header" doesn't align with recommended server configurations

### ISSUE THREAD

**Issue by tmb-github** [webhintio/hint#3922]
On Chrome I'm using the Chrome WebHint browser extension, version 2.1.3, on https://thomasbrodhead.com

I'm using Chrome Version 84.0.4147.105 (Official Build) (64-bit)

I'm running the WebHint scan in an incognito window with WebHint enabled for incognito mode.

On my site, I'm using the recommended Apache .htaccess set up as indicated here: https://webhint.io/docs/user-guide/server-configurations/apache/

When I run the WebHint extension analysis, it logs 42 warnings in the Security section of its report:

> Disallowed HTTP Headers
> The 'Expires' header should not be used, 'Cache-Control' should be preferred.
> 

It goes on to list the 42 resources, each reporting this or similar:

`expires: wed, 29 jul 2020 14:44:52 gmt`

When I click on the provided link marked _Learn why this is important and how to fix it_, it takes me to this page:

https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/

...which provides this .htaccess code as the proposed solution:

```
<IfModule mod_headers.c>
    Header unset P3P
    Header unset Public-Key-Pins
    Header unset Public-Key-Pins-Report-Only
    Header unset X-AspNet-Version
    Header unset X-AspNetMvc-version
    Header unset X-Powered-By`
    Header unset X-Runtime
    Header unset X-Version
</IfModule>
```

That is already in my .htaccess file, for it's part of the configuration provided here, which I've adopted: https://webhint.io/docs/user-guide/server-configurations/apache/

That configuration also includes this section (#-comments removed for clarity), which I'm also using, and which, as indicated in the sample .htaccess, comes before the "Header unset" section, so the "Header unset" section should cancel out whatever may undesirable here:

```
<IfModule mod_expires.c>
    ExpiresActive on
    ExpiresDefault                                   "access plus 1 year"
        ExpiresByType text/cache-manifest            "access plus 0 seconds"
        <Files "favicon.ico">
            ExpiresByType image/x-icon               "access plus 1 year"
        </Files>
        ExpiresByType application/atom+xml           "access plus 1 hour"
        ExpiresByType application/rdf+xml            "access plus 1 hour"
        ExpiresByType application/rss+xml            "access plus 1 hour"
        ExpiresByType application/json               "access plus 0 seconds"
        ExpiresByType application/ld+json            "access plus 0 seconds"
        ExpiresByType application/schema+json        "access plus 0 seconds"
        ExpiresByType application/vnd.geo+json       "access plus 0 seconds"
        ExpiresByType text/xml                       "access plus 0 seconds"
        ExpiresByType text/html                      "access plus 0 seconds"
    <IfModule mod_headers.c>
        Header merge Cache-Control immutable
        <FilesMatch "\.(appcache|cur|geojson|json(ld)?|x?html?|topojson|xml)$">
            Header edit Cache-Control immutable ""
        </FilesMatch>
    </IfModule>
</IfModule>

```
But this is part of the recommended set-up provided at the WebHint site, explained (and linked) earlier. 

Is the proposed .htaccess out-of-date? What does it need so that it will allow my site to pass the audit?

I'm unclear how to pass the WebHint test on this using the information provided at the WebHint site. What do I need to do?

**Comment by antross** [comment]
@captainbrosset This looks like a piece of documentation we missed updating when we updated this hint in https://github.com/webhintio/hint/pull/3776. Can you take a look?

**Comment by captainbrosset** [comment]
@antross I attempted a doc fix in the referenced PR above. Let me know if that's better.

**Comment by tmb-github** [comment]
Despite the commit, the changes found in https://github.com/webhintio/hint/commit/d78a83e3285c94dbee72f9e6e330a080880a76c2 are not reflected in the public documents, and the public documents are different from one to the other.

The code at the https://github.com/webhintio/hint/commit/d78a83e3285c94dbee72f9e6e330a080880a76c2 shows this:

```
<IfModule mod_headers.c>
    Header unset Expires
    Header unset Host
    Header unset P3P
    Header unset Pragma
    Header unset Public-Key-Pins
    Header unset Public-Key-Pins-Report-Only
    Header unset Via
    Header unset X-AspNet-Version
    Header unset X-AspNetMvc-version
    Header unset X-Frame-Options
    Header unset X-Powered-By
    Header unset X-Runtime
    Header unset X-Version
</IfModule>
```

So far so good.  But on [Disallowed HTTP Headers](https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/ ), the apache documentation still shows this:

```
<IfModule mod_headers.c>
    Header unset Public-Key-Pins
    Header unset Public-Key-Pins-Report-Only
    Header unset X-AspNet-Version
    Header unset X-AspNetMvc-version
    Header unset X-Powered-By`
    Header unset X-Runtime
    Header unset X-Version
</IfModule>
```
And on [Basic Server Configuration For Apache](https://webhint.io/docs/user-guide/server-configurations/apache/). the code shows this, which isn't the same as either of the above:

```
<IfModule mod_headers.c>

    # Because `mod_headers` cannot match based on the content-type,
    # the following workaround needs to be used.

    <FilesMatch "\.(appcache|atom|bbaw|bmp|crx|css|cur|eot|f4[abpv]|flv|geojson|gif|htc|ic[os]|jpe?g|m?js|json(ld)?|m4[av]|manifest|map|markdown|md|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|topojson|tt[cf]|txt|vcard|vcf|vtt|webapp|web[mp]|webmanifest|woff2?|xloc|xml|xpi)$">
        Header unset Content-Security-Policy
        Header unset X-Content-Security-Policy
        Header unset X-Frame-Options
        Header unset X-UA-Compatible
        Header unset X-WebKit-CSP
        Header unset X-XSS-Protection
    </FilesMatch>
</IfModule>

# ----------------------------------------------------------------------
# | Disallowed headers (no-disallowed-headers)                         |
# ----------------------------------------------------------------------

# Remove unneeded headers.
# https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/

# If the headers are sent, in most cases, to make Apache stop sending
# them requires removing the configurations that tells Apache to add
# them (e.g. for the `X-UA-Compatible` header, that would be mean
# removing something such as `Header set X-UA-Compatible "IE=edge"`).
# However, if the headers are added from somewhere in the stack (e.g.:
# the framework level, language level such as PHP, etc.), and that
# cannot be changed, you can try to remove them at the Apache level,
# using the following.

<IfModule mod_headers.c>
    Header unset P3P
    Header unset Public-Key-Pins
    Header unset Public-Key-Pins-Report-Only
    Header unset X-AspNet-Version
    Header unset X-AspNetMvc-version
    Header unset X-Powered-By
    Header unset X-Runtime
    Header unset X-Version
</IfModule>
```

If I adopt what's in [Basic Server Configuration For Apache](https://webhint.io/docs/user-guide/server-configurations/apache/) for a file-match block and what's in https://github.com/webhintio/hint/commit/d78a83e3285c94dbee72f9e6e330a080880a76c2 for a catch-all block, then my site passes the audit:

```
<IfModule mod_headers.c>
    <FilesMatch "\.(appcache|atom|bbaw|bmp|crx|css|cur|eot|f4[abpv]|flv|geojson|gif|htc|ic[os]|jpe?g|m?js|json(ld)?|m4[av]|manifest|map|markdown|md|mp4|oex|og[agv]|opus|otf|pdf|png|rdf|rss|safariextz|svgz?|swf|topojson|tt[cf]|txt|vcard|vcf|vtt|webapp|web[mp]|webmanifest|woff2?|xloc|xml|xpi)$">
        Header unset Content-Security-Policy
        Header unset X-Content-Security-Policy
        Header unset X-UA-Compatible
        Header unset X-WebKit-CSP
        Header unset X-XSS-Protection
    </FilesMatch>
</IfModule>
<IfModule mod_headers.c>
    Header unset Expires
    Header unset Host
    Header unset P3P
    Header unset Pragma
    Header unset Public-Key-Pins
    Header unset Public-Key-Pins-Report-Only
    Header unset Via
    Header unset X-AspNet-Version
    Header unset X-AspNetMvc-version
    Header unset X-Frame-Options
    Header unset X-Powered-By
    Header unset X-Runtime
    Header unset X-Version
</IfModule>
```

It looks like what's in the Git commit needs to appear in both of the public docs I've listed, [Basic Server Configuration For Apache](https://webhint.io/docs/user-guide/server-configurations/apache/) and [Disallowed HTTP Headers](https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/ ),.

**Comment by sarvaje** [comment]
Hi @tmb-github, that is "normal", the documentation won't be updated until a new version of webhint (with those changes) is release.
