### ISSUE TITLE
[Bug] Use `importHelpers: true` in tsconfig.json to reduce code size

### ISSUE THREAD

**Issue by antross** [webhintio/hint#3947]
Currently the webhint codebase doesn't follow [its own best practice of using `importHelpers: true`](https://webhint.io/docs/user-guide/hints/hint-typescript-config/import-helpers/) to reduce the amount of redundant helper code generated by TypeScript (also requires adding `tslib` as a dependency). This causes unnecessary bloat in the built webhint code, particularly for large bundles like the browser extension.

Seems like this should be fairly easy to do - we just haven't done it yet.

**Comment by ruppysuppy** [comment]
I could work on this one. Any suggestions on how to get started @antross?

**Comment by antross** [comment]
Hey @ruppysuppy. This should just involve adding `tslib` as a `devDependency` in the root `package.json`, then updating the root `tsconfig.json` to set `"importHelpers": true` in the `"compilerOptions"` section.

I'd recommend running `yarn build-release` from `packages/extension-browser` before and after the change to see if we get the expected decrease in bundle size (that command should tell you how large the bundle is once it finishes building it). 

If you haven't already, you'll also want to make sure to run `yarn build` from the root of the repo before you start to get all the dependencies built (this will take awhile).

**Comment by ruppysuppy** [comment]
The bundle size actually increased after setting `"importHelpers": true`

**Before setting `importHelpers`**
```
Bundle size of 714KB is within limit of 725KB defined in package.json for D:/Desktop/Projects/GitUploads/hint/packages/extension-browser/dist/firefox/webhint-2.3.1.zip.
```

**After setting `importHelpers`**
```
Bundle size of 716KB is within limit of 725KB defined in package.json for D:/Desktop/Projects/GitUploads/hint/packages/extension-browser/dist/firefox/webhint-2.3.1.zip.
```

**Comment by antross** [comment]
Thanks @ruppysuppy. That is definitely not what I expected. 

Can you post this as a draft PR so I can clone and take a look? I'm going to poke around and see exactly what code is getting generated. Thanks!

**Comment by antross** [comment]
Closing per discussion in PR. We're going to disable this hint by default as it doesn't consistently result in reduced sizes.
