### ISSUE TITLE
[Hint] Pitfalls - classList.add/remove with leading "."

### ISSUE THREAD

**Issue by antross** [webhintio/hint#3997]
I've hit this one a few times since I'm so used to writing selectors instead of plain class names. It actually adds/remove a className which includes the leading "." as part of the name which is almost never what you want. Seems like a warning/error here would be helpful as you can easily be left scratching your head about this for awhile.

E.g.
```html
<div id="foo" class="bar">
```

### Incorrect
```js
// Adds a class named ".foo" producing <div id="foo" class="bar .foo">
document.getElementById("#foo").classList.add(".foo");

// Tries to remove a class named ".bar" - silently doesn't do anything
document.getElementById("#foo").classList.remove(".bar");
```

### Correct 

```js
document.getElementById("#foo").classList.add("foo");
document.getElementById("#foo").classList.remove("bar");
```

May also be a good idea to check for a similar mistake in HTML markup too for completeness.

**Comment by ruppysuppy** [comment]
@antross, I would like to give it a shot. Could you tell me how should I approach the problem and where do I need to make the changes?

**Comment by antross** [comment]
Thanks @ruppysuppy!

This would be a new hint similar to [`hint-create-element-svg`](https://github.com/webhintio/hint/blob/main/packages/hint-create-element-svg/src/hint.ts) (feel free to copy/paste that one as a starting point). 

That hint uses `walk.simple` and `CallExpression(node)` to check for `createElement` calls. This hint should do something similar checking for `add` and `remove` calls.

To avoid false-positives this hint will also need to check if the call was on an object named `"classList"`. I suspect this can be done by switching to `walk.ancestors` and `CallExpression(node, ancestors)`, then checking if the parent is a `MemberExpression` with `parent.object.name` equal to `"classList"` (though I haven't tested this myself).
