### ISSUE TITLE
Run CI for dependency updates on Linux

### ISSUE THREAD

**Issue by antross** [webhintio/hint#4032]
Currently runs on Windows, but this is slower. Would be nice to get these through the pipeline more quickly so I propose we run on Linux. We'll still get Windows coverage once the update is merged and can always revert if necessary (same as we would do for Linux or Mac today).

**Comment by molant** [comment]
IIRC the reason why it is running on Windows is because we had problems in the past with dependencies working OK on Linux/mac and not on Win.
The reality is that most of the development of these packages is still in non-Windows environments :(
