### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by fofo384** [webhintio/hint#4058]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.1.4 
* __Browser version:__ Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:81.0) Gecko/20100101 Firefox/81.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [ ] None
* * [ ] Different origin
* * [x] Custom: google-analytics.com 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by antross** [comment]
Thanks for the report @fofo384! 

Can you share the page you were trying to analyze with webhint where this error occurred? We'll need that to try to figure out why the content script injection failed.

**Comment by hxlnt** [comment]
Hi, @fofo384--friendly ping to see if you could follow up with the URL to the page that was giving you this error so we can take a look. Otherwise, we'll assume things are all resolved and will close the issue. Thanks!
