### ISSUE TITLE
[Hint][Flexbox] Report Flex items are not correctly justified when max-width is used

### ISSUE THREAD

**Issue by captainbrosset** [webhintio/hint#4071]
_(from https://github.com/philipwalton/flexbugs#flexbug-17)_

In IE 11 the free space between or around flex items (as per their container's `justify-content` property) is not correctly calculated if a max-size property is used (`max-width` in the row direction, `max-height` in the column direction). 

Test case: https://philipwalton.github.io/flexbugs/17.1.a-bug.html

Bug (Edge on top, IE11 at the bottom)
<img width="1069" alt="bug" src="https://user-images.githubusercontent.com/1152698/95331980-0dddc680-08ab-11eb-98ef-0850b6324760.png">

This is a common pitfall that people using Flexbox and who have to support IE may fall into.
WebHint could warn against this.
WebHint could also point people to this workaround: https://github.com/philipwalton/flexbugs#workaround-16

**Comment by molant** [comment]
Maybe we can use https://github.com/webhintio/hint/issues/132 as the umbrella for all this flexbox issues?

**Comment by captainbrosset** [comment]
After talking to @antross , closing this in favor of #4072.
