### ISSUE TITLE
[docs] Issue with 'Use Apple touch icon'

### ISSUE THREAD

**Issue by firtman** [webhintio/hint#4077]
I want to express that I don't agree with this entire rule
https://webhint.io/docs/user-guide/hints/hint-apple-touch-icons/index.html

Several statements are false and/or opinionable, not actual guidelines from Apple or from the community, such as "Most sizes will probably never be used as iOS devices get upgraded quickly" (Latest iPhone SE and iPhone 11 use 120px and not 180px), or "The 180×180px image, if needed, will be automatically downscaled by Safari, and the result of the scaling is generally ok", generally ok is not enough for a recommendation. If a designer wants to create a different icon version for low-res iOS devices (120px) or for iPad devices I can't recommend that as a wrong statement. 

It might be a good recommendation for some site without an apple-touch-icon (at least, provide 180px), but if a site has 3 or 4 versions I don't see how that's bad. 

Also, wording such as "most users will probably not add the site to their home screens" are not professional, it's only someone's opinion and on some sites or PWAs that are encouraging the user to install the app, it's completely false.

**Comment by molant** [comment]
Adding the agenda label so we can discuss this during the next meeting and move forward.
@firtman it will be this Friday 16th at 9.00am PST on Zoom and you are more than welcome to join. @hxlnt creates an issue with the link a couple days earlier.

**Comment by hxlnt** [comment]
Hi, @firtman! Thanks for the feedback. The team met this morning, and we agree with the points you've made here: our `apple-touch-icons` recommendations can benefit from an update. We'd like to propose modifying this hint in the following ways:

 - Remove the current **error** that appears when multiple sizes of icons are available,
 - Present an **error** if there's no touch icon at all,
 - Present an **error** if there's only touch icon and it's not one of the default sizes per the table below,
 - Present a **warning** if additional icons aren't one of the standard sizes per our documentation (which likely needs an update), and
 - Present a **warning** if icons aren't necessary for the users' targeted browser versions.

This table of default icon sizes comes from Apple's guidance at https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/:

Device or context | Icon size
-- | --
iPhone | 180px × 180px (60pt × 60pt @3x)
  | 120px × 120px (60pt × 60pt @2x)
iPad Pro | 167px × 167px (83.5pt × 83.5pt @2x)
iPad, iPad mini | 152px × 152px (76pt × 76pt @2x)

Additionally, we would update the documentation to adjust the points you've made here. What do you think? Are there any other authoritative sources that would be helpful to include in the docs?

Thanks for reaching out and helping improve webhint! 😎

**Comment by firtman** [comment]
Great to hear that. I think the new rules are fine now. Unfortunately, there are no authoritative sources to include in the docs. Safari documentation on the topic is completely outdated. Thanks for taking the feedback and change it!

**Comment by sarvaje** [comment]
>Present an error if there's only one touch icon and it's not one of the default sizes per the table below,
Present a warning if additional icons aren't one of the standard sizes per our documentation (which likely needs an update),

If none of the icons have standard sizes, should I just show an error, or show the error and the individual warning for each of them?

**Comment by antross** [comment]
I'd lean toward showing an error for each of them in this case. No correct value is present which is what would downgrade the message to a warning normally. Plus I still think we want to report each message so the user sees all reports up-front (rather than fixing one only to get a warning on the others afterward).

**Comment by sarvaje** [comment]
I get the part of reporting individual issue for each item, but what severity, error or warning?

**Comment by antross** [comment]
If none of the icons align with sizes in the table, I'd expect all of them to report errors instead of warnings.

**Comment by sarvaje** [comment]
ok! I got it
