### ISSUE TITLE
[docs] Issue with 'Basic server configuration for Apache'

### ISSUE THREAD

**Issue by Damon-debug** [webhintio/hint#4118]
https://webhint.io/docs/user-guide/server-configurations/apache/index.html

**Comment by hxlnt** [comment]
@Damon-debug Can you provide some more information about the problem you're having with this documentation? Thanks!

**Comment by hxlnt** [comment]
Closing this issue for now; if you'd like to discuss this further, feel free to reply or open a new issue letting us know your problem so we can address it.

**Comment by Damon-debug** [comment]
Great
