### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by jchassery12** [webhintio/hint#4173]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.2.0 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by antross** [comment]
Thanks for the report @jchassery12! Any chance you could share the URL of the page you were trying to analyze when the scan timed out?

**Comment by hxlnt** [comment]
@jchassery12 Since we haven't heard back from you in over a month, we hope that this issue has since been resolved and will be marking it as closed. If you're still experiencing an issue, please feel free to reply to this issue or create a new one containing the URL that caused the error. Thanks!
