### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by kbmagill** [webhintio/hint#4176]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.2.0 
* __Browser version:__ Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:84.0) Gecko/20100101 Firefox/84.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment]
@kbmagill was this an accidental/test submission or is there a bug with the webhint browser extension you were trying to report?

**Comment by kbmagill** [comment]
can't remember which one of the things that have been hacked I've tried to sort out, but yes I guess I would have been reporting a bug. Bet you long winded nerds can't do anything about it. Let me know if I'm being unfair and you can fix it. 

    On Monday, 21 December 2020, 17:06:07 GMT, Tony Ross <notifications@github.com> wrote:  
 
 


@kbmagill was this an accidental/test submission or is there a bug with the webhint browser extension you were trying to report?

**Comment by hxlnt** [comment]
@kbmagill Whoa, let's keep the conversation friendly here! The bug report you created (https://github.com/webhintio/hint/issues/4176) was blank, so if you'd like to add more information about the trouble you're experiencing with webhint, we can take a look and see if we can help.

**Comment by hxlnt** [comment]
Since we have not received any additional information about the nature of this bug (URL scanned, error message, etc.), I'm going to close this bug for now. Feel free to respond or open a new issue if you feel this is in error. Thanks!
