### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by thatdude504016** [webhintio/hint#4197]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.2.0 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by antross** [comment]
Thanks for the report @thatdude504016! Any chance you could share the URL of the page where you hit this error?

**Comment by antross** [comment]
Closing as we aren't able to investigate without a URL to reproduce the problem. Feel free to reactivate if you're able to share more details.
