### ISSUE TITLE
[Question] Running custom actions

### ISSUE THREAD

**Issue by axemclion** [webhintio/hint#421]
What would be the best way to run custom actions - like clicking buttons, scrolling pages, etc. 

Looks like currently, the page is loaded, metrics collected and then shut down.

Would this be something that should be a part of a custom rule, where custom javascript is executed ?

**Comment by molant** [comment]
We want to add that capability in the future. So far I haven't thought exactly how to do that (don't know about @alrra or @sarvaje) but:

* I don't think it should be a custom rule, this is useful and more people will want it
* it has to run on all the connectors

Probably we will have to add a new parameter to the cli to read the actions from a file and then plug that somehow when the page is loaded.

If you want to try to do this now let us know do we can brainstorm a bit with you the best way (maybe in the glitter?).

**Comment by axemclion** [comment]
I work on a similar project called [browser-perf](http://github.com/axemclion/browser-perf/) which was more focused on rendering performance, after the page loaded. 

The basic idea was - people have selenium tests, [protractor tests](https://github.com/axemclion/protractor-perf), or other forms of integration tests. Instead of bringing those into a framework, I wrote plugin for those frameworks. These integration test frameworks would run real browsers and SOnar could record the required metrics. As a part of the test assertions, Sonar could test performance in addition to the functionality. 

Would love to chat about this on gitter.

**Comment by molant** [comment]
Hi @axemclion, sorry for disappearing. We've all been heads down working and preparing a version for the [Edge Summit](https://summit.microsoftedge.com).
After the event we will have time to think what is the best way to do this.

Thanks!

**Comment by molant** [comment]
Closing this in favor of #2200 where we explain how this will work. Work will start next week!
