### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by hub2020-hw** [webhintio/hint#4233]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.2.0 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; rv:72.0) Gecko/20100101 Firefox/72.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by antross** [comment]
Thanks for the report @hub2020-hw!

Looks like webhint timed out trying to scan the page you were viewing. Any chance you can provide a URL to the page you were analyzing so we can try to repro the issue?

**Comment by sarvaje** [comment]
Closing since we don't have anything actionable at the moment. Please feel free to reactivate with more details if there's a specific issue you want to report. Thanks!
