### ISSUE TITLE
[docs] Issue with 'Local'

### ISSUE THREAD

**Issue by nyedidikeke** [webhintio/hint#4261]
Typo under Further Reading, close to the footer of the page; "Connectors oerview" should be "Connectors overview".
https://webhint.io/docs/user-guide/connectors/connector-local/index.html

**Comment by antross** [comment]
Thanks for pointing this out @nyedidikeke! Interested in opening a (tiny) PR to fix this? The markdown that this page is generated from lives here https://github.com/webhintio/hint/blob/main/packages/connector-local/README.md.
