### ISSUE TITLE
stale-while-revalidate and stale-if-error

### ISSUE THREAD

**Issue by Simbiat** [webhintio/hint#4281]
https://webhint.io/docs/user-guide/hints/hint-http-cache/index.html

Content-Cashe hint reports:
> A 'cache-control' header contains directives with invalid values: 'stale-while-revalidate=1800', 'stale-if-error=1800'

in MS Edge 88.0.705.56, even though as per https://caniuse.com stale-while-revalidate is supported from Edge 88. stale-if-error is not supported yet by Edge, so it should be ok for it to be reported, for now. I guess an update is needed.

**Comment by antross** [comment]
Thanks for the report @Simbiat! This is a known issue with a fix is being tracked in #3691.

If you have an public URL we could use to verify the fix that'd be helpful. Feel free to link it to that bug. Thanks!
