### ISSUE TITLE
[docs] Issue with 'Webhint Visual Studio Code extension'

### ISSUE THREAD

**Issue by alexaguilar89** [webhintio/hint#4282]
https://webhint.io/docs/user-guide/extensions/vscode-webhint/index.html  i cant install

**Comment by antross** [comment]
Hi @alexaguilar89, we'd definitely like to help if we can. How are you trying to install the extension? Are there any errors you're getting that might help us figure out what's going on?

**Comment by sarvaje** [comment]
Closing since we don't have anything actionable at the moment. Please feel free to reactivate with more details if there's a specific issue you want to report. Thanks!
