### ISSUE TITLE
[docs] Issue with 'Has webpack configuration'

### ISSUE THREAD

**Issue by justinthompson313** [webhintio/hint#4304]
https://webhint.io/docs/user-guide/hints/hint-webpack-config/config-exists/index.html

**Comment by antross** [comment]
Hi @justinthompson313, is there a specific issue with the webpack config documentation you were trying to report? Thanks!

**Comment by sarvaje** [comment]
Closing since we don't have anything actionable at the moment. Please feel free to reactivate with more details if there's a specific issue you want to report. Thanks!
