### ISSUE TITLE
[docs] Issue with 'Disallowed HTTP headers'

### ISSUE THREAD

**Issue by tok3r1** [webhintio/hint#4305]
https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/index.html

**Comment by tok3r1** [comment]
https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/index.html

**Comment by sarvaje** [comment]
Hi @tok3r1, is there a bug you were trying to report or was this an accidental submission?

**Comment by antross** [comment]
Closing since we don't have anything actionable at the moment. Please feel free to reactivate with more details if there's a specific issue you want to report. Thanks!
