### ISSUE TITLE
https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/index.html

### ISSUE THREAD

**Issue by tok3r1** [webhintio/hint#4306]
https://webhint.io/docs/user-guide/hints/hint-no-disallowed-headers/index.html

_Originally posted by @tok3r1 in https://github.com/webhintio/hint/issues/4305#issuecomment-776721602_

**Comment by sarvaje** [comment]
Hi @tok3r1, is there a bug you were trying to report or was this an accidental submission?

**Comment by sarvaje** [comment]
Closing since we don't have anything actionable at the moment. Please feel free to reactivate with more details if there's a specific issue you want to report. Thanks!
