### ISSUE TITLE
[docs] Problema con 'Empezar a usar webhint'

### ISSUE THREAD

**Issue by robereight3** [webhintio/hint#4326]
https://webhint.io/docs/user-guide/index.html

**Comment by sarvaje** [comment]
Hi @robereight3.

Just to double-check, is there a bug in the documentation you were trying to report or was this an accidental submission?

**Comment by antross** [comment]
Closing since we don't have anything actionable at the moment. Please feel free to reactivate with more details if there's a specific issue you want to report. Thanks!
