### ISSUE TITLE
[Bug] webhint flags up <input type="hidden"> fields without labels

### ISSUE THREAD

**Issue by codepo8** [webhintio/hint#4383]
# 🐛 Bug report

## Input type hidden without label is flagged up as an error

Hidden form fields aren't editable and should not get a label, right?

**Comment by hxlnt** [comment]
@codepo8 This feedback comes from axe-core, so it would be worth checking https://github.com/dequelabs/axe-core. 

Also, do you have a site with this issue so we could repro?

**Comment by codepo8** [comment]
Will do. Our docs site is the problematic one.

**Comment by hxlnt** [comment]
Sounds good--will close this for now; feel free to reopen if this is actually on us and not axe.
