### ISSUE TITLE
Update tests for 'no-insecure-cookies' once 'set-cookie' header is available in headless CDP

### ISSUE THREAD

**Issue by qzhou1607** [webhintio/hint#439]
Currently, tests using `cdp`  for `no-insecure-cookies` are skipped due to the absence of `set-cookie` header when using headless cdp (Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=692090). These tests should be updated once the issue above is fixed. Also see https://github.com/sonarwhal/sonar/pull/396#issuecomment-323472531 for details.

**Comment by alrra** [comment]
> These tests should be updated once the issue above is fixed. 

![](https://user-images.githubusercontent.com/1223565/29669703-fd07b7e4-88ec-11e7-8e08-862031780a57.png)

The issue is fixed. We just need to wait until it gets into a stable release. :)
