### ISSUE TITLE
[dokumente] Problem mit 'Webhint in Ihrem Projekt konfigurieren'

### ISSUE THREAD

**Issue by MagicMark88** [webhintio/hint#4425]
https://webhint.io/docs/user-guide/configuring-webhint/summary/index.html

**Comment by MagicMark88** [comment]
position: fixed;
    border: 0;
    width: 100%;
    height: 100%;
    text-align: center;
    line-height: 100%;
    font-size: large;
    display: none;

**Comment by MagicMark88** [comment]
position: fixed;
    border: 0;
    width: 100%;
    height: 100%;
    text-align: center;
    line-height: 100%;
    font-size: large;
    display: none;

**Comment by hxlnt** [comment]
Closing this issue, as this doesn't appear to be an issue with webhint. Please be sure to include a description of the issue you're seeing in the documentation so we can troubleshoot accordingly. Thanks!
