### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by Yavnet2021** [webhintio/hint#4441]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.1 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by antross** [comment]
Thanks for the report @Yavnet2021!

Is this affecting you on all pages or only on a specific site? If it's a specific site, are you able to share a URL we can look at to repro the issue? Thanks!

**Comment by hxlnt** [comment]
Closing this for now since we're not able to repro.
