### ISSUE TITLE
report abuse

### ISSUE THREAD

**Issue by Yernando** [webhintio/hint#4444]
Hi there.

I would like to report a repository which contains confidential information which can put the Ministry of Foreign Relations at risk, this repository contains sensitive information about vulnerabilities in a URL.

URL Official: https://mexitel.sre.gob.mx/citas.webportal/pages/public/login/login.jsf
Repository: https://github.com/webhintio/scan-issues/issues/32895

I would greatly appreciate your support.

**Comment by hxlnt** [comment]
Fixed.
