### ISSUE TITLE
scanned timed out

### ISSUE THREAD

**Issue by rupesh8182** [webhintio/hint#4488]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.1 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [ ] Accessibility
* [ ] Compatibility
* [ ] Performance
* [ ] Pitfalls
* [ ] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by antross** [comment]
Thanks for the report @rupesh8182! Any chance you can share the URL for the page you were analyzing when the scan timed out? 

Without a page to reproduce the issue on we likely won't be able to fix it.
