### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by anne41** [webhintio/hint#4512]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.1 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by hxlnt** [comment]
Hi, @anne41--Without error details or a URL, we won't be able to troubleshoot. Can you please include them in your bug description? Thanks!
