### ISSUE TITLE
documents and applications when i go to submit does not do at all  any help.. 

### ISSUE THREAD

**Issue by Freedom62** [webhintio/hint#4581]
Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by hxlnt** [comment]
@Freedom62 It looks like the bug report you included is blank. Could you share the URL, webhint version, etc. and describe the problem you're encountering? Thanks!

**Comment by hxlnt** [comment]
Closing for now without any additional information about the issue at hand. Please feel free to open a new issue if you have additional debug information.
