### ISSUE TITLE
[خطأ] وصف الخطأ

### ISSUE THREAD

**Issue by srgt30** [webhintio/hint#4637]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.2 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [ ] Recommended settings
* [x] Custom: defaults, not IE 11 

Ignored resources:
* * [ ] None
* * [ ] Different origin
* * [x] Custom: google-analytics.com 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by antross** [comment]
@srgt30 are you able to share the URL where the scan timed out? It'll help us reproduce the issue so we can investigate.
