### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by dustin582** [webhintio/hint#4677]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.2 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.59 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [ ] Pitfalls
* [ ] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by dustin582** [comment]
<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160">
    <g fill="none" fill-rule="evenodd">
        <path fill="#F8F8F8" d="M0 0H1280V1299H0z" transform="translate(-560 -389)"/>
        <path fill="#FFF" stroke="#D8DDE6" d="M380.5 106.5H899.5V1126.5H380.5z" transform="translate(-560 -389)"/>
        <g fill="#003057" fill-rule="nonzero">
            <path d="M0 140.69v-19.31h38.62V160H0v-19.31zm33.103 0v-13.793H5.517v27.586h27.586V140.69z" transform="translate(-560 -389) matrix(1 0 0 -1 560 549)"/>
            <path d="M11.034 140.69L11.034 132.414 19.31 132.414 27.586 132.414 27.586 140.69 27.586 148.966 19.31 148.966 11.034 148.966z" transform="translate(-560 -389) matrix(1 0 0 -1 560 549)"/>
            <path d="M55.172 154.483v-5.517H44.138v-33.104H49.655v-11.034h-5.518V110.345h-5.516v5.518H11.034V99.31H5.517v16.552H0V99.31H5.517V93.793H11.034V82.76h5.518v11.034H22.069V71.724H11.034V77.241H5.517V71.724H0V44.138H5.517V60.69h11.035v-5.518h-5.518V44.138h33.104V38.62h11.034V16.552H49.655V33.103h-5.518V11.034h11.035V5.517h11.035V0H71.724V5.517H77.241V0H99.31V5.517H88.276v11.035h5.518V22.069h5.516V11.034h5.518V0H110.345V5.517h11.034V0h27.587V5.517H154.483v11.035H148.966v11.034h-5.518V22.07H137.931v11.034h11.035v5.518H160v11.034H154.483V55.172H148.966v16.552H154.483V77.241H148.966v5.518H137.93V88.276h11.035v5.518H154.483v5.516H148.966V93.793h-5.518V99.31H137.931V88.276H132.414V82.759H126.897V88.276h-5.518V82.759H115.862V88.276H110.345v5.518h5.518v5.516h5.516V93.793h11.035V99.31h-11.035v5.518h16.552V110.345h11.035v5.518h-27.587v-11.035h-11.034v11.034h5.518v11.035h-5.518v-5.518H104.828v5.518H99.31v-11.035H93.793V110.345H88.276v11.034h5.518v11.035h-5.518V137.93H99.31V143.448H93.793v5.518H88.276V137.93h-38.62V143.448h5.516v5.518h11.035v-5.518H71.724v11.035h-5.518V160H55.173v-5.517zm0-30.345v-2.759h5.518v5.518H66.207v-5.518H71.724v5.518H77.241v-5.518h5.518v5.518H88.276v-5.518H82.759V115.862H77.24V110.345h5.518V104.828h11.034V99.31H99.31v5.518h11.035V93.793H104.828V88.276H99.31V82.759h11.035V66.207H99.31V60.69h27.587V49.655h-16.552v-5.518H104.828V33.104H99.31V27.586h11.035V22.07h16.552V16.552h-11.035v-5.518H110.345v5.518H104.828V22.069H99.31V27.586H88.276v16.552H71.724V38.62h-5.518v-5.518h5.518V27.586H77.241V33.103h5.518V27.586H77.24V22.07h11.035V16.552H82.759v-5.518H77.24V22.07H71.724V11.034H60.69v5.518H66.207v11.034H60.69v11.035H66.207V44.138H60.69V49.655h11.034V71.724H77.241V77.241h5.518V71.724H77.24v-5.518h5.518V60.69h11.034V66.207H88.276V77.24H99.31v5.518H88.276V88.276H71.724V99.31h-5.518v5.518h5.518V110.345h-5.518v5.518H60.69v-5.518h-5.518v5.518H49.655V126.896H55.172v-2.76zm-16.551-16.552v-2.758h-5.518V99.31h16.552v5.518H60.69V99.31H49.655V93.793H55.172V88.276h5.518v5.518H66.207v-5.518H60.69V82.759H66.207V77.24H60.69V71.724H66.207v-5.518H60.69v5.518h-5.518v-5.518H44.138V60.69H60.69v-5.518h-5.518V49.655H49.655V55.172h-5.518V49.655H22.07V60.69H16.552V66.207H22.069V71.724h11.034V77.241H27.586v5.518H33.103V88.276h11.035v5.518H33.103v5.516H27.586V93.793H22.07v11.035H16.552V110.345H38.62v-2.759zm88.276-33.103v-8.276h-11.035V71.724H121.38V82.76h5.518v-8.276zM137.93 80v-2.759h11.035V71.724H137.93v-5.518H143.448V55.173h5.518V49.655h-5.518v-5.518H137.931v11.035H132.414v5.518H137.93V66.207H132.414V71.724H137.93V77.241H132.414v5.518H137.93V80zM11.034 68.966v-2.76H5.517v5.518H11.034v-2.758zm121.38-33.104v-8.276h-16.552v16.552h16.552v-8.276zm5.517-16.552v-2.758H132.414V22.069H137.93V19.31zM126.897 8.276V5.517h-5.518V11.034h5.518V8.276zm11.034 0V5.517H132.414V11.034H137.93V8.276zm11.035 0V5.517h-5.518V11.034h5.518V8.276z" transform="translate(-560 -389) matrix(1 0 0 -1 560 549)"/>
            <path d="M71.724 118.621L71.724 115.862 74.483 115.862 77.241 115.862 77.241 118.621 77.241 121.379 74.483 121.379 71.724 121.379zM77.241 96.552L77.241 93.793 80 93.793 82.759 93.793 82.759 96.552 82.759 99.31 80 99.31 77.241 99.31zM88.276 93.793L88.276 88.276 93.793 88.276 99.31 88.276 99.31 91.034 99.31 93.793 96.552 93.793 93.793 93.793 93.793 96.552 93.793 99.31 91.034 99.31 88.276 99.31zM93.793 68.966L93.793 66.207 96.552 66.207 99.31 66.207 99.31 68.966 99.31 71.724 96.552 71.724 93.793 71.724zM77.241 52.414L77.241 49.655 80 49.655 82.759 49.655 82.759 52.414 82.759 55.172 80 55.172 77.241 55.172zM88.276 52.414L88.276 49.655 91.034 49.655 93.793 49.655 93.793 46.897 93.793 44.138 96.552 44.138 99.31 44.138 99.31 46.897 99.31 49.655 96.552 49.655 93.793 49.655 93.793 52.414 93.793 55.172 91.034 55.172 88.276 55.172zM104.828 52.414L104.828 49.655 107.586 49.655 110.345 49.655 110.345 52.414 110.345 55.172 107.586 55.172 104.828 55.172zM44.138 85.517L44.138 82.759 38.621 82.759 33.103 82.759 33.103 80 33.103 77.241 38.621 77.241 44.138 77.241 44.138 74.483 44.138 71.724 38.621 71.724 33.103 71.724 33.103 68.966 33.103 66.207 27.586 66.207 22.069 66.207 22.069 63.448 22.069 60.69 27.586 60.69 33.103 60.69 33.103 57.931 33.103 55.172 35.862 55.172 38.621 55.172 38.621 57.931 38.621 60.69 35.862 60.69 33.103 60.69 33.103 63.448 33.103 66.207 38.621 66.207 44.138 66.207 44.138 68.966 44.138 71.724 46.897 71.724 49.655 71.724 49.655 80 49.655 88.276 46.897 88.276 44.138 88.276zM55.172 80L55.172 77.241 57.931 77.241 60.69 77.241 60.69 80 60.69 82.759 57.931 82.759 55.172 82.759zM121.379 35.862L121.379 33.103 124.138 33.103 126.897 33.103 126.897 35.862 126.897 38.621 124.138 38.621 121.379 38.621zM82.759 157.241L82.759 154.483 88.276 154.483 93.793 154.483 93.793 157.241 93.793 160 88.276 160 82.759 160zM99.31 157.241L99.31 154.483 107.586 154.483 115.862 154.483 115.862 157.241 115.862 160 107.586 160 99.31 160zM121.38 140.69v-19.31H160V160h-38.62v-19.31zm33.103 0v-13.793h-27.586v27.586h27.586V140.69z" transform="translate(-560 -389) matrix(1 0 0 -1 560 549)"/>
            <path d="M132.414 140.69L132.414 132.414 140.69 132.414 148.966 132.414 148.966 140.69 148.966 148.966 140.69 148.966 132.414 148.966zM77.241 146.207L77.241 143.448 80 143.448 82.759 143.448 82.759 146.207 82.759 148.966 80 148.966 77.241 148.966zM104.828 140.69L104.828 132.414 110.345 132.414 115.862 132.414 115.862 135.172 115.862 137.931 113.103 137.931 110.345 137.931 110.345 140.69 110.345 143.448 113.103 143.448 115.862 143.448 115.862 146.207 115.862 148.966 110.345 148.966 104.828 148.966zM154.483 107.586L154.483 104.828 157.241 104.828 160 104.828 160 107.586 160 110.345 157.241 110.345 154.483 110.345zM0 85.517L0 82.759 2.759 82.759 5.517 82.759 5.517 85.517 5.517 88.276 2.759 88.276 0 88.276zM154.483 85.517L154.483 82.759 157.241 82.759 160 82.759 160 85.517 160 88.276 157.241 88.276 154.483 88.276zM154.483 63.448L154.483 60.69 157.241 60.69 160 60.69 160 63.448 160 66.207 157.241 66.207 154.483 66.207zM0 19.31V0h38.62v38.62H0V19.31zm33.103 0V5.517H5.517v27.586h27.586V19.31z" transform="translate(-560 -389) matrix(1 0 0 -1 560 549)"/>
            <path d="M11.034 19.31L11.034 11.034 19.31 11.034 27.586 11.034 27.586 19.31 27.586 27.586 19.31 27.586 11.034 27.586zM154.483 27.586L154.483 22.069 157.241 22.069 160 22.069 160 27.586 160 33.103 157.241 33.103 154.483 33.103zM44.138 2.759L44.138 0 46.897 0 49.655 0 49.655 2.759 49.655 5.517 46.897 5.517 44.138 5.517z" transform="translate(-560 -389) matrix(1 0 0 -1 560 549)"/>
        </g>
        <path fill="#BD10E0" fill-opacity=".089" d="M610 482H618V509H610z" transform="translate(-560 -389)"/>
    </g>
</svg>

**Comment by hxlnt** [comment]
@dustin582 Can you let us know for what URL the scan timed out for so we can try to repro? Thanks.
