### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by shangsandalaohu123** [webhintio/hint#4684]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.2 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.55 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [ ] Recommended settings
* [x] Custom: defaults, not IE 11 

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by hxlnt** [comment]
@shangsandalaohu123 Can you include the URL and error details to help us repro? Thanks.
