### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by JanGray** [webhintio/hint#4709]
# 🐛 Bug report

## Description

Trying to open Paypal

## Environment

* __webhint version:__ 2.3.2 
* __Browser version:__ Mozilla/5.0 (Windows NT 6.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [ ] None
* * [x] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->21:38:36.128 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:205
21:38:36.135 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:33:27
21:38:36.138 Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).
21:38:36.152 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:33:25
21:38:36.153 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:54:38
21:38:36.480 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:33:25
21:38:36.481 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:54:38
21:38:38.965 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.gstatic.com/recaptcha/releases/JF4U2g-hvLrBJ_UxdbKj92gN/recaptcha__en.js. (Reason: CORS request did not succeed).
21:38:38.965 None of the “sha384” hashes in the integrity attribute match the content of the subresource. recaptcha_v2.html
21:38:39.863 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). jquery-1.12.4.js:4743:7
21:40:13.646 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. recaptcha_v2.html:4:357
21:40:13.646 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. recaptcha_v2.html:4:1055
21:40:14.052 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. app.css:22:14
21:40:14.052 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. app.css:79:14
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:172:19
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:175:22
21:40:14.052 Unknown property ‘zoom’.  Declaration dropped. app.css:194:8
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. app.css:221:7
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:244:22
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:308:22
21:40:14.052 Unknown property ‘-moz-opacity’.  Declaration dropped. app.css:380:16
21:40:14.052 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:385:11
21:40:14.052 Unknown property ‘-moz-opacity’.  Declaration dropped. app.css:388:16
21:40:14.052 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:393:11
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:454:19
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:457:22
21:40:14.052 Unknown property ‘-moz-webkit-appearance’.  Declaration dropped. app.css:465:26
21:40:14.052 Unknown property ‘webkit-appearance’.  Declaration dropped. app.css:468:21
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:579:22
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:594:22
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:616:22
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app.css:626:18
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app.css:648:27
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app.css:663:33
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:682:22
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:686:19
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:697:19
21:40:14.052 Unknown property ‘-moz-background-clip’.  Declaration dropped. app.css:709:24
21:40:14.052 Expected media feature name but found ‘-o-min-device-pixel-ratio’. app.css:720:128
21:40:14.052 Expected media feature name but found ‘min-device-pixel-ratio’. app.css:720:178
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:897:22
21:40:14.053 Unknown property ‘-moz-opacity’.  Declaration dropped. app.css:910:16
21:40:14.053 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:915:11
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:962:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1035:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1107:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1116:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1174:22
21:40:14.053 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:1178:19
21:40:14.053 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:1192:19
21:40:14.053 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:1206:19
21:43:39.566 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 70ms]




```

</details>

**Comment by JanGray** [comment]
21:38:36.128 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:205
21:38:36.135 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:33:27
21:38:36.138 Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).
21:38:36.152 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:33:25
21:38:36.153 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:54:38
21:38:36.480 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:33:25
21:38:36.481 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:54:38
21:38:38.965 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.gstatic.com/recaptcha/releases/JF4U2g-hvLrBJ_UxdbKj92gN/recaptcha__en.js. (Reason: CORS request did not succeed).
21:38:38.965 None of the “sha384” hashes in the integrity attribute match the content of the subresource. recaptcha_v2.html
21:38:39.863 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). jquery-1.12.4.js:4743:7
21:40:13.646 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. recaptcha_v2.html:4:357
21:40:13.646 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. recaptcha_v2.html:4:1055
21:40:14.052 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. app.css:22:14
21:40:14.052 Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. app.css:79:14
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:172:19
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:175:22
21:40:14.052 Unknown property ‘zoom’.  Declaration dropped. app.css:194:8
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. app.css:221:7
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:244:22
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:308:22
21:40:14.052 Unknown property ‘-moz-opacity’.  Declaration dropped. app.css:380:16
21:40:14.052 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:385:11
21:40:14.052 Unknown property ‘-moz-opacity’.  Declaration dropped. app.css:388:16
21:40:14.052 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:393:11
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:454:19
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:457:22
21:40:14.052 Unknown property ‘-moz-webkit-appearance’.  Declaration dropped. app.css:465:26
21:40:14.052 Unknown property ‘webkit-appearance’.  Declaration dropped. app.css:468:21
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:579:22
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:594:22
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:616:22
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app.css:626:18
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app.css:648:27
21:40:14.052 Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. app.css:663:33
21:40:14.052 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:682:22
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:686:19
21:40:14.052 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:697:19
21:40:14.052 Unknown property ‘-moz-background-clip’.  Declaration dropped. app.css:709:24
21:40:14.052 Expected media feature name but found ‘-o-min-device-pixel-ratio’. app.css:720:128
21:40:14.052 Expected media feature name but found ‘min-device-pixel-ratio’. app.css:720:178
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:897:22
21:40:14.053 Unknown property ‘-moz-opacity’.  Declaration dropped. app.css:910:16
21:40:14.053 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. app.css:915:11
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:962:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1035:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1107:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1116:22
21:40:14.053 Unknown property ‘-moz-border-radius’.  Declaration dropped. app.css:1174:22
21:40:14.053 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:1178:19
21:40:14.053 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:1192:19
21:40:14.053 Unknown property ‘-moz-box-shadow’.  Declaration dropped. app.css:1206:19
21:43:39.566 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 70ms]

21:44:39.616 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 94ms]

21:45:10.096 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 109ms]

21:45:40.223 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 62ms]

21:46:11.067 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 77ms]

21:48:12.356 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 78ms]

21:49:12.563 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 79ms]

21:49:43.376 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 63ms]

21:50:13.433 XHRPOSThttps://www.paypal.com/platform/tealeaftarget
[HTTP/2 200 OK 78ms]

**Comment by captainbrosset** [comment]
I am not seeing anything actionable here. The error messages don't seem related to webhint but instead seem to be messages logged by the browser upon parsing a page.
I'll go ahead and close this for now.
