### ISSUE TITLE
[Bug] Bug description<!-- ✍️ Paste the error details here -->

### ISSUE THREAD

**Issue by swetlija** [webhintio/hint#4820]
# 🐛 Bug report

## Environment

* __webhint version:__ 
* __Browser version:__ 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by hxlnt** [comment]
Closing this bug since there are no error, environment, or URL details included for us to help debug.
