### ISSUE TITLE
[Bug] Webhint failing npx hint . is run

### ISSUE THREAD

**Issue by AnselemOdims** [webhintio/hint#4836]
## Description
Webhint keeps failing when ``` npx hint . ```  is run, even though the connector is set to local and the files are in the project root directory.

Please tell us about your:

## Environment

* __`hint` version: _6.1.6_
* __`Node.js` version: _14.17.6_
* __`npm` version: _7.24.1_

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js

{
    "connector": {
      "name": "local",
      "options": {
        "pattern": ["**", "!.git/**", "!node_modules/**"]
      }
    },
    "extends": ["development"],
    "formatters": ["stylish"],
    "hints": [
      "button-type",
      "disown-opener",
      "html-checker",
      "meta-charset-utf-8",
      "meta-viewport",
      "no-inline-styles:error"
    ]
  }

```

</details>

## URL for which `webhint` failed

* __URL:__ npx webhint .

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text

Analyzing file://./
AnalyzerError: EACCES: permission denied, scandir '/lost+found'
    at Analyzer.analyze (/home/anselemcodes/Documents/Portfolio/node_modules/hint/dist/src/lib/analyzer.js:151:23)
    at async exports.default (/home/anselemcodes/Documents/Portfolio/node_modules/hint/dist/src/lib/cli/analyze.js:219:9)
    at async /home/anselemcodes/Documents/Portfolio/node_modules/hint/dist/src/lib/cli/actions.js:8:20
    at async Object.execute (/home/anselemcodes/Documents/Portfolio/node_modules/hint/dist/src/lib/cli.js:38:23)
    at async run (/home/anselemcodes/Documents/Portfolio/node_modules/hint/dist/src/bin/hint.js:21:24) {
  status: 'AnalyzeError'
}

```

</details>

**Comment by AnselemOdims** [comment]
Thanks for the follow up @antross. Hopefully, we can start testing it out soon

**Comment by MrBrN197** [comment]
Thanks, @antross, that would be helpful.

**Comment by antross** [comment]
@AnselemOdims @MrBrN197 the updated version with the fix is now live on NPM if you want to give it a try.

**Comment by AnselemOdims** [comment]
Thanks for this Tony. We run a test and give a feedback.

**Comment by MrBrN197** [comment]
Thanks @antross It's working for me. 👍

**Comment by AnselemOdims** [comment]
Thanks @antross, It's working over here too.
