### ISSUE TITLE
[Bug] removeComments is inappropriate to suggest

### ISSUE THREAD

**Issue by DanielRosenwasser** [webhintio/hint#4839]
# 🐞 Bug report

## Description

webhint currently has a suggestion that TypeScript users turn on `removeComments` in their project because this will help reduce payload size over the wire. This is inappropriate because users who care about this should either be using a minifier, or the comment emit doesn't matter enough in the first place. Ideally, TypeScript wouldn't even have supported `removeComments` if we did it all over again.

## Details

The TypeScript team received a suggestion about this behavior and it wasn't clear that this was a hint from webhint, not TypeScript.

https://github.com/microsoft/TypeScript/issues/46596

Our team doesn't believe this is an appropriate best practice to suggest though.

**Comment by antross** [comment]
Thanks @DanielRosenwasser! We'll update to remove this suggestion.

**Comment by DanielRosenwasser** [comment]
Thank you very much!
