### ISSUE TITLE
HTML fragments starting with <li> incorrectly report requiring a <ul> parent

### ISSUE THREAD

**Issue by antross** [webhintio/hint#4868]
Webhint has logic to handle HTML fragments such that expected ancestors should be assumed to be present in the final result, but that doesn't appear to be happening when `li` is the root node of a fragment. 

I can repro with just a basic HTML file containing an empty `li`:
```
<li></li>
```

When opening this in the VS Code extension, webhint reports:
> `<li> elements must be contained in a <ul> or <ol> webhint(axe/structure)`

_Originally posted by @antross in https://github.com/webhintio/hint/issues/4840#issuecomment-956414676_

**Comment by antross** [comment]
FYI @QuickScoP3s, this false-positive should be fixed now.

**Comment by QuickScoP3s** [comment]
Thank you very much
