### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by Norti85** [webhintio/hint#4892]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.5 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by hxlnt** [comment]
We're not able to repro this issue without a URL to test. Closing this for now, as it's a bit stale. Feel free to open a new bug if you continue to experience issues.
