### ISSUE TITLE
[Docs Bug] Add docs improvement idea here

### ISSUE THREAD

**Issue by fahadfa** [webhintio/hint#4893]
# 📚 Request documentation enhancements

 Description
 your idea for improving the webhint docs. -->

#4260 Details

**Comment by fahadfa** [comment]
> # 📚 Request documentation enhancements
> 
> 
> 
>  Description
> 
>  your idea for improving the webhint docs. -->
> 
> 
> 
> #4260 Details
> 
> 
> 
>

**Comment by hxlnt** [comment]
Thanks for the +1. We'll continue to track the request with #4260, so please check that thread for the latest. We also welcome community PRs. Will close this issue as a duplicate for now.
