### ISSUE TITLE
Custom event to evaluate scripts on a connector

### ISSUE THREAD

**Issue by molant** [webhintio/hint#497]
Initial comment: https://github.com/sonarwhal/sonar/pull/494#discussion_r137435860

Right now we are telling developers to use `traverse::end` to `evaluate` their scripts. The problem is that with the changes in https://github.com/sonarwhal/sonar/pull/494 with `jsdom` we could actually `evaluate` at the beginning instead of waiting at the end to save a few seconds. That is not the case with `chrome` where we will be interfering with the page.

The proposal is to create a new event `canevaluate` (or similar) that will be fired by the connectors when it is best for them to `evaluate`.  `jsdom` will fire it sooner than `chrome` in this case.

What do you think @sonarwhal/contributors ?

**Comment by molant** [comment]
@alrra we did this, right?

**Comment by alrra** [comment]
> we did this, right?

Yes, in https://github.com/webhintio/hint/commit/32bddebdb212.
