### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by dgabrial** [webhintio/hint#5029]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.5 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by dgabrial** [comment]
i been having issues with the search bar in private browsing. keeps sending me to an error page. tyin to figure out what the issue is. maybe that i need to install jquery, currently learning to use devtools its all very complicated, hoping this webhint would help so i download it in microsoft edge and it had not download, message sess that might be a javascript issue? i was able to download the desktop version. so i continue my  microsoft edge issues hoping to use this program for giudance but when i go to the scanning part in the webhint ext. it was unable to do it and then brought me here.  so it maybe issues with my browser, tht its missiing search properties or whatever. i will continue to try and figure it out. thank you

**Comment by captainbrosset** [comment]
@dgabrial I'm sorry but I don't think your issue is related to webhint. It seems you are having an issue with the browser itself, in which case I would suggest using the browser's feedback button to send a report of your problem to the browser team. To do this, click the three-dots button in the top-right corner of the browser window, and then Help and feedback, then Send feedback.

**Comment by dgabrial** [comment]
I figured it out. I didn't have java installed. So after install  my issue
was resolved. private browsing works! finally!  I will try out webhint
again.

Thank you.
