### ISSUE TITLE
[Bug] Incorrect SVG role=img warning 

### ISSUE THREAD

**Issue by captainbrosset** [webhintio/hint#5030]
# 🐞 Bug report

## Description

This was originally reported here: https://github.com/microsoft/vscode-edge-devtools/issues/824 but is most likely a bug with webhint, instead of the vscode-edge-devtools extension.

> When defining an SVG in JSX, Microsoft Edge Tools throws an error " elements with an img role must have an alternative text: Element child title is empty Element has no title attribute" if the text for the title attribute is passed in as a required prop. While the title prop passed in could, technically, be an empty string (thus making this a valid error), the extension should assume that you are passing in something valid rather than assuming you are throwing garbage in.
> 
> Repro steps:
> 1. Make a React FC with an SVG element in it, with the `role="img"` property on it.
> 1. Make the FC take a prop of `title`, a required string.
> 1. In your SVG, have `<title>{props.title}</title>`.
> 1. See VS Code error message.
> 
> **Expected behavior**:
> At maximum, I'd expect a warning in this situation - since it technically could be an empty string. However, I think this should just not raise an error if the title attribute contains a defined variable within it. It's barely an error scenario and certainly not guaranteed as one.

## Details

![image](https://user-images.githubusercontent.com/1152698/152752456-a701c7c6-128b-48ef-a0ad-553ae618ccc1.png)

![image](https://user-images.githubusercontent.com/1152698/152752482-a1a2269e-0c42-491c-9e9e-ee9e6964ced5.png)

**Comment by antross** [comment]
Thanks @captainbrosset and @tobybaratta, I agree this looks like a webhint issue.

Per https://dequeuniversity.com/rules/axe/4.4/svg-img-alt using a `<title>` element should be a valid way to label the `<svg>`. Typically, webhint has handled similar cases by ensuring the variable interpolation is replaced with placeholder text before being processed. I suspect we likely need to do the same here.
