### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by wakedick** [webhintio/hint#5053]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.5 
* __Browser version:__ Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [ ] Recommended settings
* [x] Custom: defaults, not IE 11 

Ignored resources:
* * [ ] None
* * [ ] Different origin
* * [x] Custom: google-analytics.com 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by captainbrosset** [comment]
Unfortunately this bug report is empty, so let me close it for now. Feel free to come back with more information if you have any and we can re-open the issue then.
