### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by uremycoxx** [webhintio/hint#5069]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.5 
* __Browser version:__ Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by captainbrosset** [comment]
Unfortunately this bug report is empty, so let me close it for now. Feel free to come back with more information if you have any and we can re-open the issue then.
