### ISSUE TITLE
Adapt to removal of `matches` from MDN schema

### ISSUE THREAD

**Issue by antross** [webhintio/hint#5126]
See https://github.com/mdn/browser-compat-data/issues/8945#issuecomment-1104089992

There are three CSS features we currently use this data to report issues on. Once the removal lands webhint will still work, but will not report compatibility issues for these three cases:
* Use of 3-value `transform-origin` syntax
* Use of 3D keywords in `transform` syntax
* Use of alpha in hex color values

We should review current browser support for these features and decide if there's sufficient value in continuing to report lack of browser support in these cases. If so, we can add logic to special-case these within webhint itself (and possibly look for other newer cases to include that were never covered by MDN data). If not, we can let the MDN change flow through without changes (though we should probably clean up code related to `matches`).

**Comment by queengooborg** [comment]
We'll be sure to hold off on removing `matches` from BCD for the time being.  If there's anything we can do to help out on your end as well, please don't hesitate to ask!
