### ISSUE TITLE
[Bug] Custom severity overrides do not work

### ISSUE THREAD

**Issue by downzer0** [webhintio/hint#5155]
# 🐞 Bug report

## Description

I am trying to specify custom severities for the Axe set of rules, but whenever I try to override them I get an error. It seems to only expect and allow "error" and "off", despite being configurable to be more or less severe.

The same thing happens if I use "error" for the object and override with anything other than "error" inside the object, aside from "off".

## Details

```
.hintrc
// altering base to minimum allowed then overwriting a few higher

    "axe/parsing": [
      "warning",
      {
        "duplicate-id": "warning",
        "duplicate-id-active": "warning",
        "duplicate-id-aria": "warning",
        "marquee": "error"
      }
    ],
    "axe/forms": [
      "hint",
      {
        "autocomplete-valid": "error",
        "form-field-multiple-labels": "error",
        "label": "error",
        "select-name": "error",
        "label-title-only": "hint"
      }
    ]
```

```bash
> hint -c .hintrc src/app/components/**

strict mode: unknown keyword: "typeof" Error: strict mode: unknown keyword: "typeof"
    at checkStrictMode (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/compile/util.js:174:15)
    at checkUnknownRules (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/compile/util.js:32:13)
    at checkKeywords (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/compile/validate/index.js:120:34)
    at validateFunctionCode (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/compile/validate/index.js:19:9)
    at Ajv.compileSchema (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/compile/index.js:80:45)
    at Ajv._compileSchemaEnv (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/core.js:472:37)
    at Ajv.compile (/Users/xxx/git/xxx/node_modules/hint/node_modules/ajv/dist/core.js:159:38)
    at validate (/Users/xxx/git/xxx/node_modules/hint/node_modules/@hint/utils-json/dist/src/schema-validator.js:196:40)
    at validateHint (/Users/xxx/git/xxx/node_modules/hint/dist/src/lib/config/config-hints.js:26:38)
    at /Users/xxx/git/xxx/node_modules/hint/dist/src/lib/config/config-hints.js:46:20
```

**Comment by captainbrosset** [comment]
Thanks for reaching out. Looks like we'll need @antross to investigate this one.

**Comment by downzer0** [comment]
@captainbrosset thanks! @antross i am currently blocked by this. happy to provide additional info if you need it.

**Comment by antross** [comment]
Thanks @downzer0. Looks like we're failing trying to validate the schema of the config file (which is surprising). I'll take a look and see if I can figure out what's up.

**Comment by downzer0** [comment]
got it, thanks for investigating! i'm trying to create four sets of "hints" that roughly mirror axe-core's severities (critical, serious, moderate, minor... and we could throw in best practice maybe..) for my devs. an example might be something like:

critical -> error
serious -> error
moderate -> warning
minor -> hint
bp -> information

**Comment by downzer0** [comment]
awesome! is this configurable?

**Comment by antross** [comment]
> awesome! is this configurable?

Not currently, but I'd be open to reviewing a PR to make it configurable if @molant is on board.

The current helper that maps severity lives here:
https://github.com/webhintio/hint/blob/86a21f9d09e2e0c824fff06081f329f0382af256/packages/hint-axe/src/util/axe.ts#L117

And the code that generates the allowed hint-axe configuration schema lives here:
https://github.com/webhintio/hint/blob/86a21f9d09e2e0c824fff06081f329f0382af256/packages/hint-axe/scripts/create/create-metas.js#L43

**Comment by molant** [comment]
What needs to be configurable? I can't find that quoted text in the conversation 😔

That said, as long as it's not a breaking change I'm usually on board to add new features.

**Comment by antross** [comment]
@molant this question was about adding a way to configure the mapping of axe-core impact to webhint severity. E.g. if you wanted all "serious" impact reports mapped to "error" instead of the current mapping which is "warning". At the moment, we can only configure this on a rule-by-rule basis (which is also buggy, but I'm already looking into fixing that).

**Comment by antross** [comment]
Hi @downzer0, for configuring the sub-rules you still have to use one of webhint's severities instead of the axe-core impact, so one of ["error", "warning", "hint", "information"]. My fix should also enable setting a base severity for the entire bucket that isn't `default`, but everything needs to be specified using webhint severities.

If we want to track adding a custom mapping of axe-core impact to webhint severity, I'd recommend moving that to a separate bug. We're not currently planning on doing that, but I'd be supportive of enhancing this hint with such a configuration if there's interest.
