### ISSUE TITLE
ARIA-Hidden Elements 

### ISSUE THREAD

**Issue by Butterfly818** [webhintio/hint#5157]
Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by captainbrosset** [comment]
This issue appears to be empty unfortunately. I'll go ahead and close it now as there is no information to work towards a fix. Feel free to comment with more information.
