### ISSUE TITLE
Remove or reduce severity of reports for `Via` HTTP Header

### ISSUE THREAD

**Issue by antross** [webhintio/hint#5159]
Taking the liberty to comment on this issue, especially regarding the `Via` HTTP header. More often that not, it appears that this header is added by proxies, which makes it difficult or impossible to fix. For instance, [Google Cloud Load Balancing](https://cloud.google.com/load-balancing/docs/https) adds `Via: 1.1 google` to incoming requests and responses. Any CDN sitting behind GCLB, such as [Sanity](https://sanity.io)’s, will display this header. 

The article linked in the original message from this issue also mentions this. Although it does say it’s most likely safe to remove (which I’m not arguing here), it also states that proxies have to set it up, and most people don’t have control over their proxy.

> More debatable perhaps is Via, which is required ([by RFC7230](https://httpwg.org/specs/rfc7230.html#header.via)) to be added to the request by any proxy through which it passes to identify the proxy. This can be the proxy’s hostname, but is more likely to be a generic identifier like “vegur”, “varnish”, or “squid”. Removing (or not setting) this header on a request can cause [proxy forwarding loops](http://www.icir.org/vern/papers/cdn-loops.NDSS16.pdf). However, interestingly it is also copied into the response on the way back to the browser, and here it's just informational and no browsers do anything with it, so it’s reasonably safe to get rid of it if you want to.

I was wondering if you’d be considering dropping the `Via` warning.

_Originally posted by @KittyGiraudel in https://github.com/webhintio/hint/issues/1096#issuecomment-1119311751_

**Comment by molant** [comment]
I can't remember why `Via` is not recommended so I'm inclined to remove it or revisit the severity if we find up to date information about possible issues with it.

**Comment by KittyGiraudel** [comment]
From what I gathered from the repository activity, `Via` was discussed as part of [a broader discussion](https://github.com/webhintio/hint/issues/1096#issuecomment-632722942) and just added with a bunch of other headers. I don’t think too much thought went into that header in particular.

**Comment by molant** [comment]
Thanks for the link @KittyGiraudel !

From the referenced article at the top of the issue:

> More debatable perhaps is Via, which is required (by RFC7230) to be added to the request by any proxy through which it passes to identify the proxy. This can be the proxy’s hostname, but is more likely to be a generic identifier like “vegur”, “varnish”, or “squid”. Removing (or not setting) this header on a request can cause proxy forwarding loops. However, interestingly it is also copied into the response on the way back to the browser, and here it's just informational and no browsers do anything with it, so it’s reasonably safe to get rid of it if you want to.

I think it's reasonable to remove it from the hint.

@captainbrosset, you were part of the original discussion. What do you think?

**Comment by captainbrosset** [comment]
> I don’t think too much thought went into that header in particular.

Correct. We were mostly following [the article](https://www.fastly.com/blog/headers-we-dont-want)'s recommendations at the time, and I fear the nuance about proxies using it got lost in the way. 

So, I'm fine removing the warning for Via.
