### ISSUE TITLE
[Bug] hint@7 is only partially released

### ISSUE THREAD

**Issue by chrisguttandin** [webhintio/hint#5203]
# 🐞 Bug report

## Description

A few days ago hint v7 was published on npm. https://www.npmjs.com/package/hint/v/7.0.0

Some of the packages in the @hint scope were updated (with a patch release - I would have expected that to be a major version change) to require hint at `"^7.0.0"` as peer dependency. One such package is `@hint/connector-puppeteer`.

Some other packages didn't get an update and still require hint at `"^6.0.0"` as peer dependency. An example of that is `@hint/hint-highest-available-document-mode`.

## Details

As a user of webhint you currently have to stay at v6 and lock all other packages at the exact version to keep npm happy.

**Comment by vidorteg** [comment]
Hi @chrisguttandin 

We just pushed a fixed version of webhint(version 7.0.1), it should contain the right dependency tree which fixes the issue described in here. Thanks for reporting it and please feel free to reactivate if it still does not work.

Duplicate #5198

**Comment by chrisguttandin** [comment]
Hi @vidorteg, thanks for working on this.

However it looks like some packages (at least `@hint/hint-amp-validator`) were not updated and still require v6 as peer dependency. The page for the package on npm (https://www.npmjs.com/package/@hint/hint-amp-validator) says it was last published a month ago.

**Comment by molant** [comment]
Hi @chrisguttandin,

`hint-amp-validator` got removed in v7 as a [breaking change](https://github.com/webhintio/hint/blob/main/packages/hint/CHANGELOG.md#breaking-changes).

If there are other packages that have not been updated please let us know!

**Comment by chrisguttandin** [comment]
Hi @molant, sorry I didn't even look for release notes as I thought v7 was published by accident.

I deleted `@hint/hint-amp-validator` and it's all working great now, @vidorteg. Thanks for fixing it so quickly.
