### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by mehran-sayyah** [webhintio/hint#5282]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.4.5 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by captainbrosset** [comment]
There doesn't seem to be enough information for us to investigate a potential problem here. Closing the issue as incomplete now.
Feel free to comment back with more information.
