### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by AnchousR** [webhintio/hint#5360]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.4.7 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [ ] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [ ] Recommended settings
* [x] Custom: defaults, not IE 11 

Ignored resources:
* * [ ] None
* * [ ] Different origin
* * [x] Custom: google-analytics.com 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by captainbrosset** [comment]
Closing as incomplete.
