### ISSUE TITLE
When Edge DevTools is installed and webhint enabled webhint unable to start

### ISSUE THREAD

**Issue by sonicdivx** [webhintio/hint#5364]
When Edge DevTools for vscode is enable and the setting Vscode-edge-devtools: Webhint is checked and you have webhint extension installed webhint fails to start and throws the following

"command 'vscode-webhint/apply-code-fix' already exists" error

I am new to the Edge DevTools extension use, so have not checked to see if issues section of devtools would be populated (as it would when running from standalone browser)

**Comment by captainbrosset** [comment]
@codepo8 any ideas why this would happen? Should this issue be moved to https://github.com/microsoft/vscode-edge-devtools/issues instead?

**Comment by codepo8** [comment]
@sonicdivx if you have the Edge DevTools extension installed, you can uninstall the webhint one. All the functionality of it is already available to you. We are considering to sunset the webhint extension because of that reason.

**Comment by Fania** [comment]
Noticed the same issue. Good to know that the WebHint extension functionality is included in the Edge DevTools extension. Thanks so much for the info.

**Comment by vidorteg** [comment]
Seems this is fixed. Closing it.

**Comment by johncrim** [comment]
It seems like this should be posted on the README/info page for the webhint vscode plugin. I had to search for a bit to figure this out.
