### ISSUE TITLE
Can webhint static code analysis be executed through a command?

### ISSUE THREAD

**Issue by dani-oropeza-nic** [webhintio/hint#5380]
Hello, I'm very new to webhint. I have a quick question...

I know that there is a VSCode extension that analyses de code statically. I would like to know If I can have the same (analyses the code statically), but by executing a command. Something like .eslint, you just have to execute `ng lint` and it starts to analyses the code and then shows in the console the errors/warning.

Can you please clarify this to me please? If you could share help links I would be very grateful.

**Comment by captainbrosset** [comment]
Hi @dani-oropeza-nic, yes there is a way to use webhint from the command line by installing and using the `hint` npm package. You can also try it out easily by typing `npx hint https://mywebsite.com` on the command line.
There is some documentation here: https://webhint.io/docs/user-guide/
And the npm package can be found here: https://www.npmjs.com/package/hint

Hope this helps! I'll close this issue for now, but please do feel free to reply if you need anything else.

**Comment by dani-oropeza-nic** [comment]
Thank you @captainbrosset for your response.

When running the command `npx hint something.html`, this error message is displayed in the console.

![image](https://user-images.githubusercontent.com/82594542/207619302-8893648a-f712-46d3-a6fb-f962cbffb588.png)

However, when adding local configuration, It seems that It is not checking the files correctly because something.html has accessibility errors.

![image](https://user-images.githubusercontent.com/82594542/207619968-11376136-f65d-4da4-8c98-c2e4d5be29ae.png)

**Can you please give me a hand with this?**

These are my dependencies

![image](https://user-images.githubusercontent.com/82594542/207620236-5c89ec6f-2283-4da3-8902-cd40110b8e5c.png)
