### ISSUE TITLE
Please appoint a committer for webhintio/markdown-link-validator

### ISSUE THREAD

**Issue by mi-hol** [webhintio/hint#5382]
/webhintio/markdown-link-validator is great tool for document maintenance but seems to be orphaned since about Jul 2021.
This understanding stems from lack of replies to issues and merges of dependency changes since around this time.

I'd be happy to own this role but currently am just on the "user" side.
Obviously I would need some assistance from an experienced committer to grow my knowledge in order to fulfil the role successfully.

Note: I lack permission to assign label "TSC agenda" as specified in https://github.com/webhintio/hint/blob/main/packages/hint/docs/about/GOVERNANCE.md

**Comment by molant** [comment]
That project was created to validate our internal documentation and it is mostly considered "done".

There's only a handful of dependency updates and 3 open issues that are over a year old.
Is there something in particular you are looking into adding to that project?

**Comment by mi-hol** [comment]
> That project was created to validate our internal documentation

that is a common requirement for many projects including one I'm contributing to.
A simple enhancement to make the current implementation much more useful for large number of files is described in https://github.com/webhintio/markdown-link-validator/issues/6

Your project already uses the **best possible name markdown-link-validator** for this functionality and is well known in all search engines. Anybody coming up with a new different name will have a hard time to succeed.

**Comment by molant** [comment]
If you have a PR to add that functionality I'll be more than happy to review it.

**Comment by jenkin** [comment]
@molant I interested to contribute to this project, too. Issue [#28](https://github.com/webhintio/markdown-link-validator/issues/28) is my own proposal, with some improvements (@mi-hol see `-q` option) ready for a PR.

**Comment by mi-hol** [comment]
closed via PR https://github.com/webhintio/markdown-link-validator/pull/29
