### ISSUE TITLE
Documentation for Static Code Analysis through a command line and not through VSCode extension

### ISSUE THREAD

**Issue by dani-oropeza-nic** [webhintio/hint#5383]
# 📚 Request documentation enhancements

## Description

There is not enough documentation to do the following: analyze code statically with a command line. I would like to run a command and start analyzing the static code of all the HTML files in my Angular application.

## Details

@captainbrosset, @vidorteg, @molant

When running the command `npx hint something.html`, this error message is displayed in the console.

![image](https://user-images.githubusercontent.com/82594542/207619302-8893648a-f712-46d3-a6fb-f962cbffb588.png)

However, when adding local configuration, It seems that It is not checking the files correctly because `something.html` has accessibility errors, and the linter says "Finishing..." and it doesn't show anything else

![image](https://user-images.githubusercontent.com/82594542/207619968-11376136-f65d-4da4-8c98-c2e4d5be29ae.png)

**Can you please give me a hand with this? I've been trying to do it for several days**

These are my dependencies

![image](https://user-images.githubusercontent.com/82594542/207880709-9ab129e2-bb9c-4be4-a764-e15c9cdd5dd5.png)
![image](https://user-images.githubusercontent.com/82594542/207880750-19d4ee8d-39fa-4f17-b41a-4ad03c3ace71.png)

Another clue: when I remove the `.hintrc` file and then I execute this command `npx hint something.html`. It does check against the default rules.

![image](https://user-images.githubusercontent.com/82594542/207621147-cdb8ed49-1c74-4b99-8eb8-c09a437cd32d.png)

**Comment by dani-oropeza-nic** [comment]
Hello @captainbrosset, @vidorteg, @molant, could you please give me a hand with this?

**Comment by str13tlfe** [comment]
Can you give me a little time please, I am going through a security issue at the moment. I was hacked into

**Comment by dani-oropeza-nic** [comment]
Of course I do, I'll be attentive to the comments of this Issue for when you're ready. Sorry for the security issue.

**Comment by dani-oropeza-nic** [comment]
Hello @str13tlfe, @captainbrosset, @vidorteg, @molant, can you give me a hand with this please?

**Comment by vidorteg** [comment]
Hi @dani-oropeza-nic

I do see some issues when mixing some configurations and hints e.g:

```
{
  "connector": {
    "name": "local"
  },
  "extends": ["accessibility"],
  "hints": {
    "axe/language": "error"
  }
}
```
can you try something like this:
```
{
  "connector": {
    "name": "local"
  },
  "extends": ["development"],
  "hints": {
    "axe/language": "error"
  }
}
```
on a simple test page? (opening and close `html` tags), you can then take out some of the specific hints that you are not using.

Also, for static analysis on vscode you can use extension which does this automatically for you (you can also configure it via `.hintrc` files)
https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools

**Comment by dani-oropeza-nic** [comment]
@vidorteg Thank you for your response. However, I think I don't get it yet.

Look at the first screenshot here below. The extension is `"development"` and when I execute the command `npx hint something.html`, 5 errors were found.

![image](https://user-images.githubusercontent.com/82594542/218206597-38ba5951-348d-4ead-951f-d96bfec18fc5.png)

And then executing the same command, but simply changing the extension to `"accessibility"`, it doesn't find anything. the console says "its ok", which I think it is wrong.

![image](https://user-images.githubusercontent.com/82594542/218206871-330404ec-1169-4ddb-8d18-3865cd557e6f.png)

According to the documentation here... https://webhint.io/docs/user-guide/hints/hint-axe/, The "accessibility" extension should have the `"axe/text-alternative"` rule, but it seems that it does not have.

![image](https://user-images.githubusercontent.com/82594542/218207273-97121f91-9ab4-4514-8998-4553d24524b6.png)

I don't know if it is a problem of the library or my configuration...

**Regarding to your questions:**

_on a simple test page?_  Initially, yes. Because I just want to make it work. The next step will be to apply that configuration for all .html files.

_"for static analysis on vscode you can use the Edge Devtools extension"_ Yes I can use that extension, however, we want to do the static web analysis via executing a command. In other words, we want to execute this command in the deploy pipeline and before making a git commit.
