### ISSUE TITLE
[Bug] Print button doesn't work

### ISSUE THREAD

**Issue by kevin-findigs** [webhintio/hint#5415]
# 🐛 Bug report

## Description

Ran an analysis and when clicking on the print button there's no interaction after. Also no error of any underlying issues
## Environment

* __webhint version:__ 2.4.7 
* __Browser version:__ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.0.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by vidorteg** [comment]
Hi @kevin-findigs ,

Thanks for the report, although seems we will need more information: which `Print button` are you referring to, the one on the browser when opening the report? 

Please feel free to reopen when more information is added.
