### ISSUE TITLE
[Bug] Webhint incorrectly reports `contain` as not support on Firefox for Android

### ISSUE THREAD

**Issue by thunfisch987** [webhintio/hint#5433]
# 🐞 Bug report

## Description

webhint tells me that `contain:` is not supported by Firefox for Android, despite it being supported.
https://developer.mozilla.org/en-US/docs/Web/CSS/contain#browser_compatibility
https://caniuse.com/mdn-css_properties_contain

## Details

Webhint VSCode v2.1.4, no configuration, Windows

**Comment by captainbrosset** [comment]
Thanks for reaching out about this. I suspect that the BCD dependency might need to be updated in webhint for this bug to go away.
@vidorteg, what do you think?
