### ISSUE TITLE
Is Blade.php supported ?

### ISSUE THREAD

**Issue by robinNavas** [webhintio/hint#5569]
### Discussed in https://github.com/webhintio/hint/discussions/5511

<div type='discussions-op-text'>

<sup>Originally posted by **robinNavas** April 12, 2023</sup>
Hi, 

I am currently working on websites with Sage (https://roots.io/sage/) wich use internally Laravel and its templating system Blade (php). I wanted to try the vscode extension to hint my files but it doesn't work on these file (It does on html files btw).

I wonder if it is possible to hint these files, maybe their dynamic nature avoid to use the tool ?

Thanks (and sorry if I am not in the correct place to ask this question)</div>

**Comment by vidorteg** [comment]
Hi @robinNavas 

Webhint does support php files, indeed it has support for any file but we currently do not have any hints associated to it. That being said building hints for webhint is relatively easy and we provide a guide on how to do it:
https://webhint.io/docs/contributor-guide/guides/create-custom-hint/

the `create-hint` section is specially helpful as it provides a package that creates the basic skeleton for a new hint. Thanks for the interest and please feel free to ask questions (if any) 😊
