### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by cyklop1989** [webhintio/hint#5739]
# 🐛 Bug report

## Environment

* __webhint version:__ 2.4.14 
* __Browser version:__ Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by Saloo0oh1978** [comment]
`s`

**Comment by Saloo0oh1978** [comment]
``
