### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by Dbitome88** [webhintio/hint#5758]
Console is full of errors. total 99 I have a Chromium bug that follows me around and not letting do any troubleshooting
Al Copilot got installed on Edge browser a month ago, then the Chromium bug shows up. I was able to removed  Al Copilot but all their symbols are still on the Desktop,  Right now, my Edge Browser is not normal.

Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by captainbrosset** [comment]
Thanks for filing. However, this issue looks unrelated to webhint. If you have an issue with the Console tool in Microsoft Edge DevTools, please reach out at https://github.com/MicrosoftEdge/DevTools instead, and provide as much details as you can.
For instance, a screenshot of your console, showing the errors, would help.
