### ISSUE TITLE
Enable strict mode of TypeScript

### ISSUE THREAD

**Issue by molant** [webhintio/hint#576]
Should we enable [`"strict": true`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) in `tsconfig.json`?

I've tried running it and there are quite a few things to fix, but might be better in the long-term for the project.

@alrra, @sarvaje @qzhou1607 ?

**Comment by alrra** [comment]
👍

**Comment by sarvaje** [comment]
👍

**Comment by molant** [comment]
Looks like there's agreement so removing the `question` tag

**Comment by sarvaje** [comment]
@molant @alrra do you want me to start doing this?

**Comment by molant** [comment]
Making a list of all the things that need someone to work on or where there are currently some issues

| package | owner | comments |
|-----------|-------|--------------|
| create-hint | @molant |  Issue with appinsights `Namespace '"http"' has no exported member 'ServerRequest'.` |
| create-hintrc | @molant |  Issue with appinsights `Namespace '"http"' has no exported member 'ServerRequest'.` |
| create-parser | @molant |  Issue with appinsights `Namespace '"http"' has no exported member 'ServerRequest'.` Also I think there's something broken in the logic of the package |
| connector-chrome | | |
| connector-jsdom | | |
| parser-babel-config | | |
| parser-javascript | | |
| parser-manifest | | |
| parser-typescript-config | | |
| parser-webpack-config | | |
| utils-connector-tools | | |
| utils-debugging-protocol-common | | |

@antross, @sarvaje if you can update this table when you grab one it would be awesome.

Thanks!

**Comment by molant** [comment]
All the packages that are not listed above are already done and merged or waiting to be merged.

**Comment by sarvaje** [comment]
>Issue with appinsights Namespace '"http"' has no exported member 'ServerRequest'.

@molant that happens because of the version of `@types/node`. I had the same problem in the online scanner and the solution was fix the version of that package.

**Comment by molant** [comment]
> I've updated to appinsights 1.0.5 and that seems to solve the problem.

I had to pin to @types/node to 10.9.1 to make it work 😔

**Comment by molant** [comment]
Looks like the remaining thing is the code under `scripts` 🎉
