### ISSUE TITLE
[Feature] Update MDN compat data - it's 2 years old

### ISSUE THREAD

**Issue by kuba-orlik** [webhintio/hint#5824]
# 🚀 Feature request

## Description

The project is using outdated MDN compat data - it uses @mdn/browser-compat-data@4.2.1, so the data is two years old! Due to that I get errors saying that some features are not supported in the latest browsers, when in fact they are supported.

Here it complains about `overflow-x: clip` not being supported on Safari, while it actually already is supported:

![image](https://github.com/webhintio/hint/assets/2697916/20f58b32-617a-47a0-a76d-761565506b6e)

![image](https://github.com/webhintio/hint/assets/2697916/79e4391b-b114-45af-b44c-be031e04e2d7)

**Comment by captainbrosset** [comment]
Thanks for filing this. I very much agree with this. Worth noting as well, that BCD is now much more automated and up to date than it previously was. Webhint should update. @vidorteg can we do this?

**Comment by vidorteg** [comment]
This was on my backlog for some time, I finally had some free cycles and was able to take care of this.
