### ISSUE TITLE
[Feature] Axe errors: show which element the error is about

### ISSUE THREAD

**Issue by kuba-orlik** [webhintio/hint#5835]
# 🚀 Feature request

## Description

When axe showcases issues with accessibility, it doesn't provide any hint on what item does it have in mind:

So I get an error like "Form elements must have labels: Element has no title attribute Element has no placeholder attribute" and it's not quite actionable. Which input should I look at?

![image](https://github.com/webhintio/hint/assets/2697916/e1687ea5-622d-4bd3-9f97-928568c0359b)

It would be nice if it provided an HTML snippet of the affected part of the document

**Comment by vidorteg** [comment]
thank you for your contribution, I'll do a release that will include later this week. Do you have a minimal example of a case were this happens? I would like to create a test to avoid regressing this behavior.

**Comment by kuba-orlik** [comment]
Unfortunately I couldn't figure out what's the minimal example case for this issue
