### ISSUE TITLE
[Bug] Extension incorrectly says `'@layer' is not supported by Chrome, Chrome Android, Edge...`

### ISSUE THREAD

**Issue by hamirmahal** [webhintio/hint#5854]
# 🐞 Bug report

## Description

The `webhint` extension for VSCode says `'@layer' is not supported by Chrome, Chrome Android, Edge, Opera, Samsung Internet.` [compat-api/css](https://developer.mozilla.org/docs/Web/CSS/%40layer), but the page it links, https://developer.mozilla.org/en-US/docs/Web/CSS/@layer, says otherwise.

## Details

I have `v2.1.12` of the `webhint` extension for VSCode.

**Comment by hamirmahal** [comment]
![image](https://github.com/webhintio/hint/assets/43425812/a17783e8-61b8-4c78-9870-bec7e03bcc0d)

**Comment by hamirmahal** [comment]
![image](https://github.com/webhintio/hint/assets/43425812/283de0be-7d21-4372-a6f7-97cf69b660c5)

**Comment by hamirmahal** [comment]
If I wanted to fix issues like these in the future, where in the source code would I look?

**Comment by hamirmahal** [comment]
I cloned this repository locally and saw 0 results when searching the codebase for `@layer`.

**Comment by captainbrosset** [comment]
Thanks for reporting.

> I cloned this repository locally and saw 0 results when searching the codebase for @layer.

This is expected. The source code in this repo doesn't directly deal with browser compat warnings. Instead, it uses a third-party library to do this. That library is [browser-compat-data](https://github.com/mdn/browser-compat-data) (BCD).

So, most likely, the problem is that the version of BCD used here is not the latest, and therefore webhint shows oudated warnings.

The fix would be to bump the version of BCD used in the dependencies of this project.

**Comment by hamirmahal** [comment]
You're welcome. It looks like [dac7399](https://github.com/webhintio/hint/commit/dac7399bfda302d768665d7e779d32c4aef4f5d5) bumped BCD a couple of weeks ago.

How long does it take for changes here to propagate to the `webhint` extension for VSCode?

**Comment by captainbrosset** [comment]
I'm not familiar enough with the release process for webhint. Let me ping @vidorteg here.

**Comment by vidorteg** [comment]
thanks for reporting this @hamirmahal, you are right I recently updated BCD  to avoid this issues, but have been busy with other work. I hope I have time this week to make a release for vscode extension.

**Comment by hamirmahal** [comment]
You're welcome @vidorteg.
