### ISSUE TITLE
How does one contribute a Quick Fix for an error?

### ISSUE THREAD

**Issue by hamirmahal** [webhintio/hint#5884]
### Discussed in https://github.com/webhintio/hint/discussions/5701

<div type='discussions-op-text'>

<sup>Originally posted by **hamirmahal** September 17, 2023</sup>
If I want to contribute a [Quick Fix](https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings) for [`packages/hint-button-type/src/hint.ts`](https://github.com/webhintio/hint/blob/f1b2f4f708be40c284afaef491c4bedd85d431c1/packages/hint-button-type/src/hint.ts#L0-L1), how would I go about doing so?</div>

**Comment by captainbrosset** [comment]
Thanks for your question. Pinging @vidorteg who might be able to help.

**Comment by vidorteg** [comment]
Hi @hamirmahal  and thank you for the interest in contributing 👏

The provider for quickfixes lives in here:
https://github.com/webhintio/hint/blob/main/packages/extension-vscode/src/quickfix-provider.ts

Depending on your goal you might also need to change the consumer side in here:
https://github.com/microsoft/vscode-edge-devtools

There is also documentation available in here, might not be for you specific case but it might bring some clarity on how it works:
https://webhint.io/docs/contributor-guide/
