### ISSUE TITLE
owner : need help . need ferret up and scanning now .

### ISSUE THREAD

**Issue by JasonLinn-cmyk** [webhintio/hint#5922]
- [ ] 

- [ ] soft ware 10 windows  true
- [ ] manual download 

Please tell us about your:

## Environment

* __`hint` version:__
* __`Node.js` version:__
* __`npm` version:__

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js



```

</details>

## URL for which `webhint` failed

* __URL:__

## Output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text



```

</details>

**Comment by JasonLinn-cmyk** [comment]
back to what it was doing the other day . it comes one but no scan . 
need to know if i should flash everything and reinstate the firmware,  soft, and one more download if i remember .  i did do a hot end up grade now the control panel does nothing but say creality stays on the screen and knob does not work . check all install 3 times very carefully . cannot find anything out of place.

**Comment by almeidathomas92** [comment]
> back to what it was doing the other day . it comes one but no scan . 
> 
> need to know if i should flash everything and reinstate the firmware,  soft, and one more download if i remember .  i did do a hot end up grade now the control panel does nothing but say creality stays on the screen and knob does not work . check all install 3 times very carefully . cannot find anything out of place.

Repo[indexedfiles]()
