### ISSUE TITLE
Add support for Samsung Internet

### ISSUE THREAD

**Issue by molant** [webhintio/hint#694]
https://samsunginter.net/docs/remote-debugging.html has instructions on how to debug using Chrome.

Things to investigate:

- Do we need a hard dependency on Chrome?
- For the launcher, we need to figure out a way to install the Android SDK automatically (similar to what we do with the edge one?)
- Does the user have to start the browser manually?
- Are we limited to one page or can we spawn multiple pages automatically? This is mostly for the testing part

@alrra do you want to sacrifice your device for a good cause 😛?

**Comment by alrra** [comment]
> do you want to sacrifice your device for a good cause?

Sure. 

---

Cc: @diekus, @poshaughnessy, @torgo

**Comment by poshaughnessy** [comment]
Thanks for raising this! And sorry for slow reply.

Some basic questions as a Sonarwhal newbie, please!:

- So this would allow the tests to be run in the Samsung Internet browser, via remote debugging? 
- _"similar to what we do with the edge one"_: Is this something you have set up for Edge for Android already? 
- What kind of tests would you expect to potentially show up different results in different browsers?

Re. hard dependency on Chrome? Good question, I have only been able to set up Samsung Internet remote debugging with Chrome on the desktop upto now. (I've seen mixed messages about Firefox Developer Edition working with Chromium-based browsers? But I couldn't get it working when I tried the other day. Also I tried with Opera's `chrome://inspect`, but the device doesn't show up there). I could check with colleagues for further details / ideas for other browsers!

I'll also take a look and try to understand how the current connectors work a bit better, so I can try to help further. Also we could discuss further on Thursday?

**Comment by molant** [comment]
> So this would allow the tests to be run in the Samsung Internet browser, via remote debugging?

Yes, that's the idea.

> "similar to what we do with the edge one": Is this something you have set up for Edge for Android already?

No, this is for Edge desktop. We are using [`edge-diagnostics-adapter`](https://github.com/Microsoft/edge-diagnostics-adapter/) to have a debugging protocol. I actually don't know if Edge on Android/iOS has a debugging protocol. [We should investigate](https://github.com/sonarwhal/sonarwhal/issues/709).

> What kind of tests would you expect to potentially show up different results in different browsers?

We don't know, that's why we try to run them in all supported browsers 😊 This helps us find edge cases for the rules and any missing features in the browser/connector. For example:

* You are supposed to use any file format for the image but maybe a browser only supports `png`
* Edge doesn't have a way to download the manifest of a PWA (yet) or an easy way to ignore SSL issues. * jsdom doesn't report some of the nodes when traversing

> I have only been able to set up Samsung Internet remote debugging with Chrome on the desktop upto now

Will try to get an Android phone and see if there's a way we can connect. I expect we will have to do some magic similar to Edge where we install some C++ dependencies or run as an admin.

> Also we could discuss further on Thursday?

Sure 👍

**Comment by molant** [comment]
Closing in favor of https://github.com/webhintio/rfcs/issues/35

**Comment by molant** [comment]
After the work going on with the compat-api this is less relevant. Also, if the samsung internet can be connected remotely then puppeteer should work.

Closing as there hasn't been any movement on this issue in almost 2 years and things have changed a lot since then.
