### ISSUE TITLE
Add interactive formatter

### ISSUE THREAD

**Issue by qzhou1607** [webhintio/hint#761]
Things that need to be done here:
* Group results by category/domain.
* The user can select to expand/collapse some category/domain results.
-----
I looked into the interactive formatter this morning and couldn't find a package that allows up to expand/collapse the scan results in place. I wonder if the alternative solution below works:
1.	After a scan, the results are grouped by category/domain (depending on users’ setting) and presented in the format of `summary`.
2.	A question is prompted at the end of the summary list, asking user to select the category/domain results they want to expand. (Maybe the summary list and the inquirer `choices` can be combined, since they are presenting the same content).
3.	The selected category/domain results are expanded. At the end of the expanded result, a question is prompted asking if the user wants to go back to the `main menu` (the scan result summary), if yes, it goes back to 2, if no, exit.

**Comment by molant** [comment]
Some questions:

1. How does the user select if they want the results grouped by category/domain? Is this specific to this formatter?
1. I'd probably combine the summary list and the inquirer `choices`

Everything else sounds fine.

Will be good to have a demo with some fake data and a video of it to have a better idea of the interaction.

@sonarwhal/core, @poshaughnessy, what do you think?

**Comment by qzhou1607** [comment]
Maybe we can set that when we init the `.sonarwhalrc`?
> How does the user select if they want the results grouped by category/domain? Is this specific to this formatter?

I agree. But I'm not sure if I can use `chalk` in the inquirer options, will need to confirm that.
> I'd probably combine the summary list and the inquirer choices

**Comment by qzhou1607** [comment]
@molant Here is the demo:

![interactive formatter_2](https://user-images.githubusercontent.com/20218531/35019318-1cea1a06-fadb-11e7-90ed-979e609ae143.gif)

**Comment by qzhou1607** [comment]
I have a question: When we group the results based on domain, should we group the ones with the same `domain` but different `subdomain` together? I vote no, but wonder what you think. @sonarwhal/core @poshaughnessy

**Comment by molant** [comment]
I think domain and subdomain should be separated.

**Comment by molant** [comment]
Closing in favor of #411 (HTML Formatter)
