### ISSUE TITLE
Connectors Configuration:"defaultProfile" option not working

### ISSUE THREAD

**Issue by ricardogaldino** [webhintio/hint#773]
Hi, is that correct? It did not work for me.

*File ".sonarwhalrc"
```json
{
    "browserslist": [],
    "connector": {
        "name": "chrome",
        "options": {
            "waitFor": 1000,
            "defaultProfile": true
        }
    },
    "formatters": [
        "codeframe"
    ],
    "ignoredUrls": [],
    "rules": {
        "amp-validator": "off",
        "apple-touch-icons": "error",
        "axe": "error",
        "content-type": "error",
        "disown-opener": "error",
        "highest-available-document-mode": "error",
        "html-checker": "error",
        "http-cache": "error",
        "http-compression": "error",
        "image-optimization-cloudinary": "off",
        "manifest-app-name": "error",
        "manifest-exists": "error",
        "manifest-file-extension": "error",
        "manifest-is-valid": "error",
        "meta-charset-utf-8": "error",
        "meta-viewport": "error",
        "no-disallowed-headers": "error",
        "no-friendly-error-pages": "error",
        "no-html-only-headers": "error",
        "no-http-redirects": "error",
        "no-protocol-relative-urls": "error",
        "no-vulnerable-javascript-libraries": "error",
        "ssllabs": "off",
        "strict-transport-security": "error",
        "validate-set-cookie-header": "error",
        "x-content-type-options": "error"
    },
    "rulesTimeout": 120000
}
```

**Comment by molant** [comment]
Hi @ricardogaldino 

Do you mind following the issue template? The `json` you've shared has a few issues (missing `}`, doesn't have a `rules` section, it isn't indented...). That will help us investigate what's going on.

Also, in order for `defaultProfile` we will need to know a bit more about what type of authentication system the site uses and how long the authentication state lasts. A link to the site will be helpful. In the meantime you can try the following:

* If the site remembers you from one session to another, make sure that you are already authenticated.
* If the site only authenticates you for a session (i.e.: when you close the browser you are logged out), then open the site, log in, and then run `sonarwhal` without closing the browser.

**Comment by ricardogaldino** [comment]
Hello @molant , 
When I assign "defaultProfile": true it opens a new tab with a blank page in the same open browser where I already authenticated before.

A red "X" appears on the console and it stops.

When it is set to false it only checks the login page.

**Comment by molant** [comment]
Can you please fill the template with all the requested information. It will be useful to have the debug output for this.

**Comment by alrra** [comment]
@ricardogaldino Can you provide the output for: `sonarwhal --debug <url>`, thanks!

**Comment by ricardogaldino** [comment]
![sonawhal-error](https://user-images.githubusercontent.com/11210913/35521503-0eb15c76-0501-11e8-9c11-c489761c203e.png)

**Comment by molant** [comment]
@ricardogaldino it seems like the `chrome-launcher` is having problems launching or connecting to the browser. Is this the output when the browser is already opened? Can you please share the output for the other case?

**Comment by ricardogaldino** [comment]
Hello @molant , 

I did the test with the browser closed and without logging on to the site previously. It did not give a bug and scanned the root of the site and the specific page to which I provided the url.

Is there any resource for full site scanning (all pages) or some scanning feature as I browse through the browser?

tks

**Comment by sarvaje** [comment]
There is an issue in `chrome-launcher`. The only way to make it works is having the browser close previously.
This should be fix once https://github.com/GoogleChrome/chrome-launcher/issues/118 is fixed and released.

**Comment by alrra** [comment]
See also: https://github.com/webhintio/hint/pull/1305#issuecomment-420718635.
