### ISSUE TITLE
Normalize `brotli` libraries in the project

### ISSUE THREAD

**Issue by molant** [webhintio/hint#932]
I've done a bit of research and I think we should switch the compression rule to `iltorb` even though it's a binary one. The reason is that [`brotli` hasn't been updated in about a year](https://github.com/devongovett/brotli.js/commits/master) and new versions of the algorithm have been released. The maintainers of `iltorb` seem to be doing a [good job at having everything up to date](https://github.com/MayhemYDG/iltorb/blob/master/CHANGELOG.md).

See https://github.com/sonarwhal/sonarwhal/pull/924/#discussion_r177170013

**Comment by molant** [comment]
After talking with @antross and some other first time users (especially on Windows platforms) I'm starting to think we should go back to the original `brotli` package. We will avoid installation problems when people don't have the right tools installed and we should be capable of bundling it better with webpack.

What do you think about this @alrra @sarvaje @kshyju and any other who has any opinion?

**Comment by alrra** [comment]
Even if it's a bit outdated, at the moment, for what we use it in sonarwhal for, there shouldn't be any significant / noticeable user differences if we switched.

> What do you think about this

For now, I personally think we should switch back.

**Comment by alrra** [comment]
Ref: https://github.com/devongovett/brotli.js/issues/21

**Comment by molant** [comment]
Doesn't look like `brotli` is going to get updated any time soon.
One thing we could do is fork the project and try to automate the whole compilation and publishing process. I haven't given a try but it looks a pretty straightforward to compile your own version from the sources.
